# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Display
            fields:
                info:
                    snippet:
                        html: "This plugin displays Event content items, either the current month with a day-per-block, or the current year with a month-per-block."
                view_mode:
                    label: 'View mode:'
                    plugin_setting:
                        name: view_mode
                    type: radios
                    values:
                        month_view: Show days of the month
                        year_view: Show months of the year
                    value: month_view
                    format_onchange: Yes
                start_month:
                    label: 'Start month:'
                    plugin_setting:
                        name: start_month
                    type: select
                    values:
                        January:
                            ord: 1
                            label: January
                        February:
                            ord: 2
                            label: February
                        March:
                            ord: 3
                            label: March
                        April:
                            ord: 4
                            label: April
                        May:
                            ord: 5
                            label: May
                        June:
                            ord: 6
                            label: June
                        July:
                            ord: 7
                            label: July
                        August:
                            ord: 8
                            label: August
                        September:
                            ord: 9
                            label: September
                        October:
                            ord: 10
                            label: October
                        November:
                            ord: 11
                            label: November
                        December:
                            ord: 12
                            label: December
                    value: January
                    indent: 1
                    visible_if:
                        lib.valueIs: view_mode, year_view
                display_year_beside_jan_month_name:
                    label: 'Display year beside January month name'
                    plugin_setting:
                        name: display_year_beside_jan_month_name
                    type: checkbox
                    indent: 1
                    visible_if:
                        lib.valueIs: view_mode, year_view
                months_format:
                    label: 'Months format:'
                    plugin_setting:
                        name: months_format
                    type: radios
                    values:
                        months_short_name: Short month names
                        months_long_name: Long month names
                    value: months_short_name
                    indent: 1
                first_day_of_week:
                    label: 'Week starts on:'
                    plugin_setting:
                        name: first_day_of_week
                    type: select
                    values:
                        Saturday: Saturday
                        Sunday: Sunday
                        Monday: Monday
                    value: Monday
                    indent: 1
                show_other_periods:
                    indent: 1
                    label: 'Display other years:'
                    plugin_setting:
                        name: show_other_periods
                    type: radios
                    values:
                        previous_and_next:
                            label: 'Show buttons for previous/next year'
                        current_future_and_previous:
                            label: 'Show buttons for current year, future years, and previous years'
                    value: previous_and_next
                    visible_if:
                        lib.valueIs: view_mode, year_view
                    format_onchange: true
                past_periods_limit:
                    indent: 2
                    label: 'Previous year limit:'
                    plugin_setting:
                        name: past_periods_limit
                    type: select
                    values:
                        0:
                            label: 'Don't show previous years'
                            ord: 1
                        1:
                            label: 'Up to 1'
                            ord: 2
                        2:
                            label: 'Up to 2'
                            ord: 3
                        3:
                            label: 'Up to 3'
                            ord: 4
                        4:
                            label: 'Up to 4'
                            ord: 5
                        5:
                            label: 'Up to 5'
                            ord: 6
                        6:
                            label: 'Up to 6'
                            ord: 7
                        7:
                            label: 'Up to 7'
                            ord: 8
                        8:
                            label: 'Up to 8'
                            ord: 9
                        9:
                            label: 'Up to 9'
                            ord: 10
                        10:
                            label: 'Up to 10'
                            ord: 11
                        11:
                            label: 'Up to 11'
                            ord: 12
                        12:
                            label: 'Up to 12'
                            ord: 13
                    value: 0
                    side_note: "You can specify how many previous years to display, as far back as there are events. The current year, and future years which have events, will always be shown."
                    visible_if: "lib.valueIs('view_mode', 'year_view') && lib.valueIs('show_other_periods', 'current_future_and_previous')"
                show_event_titles:
                    label: 'In each day/month, show:'
                    plugin_setting:
                        name: show_event_titles
                    type: select
                    values:
                        nothing:
                            label: "Don't show event details"
                        first_event:
                            label: "First event only"
                        first_2_events:
                            label: "Up to 2 events"
                        first_3_events:
                            label: "Up to 3 events"
                        first_4_events:
                            label: "Up to 4 events"
                        first_5_events:
                            label: "Up to 5 events"
                        all_events:
                            label: "All events"
                    value: first_event
                event_count:
                    label: 'Show number of events'
                    plugin_setting:
                        name: event_count
                    type: checkbox
                    value: true
                hide_private_items:
                    label: 'Hide private events from public view'
                    plugin_setting:
                        name: hide_private_items
                    type: checkbox
                    value: "1"
                language_selection:
                    label: 'Show events only in:'
                    plugin_setting:
                        name: language_selection
                    type: radios
                    values:
                        visitor: "Visitor's language"
                        all: All enabled languages
                    value: visitor
                category:
                    label: 'Show events only from category:'
                    plugin_setting:
                        name: category
                    pick_items:
                        path: zenario__content/panels/categories
                        min_path: zenario__content/panels/categories
                        max_path: zenario__content/panels/categories
                        target_path: zenario__content/panels/categories
                        select_phrase: Select category...
        popout:
            label: Popup
            fields:
                info:
                    snippet:
                        html: "When a visitor clicks on a day/month, a popup (modal window) appears, listing the events. Define what is shown in the popup."
                enable_popup:
                    label: 'Enable popup'
                    plugin_setting:
                        name: enable_popup
                    type: checkbox
                    format_onchange: true
                show_title:
                    label: 'Show event titles'
                    indent: 1
                    type: checkbox
                    value: "1"
                    read_only: true
                    visible_if:
                        lib.value: enable_popup
                show_summary:
                    label: 'Show event summaries'
                    indent: 1
                    plugin_setting:
                        name: show_summary
                    type: checkbox
                    value: "1"
                    visible_if:
                        lib.value: enable_popup
                date_format:
                    label: 'Date format:'
                    indent: 1
                    plugin_setting:
                        name: date_format
                    type: radios
                    values:
                        _SHORT:
                            ord: "1"
                            label: Short
                        _MEDIUM:
                            ord: "2"
                            label: Medium
                        _LONG:
                            ord: "3"
                            label: Long
                    value: _SHORT
                    visible_if:
                        lib.value: enable_popup
                    validation:
                        required_if_not_hidden: Please select the date format.
                show_featured_image:
                    indent: 1
                    plugin_setting:
                        name: show_featured_image
                    label: "Show featured image"
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                    side_note: |
                        The featured image of the content item will be shown if it exists.
                    visible_if:
                        lib.value: enable_popup
                canvas:
                    plugin_setting:
                        name: canvas
                    label: 'Image canvas:'
                    type: select
                    value: fixed_width_and_height
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                    indent: 2
                width:
                    plugin_setting:
                        name: width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: 240
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 3
                height:
                    plugin_setting:
                        name: height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: 160
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 3
    module_class_name: zenario_event_calendar