# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_slideshow_simple
    tabs:
        size:
            fields:
                desc:
                    snippet:
                        html: |
                            Simple slideshows consist of one or more slides, with each slide having one image,
                            plus additional properties in the same way as a Banner plugin.
                            The values you choose here will apply to all slides in this slideshow.
