# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Settings
            fields:
                title:
                    plugin_setting:
                        name: title
                    label: 'Title:'
                    type: text
                    value: "Your profile image"
                    style: "width: 20em;text-align: left;"
                allow_upload:
                    plugin_setting:
                        name: allow_upload
                    label: 'Allow user to upload image'
                    type: checkbox
                    value: "1"
                    format_onchange: true
                note_1:
                    snippet:
                        html: >
                            Enter the minimum dimensions of the uploaded image. If a
                            user tries to upload a smaller image, the plugin will show
                            an error.
                    full_width: Yes
                min_width:
                    plugin_setting:
                        name: min_width
                    label: 'Minimum uploaded image width:'
                    type: text
                    validation:
                        numeric: The minumum width must be a number.
                    value: "375"
                    post_field_html: pixels
                    style: "width: 5em;text-align: right;"
                min_height:
                    plugin_setting:
                        name: min_height
                    label: 'Minimum uploaded image height:'
                    type: text
                    validation:
                        numeric: The minumum height must be a number.
                    value: "500"
                    post_field_html: pixels
                    style: "width: 5em;text-align: right;"
                note_2:
                    snippet:
                        html: "Enter the maximum dimensions of the user's image to be displayed by this plugin."
                    full_width: Yes
                max_width:
                    plugin_setting:
                        name: max_width
                    label: 'Maximum displayed image width:'
                    type: text
                    validation:
                        numeric: The maximum width must be a number.
                    value: "375"
                    post_field_html: pixels
                    style: "width: 5em;text-align: right;"
                max_height:
                    plugin_setting:
                        name: max_height
                    label: 'Maximum displayed image height:'
                    type: text
                    validation:
                        numeric: The maximum height must be a number.
                    value: "500"
                    post_field_html: pixels
                    style: "width: 5em;text-align: right;"
                allow_remove:
                    plugin_setting:
                        name: allow_remove
                    label: 'Allow user to remove image'
                    type: checkbox
                    value: "1"
    module_class_name: zenario_extranet_user_image
