site_settings:
	setting_group: zenario_scheduled_task_manager__site_settings_group
	title: |
		Scheduled Task Manager Settings
	tabs:
		details:
			label:  Job logs
			edit_mode:
				enabled: Yes
			fields:
				period_to_delete_job_logs: 
					site_setting:
						name: period_to_delete_job_logs
					label: "Delete data from scheduled task log:"
					type: select
					values: 
						"90": 
							label: Delete data older than 3 months
							ord: "1"
						"180": 
							label: Delete data older than 6 months
							ord: "4"
						"365": 
							label: Delete data older than 1 year
							ord: "5"
						"730": 
							label: Delete data older than 2 years
							ord: "6"
						"1095": 
							label: Delete data older than 3 years
							ord: "7"
					empty_value: "Never delete"
					note_below: "Warning: Data older than specified period will be permanently deleted."