"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_forum

"Phrase Code",Translation
_ADD_MESSAGE_DESCRIPTION,"Please click the 'Add Reply' button below if you wish to comment."
_ADD_REPLY,"Add Reply"
_ADD_REPLY:,"Enter a Reply:"
_ADD_THREAD,"Add Thread"
_ANONYMOUS,"Anonymous"
_BY_ON,"by [[by]] on [[on]]"
_CANCEL,"Cancel"
_CONFIRM_DELETE_POST,"Are you sure that you wish to delete this message?"
_CONFIRM_DELETE_THREAD,"Are you sure that you wish to delete this thread?"
_CONFIRM_LOCK_THREAD,"Are you sure that you wish to disallow further messages?"
_CONFIRM_SUBS_FORUM,"Are you sure you wish to subscribe? A notification email will be sent to &quot;[[email]]&quot; when a new thread is created in this forum."
_CONFIRM_SUBS_THREAD,"Are you sure you wish to subscribe? A notification email will be sent to &quot;[[email]]&quot; when a new reply is added to this thread."
_CONFIRM_UNLOCK_THREAD,"Are you sure that you wish to allow further messages?"
_CONFIRM_UNSUBS_FORUM,"Are you sure you wish to unsubscribe, and no longer be notified of new threads created in this forum?"
_CONFIRM_UNSUBS_THREAD,"Are you sure you wish to unsubscribe, and no longer be notified of new replies to this thread?"
_DELETE_POST,"Delete Message"
_DELETE_THREAD,"Delete Thread"
_EDIT_MESSAGE:,"Edit Message:"
_EDIT_POST,"Edit Message"
_EDIT_TITLE:,"Edit Title:"
_EDITOR_BOLD,"Bold"
_EDITOR_CODE,"Code"
_EDITOR_EDIT_SOURCE,"View/Edit BBCode"
_EDITOR_EMOTICONS,"Insert Emoticon"
_EDITOR_IMAGE_SRC,"Please enter the URL for your Image:"
_EDITOR_INSERT_IMAGE,"Insert Image"
_EDITOR_ITALIC,"Italic"
_EDITOR_LINK_HREF,"Please enter the URL for your Link:"
_EDITOR_LINK,"Insert Link"
_EDITOR_ORDERED_LIST,"Insert Ordered List"
_EDITOR_REMOVE_CODE,"Normal Text"
_EDITOR_REMOVE_FORMAT,"Remove Formatting"
_EDITOR_STRIKE,"Strikethrough"
_EDITOR_STYLE,"Paragraph Style"
_EDITOR_TEXT_COLOR,"Text Colour"
_EDITOR_UNDERLINE,"Underline"
_EDITOR_UNLINK,"Remove Link"
_EDITOR_UNORDERED_LIST,"Insert Unordered List"
_ERROR_MESSAGE,"Please enter a message."
_ERROR_TITLE,"Please enter a title."
_EXCERPT_CUTOFF,"..."
_FIRST,"&laquo; First"
_FORUM_LOCKED,"Further messages may not be added in this forum"
_FORUM,"Forum"
_JOIN_DATE,"Join Date: [[date]]"
_LAST_POST,"Last Message"
_LAST,"Last &raquo;"
_LOCK_THREAD,"Disallow further messages"
_LOGIN_DESCRIPTION,"Please Login if you wish to add a message."
_MARK_FORUM_READ,"Mark all Messages as Read"
_MESSAGE:,"Enter a Message:"
_MOVE_THREAD,"Move Thread"
_NEXT,"Next &gt;"
_OFFLINE,"Offline"
_ONLINE,"Online"
_PLEASE_LOGIN_TO_POST,"Please Login to post"
_PLEASE_LOGIN_TO_SUBS,"Login to subscribe to this thread"
_PLEASE_LOGIN_TO_SUBS_FORUM,"Login to subscribe to this forum"
_POST_COUNT,"Post Count: [[post_count]]"
_POSTS,"Messages"
_PREV,"&lt; Prev"
_QUOTE_POST,"Quote"
_REPLIES,"Replies"
_REPORT_MESSAGE:,"Report the Message above as offensive:"
_REPORT_POST,"Report Message as offensive"
_SAID,"[[user]] said:"
_SAVE_POST,"Save Message"
_SEARCH_RETURNED_NO_RESULTS,"No Threads were found that matched your search."
_SEARCH,"Search"
_SUBMIT_DELETE_POST,"Delete Message"
_SUBMIT_DELETE_THREAD,"Delete Thread"
_SUBMIT_LOCK_THREAD,"Disallow further messages"
_SUBMIT_SUBS_FORUM,"Subscribe to this forum"
_SUBMIT_SUBS_THREAD,"Subscribe to this thread"
_SUBMIT_UNLOCK_THREAD,"Allow further comments"
_SUBMIT_UNSUBS_FORUM,"Unsubscribe from this forum"
_SUBMIT_UNSUBS_THREAD,"Unsubscribe from this thread"
_SUBS_TO_FORUM,"Subscribe to this forum"
_SUBS_TO_THREAD,"Subscribe to this thread"
_SUBSCRIBED_TO_FORUM,"You are subscribed to this forum"
_SUBSCRIBED_TO_THREAD,"You are subscribed to this thread"
_THREAD_LOCKED,"Further messages may not be added"
_THREAD_POSTER,"Posted by"
_THREAD_TITLE,"Title"
_THREADS,"Threads"
_TITLE:,"Enter a Title for this new Thread:"
_UNLOCK_THREAD,"Allow further messages"
_UNSUBS_TO_FORUM,"Unsubscribe from this forum"
_UNSUBS_TO_THREAD,"Unsubscribe from this thread"
_UPLOAD_NEW_IMAGE,"Upload image:"
_FILE_CAPTION,"Caption"
_DELETE_FILE,"Delete"
_ENLARGE_THIS_IMAGE,"Enlarge this image"