# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: email
    tabs:
        email:
            fields:
                zenario_incoming_email_manager__send_summary_email:
                    site_setting:
                        name: zenario_incoming_email_manager__send_summary_email
                    label: 'Only send a summary email for incoming email tasks'
                    type: checkbox
                    side_note: |
                        Whether to send a summary email for incoming email tasks, containing the number of emails processed and their statuses, in which case an email will be sent once the task processes all emails rather than one per email.