"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_anonymous_comments

"Phrase Code",Translation
_ADD_MESSAGE_DESCRIPTION,"Please click the 'Add Comment' button below if you wish to comment."
_ADD_REPLY,"Add Comment"
_ADD_REPLY:,"Enter a Comment:"
_ANONYMOUS,"Anonymous"
_APPROVE_POST,"Approve Comment"
_CANCEL,"Cancel"
_CAPTCHA:,"Please help us combat form submissions by spam devices:"
_CAPTCHA_INVALID,"Please correctly verify that you are human."
_CONFIRM_APPROVE_MODIFIED_POST,"The comment has just been edited. Please review it again."
_CONFIRM_APPROVE_POST,"Are you sure that you wish to approve this comment?"
_CONFIRM_DELETE_POST,"Are you sure that you wish to delete this comment?"
_CONFIRM_LOCK_THREAD,"Are you sure that you wish to disallow further comments?"
_CONFIRM_NAME_WARNING, "You must confirm your Screen Name in order to comment"
_CONFIRM_SUBS_THREAD,"Are you sure you wish to subscribe? A notification email will be sent to &quot;[[email]]&quot; when a new comment is made on this page."
_CONFIRM_UNLOCK_THREAD,"Are you sure that you wish to allow further comments?"
_CONFIRM_UNSUBS_THREAD,"Are you sure you wish to unsubscribe, and no longer be notified of new comments on this page?"
_DELETE_POST,"Delete Comment"
_EDIT_MESSAGE:,"Edit Comment:"
_EDIT_POST,"Edit Comment"
_EDITOR_BOLD,"Bold"
_EDITOR_CODE,"Code"
_EDITOR_EDIT_SOURCE,"View/Edit BBCode"
_EDITOR_EMOTICONS,"Insert Emoticon"
_EDITOR_IMAGE_SRC,"Please enter the URL for your Image:"
_EDITOR_INSERT_IMAGE,"Insert Image"
_EDITOR_ITALIC,"Italic"
_EDITOR_LINK_HREF,"Please enter the URL for your Link:"
_EDITOR_LINK,"Insert Link"
_EDITOR_ORDERED_LIST,"Insert Ordered List"
_EDITOR_REMOVE_CODE,"Normal Text"
_EDITOR_REMOVE_FORMAT,"Remove Formatting"
_EDITOR_STYLE,"Paragraph Style"
_EDITOR_TEXT_COLOR,"Text Colour"
_EDITOR_UNDERLINE,"Underline"
_EDITOR_UNLINK,"Remove Link"
_EDITOR_UNORDERED_LIST,"Insert Unordered List"
_EMAIL:,"Your Email:"
_ERROR_EMAIL,"Please enter your email address."
_ERROR_INVALID_EMAIL,"Please enter a valid email address."
_ERROR_MESSAGE,"Please enter a message."
_ERROR_NAME,"Please enter your name."
_FIRST,"&laquo; First"
_JOIN_DATE,"Join Date: [[date]]"
_LAST,"Last &raquo;"
_LOCK_THREAD,"Disallow further comments"
_LOGIN_DESCRIPTION,"Please Login if you wish to add a comment."
_NAME:, "Your Name:"
_NEXT,"Next &gt;"
_OFFLINE,"Offline"
_ONLINE,"Online"
_PLEASE_LOGIN_TO_POST,"Please Login to comment"
_PLEASE_LOGIN_TO_SUBS,"Login to subscribe"
_POST_COUNT,"Post Count: [[post_count]]"
_POST_PENDING_INFO,"Pending administrator approval"
_POST_SCREENING_NOTICE,"Please note that your comment will be verified by a site administrator before it will appear."
_PREV,"&lt; Prev"
_QUOTE_POST,"Quote"
_REPORT_MESSAGE:,"Report the comment above as offensive:"
_REPORT_POST,"Report as Offensive"
_SAID,"[[user]] said:"
_SAVE_POST,"Save Comment"
_SUBMIT_APPROVE_MODIFIED_POST,"Approve modified Comment"
_SUBMIT_APPROVE_POST,"Approve Comment"
_SUBMIT_DELETE_POST,"Delete Comment"
_SUBMIT_LOCK_THREAD,"Disallow further comments"
_SUBMIT_SUBS_THREAD,"Subscribe"
_SUBMIT_UNLOCK_THREAD,"Allow further comments"
_SUBMIT_UNSUBS_THREAD,"Unsubscribe"
_SUBS_TO_THREAD,"Subscribe"
_SUBSCRIBED_TO_THREAD,"You are subscribed to comments on this page"
_THREAD_LOCKED,"Further comments may not be added"
_UNLOCK_THREAD,"Allow further comments"
_UNSUBS_TO_THREAD,"Unsubscribe"
_FILE_CAPTION,"Caption"
_DELETE_FILE,"Delete"