"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",es

Plugin
zenario_anonymous_comments

"Phrase Code",Translation
_ADD_MESSAGE_DESCRIPTION,"Por favor haga click en el botón 'Dejar Comentario' si desea comentar."
_ADD_REPLY,"Dejar Comentario"
_ADD_REPLY:,"Haga un Comentario:"
_ANONYMOUS,"Anónimo"
_APPROVE_POST,"Aprobar Comentario"
_CANCEL,"Cancelar"
_CONFIRM_APPROVE_MODIFIED_POST,"El comentario acaba de ser modificado. Por favor revíselo nuevamente."
_CONFIRM_APPROVE_POST,"Está seguro que desea aprobar este comentario?"
_CONFIRM_DELETE_POST,"Está seguro que desea eliminar este comentario?"
_CONFIRM_LOCK_THREAD,"Está seguro que no desea aceptar la entrada de nuevos comentarios?"
_CONFIRM_SUBS_THREAD,"Está seguro que desea subscribirse? Una notificación de correo se enviará a &quot;[[email]]&quot; cuando se agregue un nuevo comentario en esta página."
_CONFIRM_UNLOCK_THREAD,"Está seguro que desea aceptar la entrada de nuevos comentarios?"
_CONFIRM_UNSUBS_THREAD,"Está seguro que desea cancelar la suscripción y no ser notificado cuando se agregue un nuevo comentario en esta página?"
_DELETE_POST,"Eliminar Comentario"
_EDIT_MESSAGE:,"Editar Comentario:"
_EDIT_POST,"Editar Comentario"
_EDITOR_BOLD,"Negrita"
_EDITOR_CODE,"Código"
_EDITOR_EDIT_SOURCE,"Ver/Editar BBCode"
_EDITOR_EMOTICONS,"Insertar Emoticono"
_EDITOR_IMAGE_SRC,"Por favor inserte una URL para su Image:"
_EDITOR_INSERT_IMAGE,"Insertar Imagen"
_EDITOR_ITALIC,"Cursiva"
_EDITOR_LINK_HREF,"Por favor inserte una URL para su Enlace:"
_EDITOR_LINK,"Insertar Enlace"
_EDITOR_ORDERED_LIST,"Insertar una Lista Ordenada"
_EDITOR_REMOVE_CODE,"Texto Normal"
_EDITOR_REMOVE_FORMAT,"Eliminar Formato"
_EDITOR_STYLE,"Estilo de Párrafo"
_EDITOR_TEXT_COLOR,"Color de Texto"
_EDITOR_UNDERLINE,"Subrayado"
_EDITOR_UNLINK,"Eliminar Enlace"
_EDITOR_UNORDERED_LIST,"Insertar Lista No Ordenada"
_EMAIL:,"Dirección de email:"
_ERROR_EMAIL,"Por favor ingrese su Dirección de email."
_ERROR_INVALID_EMAIL,"Por favor ingrese una Dirección de email válida."
_ERROR_MESSAGE,"Por favor ingrese su mensaje."
_ERROR_NAME,"Por favor ingrese su nombre."
_FIRST,"&laquo; Primero"
_JOIN_DATE,"Fecha de Registro: [[date]]"
_LAST,"Último &raquo;"
_LOCK_THREAD,"Deshabilitar nuevos comentarios"
_LOGIN_DESCRIPTION,"Por favor inicie sesión si desea dejar un comentario."
"_NAME:", "Nombre:"
_NEXT,"Siguiente &gt;"
_OFFLINE,"Desconectado"
_ONLINE,"Conectado"
_PLEASE_LOGIN_TO_POST,"Por favor inicie sesión para dejar un comentario"
_PLEASE_LOGIN_TO_SUBS,"Por favor inicie sesión para subscribirse"
_POST_COUNT,"Número de entradas: [[post_count]]"
_POST_PENDING_INFO,"(pendiente)"
_PREV,"&lt; Anterior"
_QUOTE_POST,"Cita"
_REPORT_MESSAGE:,"Reporte el comentario anterior como ofensivo:"
_REPORT_POST,"Reportar como ofensivo"
_SAID,"[[user]] dijo:"
_SAVE_POST,"Guardar Comentario"
_SUBMIT_APPROVE_MODIFIED_POST,"Aprobar Comentario modificado"
_SUBMIT_APPROVE_POST,"Aprobar Comentario"
_SUBMIT_DELETE_POST,"Eliminar Comentario"
_SUBMIT_LOCK_THREAD,"No aceptar nuevos comentarios"
_SUBMIT_SUBS_THREAD,"Subscribir"
_SUBMIT_UNLOCK_THREAD,"Permitir nuevos comentarios"
_SUBMIT_UNSUBS_THREAD,"Cancelar Subscripción"
_SUBS_TO_THREAD,"Subscribir"
_SUBSCRIBED_TO_THREAD,"Está subscrito a los comentarios de esta página"
_THREAD_LOCKED,"Puede que no se agreguen nuevos comentarios"
_UNLOCK_THREAD,"Permitir nuevos comentarios"
_UNSUBS_TO_THREAD,"Cancelar Subscripción"
_FILE_CAPTION,"Título"
_DELETE_FILE,"Borrar"