"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",pl

Plugin
zenario_anonymous_comments

"Phrase Code",Translation
_ADD_MESSAGE_DESCRIPTION,"Kliknij przycisk 'Dodaj komentarz', aby dodać swój komentarz."
_ADD_REPLY,"Dodaj komentarz"
_ADD_REPLY:,"Treść komentarza:"
_ANONYMOUS,"Anonim"
_APPROVE_POST,"Zatwierdź komentarz"
_CANCEL,"Anuluj"
_CONFIRM_APPROVE_MODIFIED_POST,"Treść komentarza została właśnie zmieniona przez autora. Prosimy o jej ponowną weryfikację."
_CONFIRM_APPROVE_POST,"Czy jesteś pewien, że chcesz zatwierdzić ten komentarz ?"
_CONFIRM_DELETE_POST,"Czy jesteś pewien, że chcesz usunąć ten komentarz ?"
_CONFIRM_LOCK_THREAD,"Czy jesteś pewien, że chcesz wyłączyć możliwość dodawania komentarzy ?"
_CONFIRM_SUBS_THREAD,"Czy jesteś pewien, że chcesz dokonać subskrypcji powiadomień ? Za każdym razem gdy pojawi się nowy komentarz na tej stronie zostaniesz o nim powiadomiony emailem na adres &quot;[[email]]&quot;."
_CONFIRM_UNLOCK_THREAD,"Czy jesteś pewien, że chcesz włączyć możliwość dodawania komentarzy ?"
_CONFIRM_UNSUBS_THREAD,"Czy jesteś pewien, że chcesz wyłączyć subskrypcję powiadomień o nowych komentarzach na tej stronie ?"
_DELETE_POST,"Usuń komentarz"
_EDIT_MESSAGE:,"Edytuj komentarz:"
_EDIT_POST,"Edytuj komentarz"
_EDITOR_BOLD,"Pogrubienie"
_EDITOR_CODE,"Kod źródłowy"
_EDITOR_EDIT_SOURCE,"Zobacz/Edytuj BBCode"
_EDITOR_EMOTICONS,"Wstaw emotikonę"
_EDITOR_IMAGE_SRC,"Wpisz URL swojego obrazka:"
_EDITOR_INSERT_IMAGE,"Wstaw obrazek"
_EDITOR_ITALIC,"Kursywa"
_EDITOR_LINK_HREF,"Wpisz URL linka:"
_EDITOR_LINK,"Wstaw link"
_EDITOR_ORDERED_LIST,"Wstaw listę numerowaną"
_EDITOR_REMOVE_CODE,"Normalny"
_EDITOR_REMOVE_FORMAT,"Wyczyść formatowanie"
_EDITOR_STYLE,"Styl akapitu"
_EDITOR_TEXT_COLOR,"Kolor czcionki"
_EDITOR_UNDERLINE,"Podkreślenie"
_EDITOR_UNLINK,"Usuń link"
_EDITOR_UNORDERED_LIST,"Wstaw listę wypunktowaną"
"_EMAIL:","Email:"
_ERROR_EMAIL,"Proszę wprowadzić swój adres email."
_ERROR_INVALID_EMAIL,"Wprowadzony adres email jest niepoprawny."
_ERROR_MESSAGE,"Proszę wpisać wiadomość."
_ERROR_NAME,"Proszę podać imię."
_FIRST,"&laquo; Pierwsza"
_JOIN_DATE,"Data rejestracji: [[date]]"
_LAST,"Ostatnia &raquo;"
_LOCK_THREAD,"Wyłącz możliwość dodawania komentarzy"
_LOGIN_DESCRIPTION,"Zaloguj się by dodać swój komentarz."
"_NAME:", "Imię:"
_NEXT,"Następna &gt;"
_OFFLINE,"Niezalogowany"
_ONLINE,"Zalogowany"
_PLEASE_LOGIN_TO_POST,"Zaloguj"
_PLEASE_LOGIN_TO_SUBS,"Zaloguj się by włączyć subskrypcję powiadomień"
_POST_COUNT,"Ilość komentarzy: [[post_count]]"
_POST_PENDING_INFO,"(oczekuje na akceptację moderatora)"
_PREV,"&lt; Poprzednia"
_QUOTE_POST,"Cytuj"
_REPORT_MESSAGE:,"Zgłoś powyższy komentarz jako łamiący regulamin:"
_REPORT_POST,"Zgłoś komentarz jako łamiący regulamin"
_SAID,"[[user]] napisał:"
_SAVE_POST,"Zapisz komentarz"
_SUBMIT_APPROVE_MODIFIED_POST,"Zatwierdź zmodyfikowany komentarz"
_SUBMIT_APPROVE_POST,"Zatwierdź komentarz"
_SUBMIT_DELETE_POST,"Usuń komentarz"
_SUBMIT_LOCK_THREAD,"Wyłącz możliwość dodawania komentarzy"
_SUBMIT_SUBS_THREAD,"Subskrybuj powiadomienia"
_SUBMIT_UNLOCK_THREAD,"Włącz możliwość dodawania komentarzy"
_SUBMIT_UNSUBS_THREAD,"Wyłącz subskrypcję powiadomień"
_SUBS_TO_THREAD,"Subskrybuj powiadomienia"
_SUBSCRIBED_TO_THREAD,"Posiadasz aktywną subskrypcję powiadomień o nowych komentarzach na tej stronie."
_THREAD_LOCKED,"Możliwość umieszczania komentarzy została wyłączona"
_UNLOCK_THREAD,"Włącz możliwość dodawania komentarzy"
_UNSUBS_TO_THREAD,"Wyłącz subskrypcję powiadomień"
_FILE_CAPTION,"Caption"
_DELETE_FILE,"Delete"