"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",tr

Plugin
zenario_anonymous_comments

"Phrase Code",Translation
_ADD_MESSAGE_DESCRIPTION,"Eğer yorum yapmak istiyorsanız, Yorum Ekle düğmesine tıklayınız."
_ADD_REPLY,"Yorum Ekle"
_ADD_REPLY:,"Bir yorum girinizi:"
_ANONYMOUS,"Anonim"
_APPROVE_POST,"Yorumu onayla"
_CANCEL,"İptal"
_CONFIRM_APPROVE_MODIFIED_POST,"Yorum az önce edit edilmiştir. Lütfen, tekrar gözden geçirin."
_CONFIRM_APPROVE_POST,"Bu yorumu onaylamak istediğinizden emin misiniz?"
_CONFIRM_DELETE_POST,"Bu mesaji silmek istediğinizden emin misiniz?"
_CONFIRM_LOCK_THREAD,"Daha fazla mesaj yollanmasını engellemek istediğinizden emin misiniz?"
_CONFIRM_SUBS_THREAD,"Abone olmak istediğinizden emin misiniz? Bu sayfada yeni bir yorum yapıldığında, bildirim e-postası bu adrese &quot;[[email]]&quot; yollanacaktır."
_CONFIRM_UNLOCK_THREAD,"Daha fazla mesaj yollanmasını istediğinizden emin misiniz?"
_CONFIRM_UNSUBS_THREAD,"Aboneliğinizi iptal etmek istediğinizden ve artık bu sayfa hakkında yeni yorumlar hakkında haberdar olmak istemediginizden emin misiniz?"
_DELETE_POST,"İletiyi Sil"
_EDIT_MESSAGE:,"Yorumu Düzenle:"
_EDIT_POST,"Mesajı Düzenle"
_EDITOR_BOLD,"Kalın"
_EDITOR_CODE,"Kod"
_EDITOR_EDIT_SOURCE,"BBCode Görüntüle/Düzenle"
_EDITOR_EMOTICONS,"Emoticon Ekle"
_EDITOR_IMAGE_SRC,"Görüntü için URL giriniz:"
_EDITOR_INSERT_IMAGE,"Görüntü Ekle"
_EDITOR_ITALIC,"İtalik"
_EDITOR_LINK_HREF,"Bağlantı için URL giriniz:"
_EDITOR_LINK,"Bağlantı Ekle"
_EDITOR_ORDERED_LIST,"Ordered List Ekle"
_EDITOR_REMOVE_CODE,"Normal Metin"
_EDITOR_REMOVE_FORMAT,"Biçimlendirmeyi Kaldır"
_EDITOR_STYLE,"Paragraf Stili"
_EDITOR_TEXT_COLOR,"Metin Rengi"
_EDITOR_UNDERLINE,"Altı çizgili"
_EDITOR_UNLINK,"Bağlantı Kaldır"
_EDITOR_UNORDERED_LIST,"Unordered List Ekle"
"_EMAIL:","E-posta Adresiniz:"
_ERROR_EMAIL,"Lütfen, e-posta adresinizi giriniz."
_ERROR_INVALID_EMAIL,"Lütfen, geçerli bir e-posta adresi giriniz."
_ERROR_MESSAGE,"Lütfen mesajınızı giriniz."
_ERROR_NAME,"Lütfen adınızı giriniz."
_FIRST,"&laquo; İlk"
_JOIN_DATE,"Üyelik Tarihi: [[date]]"
_LAST,"Son &raquo;"
_LOCK_THREAD,"Daha fazla yoruma izin verme"
_LOGIN_DESCRIPTION,"Buraya yorum ekleyebilirsiniz."
_NAME:, "Adınız:"
_NEXT,"Sonraki &gt;"
_OFFLINE,"Çevirimdışı"
_ONLINE,"Çevirimiçi"
_PLEASE_LOGIN_TO_POST,"Mesaj yollamak için giriş yapınız"
_PLEASE_LOGIN_TO_SUBS,"Abone olmak için giriş yapınız"
_POST_COUNT,"Mesaj sayısı: [[post_count]]"
_POST_PENDING_INFO,"(beklemede)"
_PREV,"&lt; Önceki"
_QUOTE_POST,"Quote"
_REPORT_MESSAGE:,"Yukarıdaki raporu saldırgan olarak rapor ediniz:"
_REPORT_POST,"Bu mesaji spam ya da saldırgan mesaj olarak rapor ediniz"
_SAID,"[[user]] söyledi:"
_SAVE_POST,"Mesaji Kaydet"
_SUBMIT_DELETE_POST,"Yorumu Sil"
_SUBMIT_LOCK_THREAD,"Daha fazla yorumu engelle"
_SUBMIT_SUBS_THREAD,"Abone Ol"
_SUBMIT_UNLOCK_THREAD,"Daha fazla yoruma izin ver"
_SUBMIT_UNSUBS_THREAD,"Aboneliği İptal Et"
_SUBS_TO_THREAD,"Abone Ol"
_SUBSCRIBED_TO_THREAD,"Bu sayfadaki yorumlara abone oldunuz"
_SUBMIT_APPROVE_MODIFIED_POST,"Approve modified Comment","Değistirilmiş yorumu onayla"
_SUBMIT_APPROVE_POST,"Approve Comment", "Yorumu onayla"
_THREAD_LOCKED,"Daha fazla mesaj yollanamayabilir"
_UNLOCK_THREAD,"Daha fazla yoruma izin ver"
_UNSUBS_TO_THREAD,"Aboneliği İptal Et"
_FILE_CAPTION,"Caption"
_DELETE_FILE,"Delete"