# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_extranet_change_password
    tabs:
        error_messages:
            label: Error messages
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: >
                            These settings control what the user sees if changing the
                            password fails.
                sub_description:
                    full_width: Yes
                    snippet:
                        html: "Error messages for changing password:"
                new_password_same_as_old_message:
                    plugin_setting:
                        name: new_password_same_as_old_message
                    label: 'If new password is the same as the old password:'
                    type: text
                    value: "Your new Password is the same as your old Password."
                    show_phrase_icon: true
                new_password_length_message:
                    plugin_setting:
                        name: new_password_length_message
                    label: 'If new password is not over min length:'
                    type: text
                    value: "Please ensure that your new Password is at least [[min_password_length]] characters long."
                    show_phrase_icon: true
                new_passwords_do_not_match:
                    plugin_setting:
                        name: new_passwords_do_not_match
                    label: 'If the new password and repeat new password fields do not match:'
                    type: text
                    value: "Your repeated Password does not match."
                    show_phrase_icon: true
                no_new_repeat_password_error_text:
                    plugin_setting:
                        name: no_new_repeat_password_error_text
                    label: 'If no new repeat password is entered:'
                    type: text
                    value: "Please repeat your new Password."
                    show_phrase_icon: true
                no_password_entered_message:
                    plugin_setting:
                        name: no_password_entered_message
                    label: 'If the old password was not entered:'
                    type: text
                    value: "Please enter your old password."
                    show_phrase_icon: true
        
                
                
                

                

                        

                    

                    

                    
                    
                wrong_password_message:
                    plugin_setting:
                        name: wrong_password_message
                    label: 'If the old password was incorrect:'
                    type: text
                    value: "You did not enter your old Password correctlty."
                    show_phrase_icon: true



