plugin_settings:
    tabs:
        first_tab:
            label: Send email confirmation
            fields:
                zenario_extranet_change_password__send_notification_email:
                    plugin_setting:
                        name: zenario_extranet_change_password__send_notification_email
                    label: 'Send email confirmation:'
                    type: checkbox
                    redraw_onchange: Yes
                    
                zenario_extranet_change_password__notification_email_template:
                    indent: 1
                    plugin_setting:
                        name: zenario_extranet_change_password__notification_email_template
                    label: 'Select email template:'
                    
                    #    You can create a picker for pretty much anything in the CMS that
                    #    has a Storekeeper Panel just by entering details of that Panel
                    pick_items:
                        path: zenario__email_template_manager/panels/email_templates
                        target_path: zenario__email_template_manager/panels/email_templates
                        min_path: zenario__email_template_manager/panels/email_templates
                        max_path: zenario__email_template_manager/panels/email_templates
                        disallow_refiners_looping_on_min_path: Yes
                        nothing_selected_phrase: No Email Template Selected
                        select_phrase: Select an email template...
                        hide_remove_button: Yes
                        
                    value: zenario_extranet_change_password_notification_en
                    
                    #    Only show this field if the checkbox above is checked, but make it
                    #    mandatory if shown
                    visible_if: "zenarioAB.value('zenario_extranet_change_password__send_notification_email')"
                    validation:
                        required_if_not_hidden: Please select an email template.
                     
    module_class_name: zenario_extranet_change_password
    




