# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            fields:
                data_field:
                    hidden: Yes
                    value: description
                use_pagination:
                    hidden: Yes
                    value: "1"
                pagination_style:
                    hidden: Yes
                enable_categories:
                    hidden: Yes
                    value: ""
                page_size:
                    label: 'Maximum number of entries to show in dropdown panel:'
                maximum_results_number:
                    plugin_setting:
                        name: maximum_results_number
                    indent: 1
                    type: text
                    same_row: true
                    maxlength: 5
                    style: "width: 5em;"
                    format_onchange: true
                    value: 20
                    visible_if: |
                        zenarioAB.value('page_size') == 'maximum_of'
                    validation:
                        required: Please enter the maximum number of entries.
                        numeric: The maximum number of entries number be a number.
                dropdown_position:
                    plugin_setting:
                        name: dropdown_position
                    label: 'The position of the dropdown:'
                    type: select
                    value: bottom_left
                    values:
                        search_bottom_left: Bottom left of search box
                        search_bottom_right: Bottom right of search box
                        slot_bottom_left: Bottom left of slot
                        slot_bottom_right: Bottom right of slot
                        form_bottom_left: Bottom left of search form
                        form_bottom_right: Bottom right of search form
                use_specific_search_results_page:
                    plugin_setting:
                        name: use_specific_search_results_page
                    type: radios
                    values:
                        0:
                            ord: 1
                            label: 'Use the sitewide search results page'
                        1:
                            ord: 2
                            label: 'Use a specific search results page:'
                    redraw_onchange: true
                plugin_page_note:
                    indent: 1
                    visible_if: |
                        !zenarioAB.value('use_specific_search_results_page')
                    snippet:
                        html: |
                            When a content item is created containing the <em style="font-style: italic;">Search Results</em> plugin,
                            this plugin will automatically link to it.
                specific_search_results_page:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('use_specific_search_results_page')
                    plugin_setting:
                        name: specific_search_results_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Search Results Page:'
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        disallow_refiners_looping_on_min_path: true
                        select_phrase: select a content item...
                        hide_remove_button: true
                    validation:
                        required_if_not_hidden: Please select a content item
                search_label:
                    plugin_setting:
                        name: search_label
                    label: 'Show "Search" label'
                    type: checkbox
                    value: 0
                    ord: 1001
                    format_onchange: Yes
                search_placeholder:
                    plugin_setting:
                        name: search_placeholder
                    label: 'Show "Search the site" placeholder'
                    type: checkbox
                    value: 0
                    ord: 1002
                    format_onchange: Yes
                search_placeholder_phrase:
                    indent: 1
                    plugin_setting:
                        name: search_placeholder_phrase
                    label: 'Search placeholder phrase:'
                    type: text
                    ord: 1003
                    format_onchange: Yes
                    visible_if:
                        lib.value: search_placeholder
                    validation:
                        required_if_not_hidden: Please enter a phrase
        content_types:
            ord: "2"
            label: Content Items to Search
            fields:
                search_html:
                    hidden: Yes
                search_document:
                    hidden: Yes
                search_news:
                    hidden: Yes
                search_in_languages:
                    label: 'Search Content Items in:'
                    plugin_setting:
                        name: search_in_languages
                    type: radios
                    values:
                        current:
                            ord: "1"
                            label: Current language
                        all:
                            ord: "1"
                            label: All languages
                    value: current
    module_class_name: zenario_search_entry_box_predictive_probusiness
