#You must use a tab-size of 4 spaces to edit this file.
---
zenario__administration:
    panels:
        site_settings:
            items:
                zenario__country_language_picker:
                    name: "Country and language picker"
                    desc: "Visitors arriving at the site see a country and language picker."