
ALTER TABLE `[[DB_PREFIX]]menu_sections` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]menu_sections` VALUES
 (1,'Main'),
 (2,'Footer');
ALTER TABLE `[[DB_PREFIX]]menu_sections` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]modules` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]modules` VALUES
 (1,'zenario_common_features','zenario_common_features','Common Features','Community','core','','zenario_common_features',0,'',1,0,0,0,'module_is_abstract',0),
 (2,'zenario_banner','zenario_banner','Banner','Community','pluggable','image_then_title_then_text','zenario_banner',1,'',0,0,0,1,'module_running',0),
 (3,'zenario_breadcrumbs','zenario_breadcrumbs','Breadcrumbs','Community','pluggable','standard','zenario_breadcrumbs',1,'',0,0,0,1,'module_running',0),
 (4,'zenario_footer','zenario_footer','Footer Menu','Community','pluggable','standard','zenario_footer',1,'',0,0,0,1,'module_running',0),
 (5,'zenario_html_snippet','zenario_html_snippet','Raw HTML Snippet','Community','pluggable','standard','zenario_html_snippet',1,'',0,1,0,1,'module_running',0),
 (6,'zenario_menu','zenario_menu','Menu (Horizontal)','Community','pluggable','standard','zenario_menu',1,'',0,0,0,1,'module_running',0),
 (7,'zenario_content_list','zenario_content_list','Content Summary List','Community','pluggable','standard','zenario_content_list',1,'',0,0,0,1,'module_running',0),
 (8,'zenario_wysiwyg_editor','zenario_wysiwyg_editor','WYSIWYG Editor','Community','pluggable','standard','zenario_html_snippet',1,'',0,1,0,1,'module_running',0),
 (9,'zenario_email_template_manager','zenario_email_template_manager','Email Template Manager','Community','management','','zenario_email_template_manager',0,'',0,0,0,0,'module_running',0),
 (10,'zenario_menu_vertical','zenario_menu_vertical','Menu (Vertical)','Community','pluggable','standard','zenario_menu_vertical',1,'',0,0,0,1,'module_running',0),
 (11,'zenario_language_picker','zenario_language_picker','Language Picker','Community','pluggable','select_list','zenario_language_picker',1,'',0,0,0,1,'module_running',0),
 (12,'zenario_menu_responsive_push_pull','zenario_menu_responsive_push_pull','Menu for Mobile with Push-Pull','Community','pluggable','standard','zenario_menu_responsive_push_pull',1,'',0,0,0,1,'module_running',0),
 (13,'zenario_slideshow_simple','zenario_plugin_nest','Slideshow (simple)','Community','pluggable','standard','zenario_slideshow',1,'',0,0,0,0,'module_running',0),
 (14,'zenario_plugin_nest','zenario_plugin_nest','Nest','Community','pluggable','standard','zenario_plugin_nest',1,'',0,0,0,0,'module_running',0),
 (15,'zenario_copyright','zenario_copyright','Copyright','Community','pluggable','standard','zenario_copyright',1,'',0,0,0,1,'module_running',0),
 (16,'zenario_document_container','zenario_document_container','Document Container','Community','pluggable','standard','zenario_document_container',1,'',0,0,0,1,'module_running',0),
 (17,'zenario_user_forms','zenario_user_forms','Form Container','Pro','management','standard','zenario_user_forms',1,'',0,0,0,1,'module_running',0),
 (18,'zenario_slideshow','zenario_plugin_nest','Slideshow (advanced)','Community','pluggable','standard','zenario_plugin_nest',1,'',0,0,0,0,'module_running',0),
 (19,'zenario_ctype_news','zenario_ctype_news','Content Type News','Community','content_type','','zenario_ctype_news',0,'',0,0,0,0,'module_running',0),
 (20,'zenario_advanced_search','zenario_advanced_search','Advanced Search','Community','content_type','standard','zenario_advanced_search',1,'',0,0,0,1,'module_running',0);
ALTER TABLE `[[DB_PREFIX]]modules` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]plugin_instances` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]plugin_instances` VALUES 
 (1,'Logo',2,0,'',0,'','image_then_title_then_text','banner_logo',0,0),
 (2,'Top Menu',6,0,'',0,'','standard','',0,0),
 (3,'Responsive Multilevel Menu',12,0,'',0,'','standard','',0,0),
 (4,'Language picker',14,0,'',0,'','standard','nest_top_bar',1,0),
 (5,'Slideshow (simple) home page',13,0,'',0,'','standard','',0,1),
 (7,'Home, call-out banner',2,0,'',0,'','image_then_title_then_text','banner_animation_parent',0,0),
 (8,'Home, services',14,0,'',0,'','standard','container_12 nest_animation_parent nest_full_boxes',1,0),
 (9,'Home, services',14,0,'',0,'','standard','nest_portfolio nest_animation_parent',1,0),
 (12,'Home, full banner',2,0,'',0,'','image_then_title_then_text','banner_more_button banner_animation_parent banner_overlay_content light align_left',0,0),
 (14,'Contact form',17,0,'',0,'','standard','form_contact',0,0),
 (16,'Company address',2,0,'',0,'','image_then_title_then_text','zenario_banner__default_style',0,0),
 (17,'Social links',5,0,'',0,'','standard','',0,0),
 (18,'Footer Menu',4,0,'',0,'','standard','',0,0),
 (19,'Copyright notice',15,0,'',0,'','standard','',0,0),
 (20,'Contact popup',17,0,'',0,'','standard','form_popup',0,0),
 (21,'Breadcrumbs',3,0,'',0,'','standard','',0,0),
 (22,'Masthead, second page',2,0,'',0,'','image_then_title_then_text','banner_masthead',0,0),
 (29,'News list for home page',7,0,'',0,'','standard','',0,0),
 (30,'Advanced Search',20,0,'',0,'','standard','',0,0);
ALTER TABLE `[[DB_PREFIX]]plugin_instances` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]nested_plugins` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]nested_plugins` VALUES 
 (1,4,1,0,0,'show',0,'','',0,1,0,0,0,0,0,0,60,'','','','','Slide 1','public','any',0,'','','','',1),
 (2,4,1,1,9,'show',2,'image_then_title_then_text','align_right',0,0,0,0,0,0,0,0,60,'','','','','Banner','public','any',0,'','','','',1),
 (3,4,1,2,3,'show',11,'select_list','align_right',0,0,0,0,0,0,0,0,60,'','','','','Language Picker','public','any',0,'','','','',1),
 (4,5,1,0,0,'show',0,'','',0,1,0,0,0,0,0,0,60,'','','','','Slide 1','public','any',0,'','','','',1),
 (5,5,1,1,0,'show',2,'image_then_title_then_text','',0,0,0,0,0,0,0,0,60,'','','','','slide-1.jpg','public','any',0,'','','','',1),
 (6,5,2,0,0,'show',0,'','',0,1,0,0,0,0,0,0,60,'','','','','Slide 2','public','any',0,'','','','',1),
 (7,5,2,1,0,'show',2,'image_then_title_then_text','',0,0,0,0,0,0,0,0,60,'','','','','slide-2.jpg','public','any',0,'','','','',1),
 (10,8,1,0,0,'show',0,'','',0,1,0,0,0,0,0,0,60,'','','','','Slide 1','public','any',0,'','','','',1),
 (11,8,1,1,4,'show',2,'image_then_title_then_text','animated_child_1',0,0,0,0,0,0,0,0,60,'','','','','Banner: Design Service','public','any',0,'','','','',1),
 (12,8,1,2,4,'show',2,'image_then_title_then_text','animated_child_2',0,0,0,0,0,0,0,0,60,'','','','','Banner: Development Service','public','any',0,'','','','',1),
 (13,8,1,3,4,'show',2,'image_then_title_then_text','animated_child_3',0,0,0,0,0,0,0,0,60,'','','','','Banner: Support Service','public','any',0,'','','','',1),
 (14,9,1,0,0,'show',0,'','',0,1,0,0,0,0,0,0,60,'','','','','Slide 1','public','any',0,'','','','',1),
 (15,9,1,1,0,'show',2,'image_then_title_then_text','',0,0,0,0,0,0,0,0,60,'','','','','Banner: a call to action...','public','any',0,'','','','',1),
 (16,9,1,2,4,'show',2,'image_then_title_then_text','animated_child_1',0,0,0,0,0,0,0,0,60,'','','','','Banner: Product 1','public','any',0,'','','','',1),
 (17,9,1,3,4,'show',2,'image_then_title_then_text','animated_child_1',0,0,0,0,0,0,0,0,60,'','','','','Banner: Product 2','public','any',0,'','','','',1),
 (18,9,1,4,4,'show',2,'image_then_title_then_text','animated_child_1',0,0,0,0,0,0,0,0,60,'','','','','Banner: Product 3','public','any',0,'','','','',1);
ALTER TABLE `[[DB_PREFIX]]nested_plugins` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]plugin_layout_link` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]plugin_layout_link` VALUES 
 (5,8,0,2,'Slot_Content_1'),
 (16,3,21,1,'Slot_Breadcrumbs'),
 (17,8,0,1,'Slot_Main_1'),
 (24,3,21,3,'Slot_Breadcrumbs'),
 (29,8,0,3,'Slot_Main_1');
ALTER TABLE `[[DB_PREFIX]]plugin_layout_link` ENABLE KEYS;


INSERT INTO `[[DB_PREFIX]]plugin_item_link` VALUES
 (1,13,5,1,'html',1,'Slot_Slideshow'),
 (2,2,7,1,'html',1,'Slot_Content_Image_1'),
 (3,14,8,1,'html',1,'Slot_Full_Boxes'),
 (4,14,9,1,'html',1,'Slot_Portfolio'),
 (7,2,12,1,'html',1,'Slot_Full_Banner'),
 (8,17,14,1,'html',1,'Slot_Contact_Form'),
 (10,2,22,2,'html',1,'Slot_Masthead'),
 (26,7,29,1,'html',1,'Slot_News');


ALTER TABLE `[[DB_PREFIX]]plugin_settings` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]plugin_settings` VALUES 
 (1,'canvas',0,'fixed_height','synchronized_setting','text',NULL,0,'','remove',NULL),
 (1,'height',0,'55','synchronized_setting','text',NULL,0,'','remove',NULL),
 (1,'hyperlink_target',0,'html_1','synchronized_setting','text','content',1,'html','remove',NULL),
 (1,'image',0,'1','synchronized_setting','text','file',1,'','remove',NULL),
 (1,'image_source',0,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (1,'link_type',0,'_CONTENT_ITEM','synchronized_setting','text',NULL,0,'','remove',NULL),
 (1,'mobile_behaviour',0,'mobile_same_image_different_size','synchronized_setting','text',NULL,0,'','remove',NULL),
 (1,'mobile_canvas',0,'fixed_height','synchronized_setting','text',NULL,0,'','remove',NULL),
 (1,'mobile_height',0,'30','synchronized_setting','text',NULL,0,'','remove',NULL),
 (4,'text',2,'<p class=\"phone\">[[Call us on +44 118 324 5555]]</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (4,'title_tags',2,'p','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'advanced_behaviour',5,'none','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'advanced_behaviour',7,'none','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'alt_tag',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'alt_tag',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'animation_library',0,'cycle2','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'banner_canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'banner_height',0,'775','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'banner_width',0,'2000','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'hyperlink_target',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'hyperlink_target',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'image',5,'8','synchronized_setting','text','file',8,'','remove',NULL),
 (5,'image',7,'6','synchronized_setting','text','file',6,'','remove',NULL),
 (5,'image_source',5,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'image_source',7,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'link_type',5,'_NO_LINK','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'link_type',7,'_NO_LINK','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_canvas',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_canvas',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_height',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_height',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_image',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_image',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_width',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'mobile_width',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'more_link_text',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'more_link_text',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'rollover_image',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'rollover_image',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'show_next_prev_buttons',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'target_blank',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'target_blank',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'text',5,'Its slide description goes here, which you can edit','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'text',7,'Its slide description goes here, which you can edit','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'title',5,'Slide title goes here','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'title',7,'And this is another slide, add more if you wish!','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'url',5,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (5,'url',7,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'advanced_behaviour',0,'none','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'alt_tag',0,'','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (7,'canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'enlarge_canvas',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'floating_box_title_mode',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'height',0,'466','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'hide_private_item',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'image',0,'7','synchronized_setting','text','file',7,'','remove',NULL),
 (7,'image_source',0,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'link_type',0,'_NO_LINK','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'mobile_behaviour',0,'mobile_same_image','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'mobile_canvas',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'set_an_anchor',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (7,'text',0,'<p>Add calls-to-action on your page using Banner plugins.</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (7,'title',0,'This is a Banner plugin with image','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (7,'title_tags',0,'h2','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'translate_text',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (7,'width',0,'588','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'banner_canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'banner_height',0,'150','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'banner_width',0,'150','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'eggs_equal_height',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'heading_tag',0,'p','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'heading_text',0,'SERVICES','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'image',11,'9','synchronized_setting','text','file',9,'','remove',NULL),
 (8,'image',12,'9','synchronized_setting','text','file',9,'','remove',NULL),
 (8,'image',13,'9','synchronized_setting','text','file',9,'','remove',NULL),
 (8,'image_source',11,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'image_source',12,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'image_source',13,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'show_heading',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (8,'text',11,'<p>This is a nested banner</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (8,'text',12,'<p>This is a nested banner</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (8,'text',13,'<p>This is a nested banner</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (8,'title',11,'Creative Design','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (8,'title',12,'Skillful Development','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (8,'title',13,'Brilliant Support','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'banner_canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'banner_height',0,'380','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'banner_width',0,'380','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'heading_tag',0,'p','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'heading_text',0,'PORTFOLIO','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'image',16,'4','synchronized_setting','text','file',4,'','remove',NULL),
 (9,'image',17,'9','synchronized_setting','text','file',9,'','remove',NULL),
 (9,'image',18,'3','synchronized_setting','text','file',3,'','remove',NULL),
 (9,'image_source',16,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'image_source',17,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'image_source',18,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'retina',16,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'retina',17,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'retina',18,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'show_heading',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (9,'text',15,' <p>This nested Banner has just words.</p>\n <p>The Banners below have images...</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (9,'text',16,'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing.</p>','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'text',17,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod ullamcorper nibh sit amet congue. Nullam rutrum orci vitae lacus luctus, eu facilisis urna varius. Morbi nec orci sed lacus tincidunt tincidunt sit amet et.','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'text',18,'Duis ut mi orci. Integer urna lacus, hendrerit nec arcu sit amet, bibendum pretium nulla.','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'title',15,'This is another Nest containing Banner plugins','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'title',16,'Software','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'title',17,'Hardware','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (9,'title',18,'Tools','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (12,'advanced_behaviour',0,'none','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'alt_tag',0,'','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (12,'canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'enlarge_canvas',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'floating_box_title_mode',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'height',0,'220','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'hide_private_item',0,'_ALWAYS_SHOW','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'hyperlink_target',0,'html_1','synchronized_setting','text','content',1,'html','remove',NULL),
 (12,'image',0,'2','synchronized_setting','text','file',2,'','remove',NULL),
 (12,'image_source',0,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'link_to_anchor',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (12,'link_type',0,'_CONTENT_ITEM','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'mobile_behaviour',0,'mobile_same_image','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'mobile_canvas',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'more_link_text',0,'','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (12,'set_an_anchor',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (12,'target_blank',0,'','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (12,'text',0,'<p>Set CSS for this Banner plugin: we\'ve predefined <em>align_center</em>, <em>align_left</em> and <em>align_right</em>; and <em>dark</em> and <em>light</em>.</p>\n<p>Edit CSS for Banners to add as many more styles as you like.</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (12,'title',0,'Your text can overlay an image','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (12,'title_tags',0,'h2','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'translate_text',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (12,'width',0,'1338','synchronized_setting','text',NULL,0,'','remove',NULL),
 (14,'user_form',0,'1','synchronized_setting','text','user_form',1,'','remove',NULL),
 (16,'text',0,'<p>Put your company address here.</p>','synchronized_setting','translatable_html',NULL,0,'','remove',NULL),
 (16,'title',0,'Your company name','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (17,'html',0,'<div class=\"social_links\">\n 	<a><i class=\"fa-brands fa-youtube\"></i></a>\n 	<a href=\"https://twitter.com/ZenarioCMS\" target=\"_blank\"><i class=\"fa-brands fa-twitter\"></i></a>\n </div>','synchronized_setting','html',NULL,0,'','remove',NULL),
 (19,'company_name',0,'Your Company','synchronized_setting','text',NULL,0,'','remove',NULL),
 (19,'display_single_year',0,'current_year','synchronized_setting','text',NULL,0,'','remove',NULL),
 (19,'year_display',0,'display_single_year','synchronized_setting','text',NULL,0,'','remove',NULL),
 (20,'display_mode',0,'inline_popup','synchronized_setting','text',NULL,0,'','remove',NULL),
 (20,'user_form',0,'1','synchronized_setting','text','user_form',1,'','remove',NULL),
 (22,'advanced_behaviour',0,'background_image','synchronized_setting','text',NULL,0,'','remove',NULL),
 (22,'canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (22,'height',0,'400','synchronized_setting','text',NULL,0,'','remove',NULL),
 (22,'image',0,'5','synchronized_setting','text','file',5,'','remove',NULL),
 (22,'image_source',0,'_CUSTOM_IMAGE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (22,'text',0,'<p>Design your own unique pages</p>','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (22,'title',0,'Second Page','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (22,'title_tags',0,'h1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (22,'width',0,'2000','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'canvas',0,'crop_and_zoom','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'category_filters_dropdown',0,'','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'child_item_levels',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'content_type',0,'news','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'data_field',0,'content_summary','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'date_format',0,'_RELATIVE','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'enable_omit_category',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'enable_rss',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'fall_back_to_default_image',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'heading_if_items',0,'Latest news','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (29,'heading_if_no_items',0,'There\'s no news just yet','synchronized_setting','translatable_text',NULL,0,'','remove',NULL),
 (29,'heading_tags',0,'h1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'height',0,'160','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'hide_private_items',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'language_selection',0,'visitor','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'make_content_items_equal_height',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'maximum_results_number',0,'5','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'more_link_text',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'offset',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'only_show',0,'public','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'only_show_child_items',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'order',0,'Most_Recent_First','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'page_limit',0,'9','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'page_size',0,'maximum_of','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'pagination_style',0,'zenario_common_features::pagCloseWithNPIfNeeded','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'phrase.framework.Download volume ',0,'Download volume','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'pinned_content_items',0,'prioritise_pinned','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'pinned_text',0,'Pinned','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'refine_type',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'relative_operator',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'relative_units',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'relative_value',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'release_date',0,'ignore','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_author',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_category_name',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_content_items_lowest_category',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_dates',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_headings',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_headings_if_no_items',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_language',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_more_link',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_pagination',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_permalink',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_pinned_icon',0,'to_admins_and_visitors','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_pinned_text',0,'to_admins_and_visitors','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_featured_image',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_text_preview',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'show_times',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'show_titles',0,'1','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'simple_access_cookie_required',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'target_blank',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'titles_tags',0,'h2','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'translate_text',0,'','synchronized_setting','text',NULL,0,'','remove',NULL),
 (29,'use_download_page',0,'0','synchronized_setting','empty',NULL,0,'','remove',NULL),
 (29,'width',0,'240','synchronized_setting','text',NULL,0,'','remove',NULL);
ALTER TABLE `[[DB_PREFIX]]plugin_settings` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]skins` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]skins` VALUES
 (1,'[[THEME]]','[[THEME]]','','zenario/styles/fea/fea_common.css\nzenario/styles/fea/fea_font_awesome.css','','body',1,0);
ALTER TABLE `[[DB_PREFIX]]skins` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]layout_head_and_foot` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]layout_head_and_foot` VALUES
 ('sitewide',12,769,1240,1,1,'{\"cols\": 12, \"cells\": [{\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Top\"}, {\"name\": \"Slot_Header_Top\", \"slot\": true, \"width\": 12}, {\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Header Fixed\"}, {\"name\": \"Slot_Header_Logo\", \"slot\": true, \"width\": 3}, {\"name\": \"Slot_Header_Menu\", \"slot\": true, \"small\": \"hide\", \"width\": 8}, {\"name\": \"Slot_Header_Search\", \"slot\": true, \"small\": \"hide\", \"width\": 1}, {\"name\": \"Slot_Header_Mobile_Menu\", \"slot\": true, \"small\": \"only\", \"width\": 12}], \"fluid\": true, \"mirror\": false, \"maxWidth\": 1240, \"minWidth\": 769, \"gutterFlu\": 1, \"responsive\": true, \"gutterLeftEdgeFlu\": 1.5, \"gutterRightEdgeFlu\": 1.5}','{\"cells\": [{\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Footer\"}, {\"name\": \"Slot_Footer_Address\", \"slot\": true, \"width\": 6}, {\"cells\": [{\"name\": \"Slot_Footer_Social\", \"slot\": true, \"width\": 6}, {\"name\": \"Slot_Footer_Menu\", \"slot\": true, \"width\": 6}, {\"name\": \"Slot_Footer_Copyright\", \"slot\": true, \"width\": 6}], \"width\": 6, \"css_class\": \"Grouping_Footer\"}, {\"name\": \"Slot_Footer_Contact\", \"slot\": true, \"width\": 12}]}');
ALTER TABLE `[[DB_PREFIX]]layout_head_and_foot` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]layouts` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]layouts` VALUES
 (1,'HTML Standard layout','html','active',12,769,1240,1,1,1,1,'ltr',0,'',NULL,NULL,'{\"cols\": 12, \"cells\": [{\"width\": 12, \"isHeader\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Top\"}, {\"name\": \"Slot_Header_Top\", \"slot\": true, \"width\": 12, \"isHeader\": true}, {\"width\": 12, \"isHeader\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Header Fixed\"}, {\"name\": \"Slot_Header_Logo\", \"slot\": true, \"width\": 3, \"isHeader\": true}, {\"name\": \"Slot_Header_Menu\", \"slot\": true, \"small\": \"hide\", \"width\": 8, \"isHeader\": true}, {\"name\": \"Slot_Header_Search\", \"slot\": true, \"small\": \"hide\", \"width\": 1, \"isHeader\": true}, {\"name\": \"Slot_Header_Mobile_Menu\", \"slot\": true, \"small\": \"only\", \"width\": 12, \"isHeader\": true}, {\"name\": \"Slot_Masthead\", \"slot\": true, \"width\": 12, \"grid_break\": true}, {\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Body\"}, {\"cells\": [{\"name\": \"Slot_Breadcrumbs\", \"slot\": true, \"width\": 12, \"height\": \"small\"}, {\"name\": \"Slot_Main_1\", \"slot\": true, \"width\": 12}, {\"name\": \"Slot_Main_2\", \"slot\": true, \"width\": 12}, {\"name\": \"Slot_Main_3\", \"slot\": true, \"width\": 12}], \"width\": 12, \"css_class\": \"Main_Area\"}, {\"width\": 12, \"isFooter\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Footer\"}, {\"name\": \"Slot_Footer_Address\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"cells\": [{\"name\": \"Slot_Footer_Social\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"name\": \"Slot_Footer_Menu\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"name\": \"Slot_Footer_Copyright\", \"slot\": true, \"width\": 6, \"isFooter\": true}], \"width\": 6, \"isFooter\": true, \"css_class\": \"Grouping_Footer\"}, {\"name\": \"Slot_Footer_Contact\", \"slot\": true, \"width\": 12, \"isFooter\": true}], \"fluid\": true, \"mirror\": false, \"maxWidth\": 1240, \"minWidth\": 769, \"gutterFlu\": 1, \"responsive\": true, \"headerAndFooter\": true, \"gutterLeftEdgeFlu\": 1.5, \"gutterRightEdgeFlu\": 1.5}','nufDhvob',NULL,'not_needed',NULL,0,NULL,'not_needed',NULL,0,0),
 (2,'Home Page Layout','html','active',12,769,1240,1,1,1,1,'ltr',0,'',NULL,NULL,'{\"cols\": 12, \"cells\": [{\"width\": 12, \"isHeader\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Top\"}, {\"name\": \"Slot_Header_Top\", \"slot\": true, \"width\": 12, \"isHeader\": true}, {\"width\": 12, \"isHeader\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Header Fixed\"}, {\"name\": \"Slot_Header_Logo\", \"slot\": true, \"width\": 3, \"isHeader\": true}, {\"name\": \"Slot_Header_Menu\", \"slot\": true, \"small\": \"hide\", \"width\": 8, \"isHeader\": true}, {\"name\": \"Slot_Header_Search\", \"slot\": true, \"small\": \"hide\", \"width\": 1, \"isHeader\": true}, {\"name\": \"Slot_Header_Mobile_Menu\", \"slot\": true, \"small\": \"only\", \"width\": 12, \"isHeader\": true}, {\"name\": \"Slot_Slideshow\", \"slot\": true, \"width\": 12, \"grid_break\": true}, {\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Body space_at_top\"}, {\"cells\": [{\"name\": \"Slot_Content_1\", \"slot\": true, \"width\": 6, \"height\": \"small\"}, {\"name\": \"Slot_Content_Image_1\", \"slot\": true, \"width\": 6, \"height\": \"small\"}], \"width\": 12, \"css_class\": \"Grouping_Content\"}, {\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Full_Boxes space_at_top\"}, {\"name\": \"Slot_Full_Boxes\", \"slot\": true, \"width\": 12, \"height\": \"small\"}, {\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Content space_at_top\"}, {\"name\": \"Slot_Portfolio\", \"slot\": true, \"width\": 12, \"height\": \"small\"}, {\"name\": \"Slot_Full_Banner\", \"slot\": true, \"width\": 12, \"height\": \"small\", \"css_class\": \"space_at_top\"}, {\"cells\": [{\"name\": \"Slot_News\", \"slot\": true, \"width\": 6, \"height\": \"small\"}, {\"name\": \"Slot_Contact_Form\", \"slot\": true, \"width\": 6, \"height\": \"small\"}], \"width\": 12, \"css_class\": \"Grouping_Contact space_at_top\"}, {\"name\": \"Slot_Map\", \"slot\": true, \"width\": 12, \"css_class\": \"space_at_top\", \"grid_break\": true}, {\"width\": 12, \"isFooter\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Footer\"}, {\"name\": \"Slot_Footer_Address\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"cells\": [{\"name\": \"Slot_Footer_Social\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"name\": \"Slot_Footer_Menu\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"name\": \"Slot_Footer_Copyright\", \"slot\": true, \"width\": 6, \"isFooter\": true}], \"width\": 6, \"isFooter\": true, \"css_class\": \"Grouping_Footer\"}, {\"name\": \"Slot_Footer_Contact\", \"slot\": true, \"width\": 12, \"isFooter\": true}], \"fluid\": true, \"mirror\": false, \"maxWidth\": 1240, \"minWidth\": 769, \"gutterFlu\": 1, \"responsive\": true, \"headerAndFooter\": true, \"gutterLeftEdgeFlu\": 1.5, \"gutterRightEdgeFlu\": 1.5}','dcpkbsP0','<link rel=\"stylesheet\" href=\"zenario/libs/yarn/animate.css/animate.min.css\"/>','not_needed',NULL,0,'<script type=\"text/javascript\" src=\"zenario/libs/yarn/wow.js/dist/wow.min.js\"></script>\n<script type=\"text/javascript\" src=\"zenario_custom/skins/zebra_designs/js/animation_load.js\"></script>','not_needed',NULL,0,0),
 (3,'News Layout','news','active',12,769,1240,1,1,1,1,'ltr',0,'',NULL,NULL,'{\"cols\": 12, \"cells\": [{\"width\": 12, \"isHeader\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Top\"}, {\"name\": \"Slot_Header_Top\", \"slot\": true, \"width\": 12, \"isHeader\": true}, {\"width\": 12, \"isHeader\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Header Fixed\"}, {\"name\": \"Slot_Header_Logo\", \"slot\": true, \"width\": 3, \"isHeader\": true}, {\"name\": \"Slot_Header_Menu\", \"slot\": true, \"small\": \"hide\", \"width\": 8, \"isHeader\": true}, {\"name\": \"Slot_Header_Search\", \"slot\": true, \"small\": \"hide\", \"width\": 1, \"isHeader\": true}, {\"name\": \"Slot_Header_Mobile_Menu\", \"slot\": true, \"small\": \"only\", \"width\": 12, \"isHeader\": true}, {\"name\": \"Slot_Masthead\", \"slot\": true, \"width\": 12, \"grid_break\": true}, {\"width\": 12, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Body\"}, {\"cells\": [{\"name\": \"Slot_Breadcrumbs\", \"slot\": true, \"width\": 12, \"height\": \"small\"}, {\"name\": \"Slot_Main_1\", \"slot\": true, \"width\": 12}], \"width\": 12, \"css_class\": \"Main_Area\"}, {\"width\": 12, \"isFooter\": true, \"grid_break\": true, \"grid_css_class\": \"Gridbreak_Footer\"}, {\"name\": \"Slot_Footer_Address\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"cells\": [{\"name\": \"Slot_Footer_Social\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"name\": \"Slot_Footer_Menu\", \"slot\": true, \"width\": 6, \"isFooter\": true}, {\"name\": \"Slot_Footer_Copyright\", \"slot\": true, \"width\": 6, \"isFooter\": true}], \"width\": 6, \"isFooter\": true, \"css_class\": \"Grouping_Footer\"}, {\"name\": \"Slot_Footer_Contact\", \"slot\": true, \"width\": 12, \"isFooter\": true}], \"fluid\": true, \"mirror\": false, \"maxWidth\": 1240, \"minWidth\": 769, \"gutterFlu\": 1, \"responsive\": true, \"headerAndFooter\": true, \"gutterLeftEdgeFlu\": 1.5, \"gutterRightEdgeFlu\": 1.5}','6xUNsHzd',NULL,'not_needed',NULL,0,NULL,'not_needed',NULL,0,0);
ALTER TABLE `[[DB_PREFIX]]layouts` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]layout_slot_link` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]layout_slot_link` VALUES
 (1,'Slot_Breadcrumbs',7,12,'show',0,0),
 (1,'Slot_Footer_Address',11,6,'show',0,1),
 (1,'Slot_Footer_Contact',15,12,'show',0,1),
 (1,'Slot_Footer_Copyright',14,6,'show',0,1),
 (1,'Slot_Footer_Menu',13,6,'show',0,1),
 (1,'Slot_Footer_Social',12,6,'show',0,1),
 (1,'Slot_Header_Logo',2,3,'show',1,0),
 (1,'Slot_Header_Menu',3,8,'hide',1,0),
 (1,'Slot_Header_Search',4,1,'hide',1,0),
 (1,'Slot_Header_Mobile_Menu',5,12,'only',1,0),
 (1,'Slot_Header_Top',1,12,'show',1,0),
 (1,'Slot_Main_1',8,12,'show',0,0),
 (1,'Slot_Main_2',9,12,'show',0,0),
 (1,'Slot_Main_3',10,12,'show',0,0),
 (1,'Slot_Masthead',6,12,'show',0,0),
 (2,'Slot_Contact_Form',13,6,'show',0,0),
 (2,'Slot_Content_1',7,6,'show',0,0),
 (2,'Slot_Content_Image_1',8,6,'show',0,0),
 (2,'Slot_Footer_Address',15,6,'show',0,1),
 (2,'Slot_Footer_Contact',19,12,'show',0,1),
 (2,'Slot_Footer_Copyright',18,6,'show',0,1),
 (2,'Slot_Footer_Menu',17,6,'show',0,1),
 (2,'Slot_Footer_Social',16,6,'show',0,1),
 (2,'Slot_Full_Banner',11,12,'show',0,0),
 (2,'Slot_Full_Boxes',9,12,'show',0,0),
 (2,'Slot_Header_Logo',2,3,'show',1,0),
 (2,'Slot_Header_Menu',3,8,'hide',1,0),
 (2,'Slot_Header_Search',4,1,'hide',1,0),
 (2,'Slot_Header_Mobile_Menu',5,12,'only',1,0),
 (2,'Slot_Header_Top',1,12,'show',1,0),
 (2,'Slot_Map',14,12,'show',0,0),
 (2,'Slot_News',12,6,'show',0,0),
 (2,'Slot_Portfolio',10,12,'show',0,0),
 (2,'Slot_Slideshow',6,12,'show',0,0),
 (3,'Slot_Breadcrumbs',7,12,'show',0,0),
 (3,'Slot_Footer_Address',9,6,'show',0,1),
 (3,'Slot_Footer_Contact',13,12,'show',0,1),
 (3,'Slot_Footer_Copyright',12,6,'show',0,1),
 (3,'Slot_Footer_Menu',11,6,'show',0,1),
 (3,'Slot_Footer_Social',10,6,'show',0,1),
 (3,'Slot_Header_Logo',2,3,'show',1,0),
 (3,'Slot_Header_Menu',3,8,'hide',1,0),
 (3,'Slot_Header_Search',4,1,'hide',1,0),
 (3,'Slot_Header_Mobile_Menu',5,12,'only',1,0),
 (3,'Slot_Header_Top',1,12,'show',1,0),
 (3,'Slot_Main_1',8,12,'show',0,0),
 (3,'Slot_Masthead',6,12,'show',0,0);
ALTER TABLE `[[DB_PREFIX]]layout_slot_link` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]plugin_sitewide_link` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]plugin_sitewide_link` VALUES
 (2,16,'Slot_Footer_Address'),
 (17,20,'Slot_Footer_Contact'),
 (15,19,'Slot_Footer_Copyright'),
 (4,18,'Slot_Footer_Menu'),
 (5,17,'Slot_Footer_Social'),
 (2,1,'Slot_Header_Logo'),
 (6,2,'Slot_Header_Menu'),
 (12,3,'Slot_Header_Mobile_Menu'),
 (20,30,'Slot_Header_Search'),
 (14,4,'Slot_Header_Top');
ALTER TABLE `[[DB_PREFIX]]plugin_sitewide_link` ENABLE KEYS;


ALTER TABLE `[[DB_PREFIX]]site_settings` DISABLE KEYS;
INSERT INTO `[[DB_PREFIX]]site_settings` VALUES
 ('admin_domain_is_public','1','1',0,0,0),
 ('email_address_from','[[EMAIL_ADDRESS_FROM]]','',0,0,0),
 ('email_name_from','[[admin_first_name]] [[admin_last_name]]','',0,0,0),
 ('short_checksum_length','5','',0,0,0),
 ('site_enabled','1','',0,0,0),
 ('site_disabled_message','<p>A site is being built at this location.</p><p><span class="x-small">If you are a site administrator please <a href="[[admin_link]]">click here</a> to manage your site.</span></p>','',0,0,0),
 ('site_disabled_title','Welcome','',0,0,0),
 ('sitewide_head',
 '<meta name="viewport" content="width=device-width, initial-scale=1" />\n\n<style>\n@font-face {\n\tfont-family: \'robotoregular\';\n\tsrc: url(\'zenario_custom/skins/zebra_designs/fonts/roboto-regular-webfont.woff2\') format(\'woff2\'),\n\t\t url(\'zenario_custom/skins/zebra_designs/fonts/roboto-regular-webfont.woff\') format(\'woff\');\n\tfont-weight: normal;\n\tfont-style: normal;\n}\n\n@font-face {\n\tfont-family: \'robotoitalic\';\n\tsrc: url(\'zenario_custom/skins/zebra_designs/fonts/roboto-italic-webfont.woff2\') format(\'woff2\'),\n\t\t url(\'zenario_custom/skins/zebra_designs/fonts/roboto-italic-webfont.woff\') format(\'woff\');\n\tfont-weight: normal;\n\tfont-style: normal;\n}\n\n@font-face {\n\tfont-family: \'robotolight\';\n\tsrc: url(\'zenario_custom/skins/zebra_designs/fonts/roboto-light-webfont.woff2\') format(\'woff2\'),\n\t\t url(\'zenario_custom/skins/zebra_designs/fonts/roboto-light-webfont.woff\') format(\'woff\');\n\tfont-weight: normal;\n\tfont-style: normal;\n}\n\n@font-face {\n\tfont-family: \'cardoregular\';\n\tsrc: url(\'zenario_custom/skins/zebra_designs/fonts/cardo-regular-webfont.woff2\') format(\'woff2\'),\n\t\t url(\'zenario_custom/skins/zebra_designs/fonts/cardo-regular-webfont.woff\') format(\'woff\');\n\tfont-weight: normal;\n\tfont-style: normal;\n}\n</style>',
 '',0,0,0),
 ('sitewide_foot',
 '<script type=\'text/javascript\' src=\'zenario_custom/skins/zebra_designs/js/sticky_header.js\' defer></script>\n\n\n<script>\n/* Contact popup form shows after 5 seconds */\nzOnLoad(function () {\n\t$(".zenario_user_forms.form_popup").delay(5000).fadeIn(500);\n});\n</script>',
 '',0,0,0),
 ('translations_different_aliases','','',0,0,0),
 ('translations_hide_language_code','','',0,0,0),
 ('period_to_delete_the_form_response_log_headers',30,'never_delete',0,0,0),
 ('period_to_delete_the_email_template_sending_log_headers',30,'never_delete',0,0,0),
 ('user_use_screen_name', '', 0, 0,0,0),
 ('min_extranet_user_password_length', 10, 10, 0,0,0),
 ('min_extranet_user_password_score', 3, 3, 0,0,0);
ALTER TABLE `[[DB_PREFIX]]site_settings` ENABLE KEYS;


INSERT INTO `[[DB_PREFIX]]lov_salutations` (name)
VALUES ('Dr'), ('Miss'), ('Mr'), ('Mrs'), ('Ms'), ('Mx'), ('Prof');

