# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Details
            fields:
                initial_volume:
                    plugin_setting:
                        name: initial_volume
                    label: 'Initial Volume:'
                    type: select
                    values:
                        0: "0"
                        10: "10"
                        20: "20"
                        30: "30"
                        40: "40"
                        50: "50"
                        60: "60"
                        70: "70"
                        80: "80"
                        90: "90"
                        100: "100"
                    value: "60"
                autostart:
                    plugin_setting:
                        name: autostart
                    label: 'Autostart:'
                    type: checkbox
                    value: "1"
                loop:
                    plugin_setting:
                        name: loop
                    label: 'Loop:'
                    type: checkbox
                    value: "0"
                animation:
                    plugin_setting:
                        name: animation
                    label: 'Animation:'
                    type: checkbox
                    value: "0"
                remaining:
                    plugin_setting:
                        name: remaining
                    label: 'Show Time Remaining:'
                    type: checkbox
                    value: "0"
                rtl:
                    plugin_setting:
                        name: rtl
                    label: 'RTL:'
                    type: checkbox
                    value: "0"
                show_details_and_link:
                    label: 'Show Audio details from:'
                    type: radios
                    plugin_setting:
                        name: show_details_and_link
                    values:
                        current_content_item:
                            ord: "1"
                            label: Current Content Item (this must be an Audio Content Item)
                        another_content_item:
                            ord: "2"
                            label: Another Audio Content Item
                    value: current_content_item
                    format_onchange: Yes
                another_audio:
                    label: 'Select Audio Content Item:'
                    plugin_setting:
                        name: another_audio
                        foreign_key_to: content
                    pick_items:
                        path: zenario__content/panels/content/refiners/content_type//audio//
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        select_phrase: Select Content Item...
                    validation:
                        required_if_not_hidden: Please select Content Item.
    module_class_name: zenario_ctype_audio
