# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_ctype_audio
    tabs:
        first_tab:
            label: Details
            fields:
                show_file_size:
                    label: 'Show file size'
                    plugin_setting:
                        name: show_file_size
                    type: checkbox
                autostart:
                    plugin_setting:
                        name: autostart
                    label: 'Autostart'
                    type: checkbox
                    value: "1"
                loop:
                    plugin_setting:
                        name: loop
                    label: 'Loop'
                    type: checkbox
                    value: "0"