# You must use a tab-size of 4 spaces to edit this file.
---
zenario__administration:
    panels:
        site_settings:
            priv: _PRIV_VIEW_SITE_SETTING
            title: Site Settings
            disable_periodic_refresh: true
            columns:
                name:
                    title: Settings
                    show_by_default: true
                    searchable: true
                    disallow_sorting: true
                    always_show: true
                    width: xlarge
                desc:
                    width: xxlarge
                    title: Description
                    show_by_default: true
                    disallow_sorting: true
                    always_show: true
                    searchable: true
                keywords:
                    title: Keywords
                    searchable: true
                    hidden: true
                    
            item:
                name: Settings
                names: Settings
                css_class: setting
            items:
                api_keys:
                    name: API keys
                    desc: API keys and settings for third party services.
                    keywords: key keys api dropbox captcha recaptcha google map maps translate translation tools
                categories:
                    name: Categories
                    desc: Settings for categories.
                cookies:
                    name: Cookie control
                    desc: "Settings that control when cookies are placed on a visitor's computer."
                    keywords: implied consent explicit consent message
                data_protection:
                    name: Data Protection
                    desc: "Settings that control how long data is stored and shows what data is encrypted."
                    keywords: data protection recording deletion encryption consent log two 2 factor authentication
                date_and_time:
                    name: Date and time
                    desc: Set the formats used when displaying dates and times.
                    keywords: date format date-picker format time timezone zone
                dirs:
                    name: Backups
                    desc: >
                        Settings for the backup storage directory and automated backups.
                    keywords: backup log directory
                domains:
                    priv: _PRIV_VIEW_SITE_SETTING
                    name: Domains
                    desc: Set the primary domain, admin domain and cookie domain for your site.
                    keywords: >
                        primary domain redirect admin domain
                        cookie-free domain for hosting static files
                embedding:
                    priv: _PRIV_VIEW_SITE_SETTING
                    name: Embedding
                    desc: Settings for embedding elements of this site in third-party sites
                    keywords: >
                        embed site iframe
                        X-Frame-Options ALLOWALL SAMEORIGIN
                email:
                    name: Email and newsletter
                    desc: Settings for sending emails and newsletters from this website.
                    keywords: smtp mail test send debug mode system email address from
                errors:
                    name: Error handling
                    desc: Settings for handling errors in PHP and MySQL
                    keywords: errors php warnings php notices mysql strict database
                external_programs:
                    name: Other server programs
                    desc: >
                        Setup other server programs such as
                        image optimizers and PDF readers
                    keywords: >
                        antiword pdftotext pdf-to-text pdf to text ghostscript word document
                        plain text extract plaintext extract image thumbnail
                        png jpeg jpg optimize optimise zip html->pdf word->text compress jpegs compress pngs pdf->image pdf->text
                logos_and_branding:
                    css_class: favicon
                    priv: _PRIV_VIEW_SITE_SETTING
                    name: Logos and branding
                    desc: >
                        Upload or remove the favicon, and the logo used on the site-disabled and
                        admin login screen.
                    keywords: >
                        favicon mobile icon home screen icon
                files_and_images:
                    name: Documents, images and file handling
                    desc: Settings for how documents, files and images are managed.
                    keywords: >
                        image thumbnail working copy jpeg file upload sizes
                        file download restrict by IP document
                        aws S3 enable support for aws s3
                head_and_foot:
                    name: Site-wide <head> and <body> HTML
                    desc: |
                        Add HTML to the <head> or <body> tag of all pages on your site.
                libs:
                    name: JavaScript and font libraries
                    desc: >
                        Control which JavaScript libraries/font libraries are included site-wide on the front-end.
                    keywords: library libraries js javascript font
                urls_and_xml_sitemap:
                    name: URL format, aliases and XML sitemap
                    desc: Settings that affect how URLs for your site are generated, and to enable an XML sitemap.
                    keywords: mod_rewrite suffix default behaviour for translations alias language code links
                users:
                    name: Users
                    desc: Settings that affect extranet users & contacts.
                    keywords: >
                        screen names log all sign-ins logins passwords maximum user image file sizes google bing search index sitemap url
                        country countries linked country linked countries permissions
                optimisation:
                    name: Cache
                    desc: Settings that affect or speed up web pages.
                    keywords: >
                        compress web pages quickly
                        CSS file wrappers
                        caching of SQL queries
                        query cache size
                        show SQL errors to visitors
                        show run-time notices
                        show strict errors
                        show all other errors
                        caching
                        cache web pages
                        cache plugins
                        cache AJAX and RSS
                        show debug info
                        cache stats refresh statistics
                        clear cache clear the cache
            
            # These controls don't use the usual Site Settings Admin Box,
            # but we put them here anyway as this is the logical place to look for them
                site_enabled:
                    css_class: site_enabled
                    name: Site is ENABLED
                    desc: Enable or disable this site.
                    is_not_site_setting: true
                site_disabled:
                    css_class: site_disabled
                    name: Site is DISABLED
                    desc: Enable this site.
                    is_not_site_setting: true
                site_offline:
                    css_class: site_disabled
                    name: Site is OFFLINE, awaiting language
                    desc: Zenario needs at least one language to be enabled in order to run.
                    is_not_site_setting: true
                site_reset:
                    priv: _PRIV_RESET_SITE
                    css_class: site_reset
                    name: Reset site
                    desc: Delete this entire site except for administrator accounts.
                    is_not_site_setting: true
            item_buttons:
                edit_setting:
                    label: Edit this setting
                    admin_box:
                        path: site_settings
                    visible_if_for_all_selected_items: |
                        !item.is_not_site_setting
                site_reset:
                    priv: _PRIV_RESET_SITE
                    label: Reset site
                    hide_in_select_mode: true
                    visible_if_for_all_selected_items: |
                        id == 'site_reset'
                    disabled_if: |
                        zenarioA.siteSettings.site_enabled
                    disabled_tooltip: >
                        Cannot Reset Site|You cannot reset this site while it is
                        enabled for visitors. You must disable the site before
                        resetting it.
                    admin_box:
                        path: zenario_site_reset
                disable_site:
                    priv: _PRIV_EDIT_SITE_SETTING
                    label: Change site mode
                    hide_in_select_mode: true
                    visible_if_for_all_selected_items: |
                        id == 'site_enabled'
                    admin_box:
                        path: zenario_enable_site
                enable_site:
                    priv: _PRIV_EDIT_SITE_SETTING
                    label: Enable this site
                    hide_in_select_mode: true
                    visible_if_for_all_selected_items: |
                        id == 'site_disabled'
                    admin_box:
                        path: zenario_enable_site
                
                #view_dropdown:
                #    label: View
                #    hide_when_children_are_not_visible: true
                #profile:
                #    parent: view_dropdown
                #    label: Profile
                #    admin_box:
                #        path: zenario_admin
                #        key:
                #            view_profile: "1"
                #    visible_if_for_all_selected_items: |
                #        id == 'profile'
                #action_dropdown:
                #    label: Actions
                #    hide_when_children_are_not_visible: true
                #change_password:
                #    parent: action_dropdown
                #    local_admins_only: true
                #    label: Change Password
                #    frontend_link: 'admin.php?task=change_password&og=zenario__administration/nav/configure_settings/panel//profile'
                #    visible_if_for_all_selected_items: |
                #        id == 'profile'
