# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Settings
            fields:
                location:
                    hidden: Yes
                role:
                    plugin_setting:
                        name: role
                        use_value_for_plugin_name: Yes
                    label: 'Role:'
                    pick_items:
                        path: zenario__users/nav/roles/panel
                        target_path: zenario__users/nav/roles/panel
                        min_path: zenario__users/nav/roles/panel
                        max_path: zenario__users/nav/roles/panel
                        select_phrase: Select Role...
                        nothing_selected_phrase: No Role selected
                user:
                    plugin_setting:
                        name: user
                    label: 'User:'
                    pick_items:
                        path: zenario__users/panels/users
                        target_path: zenario__users/panels/users
                        min_path: zenario__users/panels/users
                        max_path: zenario__users/panels/users
                        select_phrase: Select User...
                        nothing_selected_phrase: No User selected
                    note_below: >
                        Displays the details of the Location at which the User
                        selected above has the selected Role. If no User is
                        selected, and the Plugin is placed on the Descriptive Page
                        for a User, the Plugin will display details of the Location
                        set for this User.
    module_class_name: zenario_extranet_user_role_loc_view
