# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Display
            fields:
                use_specific_search_results_page:
                    plugin_setting:
                        name: use_specific_search_results_page
                    type: radios
                    values:
                        0:
                            ord: 1
                            label: 'Use the sitewide search results page'
                        1:
                            ord: 2
                            label: 'Use a specific search results page:'
                    redraw_onchange: true
                plugin_page_note:
                    indent: 1
                    visible_if: |
                        !zenarioAB.value('use_specific_search_results_page')
                    snippet:
                        html: |
                            When a content item is created containing the <em style="font-style: italic;">Search Results</em> plugin,
                            this plugin will automatically link to it.
                specific_search_results_page:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('use_specific_search_results_page')
                    plugin_setting:
                        name: specific_search_results_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Search Results Page:'
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        disallow_refiners_looping_on_min_path: true
                        select_phrase: select a content item...
                        hide_remove_button: true
                    validation:
                        required_if_not_hidden: Please select a content item
                search_label:
                    plugin_setting:
                        name: search_label
                    label: 'Show "Search" label'
                    type: checkbox
                    value: 0
                    format_onchange: Yes
                search_placeholder:
                    plugin_setting:
                        name: search_placeholder
                    label: 'Show "Search the site" placeholder'
                    type: checkbox
                    value: 0
                    format_onchange: Yes
                search_placeholder_phrase:
                    indent: 1
                    plugin_setting:
                        name: search_placeholder_phrase
                    label: 'Search placeholder phrase:'
                    type: text
                    format_onchange: Yes
                    visible_if:
                        lib.value: search_placeholder
                    validation:
                        required_if_not_hidden: Please enter a phrase
    module_class_name: zenario_search_entry_box
