# You must use a tab-size of 4 spaces to edit this file.
---
zenario__administration:
    panels:
        site_settings:
            items:
                videos:
                    name: Videos
                    desc: Settings for videos.
