# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            
            # As this Module inherits the Plugin Settings of the Menu Module,
            # we only need to list the names and default values of the Settings where
            # we want the default values to be different.
            
            fields:
                menu_start_from:
                    plugin_setting:
                        name: menu_start_from
                    value: _MENU_LEVEL_2
                menu_number_of_levels:
                    plugin_setting:
                        name: menu_number_of_levels
                    value: "3"
                menu_show_all_branches:
                    plugin_setting:
                        name: menu_show_all_branches
    module_class_name: zenario_menu_vertical
