# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            
            # As this Module inherits the Plugin Settings of the Menu Module,
            # we only need to list the names and default values of the Settings where
            # we want the default values to be different.
            
            fields:
                menu_start_from:
                    plugin_setting:
                        name: menu_start_from
                    value: _MENU_LEVEL_2
                menu_number_of_levels:
                    plugin_setting:
                        name: menu_number_of_levels
                    value: "3"
                menu_show_all_branches:
                    plugin_setting:
                        name: menu_show_all_branches
                show_parent_menu_node_text:
                    plugin_setting:
                        name: show_parent_menu_node_text
                    type: checkbox
                    label: "Show parent menu node text (if available)"
                change_welcome_message:
                    plugin_setting:
                        name: change_welcome_message
                    label: Customise welcome message
                    type: checkbox
                    format_onchange: true
                welcome_message:
                    indent: 1
                    plugin_setting:
                        name: welcome_message
                    type: text
                    label: Welcome message
                    visible_if: "zenarioAB.value('change_welcome_message')"
                    value: "Welcome, [[first_name]] [[last_name]]"
                    note_below: 'The framework must include the merge field "welcome_message" in order to display this.'
                    show_phrase_icon: true
                show_group_name_when_user_is_in_groups:
                    plugin_setting:
                        name: show_group_name_when_user_is_in_groups
                    type: checkbox
                    label: "Show group name when user is in the following group:"
                    redraw_onchange: true
                    note_below: 'The framework must include the merge field "groups" in order to display this.'
                user_groups:
                    indent: 1
                    plugin_setting:
                        name: user_groups
                    type: checkboxes
                    values: {}
                    #The list of values is populated in the parent module, Zenario Menu (fillAdminBox).
                    visible_if: lib.value('show_group_name_when_user_is_in_groups')
    module_class_name: zenario_menu_vertical
