# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            
            # As this Module inherits the Plugin Settings of the Menu Module,
            # we only need to list the names and default values of the Settings where
            # we want the default values to be different.
            
            fields:
                menu_number_of_levels:
                    plugin_setting:
                        name: menu_number_of_levels
                    value: "3"
                menu_show_all_branches:
                    plugin_setting:
                        name: menu_show_all_branches
                change_welcome_message:
                    plugin_setting:
                        name: change_welcome_message
                    label: Customise welcome message for extranet users
                    type: checkbox
                    format_onchange: true
                welcome_message:
                    indent: 1
                    plugin_setting:
                        name: welcome_message
                    type: text
                    label: |
                        Welcome message:
                    visible_if: "zenarioAB.value('change_welcome_message')"
                    value: "Welcome, [[first_name]] [[last_name]]"
                    show_phrase_icon: true
                show_group_name_when_user_is_in_groups:
                    indent: 1
                    plugin_setting:
                        name: show_group_name_when_user_is_in_groups
                    type: checkbox
                    label: "Show group name when user is in a group..."
                    format_onchange: true
                    visible_if: lib.value('change_welcome_message')
                user_groups:
                    indent: 2
                    plugin_setting:
                        name: user_groups
                    type: checkboxes
                    values: {}
                    #The list of values is populated in the parent module, Zenario Menu (fillAdminBox).
                    visible_if: lib.value('change_welcome_message') && lib.value('show_group_name_when_user_is_in_groups')
                    validation:
                        required_if_not_hidden: 'Please select at least one group.'
    module_class_name: zenario_menu_vertical
