"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",da

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andorra"
_COUNTRY_NAME_AE,"Forenede Arabiske Emirater"
_COUNTRY_NAME_AF,"Afghanistan"
_COUNTRY_NAME_AG,"Antigua og Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Albanien"
_COUNTRY_NAME_AM,"Armenien"
_COUNTRY_NAME_AN,"De Nederlandske Antiller"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antarktis"
_COUNTRY_NAME_AR,"Argentina"
_COUNTRY_NAME_AS,"Amerikansk Samoa"
_COUNTRY_NAME_AT,"Østrig"
_COUNTRY_NAME_AU,"Australien"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Ålandsøerne"
_COUNTRY_NAME_AZ,"Aserbajdsjan"
_COUNTRY_NAME_BA,"Bosnien-Hercegovina"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladesh"
_COUNTRY_NAME_BE,"Belgien"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgarien"
_COUNTRY_NAME_BH,"Bahrain"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"Saint-Barthélémy"
_COUNTRY_NAME_BM,"Bermuda"
_COUNTRY_NAME_BN,"Brunei Darussalam"
_COUNTRY_NAME_BO,"Bolivia, Plurinational State of"
_COUNTRY_NAME_BR,"Brasilien"
_COUNTRY_NAME_BS,"Bahamas"
_COUNTRY_NAME_BT,"Bhoutan"
_COUNTRY_NAME_BV,"Bouvet Island"
_COUNTRY_NAME_BW,"Botswana"
_COUNTRY_NAME_BY,"Hviderusland"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Canada"
_COUNTRY_NAME_CC,"Cocos (Keeling) øer"
_COUNTRY_NAME_CD,"Congo, Den Demokratiske Republik"
_COUNTRY_NAME_CF,"Den Centralafrikanske Republik"
_COUNTRY_NAME_CG,"Congo"
_COUNTRY_NAME_CH,"Schweiz"
_COUNTRY_NAME_CI,"Elfenbenskysten"
_COUNTRY_NAME_CK,"Cookøerne"
_COUNTRY_NAME_CL,"Chile"
_COUNTRY_NAME_CM,"Cameroun"
_COUNTRY_NAME_CN,"Kina"
_COUNTRY_NAME_CO,"Colombia"
_COUNTRY_NAME_CR,"Costa Rica"
_COUNTRY_NAME_CU,"Cuba"
_COUNTRY_NAME_CV,"Kap Verde"
_COUNTRY_NAME_CX,"Juleøen"
_COUNTRY_NAME_CY,"Cypern"
_COUNTRY_NAME_CZ,"Tjekkiet"
_COUNTRY_NAME_DE,"Tyskland"
_COUNTRY_NAME_DJ,"Djibouti"
_COUNTRY_NAME_DK,"Danmark"
_COUNTRY_NAME_DM,"Dominica"
_COUNTRY_NAME_DO,"Dominikanske republik"
_COUNTRY_NAME_DZ,"Algeriet"
_COUNTRY_NAME_EC,"Ecuador"
_COUNTRY_NAME_EE,"Estland"
_COUNTRY_NAME_EG,"Egypten"
_COUNTRY_NAME_EH,"Vestsahara"
_COUNTRY_NAME_ER,"Eritrea"
_COUNTRY_NAME_ES,"Spanien"
_COUNTRY_NAME_ET,"Etiopien"
_COUNTRY_NAME_FI,"Finland"
_COUNTRY_NAME_FJ,"Fiji"
_COUNTRY_NAME_FK,"Falklandsøerne (Malvinas)"
_COUNTRY_NAME_FM,"Mikronesien, Forenede Stater i"
_COUNTRY_NAME_FO,"Færøerne"
_COUNTRY_NAME_FR,"Frankrig"
_COUNTRY_NAME_GA,"Gabon"
_COUNTRY_NAME_GB,"Det Forenede Kongerige"
_COUNTRY_NAME_GD,"Grenada"
_COUNTRY_NAME_GE,"Georgien"
_COUNTRY_NAME_GF,"Fransk Guyana"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibraltar"
_COUNTRY_NAME_GL,"Grønland"
_COUNTRY_NAME_GM,"Gambia"
_COUNTRY_NAME_GN,"Guinea"
_COUNTRY_NAME_GP,"Guadeloupe"
_COUNTRY_NAME_GQ,"Ækvatorial Guinea"
_COUNTRY_NAME_GR,"Grækenland"
_COUNTRY_NAME_GS,"South Georgia og South Sandwich Islands"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Guinea-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hong Kong"
_COUNTRY_NAME_HM,"Heard Island og McDonald Islands"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Kroatien"
_COUNTRY_NAME_HT,"Haiti"
_COUNTRY_NAME_HU,"Ungarn"
_COUNTRY_NAME_ID,"Indonesien"
_COUNTRY_NAME_IE,"Irland"
_COUNTRY_NAME_IL,"Israël"
_COUNTRY_NAME_IM,"Isle of Man"
_COUNTRY_NAME_IN,"Indien"
_COUNTRY_NAME_IO,"Britisk territorium i Det Indiske Ocean"
_COUNTRY_NAME_IQ,"Irak"
_COUNTRY_NAME_IR,"Iran, Den Islamiske Republik"
_COUNTRY_NAME_IS,"Island"
_COUNTRY_NAME_IT,"Italien"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamaica"
_COUNTRY_NAME_JO,"Jordan"
_COUNTRY_NAME_JP,"Japan"
_COUNTRY_NAME_KE,"Kenya"
_COUNTRY_NAME_KG,"Kirgisistan"
_COUNTRY_NAME_KH,"Cambodja"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Comorerne"
_COUNTRY_NAME_KN,"Saint Kitts og Nevis"
_COUNTRY_NAME_KP,"Korea, Den Demokratiske Folkerepublik"
_COUNTRY_NAME_KR,"Korea, Republikken"
_COUNTRY_NAME_KW,"Kuwait"
_COUNTRY_NAME_KY,"Caymanøerne"
_COUNTRY_NAME_KZ,"Kasakhstan"
_COUNTRY_NAME_LA,"Laos Folkedemokratiske Republik"
_COUNTRY_NAME_LB,"Libanon"
_COUNTRY_NAME_LC,"Sankt Lucia"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberia"
_COUNTRY_NAME_LS,"Lesotho"
_COUNTRY_NAME_LT,"Litauen"
_COUNTRY_NAME_LU,"Luxembourg"
_COUNTRY_NAME_LV,"Letland"
_COUNTRY_NAME_LY,"Libysk arabisk Jamahiriya"
_COUNTRY_NAME_MA,"Marokko"
_COUNTRY_NAME_MC,"Monaco"
_COUNTRY_NAME_MD,"Moldova, Republikken"
_COUNTRY_NAME_ME,"Montenegro"
_COUNTRY_NAME_MF,"Saint Martin (fransk del)"
_COUNTRY_NAME_MG,"Madagaskar"
_COUNTRY_NAME_MH,"Marshalløerne"
_COUNTRY_NAME_MK,"Makedonien, Den Tidligere Jugoslaviske Republik"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Mongoliet"
_COUNTRY_NAME_MO,"Macao"
_COUNTRY_NAME_MP,"Nordmarianerne"
_COUNTRY_NAME_MQ,"Martinique"
_COUNTRY_NAME_MR,"Mauretanien"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauritius"
_COUNTRY_NAME_MV,"Maldiverne"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Mexico"
_COUNTRY_NAME_MY,"Malaysia"
_COUNTRY_NAME_MZ,"Mozambique"
_COUNTRY_NAME_NA,"Namibia"
_COUNTRY_NAME_NC,"Ny Kaledonien"
_COUNTRY_NAME_NE,"Niger"
_COUNTRY_NAME_NF,"Norfolk Island"
_COUNTRY_NAME_NG,"Nigeria"
_COUNTRY_NAME_NI,"Nicaragua"
_COUNTRY_NAME_NL,"Holland"
_COUNTRY_NAME_NO,"Norge"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"New Zealand"
_COUNTRY_NAME_OM,"Oman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Peru"
_COUNTRY_NAME_PF,"Fransk Polynesien"
_COUNTRY_NAME_PG,"Papua Ny Guinea"
_COUNTRY_NAME_PH,"Filippinerne"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Polen"
_COUNTRY_NAME_PM,"Saint Pierre og Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Puerto Rico"
_COUNTRY_NAME_PS,"Palæstinensisk territorium, besat"
_COUNTRY_NAME_PT,"Portugal"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Qatar"
_COUNTRY_NAME_RE,"Réunion"
_COUNTRY_NAME_RO,"Rumænien"
_COUNTRY_NAME_RS,"Serbien"
_COUNTRY_NAME_RU,"Den Russiske Føderation"
_COUNTRY_NAME_RW,"Rwanda"
_COUNTRY_NAME_SA,"Saudi Arabien"
_COUNTRY_NAME_SB,"Salomonøerne"
_COUNTRY_NAME_SC,"Seychellerne"
_COUNTRY_NAME_SD,"Sudan"
_COUNTRY_NAME_SE,"Sverige"
_COUNTRY_NAME_SG,"Singapore"
_COUNTRY_NAME_SH,"Sankt Helena"
_COUNTRY_NAME_SI,"Slovenien"
_COUNTRY_NAME_SJ,"Svalbard og Jan Mayen"
_COUNTRY_NAME_SK,"Slovakiet"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somalia"
_COUNTRY_NAME_SR,"Surinam"
_COUNTRY_NAME_ST,"Sao Tome og Principe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"Den Syriske Arabiske Republik"
_COUNTRY_NAME_SZ,"Swaziland"
_COUNTRY_NAME_TC,"Turks- og Caicosøerne"
_COUNTRY_NAME_TD,"Tchad"
_COUNTRY_NAME_TF,"Franske sydlige territorier"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Thailand"
_COUNTRY_NAME_TJ,"Tadsjikistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Turkmenistan"
_COUNTRY_NAME_TN,"Tunesien"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Tyrkiet"
_COUNTRY_NAME_TT,"Trinidad og Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Taiwan"
_COUNTRY_NAME_TZ,"Tanzania, Forenede Republik"
_COUNTRY_NAME_UA,"Ukraine"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"Amerikas mindre ydre øer"
_COUNTRY_NAME_US,"USA"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Usbekistan"
_COUNTRY_NAME_VA,"Holy See (Vatikanstaten)"
_COUNTRY_NAME_VC,"Saint Vincent og Grenadinerne"
_COUNTRY_NAME_VE,"Venezuela, Bolivariske Republik"
_COUNTRY_NAME_VG,"Jomfruøerne, Britisk"
_COUNTRY_NAME_VI,"Jomfruøerne, USA"
_COUNTRY_NAME_VN,"Vietnam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis og Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Yemen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"Sydafrika"
_COUNTRY_NAME_ZM,"Zambia"
_COUNTRY_NAME_ZW,"Zimbabwe"
