"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",de

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andorra"
_COUNTRY_NAME_AE,"Vereinigte Arabische Emirate"
_COUNTRY_NAME_AF,"Afghanistan"
_COUNTRY_NAME_AG,"Antigua und Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Albanien"
_COUNTRY_NAME_AM,"Armenien"
_COUNTRY_NAME_AN,"Niederländische Antillen"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antarktis"
_COUNTRY_NAME_AR,"Argentinien"
_COUNTRY_NAME_AS,"Amerikanisch-Samoa"
_COUNTRY_NAME_AT,"Österreich"
_COUNTRY_NAME_AU,"Australien"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Åland-Inseln"
_COUNTRY_NAME_AZ,"Aserbaidschan"
_COUNTRY_NAME_BA,"Bosnien und Herzegowina"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladesch"
_COUNTRY_NAME_BE,"Belgien"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgarien"
_COUNTRY_NAME_BH,"Bahrain"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"St. Barthélemy"
_COUNTRY_NAME_BM,"Bermuda"
_COUNTRY_NAME_BN,"Brunei Darussalam"
_COUNTRY_NAME_BO,"Bolivien, plurinationalen Staat"
_COUNTRY_NAME_BR,"Brasilien"
_COUNTRY_NAME_BS,"Bahamas"
_COUNTRY_NAME_BT,"Bhutan"
_COUNTRY_NAME_BV,"Bouvetinsel"
_COUNTRY_NAME_BW,"Botsuana"
_COUNTRY_NAME_BY,"Weißrussland"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Kanada"
_COUNTRY_NAME_CC,"Cocos (Keeling) Islands"
_COUNTRY_NAME_CD,"Kongo, die Demokratische Republik"
_COUNTRY_NAME_CF,"Zentralafrikanische Republik"
_COUNTRY_NAME_CG,"Kongo"
_COUNTRY_NAME_CH,"Schweiz"
_COUNTRY_NAME_CI,"Côte d'Ivoire"
_COUNTRY_NAME_CK,"Cookinseln"
_COUNTRY_NAME_CL,"Chile"
_COUNTRY_NAME_CM,"Kamerun"
_COUNTRY_NAME_CN,"Kina"
_COUNTRY_NAME_CO,"Kolumbien"
_COUNTRY_NAME_CR,"Costa Rica"
_COUNTRY_NAME_CU,"Kuba"
_COUNTRY_NAME_CV,"Kap Verde"
_COUNTRY_NAME_CX,"Weihnachtsinsel"
_COUNTRY_NAME_CY,"Zypern"
_COUNTRY_NAME_CZ,"Tschechische Republik"
_COUNTRY_NAME_DE,"Deutschland"
_COUNTRY_NAME_DJ,"Dschibuti"
_COUNTRY_NAME_DK,"Dänemark"
_COUNTRY_NAME_DM,"Dominica"
_COUNTRY_NAME_DO,"Dominikanische Republik"
_COUNTRY_NAME_DZ,"Algerien"
_COUNTRY_NAME_EC,"Ecuador"
_COUNTRY_NAME_EE,"Estland"
_COUNTRY_NAME_EG,"Ägypten"
_COUNTRY_NAME_EH,"Westsahara"
_COUNTRY_NAME_ER,"Eritrea"
_COUNTRY_NAME_ES,"Spanien"
_COUNTRY_NAME_ET,"Äthiopien"
_COUNTRY_NAME_FI,"Finnland"
_COUNTRY_NAME_FJ,"Fidschi"
_COUNTRY_NAME_FK,"Falklandinseln (Malvinas)"
_COUNTRY_NAME_FM,"Mikronesien, Föderierte Staaten von"
_COUNTRY_NAME_FO,"Färöer"
_COUNTRY_NAME_FR,"Frankreich"
_COUNTRY_NAME_GA,"Gabun"
_COUNTRY_NAME_GB,"Vereinigtes Königreich"
_COUNTRY_NAME_GD,"Grenada"
_COUNTRY_NAME_GE,"Georgien"
_COUNTRY_NAME_GF,"Französisch-Guayana"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibraltar"
_COUNTRY_NAME_GL,"Grönland"
_COUNTRY_NAME_GM,"Gambia"
_COUNTRY_NAME_GN,"Guinea"
_COUNTRY_NAME_GP,"Guadeloupe"
_COUNTRY_NAME_GQ,"Äquatorialguinea"
_COUNTRY_NAME_GR,"Griechenland"
_COUNTRY_NAME_GS,"Südgeorgien und die Südlichen Sandwichinseln"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Guinea-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hongkong"
_COUNTRY_NAME_HM,"Heard-und McDonald-Inseln"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Kroatien"
_COUNTRY_NAME_HT,"Haiti"
_COUNTRY_NAME_HU,"Ungarn"
_COUNTRY_NAME_ID,"Indonesien"
_COUNTRY_NAME_IE,"Irland"
_COUNTRY_NAME_IL,"Israel"
_COUNTRY_NAME_IM,"Isle of Man"
_COUNTRY_NAME_IN,"Indien"
_COUNTRY_NAME_IO,"Britisches Territorium im Indischen Ozean"
_COUNTRY_NAME_IQ,"Irak"
_COUNTRY_NAME_IR,"Iran, Islamische Republik"
_COUNTRY_NAME_IS,"Island"
_COUNTRY_NAME_IT,"Italien"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamaika"
_COUNTRY_NAME_JO,"Jordanien"
_COUNTRY_NAME_JP,"Japan"
_COUNTRY_NAME_KE,"Kenia"
_COUNTRY_NAME_KG,"Kirgisistan"
_COUNTRY_NAME_KH,"Kambodscha"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Komoren"
_COUNTRY_NAME_KN,"St. Kitts und Nevis"
_COUNTRY_NAME_KP,"Korea, Democratic People's Republic of"
_COUNTRY_NAME_KR,"Korea, Republik"
_COUNTRY_NAME_KW,"Kuwait"
_COUNTRY_NAME_KY,"Kaimaninseln"
_COUNTRY_NAME_KZ,"Kasachstan"
_COUNTRY_NAME_LA,"Lao People's Democratic Republic"
_COUNTRY_NAME_LB,"Libanon"
_COUNTRY_NAME_LC,"St. Lucia"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberia"
_COUNTRY_NAME_LS,"Lesotho"
_COUNTRY_NAME_LT,"Litauen"
_COUNTRY_NAME_LU,"Luxemburg"
_COUNTRY_NAME_LV,"Lettland"
_COUNTRY_NAME_LY,"Libyen"
_COUNTRY_NAME_MA,"Marokko"
_COUNTRY_NAME_MC,"Monaco"
_COUNTRY_NAME_MD,"Moldawien, Republik"
_COUNTRY_NAME_ME,"Montenegro"
_COUNTRY_NAME_MF,"St. Martin (Französisch Teil)"
_COUNTRY_NAME_MG,"Madagaskar"
_COUNTRY_NAME_MH,"Marshallinseln"
_COUNTRY_NAME_MK,"Mazedonien, ehemalige jugoslawische Republik"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Mongolei"
_COUNTRY_NAME_MO,"Macao"
_COUNTRY_NAME_MP,"Nördliche Marianen"
_COUNTRY_NAME_MQ,"Martinique"
_COUNTRY_NAME_MR,"Mauretanien"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauritius"
_COUNTRY_NAME_MV,"Malediven"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Mexiko"
_COUNTRY_NAME_MY,"Malaysia"
_COUNTRY_NAME_MZ,"Mosambik"
_COUNTRY_NAME_NA,"Namibia"
_COUNTRY_NAME_NC,"Neukaledonien"
_COUNTRY_NAME_NE,"Niger"
_COUNTRY_NAME_NF,"Norfolkinsel"
_COUNTRY_NAME_NG,"Nigeria"
_COUNTRY_NAME_NI,"Nicaragua"
_COUNTRY_NAME_NL,"Niederlande"
_COUNTRY_NAME_NO,"Norwegen"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"Neuseeland"
_COUNTRY_NAME_OM,"Oman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Peru"
_COUNTRY_NAME_PF,"Französisch-Polynesien"
_COUNTRY_NAME_PG,"Papua-Neuguinea"
_COUNTRY_NAME_PH,"Philippinen"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Polen"
_COUNTRY_NAME_PM,"St. Pierre und Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Puerto Rico"
_COUNTRY_NAME_PS,"Besetzte palästinensische Gebiete"
_COUNTRY_NAME_PT,"Portugal"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Katar"
_COUNTRY_NAME_RE,"Réunion Réunion"
_COUNTRY_NAME_RO,"Rumänien"
_COUNTRY_NAME_RS,"Serbien"
_COUNTRY_NAME_RU,"Russische Föderation"
_COUNTRY_NAME_RW,"Ruanda"
_COUNTRY_NAME_SA,"Saudi-Arabien"
_COUNTRY_NAME_SB,"Salomonen"
_COUNTRY_NAME_SC,"Seychellen"
_COUNTRY_NAME_SD,"Sudan"
_COUNTRY_NAME_SE,"Schweden"
_COUNTRY_NAME_SG,"Singapur"
_COUNTRY_NAME_SH,"St. Helena"
_COUNTRY_NAME_SI,"Slowenien"
_COUNTRY_NAME_SJ,"Svalbard und Jan Mayen"
_COUNTRY_NAME_SK,"Slowakei"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somalia"
_COUNTRY_NAME_SR,"Suriname"
_COUNTRY_NAME_ST,"São Tomé und Príncipe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"Arabische Republik Syrien"
_COUNTRY_NAME_SZ,"Swasiland"
_COUNTRY_NAME_TC,"Turks-und Caicosinseln"
_COUNTRY_NAME_TD,"Tschad"
_COUNTRY_NAME_TF,"Französisch Southern Gebiete"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Thailand"
_COUNTRY_NAME_TJ,"Tadschikistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Turkmenistan"
_COUNTRY_NAME_TN,"Tunesien"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Türkei"
_COUNTRY_NAME_TT,"Trinidad und Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Taiwan, Provinz von China"
_COUNTRY_NAME_TZ,"Tansania, Vereinigte Republik"
_COUNTRY_NAME_UA,"Ukraine"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"Amerikanisch-Ozeanien"
_COUNTRY_NAME_US,"Vereinigte Staaten"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Usbekistan"
_COUNTRY_NAME_VA,"Heiliger Stuhl (Vatikanstadt)"
_COUNTRY_NAME_VC,"St. Vincent und die Grenadinen"
_COUNTRY_NAME_VE,"Venezuela, Bolivarische Republik"
_COUNTRY_NAME_VG,"Britische Jungferninseln"
_COUNTRY_NAME_VI,"Virgin Islands, US"
_COUNTRY_NAME_VN,"Viet Nam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis und Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Jemen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"Südafrika"
_COUNTRY_NAME_ZM,"Sambia"
_COUNTRY_NAME_ZW,"Simbabwe"