"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andorra"
_COUNTRY_NAME_AE,"United Arab Emirates"
_COUNTRY_NAME_AF,"Afghanistan"
_COUNTRY_NAME_AG,"Antigua and Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Albania"
_COUNTRY_NAME_AM,"Armenia"
_COUNTRY_NAME_AN,"Netherlands Antilles"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antarctica"
_COUNTRY_NAME_AR,"Argentina"
_COUNTRY_NAME_AS,"American Samoa"
_COUNTRY_NAME_AT,"Austria"
_COUNTRY_NAME_AU,"Australia"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Åland Islands"
_COUNTRY_NAME_AZ,"Azerbaijan"
_COUNTRY_NAME_BA,"Bosnia and Herzegovina"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladesh"
_COUNTRY_NAME_BE,"Belgium"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgaria"
_COUNTRY_NAME_BH,"Bahrain"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"Saint Barthélemy"
_COUNTRY_NAME_BM,"Bermuda"
_COUNTRY_NAME_BN,"Brunei Darussalam"
_COUNTRY_NAME_BO,"Bolivia, Plurinational State of"
_COUNTRY_NAME_BR,"Brazil"
_COUNTRY_NAME_BS,"Bahamas"
_COUNTRY_NAME_BT,"Bhutan"
_COUNTRY_NAME_BV,"Bouvet Island"
_COUNTRY_NAME_BW,"Botswana"
_COUNTRY_NAME_BY,"Belarus"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Canada"
_COUNTRY_NAME_CC,"Cocos (Keeling) Islands"
_COUNTRY_NAME_CD,"Congo, the Democratic Republic of the"
_COUNTRY_NAME_CF,"Central African Republic"
_COUNTRY_NAME_CG,"Congo"
_COUNTRY_NAME_CH,"Switzerland"
_COUNTRY_NAME_CI,"Côte d'Ivoire"
_COUNTRY_NAME_CK,"Cook Islands"
_COUNTRY_NAME_CL,"Chile"
_COUNTRY_NAME_CM,"Cameroon"
_COUNTRY_NAME_CN,"China"
_COUNTRY_NAME_CO,"Colombia"
_COUNTRY_NAME_CR,"Costa Rica"
_COUNTRY_NAME_CU,"Cuba"
_COUNTRY_NAME_CV,"Cape Verde"
_COUNTRY_NAME_CX,"Christmas Island"
_COUNTRY_NAME_CY,"Cyprus"
_COUNTRY_NAME_CZ,"Czech Republic"
_COUNTRY_NAME_DE,"Germany"
_COUNTRY_NAME_DJ,"Djibouti"
_COUNTRY_NAME_DK,"Denmark"
_COUNTRY_NAME_DM,"Dominica"
_COUNTRY_NAME_DO,"Dominican Republic"
_COUNTRY_NAME_DZ,"Algeria"
_COUNTRY_NAME_EC,"Ecuador"
_COUNTRY_NAME_EE,"Estonia"
_COUNTRY_NAME_EG,"Egypt"
_COUNTRY_NAME_EH,"Western Sahara"
_COUNTRY_NAME_ER,"Eritrea"
_COUNTRY_NAME_ES,"Spain"
_COUNTRY_NAME_ET,"Ethiopia"
_COUNTRY_NAME_FI,"Finland"
_COUNTRY_NAME_FJ,"Fiji"
_COUNTRY_NAME_FK,"Falkland Islands (Malvinas)"
_COUNTRY_NAME_FM,"Micronesia, Federated States of"
_COUNTRY_NAME_FO,"Faroe Islands"
_COUNTRY_NAME_FR,"France"
_COUNTRY_NAME_GA,"Gabon"
_COUNTRY_NAME_GB,"United Kingdom"
_COUNTRY_NAME_GD,"Grenada"
_COUNTRY_NAME_GE,"Georgia"
_COUNTRY_NAME_GF,"French Guiana"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibraltar"
_COUNTRY_NAME_GL,"Greenland"
_COUNTRY_NAME_GM,"Gambia"
_COUNTRY_NAME_GN,"Guinea"
_COUNTRY_NAME_GP,"Guadeloupe"
_COUNTRY_NAME_GQ,"Equatorial Guinea"
_COUNTRY_NAME_GR,"Greece"
_COUNTRY_NAME_GS,"South Georgia and the South Sandwich Islands"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Guinea-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hong Kong"
_COUNTRY_NAME_HM,"Heard Island and McDonald Islands"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Croatia"
_COUNTRY_NAME_HT,"Haiti"
_COUNTRY_NAME_HU,"Hungary"
_COUNTRY_NAME_ID,"Indonesia"
_COUNTRY_NAME_IE,"Ireland"
_COUNTRY_NAME_IL,"Israel"
_COUNTRY_NAME_IM,"Isle of Man"
_COUNTRY_NAME_IN,"India"
_COUNTRY_NAME_IO,"British Indian Ocean Territory"
_COUNTRY_NAME_IQ,"Iraq"
_COUNTRY_NAME_IR,"Iran, Islamic Republic of"
_COUNTRY_NAME_IS,"Iceland"
_COUNTRY_NAME_IT,"Italy"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamaica"
_COUNTRY_NAME_JO,"Jordan"
_COUNTRY_NAME_JP,"Japan"
_COUNTRY_NAME_KE,"Kenya"
_COUNTRY_NAME_KG,"Kyrgyzstan"
_COUNTRY_NAME_KH,"Cambodia"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Comoros"
_COUNTRY_NAME_KN,"Saint Kitts and Nevis"
_COUNTRY_NAME_KP,"Korea, Democratic People's Republic of"
_COUNTRY_NAME_KR,"Korea, Republic of"
_COUNTRY_NAME_KW,"Kuwait"
_COUNTRY_NAME_KY,"Cayman Islands"
_COUNTRY_NAME_KZ,"Kazakhstan"
_COUNTRY_NAME_LA,"Lao People's Democratic Republic"
_COUNTRY_NAME_LB,"Lebanon"
_COUNTRY_NAME_LC,"Saint Lucia"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberia"
_COUNTRY_NAME_LS,"Lesotho"
_COUNTRY_NAME_LT,"Lithuania"
_COUNTRY_NAME_LU,"Luxembourg"
_COUNTRY_NAME_LV,"Latvia"
_COUNTRY_NAME_LY,"Libyan Arab Jamahiriya"
_COUNTRY_NAME_MA,"Morocco"
_COUNTRY_NAME_MC,"Monaco"
_COUNTRY_NAME_MD,"Moldova, Republic of"
_COUNTRY_NAME_ME,"Montenegro"
_COUNTRY_NAME_MF,"Saint Martin (French part)"
_COUNTRY_NAME_MG,"Madagascar"
_COUNTRY_NAME_MH,"Marshall Islands"
_COUNTRY_NAME_MK,"Macedonia, the former Yugoslav Republic of"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Mongolia"
_COUNTRY_NAME_MO,"Macao"
_COUNTRY_NAME_MP,"Northern Mariana Islands"
_COUNTRY_NAME_MQ,"Martinique"
_COUNTRY_NAME_MR,"Mauritania"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauritius"
_COUNTRY_NAME_MV,"Maldives"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Mexico"
_COUNTRY_NAME_MY,"Malaysia"
_COUNTRY_NAME_MZ,"Mozambique"
_COUNTRY_NAME_NA,"Namibia"
_COUNTRY_NAME_NC,"New Caledonia"
_COUNTRY_NAME_NE,"Niger"
_COUNTRY_NAME_NF,"Norfolk Island"
_COUNTRY_NAME_NG,"Nigeria"
_COUNTRY_NAME_NI,"Nicaragua"
_COUNTRY_NAME_NL,"Netherlands"
_COUNTRY_NAME_NO,"Norway"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"New Zealand"
_COUNTRY_NAME_OM,"Oman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Peru"
_COUNTRY_NAME_PF,"French Polynesia"
_COUNTRY_NAME_PG,"Papua New Guinea"
_COUNTRY_NAME_PH,"Philippines"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Poland"
_COUNTRY_NAME_PM,"Saint Pierre and Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Puerto Rico"
_COUNTRY_NAME_PS,"Palestinian Territory, Occupied"
_COUNTRY_NAME_PT,"Portugal"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Qatar"
_COUNTRY_NAME_RE,"Réunion"
_COUNTRY_NAME_RO,"Romania"
_COUNTRY_NAME_RS,"Serbia"
_COUNTRY_NAME_RU,"Russian Federation"
_COUNTRY_NAME_RW,"Rwanda"
_COUNTRY_NAME_SA,"Saudi Arabia"
_COUNTRY_NAME_SB,"Solomon Islands"
_COUNTRY_NAME_SC,"Seychelles"
_COUNTRY_NAME_SD,"Sudan"
_COUNTRY_NAME_SE,"Sweden"
_COUNTRY_NAME_SG,"Singapore"
_COUNTRY_NAME_SH,"Saint Helena"
_COUNTRY_NAME_SI,"Slovenia"
_COUNTRY_NAME_SJ,"Svalbard and Jan Mayen"
_COUNTRY_NAME_SK,"Slovakia"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somalia"
_COUNTRY_NAME_SR,"Suriname"
_COUNTRY_NAME_ST,"Sao Tome and Principe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"Syrian Arab Republic"
_COUNTRY_NAME_SZ,"Swaziland"
_COUNTRY_NAME_TC,"Turks and Caicos Islands"
_COUNTRY_NAME_TD,"Chad"
_COUNTRY_NAME_TF,"French Southern Territories"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Thailand"
_COUNTRY_NAME_TJ,"Tajikistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Turkmenistan"
_COUNTRY_NAME_TN,"Tunisia"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Turkey"
_COUNTRY_NAME_TT,"Trinidad and Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Taiwan"
_COUNTRY_NAME_TZ,"Tanzania, United Republic of"
_COUNTRY_NAME_UA,"Ukraine"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"United States Minor Outlying Islands"
_COUNTRY_NAME_US,"United States"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Uzbekistan"
_COUNTRY_NAME_VA,"Holy See (Vatican City State)"
_COUNTRY_NAME_VC,"Saint Vincent and the Grenadines"
_COUNTRY_NAME_VE,"Venezuela, Bolivarian Republic of"
_COUNTRY_NAME_VG,"Virgin Islands, British"
_COUNTRY_NAME_VI,"Virgin Islands, U.S."
_COUNTRY_NAME_VN,"Vietnam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis and Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Yemen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"South Africa"
_COUNTRY_NAME_ZM,"Zambia"
_COUNTRY_NAME_ZW,"Zimbabwe"