"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",es

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andorra"
_COUNTRY_NAME_AE,"Emiratos Árabes Unidos"
_COUNTRY_NAME_AF,"Afganistán"
_COUNTRY_NAME_AG,"Antigua y Barbuda"
_COUNTRY_NAME_AI,"Anguila"
_COUNTRY_NAME_AL,"Albania"
_COUNTRY_NAME_AM,"Armenia"
_COUNTRY_NAME_AN,"Antillas Neerlandesas"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antártida"
_COUNTRY_NAME_AR,"Argentina"
_COUNTRY_NAME_AS,"Samoa Americana"
_COUNTRY_NAME_AT,"Austria"
_COUNTRY_NAME_AU,"Australia"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Islas √Öland"
_COUNTRY_NAME_AZ,"Azerbaiyán"
_COUNTRY_NAME_BA,"Bosnia y Herzegovina"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladesh"
_COUNTRY_NAME_BE,"Bélgica"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgaria"
_COUNTRY_NAME_BH,"Bahrein"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"San Bartolomé"
_COUNTRY_NAME_BM,"Bermudas"
_COUNTRY_NAME_BN,"Brunei Darussalam"
_COUNTRY_NAME_BO,"Bolivia, el Estado Plurinacional de"
_COUNTRY_NAME_BR,"Brasil"
_COUNTRY_NAME_BS,"Bahamas"
_COUNTRY_NAME_BT,"Bhután"
_COUNTRY_NAME_BV,"Isla Bouvet"
_COUNTRY_NAME_BW,"Botswana"
_COUNTRY_NAME_BY,"Belarús"
_COUNTRY_NAME_BZ,"Belice"
_COUNTRY_NAME_CA,"Canadá"
_COUNTRY_NAME_CC,"Islas Cocos (Keeling) Islands"
_COUNTRY_NAME_CD,"Congo, la República Democrática del"
_COUNTRY_NAME_CF,"República Centroafricana"
_COUNTRY_NAME_CG,"Congo"
_COUNTRY_NAME_CH,"Suiza"
_COUNTRY_NAME_CI,"C√¥te d'Ivoire"
_COUNTRY_NAME_CK,"Islas Cook"
_COUNTRY_NAME_CL,"Chile"
_COUNTRY_NAME_CM,"Camerún"
_COUNTRY_NAME_CN,"China"
_COUNTRY_NAME_CO,"Colombia"
_COUNTRY_NAME_CR,"Costa Rica"
_COUNTRY_NAME_CU,"Cuba"
_COUNTRY_NAME_CV,"Cabo Verde"
_COUNTRY_NAME_CX,"Isla de Navidad"
_COUNTRY_NAME_CY,"Chipre"
_COUNTRY_NAME_CZ,"República Checa"
_COUNTRY_NAME_DE,"Alemania"
_COUNTRY_NAME_DJ,"Djibouti"
_COUNTRY_NAME_DK,"Dinamarca"
_COUNTRY_NAME_DM,"Dominica"
_COUNTRY_NAME_DO,"República Dominicana"
_COUNTRY_NAME_DZ,"Argelia"
_COUNTRY_NAME_EC,"Ecuador"
_COUNTRY_NAME_EE,"Estonia"
_COUNTRY_NAME_EG,"Egipto"
_COUNTRY_NAME_EH,"Sáhara Occidental"
_COUNTRY_NAME_ER,"Eritrea"
_COUNTRY_NAME_ES,"España"
_COUNTRY_NAME_ET,"Etiopía"
_COUNTRY_NAME_FI,"Finlandia"
_COUNTRY_NAME_FJ,"Fiji"
_COUNTRY_NAME_FK,"Islas Malvinas (Falkland)"
_COUNTRY_NAME_FM,"Micronesia, Estados Federados de"
_COUNTRY_NAME_FO,"Islas Feroe"
_COUNTRY_NAME_FR,"Francia"
_COUNTRY_NAME_GA,"Gabón"
_COUNTRY_NAME_GB,"Reino Unido"
_COUNTRY_NAME_GD,"Granada"
_COUNTRY_NAME_GE,"Georgia"
_COUNTRY_NAME_GF,"Francés Guayana"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibraltar"
_COUNTRY_NAME_GL,"Groenlandia"
_COUNTRY_NAME_GM,"Gambia"
_COUNTRY_NAME_GN,"Guinea"
_COUNTRY_NAME_GP,"Guadalupe"
_COUNTRY_NAME_GQ,"Guinea Ecuatorial"
_COUNTRY_NAME_GR,"Grecia"
_COUNTRY_NAME_GS,"Georgia del Sur e Islas Sandwich del Sur"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Guinea-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hong Kong"
_COUNTRY_NAME_HM,"Islas Heard y McDonald Islas"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Croacia"
_COUNTRY_NAME_HT,"Haití"
_COUNTRY_NAME_HU,"Hungría"
_COUNTRY_NAME_ID,"Indonesia"
_COUNTRY_NAME_IE,"Irlanda"
_COUNTRY_NAME_IL,"Israel"
_COUNTRY_NAME_IM,"Isla de Man"
_COUNTRY_NAME_IN,"India"
_COUNTRY_NAME_IO,"British Indian Ocean Territory"
_COUNTRY_NAME_IQ,"Iraq"
_COUNTRY_NAME_IR,"Irán, República Islámica del"
_COUNTRY_NAME_IS,"Islandia"
_COUNTRY_NAME_IT,"Italia"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamaica"
_COUNTRY_NAME_JO,"Jordania"
_COUNTRY_NAME_JP,"Japón"
_COUNTRY_NAME_KE,"Kenya"
_COUNTRY_NAME_KG,"Kirguistán"
_COUNTRY_NAME_KH,"Camboya"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Comoras"
_COUNTRY_NAME_KN,"Saint Kitts y Nevis"
_COUNTRY_NAME_KP,"Corea, República Popular Democrática de"
_COUNTRY_NAME_KR,"De Corea, República de"
_COUNTRY_NAME_KW,"Kuwait"
_COUNTRY_NAME_KY,"Islas Caimán"
_COUNTRY_NAME_KZ,"Kazajstán"
_COUNTRY_NAME_LA,"Democrática Popular Lao"
_COUNTRY_NAME_LB,"Líbano"
_COUNTRY_NAME_LC,"Santa Lucía"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberia"
_COUNTRY_NAME_LS,"Lesotho"
_COUNTRY_NAME_LT,"Lituania"
_COUNTRY_NAME_LU,"Luxemburgo"
_COUNTRY_NAME_LV,"Letonia"
_COUNTRY_NAME_LY,"Jamahiriya Árabe Libia"
_COUNTRY_NAME_MA,"Marruecos"
_COUNTRY_NAME_MC,"Mónaco"
_COUNTRY_NAME_MD,"Moldova, República de"
_COUNTRY_NAME_ME,"Montenegro"
_COUNTRY_NAME_MF,"San Martín (parte francesa)"
_COUNTRY_NAME_MG,"Madagascar"
_COUNTRY_NAME_MH,"Islas Marshall"
_COUNTRY_NAME_MK,"Macedonia, la ex República Yugoslava de"
_COUNTRY_NAME_ML,"Malí"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Mongolia"
_COUNTRY_NAME_MO,"Macao"
_COUNTRY_NAME_MP,"Islas Marianas del Norte"
_COUNTRY_NAME_MQ,"Martinica"
_COUNTRY_NAME_MR,"Mauritania"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauricio"
_COUNTRY_NAME_MV,"Maldivas"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"México"
_COUNTRY_NAME_MY,"Malasia"
_COUNTRY_NAME_MZ,"Mozambique"
_COUNTRY_NAME_NA,"Namibia"
_COUNTRY_NAME_NC,"Nueva Caledonia"
_COUNTRY_NAME_NE,"Níger"
_COUNTRY_NAME_NF,"Norfolk Island"
_COUNTRY_NAME_NG,"Nigeria"
_COUNTRY_NAME_NI,"Nicaragua"
_COUNTRY_NAME_NL,"Países Bajos"
_COUNTRY_NAME_NO,"Noruega"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"Nueva Zelanda"
_COUNTRY_NAME_OM,"Omán"
_COUNTRY_NAME_PA,"Panamá"
_COUNTRY_NAME_PE,"Perú"
_COUNTRY_NAME_PF,"Polinesia francés"
_COUNTRY_NAME_PG,"Papua Nueva Guinea"
_COUNTRY_NAME_PH,"Filipinas"
_COUNTRY_NAME_PK,"Pakistán"
_COUNTRY_NAME_PL,"Polonia"
_COUNTRY_NAME_PM,"San Pedro y Miquelón"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Puerto Rico"
_COUNTRY_NAME_PS,"Palestina, Territorios Ocupados"
_COUNTRY_NAME_PT,"Portugal"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Qatar"
_COUNTRY_NAME_RE,"Reunion"
_COUNTRY_NAME_RO,"Rumania"
_COUNTRY_NAME_RS,"Serbia"
_COUNTRY_NAME_RU,"Federación de Rusia"
_COUNTRY_NAME_RW,"Rwanda"
_COUNTRY_NAME_SA,"Arabia Saudita"
_COUNTRY_NAME_SB,"Islas Salomón"
_COUNTRY_NAME_SC,"Seychelles"
_COUNTRY_NAME_SD,"Sudán"
_COUNTRY_NAME_SE,"Suecia"
_COUNTRY_NAME_SG,"Singapur"
_COUNTRY_NAME_SH,"Santa Elena"
_COUNTRY_NAME_SI,"Eslovenia"
_COUNTRY_NAME_SJ,"Svalbard y Jan Mayen"
_COUNTRY_NAME_SK,"Eslovaquia"
_COUNTRY_NAME_SL,"Sierra Leona"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somalia"
_COUNTRY_NAME_SR,"Suriname"
_COUNTRY_NAME_ST,"Santo Tomé y Príncipe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"República Árabe Siria"
_COUNTRY_NAME_SZ,"Swazilandia"
_COUNTRY_NAME_TC,"Islas Turcas y Caicos"
_COUNTRY_NAME_TD,"Chad"
_COUNTRY_NAME_TF,"Territorios del sur francés"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Tailandia"
_COUNTRY_NAME_TJ,"Tayikistán"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Turkmenistán"
_COUNTRY_NAME_TN,"Túnez"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Turquía"
_COUNTRY_NAME_TT,"Trinidad y Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Taiwán"
_COUNTRY_NAME_TZ,"Tanzania, República Unida de"
_COUNTRY_NAME_UA,"Ucrania"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"Estados Unidos Islas Menores"
_COUNTRY_NAME_US,"Estados Unidos"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Uzbekistán"
_COUNTRY_NAME_VA,"Santa Sede (Ciudad del Vaticano)"
_COUNTRY_NAME_VC,"San Vicente y las Granadinas"
_COUNTRY_NAME_VE,"Venezuela, República Bolivariana de"
_COUNTRY_NAME_VG,"Islas Vírgenes Británicas"
_COUNTRY_NAME_VI,"Islas Vírgenes, EE.UU."
_COUNTRY_NAME_VN,"Viet Nam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis y Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Yemen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"Sudáfrica"
_COUNTRY_NAME_ZM,"Zambia"
_COUNTRY_NAME_ZW,"Zimbabwe"
