"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",fr

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andorre"
_COUNTRY_NAME_AE,"Émirats arabes unis"
_COUNTRY_NAME_AF,"Afghanistan"
_COUNTRY_NAME_AG,"Antigua et Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Albanie"
_COUNTRY_NAME_AM,"Arménie"
_COUNTRY_NAME_AN,"Antilles néerlandaises"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antarctique"
_COUNTRY_NAME_AR,"Argentine"
_COUNTRY_NAME_AS,"Samoa américaines"
_COUNTRY_NAME_AT,"Autriche"
_COUNTRY_NAME_AU,"Australie"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Îles Åland"
_COUNTRY_NAME_AZ,"Azerbaïdjan"
_COUNTRY_NAME_BA,"Bosnie-Herzégovine"
_COUNTRY_NAME_BB,"Barbade"
_COUNTRY_NAME_BD,"Bangladesh"
_COUNTRY_NAME_BE,"Belgique"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgarie"
_COUNTRY_NAME_BH,"Bahreïn"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Bénin"
_COUNTRY_NAME_BL,"Saint-Barthélémy"
_COUNTRY_NAME_BM,"Bermudes"
_COUNTRY_NAME_BN,"Brunéi Darussalam"
_COUNTRY_NAME_BO,"Bolivie, État plurinational de"
_COUNTRY_NAME_BR,"Brésil"
_COUNTRY_NAME_BS,"Bahamas"
_COUNTRY_NAME_BT,"Bhoutan"
_COUNTRY_NAME_BV,"Île Bouvet"
_COUNTRY_NAME_BW,"Botswana"
_COUNTRY_NAME_BY,"Bélarus"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Canada"
_COUNTRY_NAME_CC,"Cocos (Keeling) Islands"
_COUNTRY_NAME_CD,"Congo, République démocratique du"
_COUNTRY_NAME_CF,"République centrafricaine"
_COUNTRY_NAME_CG,"Congo"
_COUNTRY_NAME_CH,"Suisse"
_COUNTRY_NAME_CI,"Côte d'Ivoire"
_COUNTRY_NAME_CK,"Îles Cook"
_COUNTRY_NAME_CL,"Chili"
_COUNTRY_NAME_CM,"Cameroun"
_COUNTRY_NAME_CN,"Chine"
_COUNTRY_NAME_CO,"Colombie"
_COUNTRY_NAME_CR,"Costa Rica"
_COUNTRY_NAME_CU,"Cuba"
_COUNTRY_NAME_CV,"Cap-Vert"
_COUNTRY_NAME_CX,"Île Christmas"
_COUNTRY_NAME_CY,"Chypre"
_COUNTRY_NAME_CZ,"République tchèque"
_COUNTRY_NAME_DE,"Allemagne"
_COUNTRY_NAME_DJ,"Djibouti"
_COUNTRY_NAME_DK,"Danemark"
_COUNTRY_NAME_DM,"Dominique"
_COUNTRY_NAME_DO,"République dominicaine"
_COUNTRY_NAME_DZ,"Algérie"
_COUNTRY_NAME_EC,"Équateur"
_COUNTRY_NAME_EE,"Estonie"
_COUNTRY_NAME_EG,"Égypte"
_COUNTRY_NAME_EH,"Sahara occidental"
_COUNTRY_NAME_ER,"Érythrée"
_COUNTRY_NAME_ES,"Espagne"
_COUNTRY_NAME_ET,"Éthiopie"
_COUNTRY_NAME_FI,"Finlande"
_COUNTRY_NAME_FJ,"Fidji"
_COUNTRY_NAME_FK,"Iles Falkland (Malvinas)"
_COUNTRY_NAME_FM,"Micronésie, États fédérés de"
_COUNTRY_NAME_FO,"Îles Féroé"
_COUNTRY_NAME_FR,"France"
_COUNTRY_NAME_GA,"Gabon"
_COUNTRY_NAME_GB,"Royaume-Uni"
_COUNTRY_NAME_GD,"Grenade"
_COUNTRY_NAME_GE,"Géorgie"
_COUNTRY_NAME_GF,"Guyane française"
_COUNTRY_NAME_GG,"Guernesey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibraltar"
_COUNTRY_NAME_GL,"Groenland"
_COUNTRY_NAME_GM,"Gambie"
_COUNTRY_NAME_GN,"Guinée"
_COUNTRY_NAME_GP,"Guadeloupe"
_COUNTRY_NAME_GQ,"Guinée équatoriale"
_COUNTRY_NAME_GR,"Grèce"
_COUNTRY_NAME_GS,"Géorgie du Sud et les Îles Sandwich du Sud"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Guinée-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hong Kong"
_COUNTRY_NAME_HM,"Îles Heard et MacDonald"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Croatie"
_COUNTRY_NAME_HT,"Haïti"
_COUNTRY_NAME_HU,"Hongrie"
_COUNTRY_NAME_ID,"Indonésie"
_COUNTRY_NAME_IE,"Irlande"
_COUNTRY_NAME_IL,"Israël"
_COUNTRY_NAME_IM,"Ile de Man"
_COUNTRY_NAME_IN,"Inde"
_COUNTRY_NAME_IO,"Territoire britannique de l'océan Indien"
_COUNTRY_NAME_IQ,"Iraq"
_COUNTRY_NAME_IR,"Iran, République islamique d '"
_COUNTRY_NAME_IS,"Islande"
_COUNTRY_NAME_IT,"Italie"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamaïque"
_COUNTRY_NAME_JO,"Jordanie"
_COUNTRY_NAME_JP,"Japon"
_COUNTRY_NAME_KE,"Kenya"
_COUNTRY_NAME_KG,"Kirghizistan"
_COUNTRY_NAME_KH,"Cambodge"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Comores"
_COUNTRY_NAME_KN,"Saint Kitts et Nevis"
_COUNTRY_NAME_KP,"Corée, République populaire démocratique de"
_COUNTRY_NAME_KR,"Corée, République de"
_COUNTRY_NAME_KW,"Koweït"
_COUNTRY_NAME_KY,"Îles Caïmans"
_COUNTRY_NAME_KZ,"Kazakhstan"
_COUNTRY_NAME_LA,"Lao People's Republic"
_COUNTRY_NAME_LB,"Liban"
_COUNTRY_NAME_LC,"Sainte-Lucie"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Libéria"
_COUNTRY_NAME_LS,"Lesotho"
_COUNTRY_NAME_LT,"Lituanie"
_COUNTRY_NAME_LU,"Luxembourg"
_COUNTRY_NAME_LV,"Lettonie"
_COUNTRY_NAME_LY,"Jamahiriya arabe libyenne"
_COUNTRY_NAME_MA,"Maroc"
_COUNTRY_NAME_MC,"Monaco"
_COUNTRY_NAME_MD,"Moldova, République de"
_COUNTRY_NAME_ME,"Monténégro"
_COUNTRY_NAME_MF,"Saint-Martin (partie française)"
_COUNTRY_NAME_MG,"Madagascar"
_COUNTRY_NAME_MH,"Îles Marshall"
_COUNTRY_NAME_MK,"Macédoine, ancienne République yougoslave de"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Mongolie"
_COUNTRY_NAME_MO,"Macao"
_COUNTRY_NAME_MP,"Îles Mariannes du Nord"
_COUNTRY_NAME_MQ,"Martinique"
_COUNTRY_NAME_MR,"Mauritanie"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malte"
_COUNTRY_NAME_MU,"Maurice"
_COUNTRY_NAME_MV,"Maldives"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Mexique"
_COUNTRY_NAME_MY,"Malaisie"
_COUNTRY_NAME_MZ,"Mozambique"
_COUNTRY_NAME_NA,"Namibie"
_COUNTRY_NAME_NC,"Nouvelle-Calédonie"
_COUNTRY_NAME_NE,"Niger"
_COUNTRY_NAME_NF,"Île Norfolk"
_COUNTRY_NAME_NG,"Nigéria"
_COUNTRY_NAME_NI,"Nicaragua"
_COUNTRY_NAME_NL,"Pays-Bas"
_COUNTRY_NAME_NO,"Norvège"
_COUNTRY_NAME_NP,"Népal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"Nouvelle-Zélande"
_COUNTRY_NAME_OM,"Oman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Pérou"
_COUNTRY_NAME_PF,"Polynésie française"
_COUNTRY_NAME_PG,"Papouasie-Nouvelle-Guinée"
_COUNTRY_NAME_PH,"Philippines"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Pologne"
_COUNTRY_NAME_PM,"Saint-Pierre-et-Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Porto Rico"
_COUNTRY_NAME_PS,"Territoire palestinien occupé,"
_COUNTRY_NAME_PT,"Portugal"
_COUNTRY_NAME_PW,"Palaos"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Qatar"
_COUNTRY_NAME_RE,"Reunion"
_COUNTRY_NAME_RO,"Roumanie"
_COUNTRY_NAME_RS,"Serbie"
_COUNTRY_NAME_RU,"Fédération de Russie"
_COUNTRY_NAME_RW,"Rwanda"
_COUNTRY_NAME_SA,"Arabie Saoudite"
_COUNTRY_NAME_SB,"Îles Salomon"
_COUNTRY_NAME_SC,"Seychelles"
_COUNTRY_NAME_SD,"Soudan"
_COUNTRY_NAME_SE,"Suède"
_COUNTRY_NAME_SG,"Singapour"
_COUNTRY_NAME_SH,"Sainte-Hélène"
_COUNTRY_NAME_SI,"Slovénie"
_COUNTRY_NAME_SJ,"Svalbard et Île Jan Mayen"
_COUNTRY_NAME_SK,"Slovaquie"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"Saint-Marin"
_COUNTRY_NAME_SN,"Sénégal"
_COUNTRY_NAME_SO,"Somalie"
_COUNTRY_NAME_SR,"Suriname"
_COUNTRY_NAME_ST,"São Tomé et Príncipe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"République arabe syrienne"
_COUNTRY_NAME_SZ,"Swaziland"
_COUNTRY_NAME_TC,"Îles Turks et Caïques"
_COUNTRY_NAME_TD,"Tchad"
_COUNTRY_NAME_TF,"Terres australes françaises"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Thaïlande"
_COUNTRY_NAME_TJ,"Tadjikistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Turkménistan"
_COUNTRY_NAME_TN,"Tunisie"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Turquie"
_COUNTRY_NAME_TT,"Trinidad et Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Taïwan"
_COUNTRY_NAME_TZ,"Tanzanie, République-Unie de"
_COUNTRY_NAME_UA,"Ukraine"
_COUNTRY_NAME_UG,"Ouganda"
_COUNTRY_NAME_UM,"Îles mineures éloignées des états-unis"
_COUNTRY_NAME_US,"États-Unis"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Ouzbékistan"
_COUNTRY_NAME_VA,"Saint-Siège (Vatican City State)"
_COUNTRY_NAME_VC,"Saint Vincent et les Grenadines"
_COUNTRY_NAME_VE,"Venezuela, République bolivarienne du"
_COUNTRY_NAME_VG,"Îles Vierges britanniques"
_COUNTRY_NAME_VI,"Iles Vierges américaines"
_COUNTRY_NAME_VN,"Viet Nam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis et Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Yémen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"Afrique du Sud"
_COUNTRY_NAME_ZM,"Zambie"
_COUNTRY_NAME_ZW,"Zimbabwe"