"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",it

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andorra"
_COUNTRY_NAME_AE,"Emirati Arabi Uniti"
_COUNTRY_NAME_AF,"Afghanistan"
_COUNTRY_NAME_AG,"Antigua e Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Albania"
_COUNTRY_NAME_AM,"Armenia"
_COUNTRY_NAME_AN,"Antille Olandesi"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antartide"
_COUNTRY_NAME_AR,"Argentina"
_COUNTRY_NAME_AS,"Samoa Americane"
_COUNTRY_NAME_AT,"Austria"
_COUNTRY_NAME_AU,"Australia"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Isole Åland"
_COUNTRY_NAME_AZ,"Azerbaijan"
_COUNTRY_NAME_BA,"Bosnia-Erzegovina"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladesh"
_COUNTRY_NAME_BE,"Belgio"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgaria"
_COUNTRY_NAME_BH,"Bahrain"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"Saint-Barthélemy"
_COUNTRY_NAME_BM,"Bermuda"
_COUNTRY_NAME_BN,"Brunei Darussalam"
_COUNTRY_NAME_BO,"Bolivia"
_COUNTRY_NAME_BR,"Brasile"
_COUNTRY_NAME_BS,"Bahamas"
_COUNTRY_NAME_BT,"Bhutan"
_COUNTRY_NAME_BV,"Isola Bouvet"
_COUNTRY_NAME_BW,"Botswana"
_COUNTRY_NAME_BY,"Bielorussia"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Canada"
_COUNTRY_NAME_CC,"Isole Cocos e Keeling"
_COUNTRY_NAME_CD,"Repubblica Democratica del Congo"
_COUNTRY_NAME_CF,"Repubblica Centrafricana"
_COUNTRY_NAME_CG,"Congo"
_COUNTRY_NAME_CH,"Svizzera"
_COUNTRY_NAME_CI,"Costa d'Avorio"
_COUNTRY_NAME_CK,"Isole Cook "
_COUNTRY_NAME_CL,"Cile"
_COUNTRY_NAME_CM,"Camerun"
_COUNTRY_NAME_CN,"Cina"
_COUNTRY_NAME_CO,"Colombia"
_COUNTRY_NAME_CR,"Costarica"
_COUNTRY_NAME_CU,"Cuba"
_COUNTRY_NAME_CV,"Capo Verde"
_COUNTRY_NAME_CX,"Isola di Natale"
_COUNTRY_NAME_CY,"Cipro"
_COUNTRY_NAME_CZ,"Repubblica Ceca"
_COUNTRY_NAME_DE,"Germania"
_COUNTRY_NAME_DJ,"Gibuti"
_COUNTRY_NAME_DK,"Danimarca"
_COUNTRY_NAME_DM,"Dominica"
_COUNTRY_NAME_DO,"Repubblica Dominicana"
_COUNTRY_NAME_DZ,"Algeria"
_COUNTRY_NAME_EC,"Ecuador"
_COUNTRY_NAME_EE,"Estonia"
_COUNTRY_NAME_EG,"Egitto"
_COUNTRY_NAME_EH,"Sahara occidentale"
_COUNTRY_NAME_ER,"Eritrea"
_COUNTRY_NAME_ES,"Spagna"
_COUNTRY_NAME_ET,"Etiopia"
_COUNTRY_NAME_FI,"Finlandia"
_COUNTRY_NAME_FJ,"Fiji"
_COUNTRY_NAME_FK,"Isole Falkland (Malvinas)"
_COUNTRY_NAME_FM,"Stati Federati di Micronesi"
_COUNTRY_NAME_FO,"Isole Fær Øer"
_COUNTRY_NAME_FR,"Francia"
_COUNTRY_NAME_GA,"Gabon"
_COUNTRY_NAME_GB,"Regno Unito"
_COUNTRY_NAME_GD,"Grenada"
_COUNTRY_NAME_GE,"Georgia"
_COUNTRY_NAME_GF,"Guyana Francese"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibilterra"
_COUNTRY_NAME_GL,"Groenlandia"
_COUNTRY_NAME_GM,"Gambia"
_COUNTRY_NAME_GN,"Guinea"
_COUNTRY_NAME_GP,"Guadalupa"
_COUNTRY_NAME_GQ,"Guinea equatoriale"
_COUNTRY_NAME_GR,"Grecia"
_COUNTRY_NAME_GS,"Georgia del Sud e isole Sandwich Australi"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Guinea-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hong Kong"
_COUNTRY_NAME_HM,"Isole Heard e McDonald"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Croazia"
_COUNTRY_NAME_HT,"Haiti"
_COUNTRY_NAME_HU,"Ungheria"
_COUNTRY_NAME_ID,"Indonesia"
_COUNTRY_NAME_IE,"Irlanda"
_COUNTRY_NAME_IL,"Israele"
_COUNTRY_NAME_IM,"Isola di Man"
_COUNTRY_NAME_IN,"India"
_COUNTRY_NAME_IO,"Territorio britannico dell'Oceano Indiano"
_COUNTRY_NAME_IQ,"Iraq"
_COUNTRY_NAME_IR,"Iran"
_COUNTRY_NAME_IS,"Islanda"
_COUNTRY_NAME_IT,"Italia"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Giamaica"
_COUNTRY_NAME_JO,"Giordania"
_COUNTRY_NAME_JP,"Giappone"
_COUNTRY_NAME_KE,"Kenia"
_COUNTRY_NAME_KG,"Kirghizistan"
_COUNTRY_NAME_KH,"Cambogia"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Comore"
_COUNTRY_NAME_KN,"Saint Kitts e Nevis"
_COUNTRY_NAME_KP,"Repubblica Democratica Popolare di Corea"
_COUNTRY_NAME_KR,"Repubblica di Corea"
_COUNTRY_NAME_KW,"Kuwait"
_COUNTRY_NAME_KY,"Isole Cayman"
_COUNTRY_NAME_KZ,"Kazakhstan"
_COUNTRY_NAME_LA,"Repubblica Democratica Popolare del Laos"
_COUNTRY_NAME_LB,"Libano"
_COUNTRY_NAME_LC,"Santa Lucia"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberia"
_COUNTRY_NAME_LS,"Lesoto"
_COUNTRY_NAME_LT,"Lituania"
_COUNTRY_NAME_LU,"Lussemburgo"
_COUNTRY_NAME_LV,"Lettonia"
_COUNTRY_NAME_LY,"Libyan Arab Jamahiriya"
_COUNTRY_NAME_MA,"Marocco"
_COUNTRY_NAME_MC,"Monaco"
_COUNTRY_NAME_MD,"Moldavia"
_COUNTRY_NAME_ME,"Montenegro"
_COUNTRY_NAME_MF,"Saint Martin (parte francese)"
_COUNTRY_NAME_MG,"Madagascar"
_COUNTRY_NAME_MH,"Isole Marshall"
_COUNTRY_NAME_MK,"Macedonia"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Mongolia"
_COUNTRY_NAME_MO,"Macao"
_COUNTRY_NAME_MP,"Isole Marianne Settentrionali"
_COUNTRY_NAME_MQ,"Martinica"
_COUNTRY_NAME_MR,"Mauritania"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauritius"
_COUNTRY_NAME_MV,"Maldive"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Messico"
_COUNTRY_NAME_MY,"Malaysia"
_COUNTRY_NAME_MZ,"Mozambico"
_COUNTRY_NAME_NA,"Namibia"
_COUNTRY_NAME_NC,"Nuova Caledonia"
_COUNTRY_NAME_NE,"Niger"
_COUNTRY_NAME_NF,"Isole Norfolk "
_COUNTRY_NAME_NG,"Nigeria"
_COUNTRY_NAME_NI,"Nicaragua"
_COUNTRY_NAME_NL,"Paesi Bassi"
_COUNTRY_NAME_NO,"Norvegia"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"Nuova Zelanda"
_COUNTRY_NAME_OM,"Oman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Perù"
_COUNTRY_NAME_PF,"Polinesia Francese"
_COUNTRY_NAME_PG,"Papua Nuova Guinea"
_COUNTRY_NAME_PH,"Filippine"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Polonia"
_COUNTRY_NAME_PM,"Saint-Pierre e Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Porto Rico"
_COUNTRY_NAME_PS,"Territorio palestinese occupato"
_COUNTRY_NAME_PT,"Portogallo"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Qatar"
_COUNTRY_NAME_RE,"Reunion Réunion"
_COUNTRY_NAME_RO,"Romania"
_COUNTRY_NAME_RS,"Serbia"
_COUNTRY_NAME_RU,"Federazione Russa"
_COUNTRY_NAME_RW,"Ruanda"
_COUNTRY_NAME_SA,"Arabia Saudita"
_COUNTRY_NAME_SB,"Isole Salomone"
_COUNTRY_NAME_SC,"Seychelles"
_COUNTRY_NAME_SD,"Sudan"
_COUNTRY_NAME_SE,"Svezia"
_COUNTRY_NAME_SG,"Singapore"
_COUNTRY_NAME_SH,"Saint Helena"
_COUNTRY_NAME_SI,"Slovenia"
_COUNTRY_NAME_SJ,"Svalbard e Jan Mayen"
_COUNTRY_NAME_SK,"Slovacchia"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somalia"
_COUNTRY_NAME_SR,"Suriname"
_COUNTRY_NAME_ST,"Sao Tome e Principe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"Repubblica araba siriana"
_COUNTRY_NAME_SZ,"Swaziland"
_COUNTRY_NAME_TC,"Isole Turks e Caicos"
_COUNTRY_NAME_TD,"Ciad"
_COUNTRY_NAME_TF,"Territori Francesi del Sud"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Thailandia"
_COUNTRY_NAME_TJ,"Tagikistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Turkmenistan"
_COUNTRY_NAME_TN,"Tunisia"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Turchia"
_COUNTRY_NAME_TT,"Trinidad e Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Taiwan"
_COUNTRY_NAME_TZ,"Repubblica Unita di Tanzania"
_COUNTRY_NAME_UA,"Ucraina"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"Isole Minori degli Stati Uniti "
_COUNTRY_NAME_US,"Stati Uniti"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Uzbekistan"
_COUNTRY_NAME_VA,"Città del Vaticano"
_COUNTRY_NAME_VC,"Saint Vincent e Grenadine"
_COUNTRY_NAME_VE,"Repubblica Bolivariana del Venezuela"
_COUNTRY_NAME_VG,"Isole Vergini Britanniche"
_COUNTRY_NAME_VI,"Isole Vergini Americane"
_COUNTRY_NAME_VN,"Vietnam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis e Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Yemen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"Sudafrica"
_COUNTRY_NAME_ZM,"Zambia"
_COUNTRY_NAME_ZW,"Zimbabwe"