"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",pl

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andora"
_COUNTRY_NAME_AE,"Zjednoczone Emiraty Arabskie"
_COUNTRY_NAME_AF,"Afganistan"
_COUNTRY_NAME_AG,"Antigua i Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Albania"
_COUNTRY_NAME_AM,"Armenia"
_COUNTRY_NAME_AN,"Antyle Holenderskie"
_COUNTRY_NAME_AO,"Angola"
_COUNTRY_NAME_AQ,"Antarktyka"
_COUNTRY_NAME_AR,"Argentyna"
_COUNTRY_NAME_AS,"Samoa Amerykańskie"
_COUNTRY_NAME_AT,"Austria"
_COUNTRY_NAME_AU,"Australia"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Wyspy Alandzkie"
_COUNTRY_NAME_AZ,"Azerbejdżan"
_COUNTRY_NAME_BA,"Bośnia i Hercegowina"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladesz"
_COUNTRY_NAME_BE,"Belgia"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bułgaria"
_COUNTRY_NAME_BH,"Bahrajn"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"Saint Barthélemy"
_COUNTRY_NAME_BM,"Bermudy"
_COUNTRY_NAME_BN,"Brunei Darussalam"
_COUNTRY_NAME_BO,"Boliwia, Plurinational państwa"
_COUNTRY_NAME_BR,"Brazylia"
_COUNTRY_NAME_BS,"Bahamy"
_COUNTRY_NAME_BT,"Bhutan"
_COUNTRY_NAME_BV,"Wyspa Bouveta"
_COUNTRY_NAME_BW,"Botswana"
_COUNTRY_NAME_BY,"Białoruś"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Kanada"
_COUNTRY_NAME_CC,"Wyspy Kokosowe (Keelinga)"
_COUNTRY_NAME_CD,"Kongo, Demokratyczna Republika"
_COUNTRY_NAME_CF,"Republika Środkowoafrykańska"
_COUNTRY_NAME_CG,"Kongo"
_COUNTRY_NAME_CH,"Szwajcaria"
_COUNTRY_NAME_CI,"Wybrzeże Kości Słoniowej"
_COUNTRY_NAME_CK,"Wyspy Cooka"
_COUNTRY_NAME_CL,"Chile"
_COUNTRY_NAME_CM,"Kamerun"
_COUNTRY_NAME_CN,"Chiny"
_COUNTRY_NAME_CO,"Kolumbia"
_COUNTRY_NAME_CR,"Kostaryka"
_COUNTRY_NAME_CU,"Kuba"
_COUNTRY_NAME_CV,"Wyspy Zielonego Przylądka"
_COUNTRY_NAME_CX,"Wyspa Bożego Narodzenia"
_COUNTRY_NAME_CY,"Cypr"
_COUNTRY_NAME_CZ,"Czechy"
_COUNTRY_NAME_DE,"Niemcy"
_COUNTRY_NAME_DJ,"Dżibuti"
_COUNTRY_NAME_DK,"Dania"
_COUNTRY_NAME_DM,"Dominika"
_COUNTRY_NAME_DO,"Dominikana"
_COUNTRY_NAME_DZ,"Algieria"
_COUNTRY_NAME_EC,"Ekwador"
_COUNTRY_NAME_EE,"Estonia"
_COUNTRY_NAME_EG,"Egipt"
_COUNTRY_NAME_EH,"Sahara Zachodnia"
_COUNTRY_NAME_ER,"Erytrea"
_COUNTRY_NAME_ES,"Hiszpania"
_COUNTRY_NAME_ET,"Etiopia"
_COUNTRY_NAME_FI,"Finlandia"
_COUNTRY_NAME_FJ,"Fidżi"
_COUNTRY_NAME_FK,"Falklandy (Malwiny)"
_COUNTRY_NAME_FM,"Mikronezja, Sfederowane Stany"
_COUNTRY_NAME_FO,"Wyspy Owcze"
_COUNTRY_NAME_FR,"Francja"
_COUNTRY_NAME_GA,"Gabon"
_COUNTRY_NAME_GB,"Wielka Brytania"
_COUNTRY_NAME_GD,"Grenada"
_COUNTRY_NAME_GE,"Gruzja"
_COUNTRY_NAME_GF,"Gujana Francuska"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Ghana"
_COUNTRY_NAME_GI,"Gibraltar"
_COUNTRY_NAME_GL,"Grenlandia"
_COUNTRY_NAME_GM,"Gambia"
_COUNTRY_NAME_GN,"Gwinea"
_COUNTRY_NAME_GP,"Gwadelupa"
_COUNTRY_NAME_GQ,"Gwinea Równikowa"
_COUNTRY_NAME_GR,"Grecja"
_COUNTRY_NAME_GS,"Georgia Południowa i Sandwich Południowy"
_COUNTRY_NAME_GT,"Gwatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Gwinea Bissau"
_COUNTRY_NAME_GY,"Gujana"
_COUNTRY_NAME_HK,"Hongkong"
_COUNTRY_NAME_HM,"Wyspy Heard i McDonalda"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Chorwacja"
_COUNTRY_NAME_HT,"Haiti"
_COUNTRY_NAME_HU,"Węgry"
_COUNTRY_NAME_ID,"Indonezja"
_COUNTRY_NAME_IE,"Irlandia"
_COUNTRY_NAME_IL,"Izrael"
_COUNTRY_NAME_IM,"Wyspa Man"
_COUNTRY_NAME_IN,"Indie"
_COUNTRY_NAME_IO,"Brytyjskie Terytorium Oceanu Indyjskiego"
_COUNTRY_NAME_IQ,"Irak"
_COUNTRY_NAME_IR,"Iran"
_COUNTRY_NAME_IS,"Islandia"
_COUNTRY_NAME_IT,"Włochy"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamajka"
_COUNTRY_NAME_JO,"Jordania"
_COUNTRY_NAME_JP,"Japonia"
_COUNTRY_NAME_KE,"Kenia"
_COUNTRY_NAME_KG,"Kirgistan"
_COUNTRY_NAME_KH,"Kambodża"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Komory"
_COUNTRY_NAME_KN,"Saint Kitts i Nevis"
_COUNTRY_NAME_KP,"Korea Północna"
_COUNTRY_NAME_KR,"Korea Południowa"
_COUNTRY_NAME_KW,"Kuwejt"
_COUNTRY_NAME_KY,"Kajmany"
_COUNTRY_NAME_KZ,"Kazachstan"
_COUNTRY_NAME_LA,"Laotańska Republika Ludowo-Demokratyczna"
_COUNTRY_NAME_LB,"Liban"
_COUNTRY_NAME_LC,"Saint Lucia"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberia"
_COUNTRY_NAME_LS,"Lesotho"
_COUNTRY_NAME_LT,"Litwa"
_COUNTRY_NAME_LU,"Luksemburg"
_COUNTRY_NAME_LV,"Łotwa"
_COUNTRY_NAME_LY,"Libia"
_COUNTRY_NAME_MA,"Maroko"
_COUNTRY_NAME_MC,"Monako"
_COUNTRY_NAME_MD,"Republika Mołdawii"
_COUNTRY_NAME_ME,"Czarnogóra"
_COUNTRY_NAME_MF,"Saint Martin (francuska część)"
_COUNTRY_NAME_MG,"Madagaskar"
_COUNTRY_NAME_MH,"Wyspy Marshalla"
_COUNTRY_NAME_MK,"Macedonia, Była Jugosłowiańska Republika"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Birma"
_COUNTRY_NAME_MN,"Mongolia"
_COUNTRY_NAME_MO,"Makau"
_COUNTRY_NAME_MP,"Mariany Północne"
_COUNTRY_NAME_MQ,"Martynika"
_COUNTRY_NAME_MR,"Mauretania"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauritius"
_COUNTRY_NAME_MV,"Malediwy"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Meksyk"
_COUNTRY_NAME_MY,"Malezja"
_COUNTRY_NAME_MZ,"Mozambik"
_COUNTRY_NAME_NA,"Namibia"
_COUNTRY_NAME_NC,"Nowa Kaledonia"
_COUNTRY_NAME_NE,"Niger"
_COUNTRY_NAME_NF,"Wyspa Norfolk"
_COUNTRY_NAME_NG,"Nigeria"
_COUNTRY_NAME_NI,"Nikaragua"
_COUNTRY_NAME_NL,"Holandia"
_COUNTRY_NAME_NO,"Norwegia"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"Nowa Zelandia"
_COUNTRY_NAME_OM,"Oman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Peru"
_COUNTRY_NAME_PF,"Polinezja Francuska"
_COUNTRY_NAME_PG,"Papua-Nowa Gwinea"
_COUNTRY_NAME_PH,"Filipiny"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Polska"
_COUNTRY_NAME_PM,"Saint-Pierre i Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Portoryko"
_COUNTRY_NAME_PS,"Okupowane Terytorium Palestyny"
_COUNTRY_NAME_PT,"Portugalia"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paragwaj"
_COUNTRY_NAME_QA,"Katar"
_COUNTRY_NAME_RE,"Reunion"
_COUNTRY_NAME_RO,"Rumunia"
_COUNTRY_NAME_RS,"Serbia"
_COUNTRY_NAME_RU,"Federacja Rosyjska"
_COUNTRY_NAME_RW,"Rwanda"
_COUNTRY_NAME_SA,"Arabia Saudyjska"
_COUNTRY_NAME_SB,"Wyspy Salomona"
_COUNTRY_NAME_SC,"Seszele"
_COUNTRY_NAME_SD,"Sudan"
_COUNTRY_NAME_SE,"Szwecja"
_COUNTRY_NAME_SG,"Singapur"
_COUNTRY_NAME_SH,"Święta Helena"
_COUNTRY_NAME_SI,"Słowenia"
_COUNTRY_NAME_SJ,"Svalbard i Jan Mayen"
_COUNTRY_NAME_SK,"Słowacja"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somalia"
_COUNTRY_NAME_SR,"Surinam"
_COUNTRY_NAME_ST,"Wyspy Świętego Tomasza i Książęca"
_COUNTRY_NAME_SV,"Salwador"
_COUNTRY_NAME_SY,"Syryjska Republika Arabska"
_COUNTRY_NAME_SZ,"Suazi"
_COUNTRY_NAME_TC,"Turks i Caicos"
_COUNTRY_NAME_TD,"Czad"
_COUNTRY_NAME_TF,"Francuskie Terytoria Południowe"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Tajlandia"
_COUNTRY_NAME_TJ,"Tadżykistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor Wschodni"
_COUNTRY_NAME_TM,"Turkmenistan"
_COUNTRY_NAME_TN,"Tunezja"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Turcja"
_COUNTRY_NAME_TT,"Trynidad i Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Tajwan"
_COUNTRY_NAME_TZ,"Tanzania, Zjednoczona Republika"
_COUNTRY_NAME_UA,"Ukraina"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"Dalekie Wyspy Mniejsze Stanów Zjednoczonych"
_COUNTRY_NAME_US,"Stany Zjednoczone"
_COUNTRY_NAME_UY,"Urugwaj"
_COUNTRY_NAME_UZ,"Uzbekistan"
_COUNTRY_NAME_VA,"Stolica Apostolska (Państwo Watykańskie)"
_COUNTRY_NAME_VC,"Saint Vincent i Grenadyny"
_COUNTRY_NAME_VE,"Wenezuela, Boliwariańska Republika"
_COUNTRY_NAME_VG,"Brytyjskie Wyspy Dziewicze"
_COUNTRY_NAME_VI,"Wyspy Dziewicze Stanów Zjednoczonych"
_COUNTRY_NAME_VN,"Wietnam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis i Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Jemen"
_COUNTRY_NAME_YT,"Majotta"
_COUNTRY_NAME_ZA,"Republika Południowej Afryki"
_COUNTRY_NAME_ZM,"Zambia"
_COUNTRY_NAME_ZW,"Zimbabwe"
