"<?php if (!defined('NOT_ACCESSED_DIRETLY')) exit; ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",tr

Plugin
zenario_country_manager

"Phrase Code",Translation
_COUNTRY_NAME_AD,"Andora"
_COUNTRY_NAME_AE,"Birleşik Arap Emirlikleri"
_COUNTRY_NAME_AF,"Afganistan"
_COUNTRY_NAME_AG,"Antigua ve Barbuda"
_COUNTRY_NAME_AI,"Anguilla"
_COUNTRY_NAME_AL,"Arnavutluk"
_COUNTRY_NAME_AM,"Ermenistan"
_COUNTRY_NAME_AN,"Hollanda Antilleri"
_COUNTRY_NAME_AO,"Angora"
_COUNTRY_NAME_AQ,"Antartika"
_COUNTRY_NAME_AR,"Arjantin"
_COUNTRY_NAME_AS,"Amerikan Samoası"
_COUNTRY_NAME_AT,"Avusturya"
_COUNTRY_NAME_AU,"Avustralya"
_COUNTRY_NAME_AW,"Aruba"
_COUNTRY_NAME_AX,"Åland Adaları"
_COUNTRY_NAME_AZ,"Azerbeycan"
_COUNTRY_NAME_BA,"Bosna-Hersek"
_COUNTRY_NAME_BB,"Barbados"
_COUNTRY_NAME_BD,"Bangladeş"
_COUNTRY_NAME_BE,"Belçika"
_COUNTRY_NAME_BF,"Burkina Faso"
_COUNTRY_NAME_BG,"Bulgaristan"
_COUNTRY_NAME_BH,"Bahreyn"
_COUNTRY_NAME_BI,"Burundi"
_COUNTRY_NAME_BJ,"Benin"
_COUNTRY_NAME_BL,"Saint Barthélemy"
_COUNTRY_NAME_BM,"Bermuda"
_COUNTRY_NAME_BN,"Brunei Sultanlığı"
_COUNTRY_NAME_BO,"Bolivya, Çokuluslu Devlet"
_COUNTRY_NAME_BR,"Brezilya"
_COUNTRY_NAME_BS,"Bahamalar"
_COUNTRY_NAME_BT,"Butan"
_COUNTRY_NAME_BV,"Bouvet Adası"
_COUNTRY_NAME_BW,"Botsvana"
_COUNTRY_NAME_BY,"Beyazrusya"
_COUNTRY_NAME_BZ,"Belize"
_COUNTRY_NAME_CA,"Kanada"
_COUNTRY_NAME_CC,"Cocos (Keeling) Islands"
_COUNTRY_NAME_CD,"Kongo Demokratik Cumhuriyeti"
_COUNTRY_NAME_CF,"Orta Afrika Cumhuriyeti"
_COUNTRY_NAME_CG,"Kongo"
_COUNTRY_NAME_CH,"İsviçre"
_COUNTRY_NAME_CI,"Cote d'Ivoire"
_COUNTRY_NAME_CK,"Cook Adaları"
_COUNTRY_NAME_CL,"Şili"
_COUNTRY_NAME_CM,"Kamerun"
_COUNTRY_NAME_CN,"Çin"
_COUNTRY_NAME_CO,"Kolombiya"
_COUNTRY_NAME_CR,"Kostarika"
_COUNTRY_NAME_CU,"Küba"
_COUNTRY_NAME_CV,"Cape Verde"
_COUNTRY_NAME_CX,"Christmas Adası"
_COUNTRY_NAME_CY,"Kıbrıs"
_COUNTRY_NAME_CZ,"Çek Cumhuriyeti"
_COUNTRY_NAME_DE,"Almanya"
_COUNTRY_NAME_DJ,"Cibuti"
_COUNTRY_NAME_DK,"Danimarka"
_COUNTRY_NAME_DM,"Dominika"
_COUNTRY_NAME_DO,"Dominik Cumhuriyeti"
_COUNTRY_NAME_DZ,"Cezayir"
_COUNTRY_NAME_EC,"Ekvador"
_COUNTRY_NAME_EE,"Estonya"
_COUNTRY_NAME_EG,"Mısır"
_COUNTRY_NAME_EH,"Batı Sahara"
_COUNTRY_NAME_ER,"Eritre"
_COUNTRY_NAME_ES,"İspanya"
_COUNTRY_NAME_ET,"Etiyopya"
_COUNTRY_NAME_FI,"Finlandiya"
_COUNTRY_NAME_FJ,"Fiji"
_COUNTRY_NAME_FK,"Falkland Adaları (Malvinas)"
_COUNTRY_NAME_FM,"Mikronezya, Federe Devletleri"
_COUNTRY_NAME_FO,"Faroe Adaları"
_COUNTRY_NAME_FR,"Fransa"
_COUNTRY_NAME_GA,"Gabon"
_COUNTRY_NAME_GB,"Büyük Britanya"
_COUNTRY_NAME_GD,"Grenada"
_COUNTRY_NAME_GE,"Georgia"
_COUNTRY_NAME_GF,"Fransız Guyanası"
_COUNTRY_NAME_GG,"Guernsey"
_COUNTRY_NAME_GH,"Gana"
_COUNTRY_NAME_GI,"Cebelitarık"
_COUNTRY_NAME_GL,"Grönland"
_COUNTRY_NAME_GM,"Gambiya"
_COUNTRY_NAME_GN,"Gine"
_COUNTRY_NAME_GP,"Guadeloupe"
_COUNTRY_NAME_GQ,"Ekvator Ginesi"
_COUNTRY_NAME_GR,"Yunanistan"
_COUNTRY_NAME_GS,"Güney Georgia ve Güney Sandwich Adaları"
_COUNTRY_NAME_GT,"Guatemala"
_COUNTRY_NAME_GU,"Guam"
_COUNTRY_NAME_GW,"Gine-Bissau"
_COUNTRY_NAME_GY,"Guyana"
_COUNTRY_NAME_HK,"Hong Kong"
_COUNTRY_NAME_HM,"Heard Adası ve McDonald Adaları"
_COUNTRY_NAME_HN,"Honduras"
_COUNTRY_NAME_HR,"Hırvatistan"
_COUNTRY_NAME_HT,"Haiti"
_COUNTRY_NAME_HU,"Macaristan"
_COUNTRY_NAME_ID,"Endonezya"
_COUNTRY_NAME_IE,"İrlanda"
_COUNTRY_NAME_IL,"İsrail"
_COUNTRY_NAME_IM,"Isle of Man"
_COUNTRY_NAME_IN,"Hindistan"
_COUNTRY_NAME_IO,"İngiliz Hint Okyanusu Toprakları"
_COUNTRY_NAME_IQ,"Irak"
_COUNTRY_NAME_IR,"İran İslam Cumhuriyeti"
_COUNTRY_NAME_IS,"İzlanda"
_COUNTRY_NAME_IT,"İtalya"
_COUNTRY_NAME_JE,"Jersey"
_COUNTRY_NAME_JM,"Jamaika"
_COUNTRY_NAME_JO,"Ürdün"
_COUNTRY_NAME_JP,"Japonya"
_COUNTRY_NAME_KE,"Kenya"
_COUNTRY_NAME_KG,"Kırgızistan"
_COUNTRY_NAME_KH,"Kamboçya"
_COUNTRY_NAME_KI,"Kiribati"
_COUNTRY_NAME_KM,"Komorlar"
_COUNTRY_NAME_KN,"Saint Kitts ve Nevis"
_COUNTRY_NAME_KP,"Kore Demokratik Halk Cumhuriyeti"
_COUNTRY_NAME_KR,"Kore Cumhuriyeti"
_COUNTRY_NAME_KW,"Kuveyt"
_COUNTRY_NAME_KY,"Cayman Adaları"
_COUNTRY_NAME_KZ,"Kazakistan"
_COUNTRY_NAME_LA,"Lao Demokratik Halk Cumhuriyeti"
_COUNTRY_NAME_LB,"Lübnan"
_COUNTRY_NAME_LC,"Saint Lucia"
_COUNTRY_NAME_LI,"Liechtenstein"
_COUNTRY_NAME_LK,"Sri Lanka"
_COUNTRY_NAME_LR,"Liberya"
_COUNTRY_NAME_LS,"Lesoto"
_COUNTRY_NAME_LT,"Litvanya"
_COUNTRY_NAME_LU,"Lüksemburg"
_COUNTRY_NAME_LV,"Letonya"
_COUNTRY_NAME_LY,"Libya Arap Halk Sosyalist Cemahiriyesi"
_COUNTRY_NAME_MA,"Fas"
_COUNTRY_NAME_MC,"Monako"
_COUNTRY_NAME_MD,"Moldova, Cumhuriyeti"
_COUNTRY_NAME_ME,"Karadağ"
_COUNTRY_NAME_MF,"Saint Martin (Fransızca kısımı)"
_COUNTRY_NAME_MG,"Madagaskar"
_COUNTRY_NAME_MH,"Marshall Adaları"
_COUNTRY_NAME_MK,"Makedonya, Eski Yugoslav Cumhuriyeti"
_COUNTRY_NAME_ML,"Mali"
_COUNTRY_NAME_MM,"Myanmar"
_COUNTRY_NAME_MN,"Moğolistan"
_COUNTRY_NAME_MO,"Makao"
_COUNTRY_NAME_MP,"Kuzey Mariana Adaları"
_COUNTRY_NAME_MQ,"Martinik"
_COUNTRY_NAME_MR,"Moritanya"
_COUNTRY_NAME_MS,"Montserrat"
_COUNTRY_NAME_MT,"Malta"
_COUNTRY_NAME_MU,"Mauritius"
_COUNTRY_NAME_MV,"Maldivler"
_COUNTRY_NAME_MW,"Malawi"
_COUNTRY_NAME_MX,"Meksika"
_COUNTRY_NAME_MY,"Malezya"
_COUNTRY_NAME_MZ,"Mozambik"
_COUNTRY_NAME_NA,"Namibya"
_COUNTRY_NAME_NC,"Yeni Kaledonya"
_COUNTRY_NAME_NE,"Nijer"
_COUNTRY_NAME_NF,"Norfolk Adası"
_COUNTRY_NAME_NG,"Nijerya"
_COUNTRY_NAME_NI,"Nikaragua"
_COUNTRY_NAME_NL,"Hollanda"
_COUNTRY_NAME_NO,"Norveç"
_COUNTRY_NAME_NP,"Nepal"
_COUNTRY_NAME_NR,"Nauru"
_COUNTRY_NAME_NU,"Niue"
_COUNTRY_NAME_NZ,"Yeni Zelanda"
_COUNTRY_NAME_OM,"Umman"
_COUNTRY_NAME_PA,"Panama"
_COUNTRY_NAME_PE,"Peru"
_COUNTRY_NAME_PF,"Fransız Polinezyası"
_COUNTRY_NAME_PG,"Papua Yeni Gine"
_COUNTRY_NAME_PH,"Filipinler"
_COUNTRY_NAME_PK,"Pakistan"
_COUNTRY_NAME_PL,"Polonya"
_COUNTRY_NAME_PM,"Saint Pierre ve Miquelon"
_COUNTRY_NAME_PN,"Pitcairn"
_COUNTRY_NAME_PR,"Porto Riko"
_COUNTRY_NAME_PS,"Filistin"
_COUNTRY_NAME_PT,"Portekiz"
_COUNTRY_NAME_PW,"Palau"
_COUNTRY_NAME_PY,"Paraguay"
_COUNTRY_NAME_QA,"Katar"
_COUNTRY_NAME_RE,"Reunion"
_COUNTRY_NAME_RO,"Romanya"
_COUNTRY_NAME_RS,"Sırbistan"
_COUNTRY_NAME_RU,"Rusya Federasyonu"
_COUNTRY_NAME_RW,"Ruanda"
_COUNTRY_NAME_SA,"Suudi Arabistan"
_COUNTRY_NAME_SB,"Solomon Adaları"
_COUNTRY_NAME_SC,"Seyşeller"
_COUNTRY_NAME_SD,"Sudan"
_COUNTRY_NAME_SE,"İsveç"
_COUNTRY_NAME_SG,"Singapur"
_COUNTRY_NAME_SH,"Saint Helena"
_COUNTRY_NAME_SI,"Slovenya"
_COUNTRY_NAME_SJ,"Svalbard ve Jan Mayen"
_COUNTRY_NAME_SK,"Slovakya"
_COUNTRY_NAME_SL,"Sierra Leone"
_COUNTRY_NAME_SM,"San Marino"
_COUNTRY_NAME_SN,"Senegal"
_COUNTRY_NAME_SO,"Somali"
_COUNTRY_NAME_SR,"Surinam"
_COUNTRY_NAME_ST,"Sao Tome ve Principe"
_COUNTRY_NAME_SV,"El Salvador"
_COUNTRY_NAME_SY,"Suriye Arap Cumhuriyeti"
_COUNTRY_NAME_SZ,"Svaziland"
_COUNTRY_NAME_TC,"Turks ve Caicos Adaları"
_COUNTRY_NAME_TD,"Çad"
_COUNTRY_NAME_TF,"Fransız Güney Toprakları"
_COUNTRY_NAME_TG,"Togo"
_COUNTRY_NAME_TH,"Tayland"
_COUNTRY_NAME_TJ,"Tacikistan"
_COUNTRY_NAME_TK,"Tokelau"
_COUNTRY_NAME_TL,"Timor-Leste"
_COUNTRY_NAME_TM,"Türkmenistan"
_COUNTRY_NAME_TN,"Tunus"
_COUNTRY_NAME_TO,"Tonga"
_COUNTRY_NAME_TR,"Türkiye"
_COUNTRY_NAME_TT,"Trinidad ve Tobago"
_COUNTRY_NAME_TV,"Tuvalu"
_COUNTRY_NAME_TW,"Tayvan"
_COUNTRY_NAME_TZ,"Tanzanya, Birleşik Cumhuriyeti"
_COUNTRY_NAME_UA,"Ukrayna"
_COUNTRY_NAME_UG,"Uganda"
_COUNTRY_NAME_UM,"Amerika Birleşik Devletleri Küçük Dış Adaları"
_COUNTRY_NAME_US,"Amerika Birleşik Devletleri"
_COUNTRY_NAME_UY,"Uruguay"
_COUNTRY_NAME_UZ,"Özbekistan"
_COUNTRY_NAME_VA,"Holy See (Vatikan Şehir Devleti)"
_COUNTRY_NAME_VC,"Saint Vincent ve Grenadinler"
_COUNTRY_NAME_VE,"Venezuela, Bolivar Cumhuriyeti"
_COUNTRY_NAME_VG,"Virgin Adaları, İngiliz"
_COUNTRY_NAME_VI,"Virgin Adaları, ABD"
_COUNTRY_NAME_VN,"Vietnam"
_COUNTRY_NAME_VU,"Vanuatu"
_COUNTRY_NAME_WF,"Wallis ve Futuna"
_COUNTRY_NAME_WS,"Samoa"
_COUNTRY_NAME_YE,"Yemen"
_COUNTRY_NAME_YT,"Mayotte"
_COUNTRY_NAME_ZA,"Güney Afrika"
_COUNTRY_NAME_ZM,"Zambiya"
_COUNTRY_NAME_ZW,"Zimbabve"
