plugin_settings: 
    tabs: 
        first_tab: 
            fields: 
                search_results_per_page: 
                    plugin_setting: 
                        name: search_results_per_page
                    label: "Number of results per page:"
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter the number of results per page.
                        numeric: The number of results per page must be a number.
                    value: "10"
                    maxlength: "5"
                    style: "width: 5em;"
                    note_below: The number of results per page to be shown when visitors use this search facility.
                sticky_image_width: 
                    plugin_setting: 
                        name: sticky_image_width
                    label: "Sticky image width:"
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: "120"
                    maxlength: "5"
                    style: "width: 5em;"
                    post_field_html: "&nbsp;pixels"
                    note_below: "Images may be scaled down maintaining aspect ratio, but will never be scaled up."
                sticky_image_height: 
                    plugin_setting: 
                        name: sticky_image_height
                    label: "Sticky image height:"
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: "120"
                    maxlength: "5"
                    style: "width: 5em;"
                    post_field_html: "&nbsp;pixels"
                    note_below: "Images may be scaled down maintaining aspect ratio, but will never be scaled up."
                map_cluster_grid_size: 
                    plugin_setting: 
                        name: map_cluster_grid_size
                    label: "Map cluster grid size:"
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a cluster grid size.
                        numeric: The cluster grid size must be a number.
                    value: "10"
                    maxlength: "5"
                    style: "width: 5em;"
                    post_field_html: "&nbsp;pixels"
                    note_below: The cluster grid size for clustering map marks together.
                map_cluster_zoom_click_info: 
                    plugin_setting: 
                        name: map_cluster_zoom_click_info
                    label: "Map zoom level to trigger click:"
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a zoom level.
                        numeric: The zoom level size must be a number.
                    value: "15"
                    maxlength: "5"
                    style: "width: 5em;"
                    note_below: "The zoom level we have to be in for infoOnClick to trigger, google maps valid zoom levels should be between 0 and 15."
    module_class_name: zenario_project_locations