zenario_project_location_service: 
    key: 
        id: 
    

    title: Viewing a project service
    max_height: 120

    tabs: 
        project_location_service: 
            label: Project service details

            edit_mode: 
                priv: _PRIV_MANAGE_PROJECT_LOCATIONS
                enabled: Yes
            

            fields: 
                name: 
                    label: 'Project service:'
                    type: text
                    maxlength: 255
                    validation: 
                        required_if_not_hidden: Please enter a name for the sector.
