plugin_settings:
    module_class_name: zenario_event_slideshow
    tabs:
        first_tab:
            label: Details
            fields:
                title:
                    plugin_setting:
                        name: title
                    label: 'Title:'
                    type: text
                    maxlength: 255
                    value: 'Upcoming Events'
                filter_by_category:
                    plugin_setting:
                        name: filter_by_category
                    label: 'Filter by category'
                    type: checkbox
                    format_onchange: true
                content_category:
                    plugin_setting:
                        name: content_category
                    label: 'Category:'
                    type: select
                    empty_value: ' -- Select -- '
                    load_values_from_organizer_path: zenario__content/panels/categories
                    validation:
                        required_if_not_hidden: Please select a category
                    indent: 1
                slide_canvas:
                    plugin_setting:
                        name: slide_canvas
                    label: 'Slide size constraint:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                    side_note: |
                        The plugin will display the featured image from an Event content item constrained by these dimensions. If there is no featured image, the title of the event will be shown.
                slide_width:
                    plugin_setting:
                        name: slide_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em; text-align: right'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                    
                slide_height:
                    plugin_setting:
                        name: slide_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em; text-align: right'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
