# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_user_profile_search
    tabs:
        first_tab:
            label: Search parameters
            fields:
                description:
                    full_width: "1"
                    snippet: 
                        html: 'Only users with status of "active" will be searched.<br/><br/>'
                    ord: 1
                
                name_user_characteristics:
                    plugin_setting:
                        name: name_user_characteristics
                    label: 'Name on user characteristic(s):'
                    type: checkboxes
                    values:
                    validation:
                        required_if_not_hidden: Please select a user characteristic.
                    side_note: |
                       When the user searches on "name", specify which user characteristics should be searched (e.g. first name, last name).

                country_search_user_characteristic:
                    plugin_setting:
                        name: country_search_user_characteristic
                    label: 'Country on user characteristic:'
                    type: select
                    empty_value: ' -- Select -- '
                    validation:
                        required_if_not_hidden: Please select a country user characteristic.
                    side_note: |
                       When the user searches on "country", specify which user characteristics should be searched.

                keyword_user_characteristics:
                    plugin_setting:
                        name: keyword_user_characteristics
                    label: 'Keywords on user characteristic(s):'
                    type: checkboxes
                    values:
                    validation:
                        required_if_not_hidden: Please select a keyword user characteristic.
                    side_note: |
                       When the user searches on "keywords", specify which user characteristics should be searched (e.g. job title, company name, town).
                
        results_tab:
            label: Result display
            fields:
                search_results_per_page:
                    plugin_setting:
                        name: search_results_per_page
                    label: 'Number of results per page:'
                    type: text
                    value: 12
                    maxlength: 5
                    style: 'width: 5em;'
                    validation:
                        required_if_not_hidden: Please enter the number of results per page.
                        numeric: The number of results per page must be a number.
                    side_note: |
                        The number of results per page to be shown when visitors use this search facility.
                        It should be a multiple for the number of columns below.

                search_results_columns_page:
                    plugin_setting:
                        name: search_results_columns_page
                    label: 'Number of columns for results:'
                    type: text
                    value: 3
                    maxlength: 5
                    style: 'width: 5em;'
                    validation:
                        required_if_not_hidden: Please enter the number of columns for results.
                        numeric: The number of results per page must be a number.
                    side_note: |
                        The number of columns for results to be shown when visitors use this search facility.

                    
                photo_list_show:
                    plugin_setting:
                        name: photo_list_show
                    label: 'Show photo on search results'
                    type: checkbox
                    format_onchange: Yes

                photo_list_canvas:
                    plugin_setting:
                        name: photo_list_canvas
                    label: 'Photo list canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                    indent: 1

                photo_list_width:
                    plugin_setting:
                        name: photo_list_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width for listing photo.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                photo_list_height:
                    plugin_setting:
                        name: photo_list_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height for listing photo.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                    
                photo_popup_show:
                    plugin_setting:
                        name: photo_popup_show
                    label: 'Show photo on popup'
                    type: checkbox
                    format_onchange: Yes

                photo_popup_canvas:
                    plugin_setting:
                        name: photo_popup_canvas
                    label: 'Photo popup canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                    indent: 1

                photo_popup_width:
                    plugin_setting:
                        name: photo_popup_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width for popup photo.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                photo_popup_height:
                    plugin_setting:
                        name: photo_popup_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height for popup photo.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                    