# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_menu_responsive_multilevel_2
    tabs:
        animations:
            ord: 1.1
            label: Animations
            fields:
                desc:
                    snippet:
                        html: |
                            Set the options for the animation when nodes appear and disappear.
                easing_effect:
                    plugin_setting:
                        name: easing_effect
                    label: 'Easing effect:'
                    type: select
                    value: easeInOutQuint
                    values:
                        easeInSine: easeInSine
                        easeOutSine: easeOutSine
                        easeInOutSine: easeInOutSine
                        easeInQuad: easeInQuad
                        easeOutQuad: easeOutQuad
                        easeInOutQuad: easeInOutQuad
                        easeInCubic: easeInCubic
                        easeOutCubic: easeOutCubic
                        easeInOutCubic: easeInOutCubic
                        easeInQuart: easeInQuart
                        easeOutQuart: easeOutQuart
                        easeInOutQuart: easeInOutQuart
                        easeInQuint: easeInQuint
                        easeOutQuint: easeOutQuint
                        easeInOutQuint: easeInOutQuint
                        easeInExpo: easeInExpo
                        easeOutExpo: easeOutExpo
                        easeInOutExpo: easeInOutExpo
                        easeInCirc: easeInCirc
                        easeOutCirc: easeOutCirc
                        easeInOutCirc: easeInOutCirc
                        easeInBack: easeInBack
                        easeOutBack: easeOutBack
                        easeInOutBack: easeInOutBack
                        easeInElastic: easeInElastic
                        easeOutElastic: easeOutElastic
                        easeInOutElastic: easeInOutElastic
                        easeInBounce: easeInBounce
                        easeOutBounce: easeOutBounce
                        easeInOutBounce: easeInOutBounce
                        linear: linear
                    note_below: |
                        Please see
                        <a href="http://api.jqueryui.com/easings/" target="_blank">
                            http://api.jqueryui.com/easings/</a>
                        for more information.
                anim_speed:
                    plugin_setting:
                        name: anim_speed
                    label: 'Animation speed:'
                    type: radios
                    value: medium
                    values:
                        slow:
                            ord: 1
                            label: Slow
                        medium:
                            ord: 2
                            label: Medium
                        fast:
                            ord: 3
                            label: Fast
        links:
            ord: 1.2
            label: Links
            fields:
                show_link_to_home_page:
                    plugin_setting:
                        name: show_link_to_home_page
                    label: 'Show link to home page'
                    type: checkbox
                    value: ""
                    format_onchange: true
                    side_note: 'Only enable this setting if you don't have a visible link to the home page in the menu.'
                home_page:
                    plugin_setting:
                        name: home_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Home Page:'
                    indent: 1
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        disallow_refiners_looping_on_min_path: true
                        select_phrase: Select a content item...
                        hide_remove_button: true
                    visible_if: zenarioAB.value('show_link_to_home_page')
                    validation:
                        required_if_not_hidden: Please select a content item
                show_search_box:
                    plugin_setting:
                        name: show_search_box
                    label: 'Show search'
                    type: checkbox
                    value: false
                    redraw_onchange: true
                specific_search_results_page:
                    plugin_setting:
                        name: specific_search_results_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Search Results Page:'
                    indent: 1
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        disallow_refiners_looping_on_min_path: true
                        select_phrase: Select a content item...
                        hide_remove_button: true
                    visible_if: zenarioAB.value('show_search_box')
                    validation:
                        required_if_not_hidden: Please select a content item
                search_placeholder:
                    indent: 1
                    plugin_setting:
                        name: search_placeholder
                    label: 'Show "Search the site" placeholder'
                    type: checkbox
                    value: 0
                    format_onchange: true
                    visible_if: zenarioAB.value('show_search_box')
                search_placeholder_phrase:
                    indent: 2
                    plugin_setting:
                        name: search_placeholder_phrase
                    label: 'Search placeholder phrase:'
                    type: text
                    value: "Search the site"
                    format_onchange: true
                    visible_if: zenarioAB.value('show_search_box') && zenarioAB.value('search_placeholder')
                    validation:
                        required_if_not_hidden: Please enter a phrase
                
                show_link_to_registration_page:
                    plugin_setting:
                        name: show_link_to_registration_page
                    label: 'Show link to registration page'
                    type: checkbox
                    value: ""
                    format_onchange: true
                registration_page:
                    plugin_setting:
                        name: registration_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Registration Page:'
                    indent: 1
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        disallow_refiners_looping_on_min_path: true
                        select_phrase: Select a content item...
                        hide_remove_button: true
                    visible_if: zenarioAB.value('show_link_to_registration_page')
                    validation:
                        required_if_not_hidden: Please select a content item
                show_link_to_login_page:
                    plugin_setting:
                        name: show_link_to_login_page
                    label: 'Show link to login page'
                    type: checkbox
                    value: ""
                    format_onchange: true
                login_page:
                    plugin_setting:
                        name: login_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Login Page:'
                    indent: 1
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        disallow_refiners_looping_on_min_path: true
                        select_phrase: Select a content item...
                        hide_remove_button: true
                    visible_if: zenarioAB.value('show_link_to_login_page')
                    validation:
                        required_if_not_hidden: Please select a content item