# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_slideshow
    tabs:
        first_tab:
            label: Display
            fields:
                show_heading:
                    plugin_setting:
                        name: show_heading
                    label: 'Show a heading'
                    type: checkbox
                    redraw_onchange: true
                heading_text:
                    plugin_setting:
                        name: heading_text
                    indent: 1
                    visible_if: zenarioAB.value('show_heading')
                    label: Heading
                    type: text
                    placeholder: 'Type your heading here'
                heading_tag: 
                    plugin_setting: 
                        name: heading_tag
                    label: "Heading tag:"
                    indent: 1
                    visible_if: zenarioAB.value('show_heading')
                    type: select
                    values: 
                        h1: Heading 1
                        h2: Heading 2
                        h3: Heading 3
                        h4: Heading 4
                        h5: Heading 5
                        h6: Heading 6
                        p: Paragraph
                    value: h1
                    side_note: Choose which HTML tag the heading will be displayed in.
                show_tabs:
                    plugin_setting:
                        name: show_tabs
                    label: 'Show tabs'
                    type: checkbox
                    value: 1
                
                show_next_prev_buttons:
                    plugin_setting:
                        name: show_next_prev_buttons
                    label: 'Show next/previous buttons'
                    type: checkbox
                
                mode:
                    plugin_setting:
                        name: mode
                    label:  'Animation library for slides'
                    type: radios
                    value: cycle
                    values:
                        0:
                            label: 'None (advanced)'
                            side_note: |
                                If you check this option, no animation library will be included.
                                However the HTML code of the slideshow will still be placed on the page,
                                and you may use your own CSS or JavaScript code to do what you wish with it.
                        cycle:
                            label: 'Cycle (recommended)'
                            side_note: |
                                The jQuery Cycle library will be used to power the transitions.
                        roundabout:
                            label: 'Roundabout'
                            side_note: |
                                The jQuery Roundabout library will be used to power the transitions.
                                This will create a turntable-like area with the slides circling around.
                    format_onchange: true
                    
                use_timeout:
                    plugin_setting:
                        name: use_timeout
                    visible_if: zenarioAB.value('mode')
                    indent: 1
                    label: 'Auto-advance slides'
                    type: checkbox
                    value: 1
                    redraw_onchange: true
                timeout:
                    plugin_setting:
                        name: timeout
                    visible_if: zenarioAB.value('mode') && zenarioAB.value('use_timeout')
                    indent: 2
                    label: 'Display duration'
                    type: text
                    slider:
                        min: 0
                        max: 20000
                        step: 500
                        range: min
                        before_field: true
                    validation:
                        numeric: The display duration must be a number.
                    value: 4000
                    style: |
                        width: 4em;
                    post_field_html: ms
                pause:
                    plugin_setting:
                        name: pause
                    visible_if: zenarioAB.value('mode') && zenarioAB.value('use_timeout')
                    indent: 2
                    label: 'Hover to pause'
                    type: checkbox
                    value: ""
                    side_note: Hovering over a slide pauses the slideshow.
                
                # N.b. this is not for roundabouts
                next_prev_buttons_loop:
                    plugin_setting:
                        name: next_prev_buttons_loop
                    visible_if: zenarioAB.value('mode') == 'cycle'
                    indent: 1
                    label: 'Loop slides'
                    type: checkbox
                    value: 1
                    side_note: After the last slide, show the first one.
                
                use_tab_hover:
                    plugin_setting:
                        name: use_tab_hover
                    visible_if: zenarioAB.value('mode')
                    indent: 1
                    label: 'Hover to change'
                    type: checkbox
                    value: 1
                    side_note: |
                        Hovering over a tab changes to that tab's slide.
                        Only applies with Frameworks with Tabs.
                use_tab_clicks:
                    plugin_setting:
                        name: use_tab_clicks
                    visible_if: zenarioAB.value('mode')
                    indent: 1
                    label: 'Click to change'
                    type: checkbox
                    value: ""
                    side_note: |
                        Clicking on a tab changes to that tab's slide.
                        Only applies with Frameworks with Tabs.
        cycle_effects:
            label: Effects
            fields:
                fx:
                    plugin_setting:
                        name: fx
                    label: 'Effect for Transitions:'
                    type: select
                    values:
                        none:
                            label: None
                        blindX:
                            label: Blind (Horizontal)
                        blindY:
                            label: Blind (Vertical)
                        blindZ:
                            label: Blind (Diagonal)
                        Cover:
                            label: Cover
                        curtainX:
                            label: Curtain (Horizontal)
                        curtainY:
                            label: Curtain (Vertical)
                        fade:
                            label: Fade
                        fadeout:
                            label: Fadeout
                        fadeZoom:
                            label: Fade and Zoom
                        growX:
                            label: Grow (Horizontal)
                        growY:
                            label: Grow (Vertical)
                        scrollUp:
                            label: Scroll (Up)
                        scrollDown:
                            label: Scroll (Down)
                        scrollLeft:
                            label: Scroll (Left)
                        scrollRight:
                            label: Scroll (Right)
                        scrollHorz:
                            label: Scroll (Horizontal)
                        scrollVert:
                            label: Scroll (Vertical)
                        shuffle:
                            label: Shuffle
                        slideX:
                            label: Slide (Horizontal)
                        slideY:
                            label: Slide (Vertical)
                        toss:
                            label: Toss
                        turnUp:
                            label: Turn (Up)
                        turnDown:
                            label: Turn (Down)
                        turnLeft:
                            label: Turn (Left)
                        turnRight:
                            label: Turn (Right)
                        uncover:
                            label: Uncover
                        wipe:
                            label: Wipe
                        zoom:
                            label: Zoom
                    value: fade
                    side_note: 'See <a href="http://malsup.com/jquery/cycle/" target="_blank">http://malsup.com/jquery/cycle/</a> for more information.'
                sync:
                    plugin_setting:
                        name: sync
                    label: 'Hide/show effects happen simultaneously'
                    type: checkbox
                    value: 1
                speed:
                    plugin_setting:
                        name: speed
                    label: 'Animation duration:'
                    type: text
                    validation:
                        numeric: The animation duration must be a number.
                    value: 1000
                    slider:
                        min: 0
                        max: 5000
                        step: 50
                        range: min
                        before_field: true
                    style: |
                        width: 4em;
                    post_field_html: ms
        
        roundabout_effects:
            label: Shape and Speed
            fields:
                shape:
                    plugin_setting:
                        name: shape
                    label: 'Shape:'
                    type: select
                    values:
                        lazySusan:
                            label: Default
                        waterWheel:
                            label: Water Wheel
                        figure8:
                            label: Figure 8
                        square:
                            label: Square
                        conveyorBeltLeft:
                            label: Conveyor Belt (Left)
                        conveyorBeltRight:
                            label: Conveyor Belt (Right)
                        diagonalRingLeft:
                            label: Diagonal Ring (Left)
                        diagonalRingRight:
                            label: Diagonal Ring (Right)
                        rollerCoaster:
                            label: Roller Coaster
                        tearDrop:
                            label: Tear Drop
                    value: lazySusan
                tilt:
                    plugin_setting:
                        name: tilt
                    label: 'Tilt:'
                    type: text
                    value: 0
                    style: 'width: 50px;'
                    slider:
                        range: min
                        min: -5.0
                        max: 15.0
                        step: 0.1
                        before_field: true
                    note_below: |
                        This setting affects the shape in some way.
                        For the default shape it will adjust the apparent tilt.
                        It will have different effects on other shapes.
                speed:
                    plugin_setting:
                        name: roundabout_speed
                    label: 'Animation duration:'
                    type: text
                    validation:
                        numeric: The animation duration must be a number.
                    value: 1000
                    slider:
                        min: 0
                        max: 5000
                        step: 50
                        range: min
                        before_field: true
                    style: |
                        width: 4em;
                    post_field_html: ms

        
        size:
            label: Image size
            fields:
                desc:
                    full_width: true
                    snippet:
                        html: |
                            The following settings let you set default values to apply to Banner Plugins that have an image.
                            The values you choose here will apply to every Banner, unless overridden by settings of individual Banners.
                banner_canvas:
                    plugin_setting:
                        name: banner_canvas
                    label: Size constraint
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            label: Unlimited size
                        fixed_width:
                            label: Constrain by width
                        fixed_height:
                            label: Constrain by height
                        fixed_width_and_height:
                            label: Constrain by width and height
                        resize_and_crop:
                            label: Resize and crop
                    format_onchange: true
                banner_width:
                    plugin_setting:
                        name: banner_width
                    indent: 1
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                banner_height:
                    plugin_setting:
                        name: banner_height
                    indent: 1
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                enlarge_image:
                    plugin_setting:
                        name: enlarge_image
                    label: 'Enlarge images in a floating box:'
                    type: checkbox
                    format_onchange: true
                enlarge_canvas:
                    plugin_setting:
                        name: enlarge_canvas
                    indent: 1
                    label: 'Enlarged image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: 1
                            label: Unlimited size
                        fixed_width:
                            ord: 2
                            label: Constrain by width
                        fixed_height:
                            ord: 3
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: 4
                            label: Constrain by width and height
                    format_onchange: true
                enlarge_width:
                    plugin_setting:
                        name: enlarge_width
                    indent: 2
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter an enlarged width.
                        numeric: The enlarged width must be a number.
                    value: ""
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                enlarge_height:
                    plugin_setting:
                        name: enlarge_height
                    indent: 2
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter an enlarged height.
                        numeric: The enlarged height must be a number.
                    value: ""
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
        author_advice:
            visible_if: '!zenarioAB.tuix.key.isVersionControlled && !zenarioAB.tuix.key.nest'
            label: Author advice
            fields:
                author_advice:
                    plugin_setting:
                        name: author_advice
                    label: 'Author advice:'
                    type: textarea
                    rows: 4
                    cols: 60
                    style: 'width: auto;'
                    side_note: >
                        Enter advice that you would like to give to Authors. This
                        will appear while in Edit Mode.

