# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_html_snippet
    tabs:
        first_tab:
            label: Raw HTML
            fields:
                html:
                    plugin_setting:
                        name: html
                        is_searchable_content: Yes
                    label: 'Raw HTML:'
                    side_note: 'Enter JavaScript on the next tab'
                    type: code_editor
                    tall_as_possible: true
                    value: ""
                    dont_trim: true
                    language: html
                    style: >
                        height: 30em;
                        width: 99%;
                cookie_consent:
                    plugin_setting:
                        name: cookie_consent
                    label: 'Cookie consent:'
                    type: select
                    visible_if: "zenarioA.siteSettings.cookie_require_consent == 'explicit'"
                    value: not_needed
                    values:
                        not_needed:
                            label: Always show (ignore cookie settings)
                        needed:
                            label: Hide until visitor accepts at least necessary cookies
                        specific_types:
                            label: Hide until visitor accepts cookie type...
                    redraw_onchange: true
                cookie_consent_specific_cookie_types:
                    indent: 1
                    plugin_setting:
                        name: cookie_consent_specific_cookie_types
                    type: radios
                    visible_if: "zenarioA.siteSettings.cookie_require_consent == 'explicit' && lib.value('cookie_consent') == 'specific_types'"
                    value: functionality
                    values:
                        functionality:
                            ord: 1
                            label: 'Functionality cookies'
                        analytics:
                            ord: 2
                            label: 'Analytics cookies'
                        social_media:
                            ord: 3
                            label: 'Social media cookies'
                    validation:
                        required_if_not_hidden: 'Please select the cookie type. The output will be withheld until the visitor accepts this type of cookie or all cookies.'
                hide_in_admin_mode:
                    plugin_setting:
                        name: hide_in_admin_mode
                    label: 'Hide when in admin mode'
                    side_note: Check this if you some JavaScript in this plugin is clashing with the administration features of Zenario.
                    type: checkbox
                    value: ""
        javascript:
            label: 'JavaScript'
            fields:
                desc:
                    snippet:
                        html: |
                            Use this if you need to add JavaScript, which will be inserted to the bottom of the page. You do not need &lt;script&gt; tags.
                            The variables 
                            <a href="https://zenar.io/ref-var-slotname" target="_blank"><code>slotName</code></a>
                            and
                            <a href="https://zenar.io/ref-var-containerid" target="_blank"><code>containerId</code></a>
                            variables are available.
                            
                javascript:
                    plugin_setting:
                        name: javascript
                    label: 'JavaScript code:'
                    type: code_editor
                    tall_as_possible: true
                    value: ""
                    dont_trim: true
                    language: javascript
                    style: >
                        height: 25em;
