# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_html_snippet
    tabs:
        first_tab:
            label: Content
            fields:
                html:
                    plugin_setting:
                        name: html
                        is_searchable_content: Yes
                    label: 'Raw HTML:'
                    type: code_editor
                    tall_as_possible: true
                    value: ""
                    dont_trim: true
                    language: html
                    style: >
                        height: 30em;
                cookie_consent:
                    plugin_setting:
                        name: cookie_consent
                    label: 'Cookie Consent:'
                    type: select
                    visible_if: "zenarioA.siteSettings.cookie_require_consent == 'explicit'"
                    value: not_needed
                    values:
                        not_needed:
                            label: HTML does not contain code that sets cookies
                        needed:
                            label: >
                                HTML contains code that sets cookies; hide it when consent
                                is not given by the visitor
                        required:
                            label: >
                                HTML contains code that sets cookies; hide it and request
                                consent until consent is given by the visitor
                hide_in_admin_mode:
                    plugin_setting:
                        name: hide_in_admin_mode
                    label: 'Hide in Admin Mode:'
                    type: checkbox
                    value: ""
        javascript:
            label: 'JavaScript'
            fields:
                desc:
                    snippet:
                        html: |
                            Use this if you need to add JavaScript to the bottom of the page.
                            The
                            <a href="http://zenar.io/ref-var-slotname" target="_blank"><code>slotName</code></a>
                            and
                            <a href="http://zenar.io/ref-var-containerid" target="_blank"><code>containerId</code></a>
                            variables are avilable to use in your code if you need them.
                            
                javascript:
                    plugin_setting:
                        name: javascript
                    label: 'JavaScript code:'
                    type: code_editor
                    tall_as_possible: true
                    value: ""
                    dont_trim: true
                    language: javascript
                    style: >
                        height: 25em;
                minify:
                    type: submit
                    value: ' ▼ Minify ▼ '
                    format_onchange: true
                    side_note: |
                        Press this button to minify your JavaScript code
                minified_javascript:
                    plugin_setting:
                        name: minified_javascript
                    label: 'Minified code:'
                    type: code_editor
                    value: ""
                    dont_trim: true
                    language: javascript
                    style: >
                        height: 4em;
                    note_below: |
                        If provided, the minified code will be used instead of your JavaScript code
                        for a smaller page-size.
