"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_extranet_registration

"Phrase Code",Translation
_CAPTCHA_INVALID,"Please correctly verify that you are human."
_CAPTCHA:,"Please help us combat form submissions by spam devices:"
_CHANGE_PASSWORD,"Change your password"
_COULD_NOT_SEND_REGISTRATION_EMAIL,"There appears to be a problem with our email system. We are unable to send you a verification email."
_EMAIL:,"Email:"
_ERROR_EMAIL_IN_USE_RESEND_VERIFICATION_EMAIL,"It looks like your email address has already been registered. If you have registered on this site using this email address, but have not received a verification email, please <a [[resend_verification_email]]>click here to have this site send you a new verification email</a>."
_ERROR_EMAIL_IN_USE,"This email address is already in use and cannot be registered again."
_ERROR_EMAIL_NOT_IN_USE,"This email address is not associated with any account."
_ERROR_EMAIL,"Please enter your email address."
_ERROR_EMAIL_VERIFIED,"This email address has already been verified."
_ERROR_EXTRANET_TERMS_AND_CONDITIONS, "You must accept our terms and conditions to register."
_ERROR_FIRST_NAME,"Please enter your first name."
_ERROR_INVALID_EMAIL,"Please enter a valid email address."
_ERROR_INVALID_SCREEN_NAME,"Your Screen Name contains special characters. Please choose a Screen Name that contains only word-characters."
_ERROR_LAST_NAME,"Please enter your last name."
_ERROR_NEW_PASSWORD_LENGTH,"Please ensure that your password is at least [[min_password_length]] characters long."
_ERROR_NEW_PASSWORD_MATCH,"The passwords you entered do not match."
_ERROR_NEW_PASSWORD_NOT_STRONG_ENOUGH,"The password provided is not strong enough. Please make the password longer, or try mixing in upper and lower case letters, numbers or non-alphanumeric characters."
_ERROR_NEW_PASSWORD,"Please enter a password."
_ERROR_REPEAT_NEW_PASSWORD,"Please re-enter your password."
_ERROR_SCREEN_NAME_IN_USE,"This Screen Name is already in use on this site. Please choose another one."
_ERROR_SCREEN_NAME,"Please enter your Screen Name."
_ERROR_VERIFICATION_FAILED,"We are sorry, but we were unable to find your registration. Please check whether the verification link is correct."
_FIRST_NAME:,"First Name:"
_LAST_NAME:,"Last Name:"
_LOGIN,"Go back to Login"
_LOGOUT,"Logout"
_PASSWORD_CONFIRMATION:,"Repeat password:"
_PASSWORD:,"Password:"
_PLEASE_ACCEPT_COOKIES,"This site needs to place a cookie on your computer before you can register. Please accept cookies from this site to continue."
_REGISTER,"Register"
_REGISTRATION_TITLE,"Create an account"
_REQUESTED_LINK:,"Your requested page:"
_RESEND_VERIFICATION_EMAIL_DESC,"Use this if you have previously registered but not received your verification email."
_RESEND_VERIFICATION_EMAIL,"Resend verification email"
_RESEND_VERIFICATION_EMAIL_TITLE,"Resend verification email"
_RESIDENTIAL_ADDRESS,"Residential Address",
_SALUTATION:,"Salutation:"
_SCREEN_NAME:,"Screen Name:"
_SELECT,"-- Please select --"
_T_C_LINK, "I have read and accept the <a href='[[TCLink]]' target='_blank'>Terms and Conditions</a>."
_THANK_YOU_VERIFY_EMAIL_RESENT,"Your verification email has been resent. Please be sure to check your spam/bulk mail folder."
_THANK_YOU_VERIFY_EMAIL,"Thank you for registering. You have been sent an email with a verification link. You should check your spam/bulk mail if you do not see it soon. Please click the link in the email to verify your account."
_THANK_YOU_WAIT_FOR_ACTIVATION,"Thank you for registering. Your account will need to be manually activated by one of our Administrators before you may log in."
_WELCOME,"Welcome, [[user]]"
