"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",pl

Plugin
zenario_extranet_registration

"Phrase Code",Translation
_CAPTCHA_INVALID,"Niestety nie byliśmy w stanie potwierdzić iż formularz został wypełniony przez człowieka. Prosimy o ponowne wpisanie odpowiednich słów w polu weryfikacyjnym."
_CAPTCHA:,"Przepraszamy za niedogodności, ale chcielibyśmy upewnić się, że wiadomość wysyłana jest przez człowieka:"
_CHANGE_PASSWORD,"Zmień hasło"
_COULD_NOT_SEND_REGISTRATION_EMAIL,"Niestety chwilowo nie jesteśmy w stanie wysłać wiadomości email z linkiem weryfikacyjnym do Twojego konta. Prosimy spróbować ponownie później."
_EMAIL:,"Email:"
_ERROR_EMAIL_NAME_IN_USE_RESEND_VERIFICATION_EMAIL,"Wprowadzony adres email jest już używany przez innego użytkownika. Jeśli jesteś tą osobą i nie otrzymałeś emaila z linkiem weryfikacyjnym możesz go wysłać ponownie klikając <a [[resend_verification_email]]>ten link</a>."
_ERROR_EMAIL_NAME_IN_USE,"Wprowadzony adres email jest już używany przez inną osobę."
_ERROR_EMAIL_NOT_IN_USE,"Wprowadzony adres email nie jest przypisany do żadnego konta użytkownika."
_ERROR_EMAIL,"Proszę wprowadzić swój adres email."
_ERROR_EMAIL_VERIFIED,"Ten adres email został już zweryfikowany w przeszłości."
_ERROR_FIRST_NAME,"Proszę wprowadzić swoje imię."
_ERROR_EMAIL_INVALID,"Wprowadzony adres email jest niepoprawny."
_ERROR_SCREEN_NAME_INVALID,"Wprowadzony nick zawiera znaki specjalne. Proszę wpisać nick zawierający tylko litery i cyfry."
_ERROR_LAST_NAME,"Proszę wprowadzić swoje nazwisko."
_ERROR_NEW_PASSWORD_LENGTH,"Hasło musi być długości co najmniej [[min_password_length]] znaków."
_ERROR_NEW_PASSWORD_MATCH,"Hasło i jego powtórzenie nie zgadzają się."
_ERROR_NEW_PASSWORD_NOT_STRONG_ENOUGH,"Wprowadzone hasło nie jest wystarczająco bezpieczne. Proszę spróbować wprowadzić hasło dłuższe i/lub składające się z kombinacji znaków specjalnych, cyfr oraz małych i wielkich liter."
_ERROR_NEW_PASSWORD,"Proszę wprowadzić hasło."
_ERROR_REPEAT_NEW_PASSWORD,"Proszę wprowadzić powtórzenie hasła."
_ERROR_SCREEN_NAME_IN_USE,"Wprowadzony nick jest już używany przez inną osobę."
_ERROR_SCREEN_NAME,"Proszę wprowadzić swój nick."
_ERROR_VERIFICATION_FAILED,"Niestety nie udało się odnaleźć Twojej rejestracji. Prosimy o sprawdzenie czy użyty link weryfikacyjny jest poprawny."
_FIRST_NAME:,"Imię:"
_LAST_NAME:,"Nazwisko:"
_LOGIN,"Zaloguj"
_LOGOUT,"Wyloguj"
_PASSWORD_CONFIRMATION:,"Powtorzenie hasła:"
_PASSWORD:,"Hasło:"
_PLEASE_ACCEPT_COOKIES,"Ta strona wymaga umieszczenia ciasteczka w pamięci Twojej przeglądarki. Prosimy o zezwolenie na instalację ciasteczek przed zalogowaniem się."
_REGISTER,"Zarejestruj"
_REGISTRATION_TITLE,"Utwórz konto"
_REQUESTED_LINK:,"Żądana strona:"
_RESEND_VERIFICATION_EMAIL_DESC,"Skorzystaj z tej opcji jeśli nie otrzymałeś lub skasowałeś poprzedni email z linkiem weryfikacyjnym."
_RESEND_VERIFICATION_EMAIL_TITLE,"Ponowne wysyłanie linka weryfikacyjnego"
_RESEND_VERIFICATION_EMAIL,"Wyślij ponownie link weryfikacyjny."
_RESIDENTIAL_ADDRESS,"Adres prywatny"
_SALUTATION:,"Tytuł / Stanowisko:"
_SCREEN_NAME:,"Nick:"
_SELECT,"-- Proszę wybrać --"
_THANK_YOU_VERIFY_EMAIL,"Dziękujemy za rejestrację. Na Twój adres email wysłaliśmy wiadomość z linkiem weryfikacyjnym. Dalsze kroki rejestracji zostaną przeprowadzone po kliknięciu linka weryfikacyjnego z wiadomości i potwierdzeniu adresu email. W przypadku nieotrzymania wiadomości prosimy o sprawdzenie czy nie została ona automatycznie przeniesiona do folderu spam."
_THANK_YOU_VERIFY_EMAIL_RESENT,"Wiadomość z linkiem weryfikacyjnym została ponownie wysłana na Twój adres email. W przypadku nieotrzymania wiadomości prosimy o sprawdzenie czy nie została ona automatycznie przeniesiona do folderu spam."
_THANK_YOU_WAIT_FOR_ACTIVATION,"Dziękujemy za rejestrację. Zanim będziesz mógł się zalogować, dostęp do Twojego konta musi być jeszcze aktywowany przez jednego z naszych Administratorów."
_WELCOME,"Witaj [[user]]"
