"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",tr

Plugin
zenario_extranet_registration

"Phrase Code",Translation
_CAPTCHA_INVALID,"Lütfen insan olduğunuzu doğrulayınız."
_CAPTCHA:,"Pardon, insan olup olmadığınızı kontrol etmemiz gerekiyor:"
_CHANGE_PASSWORD,"Şifre değiştir"
_COULD_NOT_SEND_REGISTRATION_EMAIL,"There appears to be a problem with our email system. We are unable to send you a verification email."
_EMAIL:,"E-posta:"
_ERROR_EMAIL,"E-posta adresinizi giriniz."
_ERROR_EMAIL_IN_USE,"Bu e-posta adresi bu sitede halihazırda kullanılmaktadır."
_ERROR_EMAIL_IN_USE_RESEND_VERIFICATION_EMAIL,"Bu e-posta adresi sistemimizde kayıtlıdır. Daha önce bu e-posta adresi ile kayıt olup doğrulama e-postası almadıysanız, doğrulama linkine <a [[resend_verification_email]]> yeniden tıklayınız."
_ERROR_EMAIL_VERIFIED,"This email address has already been verified."
_ERROR_FIRST_NAME,"Adınızı giriniz."
_ERROR_INVALID_EMAIL,"Geçerli bir e-posta adresi giriniz."
_ERROR_INVALID_SCREEN_NAME,"Ekran adınız özel karakterler içermektedir. Lütfen, sadece harfler içeren ekran adı seçiniz."
_ERROR_LAST_NAME,"Soyadınızı giriniz."
_ERROR_NEW_PASSWORD_LENGTH,"Lütfen şifrenizin en az [[min_password_length]] olduğundan emin olunuz."
_ERROR_NEW_PASSWORD,"Lütfen bir şifre giriniz."
_ERROR_NEW_PASSWORD_MATCH,"Girdiğiniz şifreler eşleşmiyor."
_ERROR_NEW_PASSWORD_NOT_STRONG_ENOUGH,"Sağlanan şifre yeterince güçlü degildir. Lütfen şifrenizi ya biraz uzun yapın. Ya da küçük veya büyük harfler veya sayılar ya da alfasayısal olmayan karakterler içeridiğinden emin olunuz."
_ERROR_REPEAT_NEW_PASSWORD,"Lütfen şifrenizi yeniden giriniz"
_ERROR_SCREEN_NAME,"Ekran Adınızı giriniz."
_ERROR_SCREEN_NAME_IN_USE,"Bu ekran adı halıhazırda bu sitede kullanılmaktadır."
_ERROR_VERIFICATION_FAILED,"We are sorry, but we were unable to find your registration. Please check whether the verification link is correct."
_FIRST_NAME:,"Adınız:"
_LAST_NAME:,"Soyadınız:"
_LOGIN,"Go back to Login"
_LOGOUT,"Çıkış"
_PASSWORD_CONFIRMATION:,"Şifrenizi tekrar giriniz:"
_PASSWORD:,"Şifreniz:"
_POSTCODE_ZIP:,"Posta kodu:"
_REGISTER,"Kaydet"
_REGISTRATION_TITLE,"Kullanıcı yarat"
_REQUESTED_LINK:,"İstediğiniz sayfa:"
_RESEND_VERIFICATION_EMAIL_DESC,"Use this if you have previously registered but not received your verification email."
_RESEND_VERIFICATION_EMAIL,"Resend verification Email"
_RESEND_VERIFICATION_EMAIL_TITLE,"Resend verification Email"
_RESIDENTIAL_ADDRESS,"Konut Adresi",
_SALUTATION:,"Salutation:"
_SCREEN_NAME:,"Ekrdan Adı:"
_SELECT,"-- Lütfen seçiniz --"
_TELEPHONE_NUMBER:,"Telefon numaranı:"
_THANK_YOU_VERIFY_EMAIL_RESENT,"Your verification email has been resent. Please be sure to check your spam/bulk mail folder."
_THANK_YOU_VERIFY_EMAIL,"Thank you for registering. You have been sent an email with a verification link. You should check your spam/bulk mail if you do not see it soon. Please click the link in the email to verify your account."
_THANK_YOU_WAIT_FOR_ACTIVATION,"Thank you for registering. Your account will need to be manually activated by one of our Administrators before you may log in."
_WELCOME,"Hoşgeldiniz, [[user]]"
