# You must use a tab-size of 4 spaces to edit this file.
---
zenario__administration:
    panels:
        site_settings:
            items:
                users:
                    name: Users
                    desc: Settings that affect extranet users and contacts.
                perms:
                    name: User Permissions
                    desc: Settings that control what data can be seen or changed by which extranet users
