# You must use a tab-size of 4 spaces to edit this file.
---
zenario__administration:
    panels:
        site_settings:
            items:
                zenario_newsletter__site_settings_group:
                    name: Newsletters
                    desc: Settings for Newsletters
