site_settings:
    setting_group: zenario_user_forms__site_settings_group
    tabs:
        zenario_salesforce_api_form_integration:
            label: Salesforce API Integration
            edit_mode:
                enabled: Yes
            fields:
                zenario_salesforce_api_form_integration__client_id:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__client_id
                    label: 'Client ID'
                    type: text
                zenario_salesforce_api_form_integration__client_secret:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__client_secret
                    label: 'Client secret key'
                    type: text
                zenario_salesforce_api_form_integration__username:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__username
                    label: 'Username'
                    type: text
                    autocomplete: "off"
                    pre_field_html: |
                        <input type="text" name="dummy_username" autocomplete="off" tabindex="-1" style="
                            position: fixed;
                            top: -1000px;
                            width: 1px;
                            height: 1px;
                        "/>
                        <input type="password" name="dummy_password" autocomplete="off" tabindex="-1" style="
                            position: fixed;
                            top: -1000px;
                            width: 1px;
                            height: 1px;
                        "/>
                
                zenario_salesforce_api_form_integration__password:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__password
                    label: 'Password'
                    type: password
                    autocomplete: "off"
                zenario_salesforce_api_form_integration__security_token:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__security_token
                    label: "User's security token"
                    type: password
                    autocomplete: "off"
                zenario_salesforce_api_form_integration__login_uri:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__login_uri
                    label: 'Login URI'
                    type: text
                    value: "https://login.salesforce.com"
                zenario_salesforce_api_form_integration__log_expiry_time:
                    site_setting:
                        name: zenario_salesforce_api_form_integration__log_expiry_time
                    label: 'Days that log entries are stored for:'
                    type: select
                    empty_value: -- Forever --
                    values:
                        1: 
                            label: 1 day
                        3: 
                            label: 3 days
                        7: 
                            label: 7 days
                        30: 
                            label: 30 days
                        100: 
                            label: 100 days
                        