"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",ar

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"يناير"
_MONTH_LONG_02,"فبراير"
_MONTH_LONG_03,"مسيرة"
_MONTH_LONG_04,"أبريل"
_MONTH_LONG_05,"قد"
_MONTH_LONG_06,"حزيران"
_MONTH_LONG_07,"يوليو"
_MONTH_LONG_08,"أغسطس"
_MONTH_LONG_09,"سبتمبر"
_MONTH_LONG_10,"أكتوبر"
_MONTH_LONG_11,"تشرين"
_MONTH_LONG_12,"الثاني"
_MONTH_SHORT_01,"ديسمبر"
_MONTH_SHORT_02,"يناير"
_MONTH_SHORT_03,"فبراير"
_MONTH_SHORT_04,"مسيرة"
_MONTH_SHORT_05,"أبريل"
_MONTH_SHORT_06,"قد"
_MONTH_SHORT_07,"حزيران"
_MONTH_SHORT_08,"يوليو"
_MONTH_SHORT_09,"أغسطس"
_MONTH_SHORT_10,"سبتمبر"
_MONTH_SHORT_11,"أكتوبر"
_MONTH_SHORT_12,"تشرين"
_WEEKDAY_0,"الثاني"
_WEEKDAY_1,"ديسمبر"
_WEEKDAY_2,"الأحد"
_WEEKDAY_3,"يوم"
_WEEKDAY_4,"الاثنين"
_WEEKDAY_5,"الثلاثاء"
_WEEKDAY_6,"الأربعاء"