"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",cs

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"leden"
_MONTH_LONG_02,"únor"
_MONTH_LONG_03,"březen"
_MONTH_LONG_04,"duben"
_MONTH_LONG_05,"květen"
_MONTH_LONG_06,"červen"
_MONTH_LONG_07,"červenec"
_MONTH_LONG_08,"srpen"
_MONTH_LONG_09,"září"
_MONTH_LONG_10,"říjen"
_MONTH_LONG_11,"listopad"
_MONTH_LONG_12,"prosinec"
_MONTH_SHORT_01,"leden"
_MONTH_SHORT_02,"únor"
_MONTH_SHORT_03,"březen"
_MONTH_SHORT_04,"duben"
_MONTH_SHORT_05,"květen"
_MONTH_SHORT_06,"červen"
_MONTH_SHORT_07,"červenec"
_MONTH_SHORT_08,"srpen"
_MONTH_SHORT_09,"září"
_MONTH_SHORT_10,"říjen"
_MONTH_SHORT_11,"listopad"
_MONTH_SHORT_12,"prosinec"
_WEEKDAY_0,"neděle"
_WEEKDAY_1,"pondělí"
_WEEKDAY_2,"úterý"
_WEEKDAY_3,"středa"
_WEEKDAY_4,"čtvrtek"
_WEEKDAY_5,"pátek"
_WEEKDAY_6,"sobota"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"