"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",da

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"januar"
_MONTH_LONG_02,"februar"
_MONTH_LONG_03,"marts"
_MONTH_LONG_04,"april"
_MONTH_LONG_05,"maj"
_MONTH_LONG_06,"juni"
_MONTH_LONG_07,"juli"
_MONTH_LONG_08,"august"
_MONTH_LONG_09,"september"
_MONTH_LONG_10,"oktober"
_MONTH_LONG_11,"november"
_MONTH_LONG_12,"december"
_MONTH_SHORT_01,"januar"
_MONTH_SHORT_02,"februar"
_MONTH_SHORT_03,"marts"
_MONTH_SHORT_04,"april"
_MONTH_SHORT_05,"maj"
_MONTH_SHORT_06,"juni"
_MONTH_SHORT_07,"juli"
_MONTH_SHORT_08,"august"
_MONTH_SHORT_09,"september"
_MONTH_SHORT_10,"oktober"
_MONTH_SHORT_11,"november"
_MONTH_SHORT_12,"december"
_WEEKDAY_0,"søndag"
_WEEKDAY_1,"Mandag"
_WEEKDAY_2,"Tirsdag"
_WEEKDAY_3,"Onsdag"
_WEEKDAY_4,"Torsdag"
_WEEKDAY_5,"Fredag"
_WEEKDAY_6,"lørdag"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"