"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"January"
_MONTH_LONG_02,"February"
_MONTH_LONG_03,"March"
_MONTH_LONG_04,"April"
_MONTH_LONG_05,"May"
_MONTH_LONG_06,"June"
_MONTH_LONG_07,"July"
_MONTH_LONG_08,"August"
_MONTH_LONG_09,"September"
_MONTH_LONG_10,"October"
_MONTH_LONG_11,"November"
_MONTH_LONG_12,"December"
_MONTH_SHORT_01,"Jan"
_MONTH_SHORT_02,"Feb"
_MONTH_SHORT_03,"Mar"
_MONTH_SHORT_04,"Apr"
_MONTH_SHORT_05,"May"
_MONTH_SHORT_06,"Jun"
_MONTH_SHORT_07,"Jul"
_MONTH_SHORT_08,"Aug"
_MONTH_SHORT_09,"Sep"
_MONTH_SHORT_10,"Oct"
_MONTH_SHORT_11,"Nov"
_MONTH_SHORT_12,"Dec"
_WEEKDAY_0,"Sunday"
_WEEKDAY_1,"Monday"
_WEEKDAY_2,"Tuesday"
_WEEKDAY_3,"Wednesday"
_WEEKDAY_4,"Thursday"
_WEEKDAY_5,"Friday"
_WEEKDAY_6,"Saturday"
_WEEKDAY_SHORT_0,"Sun"
_WEEKDAY_SHORT_1,"Mon"
_WEEKDAY_SHORT_2,"Tue"
_WEEKDAY_SHORT_3,"Wed"
_WEEKDAY_SHORT_4,"Thu"
_WEEKDAY_SHORT_5,"Fri"
_WEEKDAY_SHORT_6,"Sat"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"
