"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_common_features

"Phrase Code",Translation
_COOKIE_BOX1_01_IMPLIED_MSG,"This site uses cookies, and places cookies on your computer to provide you with the best experience. If you continue to use this site, we will assume that you consent to this. Please see our privacy policy for more information."
_COOKIE_BOX1_02_CONTINUE_BTN,"Continue"
_COOKIE_BOX1_03_COOKIE_CONSENT_MSG,"This site would like to place cookies on your computer. These are designed to improve your experience and provide personalised content. You can accept all cookies, or find out more and accept only certain types."
_COOKIE_BOX1_04_MANAGE_BTN,"Manage cookies"
_COOKIE_BOX1_05_ACCEPT_BTN,"Accept all"
_COOKIE_BOX2_01_INTRO_MSG,"<h2>Cookie settings</h2><p>This site uses cookies, which are small text files, to improve your experience and show you personalised content. You can accept all cookies, or manage them by type.</p><p>You can find out more on our privacy page.</p>"
_COOKIE_BOX2_02_ACCEPT_ALL_BTN,"Accept all"
_COOKIE_BOX2_03_NECESSARY_HEADER_1,"Necessary cookies"
_COOKIE_BOX2_04_NECESSARY_MSG_1,"Essential cookies needed by this site. Without these cookies services cannot be provided."
_COOKIE_BOX2_05_FUNCT_HEADER_2,"Functionality"
_COOKIE_BOX2_06_FUNCT_MSG_2,"These cookies are used for usability features of the site, such as to remember choices you have made."
_COOKIE_BOX2_07_ANALYTICS_HEADER_3,"Analytics"
_COOKIE_BOX2_08_ANALYTICS_MSG_3,"These cookies are used to anonymously monitor traffic levels on our site."
_COOKIE_BOX2_09_SOC_MEDIA_HEADER_4,"Social Media"
_COOKIE_BOX2_10_SOC_MEDIA_MSG_4,"These cookies allow easy sharing of pages via social media, and allow tracking of shares."
_COOKIE_BOX2_11_SAVE_PREFERENCES_BTN,"Save preferences"
_MONTH_LONG_01,"January"
_MONTH_LONG_02,"February"
_MONTH_LONG_03,"March"
_MONTH_LONG_04,"April"
_MONTH_LONG_05,"May"
_MONTH_LONG_06,"June"
_MONTH_LONG_07,"July"
_MONTH_LONG_08,"August"
_MONTH_LONG_09,"September"
_MONTH_LONG_10,"October"
_MONTH_LONG_11,"November"
_MONTH_LONG_12,"December"
_MONTH_SHORT_01,"Jan"
_MONTH_SHORT_02,"Feb"
_MONTH_SHORT_03,"Mar"
_MONTH_SHORT_04,"Apr"
_MONTH_SHORT_05,"May"
_MONTH_SHORT_06,"Jun"
_MONTH_SHORT_07,"Jul"
_MONTH_SHORT_08,"Aug"
_MONTH_SHORT_09,"Sep"
_MONTH_SHORT_10,"Oct"
_MONTH_SHORT_11,"Nov"
_MONTH_SHORT_12,"Dec"
_WEEKDAY_0,"Sunday"
_WEEKDAY_1,"Monday"
_WEEKDAY_2,"Tuesday"
_WEEKDAY_3,"Wednesday"
_WEEKDAY_4,"Thursday"
_WEEKDAY_5,"Friday"
_WEEKDAY_6,"Saturday"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"