"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",es

Plugin
zenario_common_features

"Phrase Code",Translation
_COOKIE_CONSENT_ACCEPT,"Aceptar"
_COOKIE_CONSENT_CLOSE,"Cerrar"
_COOKIE_CONSENT_CONTINUE,"Continuar"
_COOKIE_CONSENT_IMPLIED_MESSAGE,"Este sitio almacena 'cookies' en su ordenador para el correcto funcionamiento del sitio y para ofrecer una mejor experiencia de navegaci;on. Si usted continúa navegando este sitio web se asumirá que está de acuerdo. Por favor revise nuestras políticas de privacidad para mayor información."
_COOKIE_CONSENT_MESSAGE,"Este sitio web almacenará información en forma de 'cookies' en su ordenador. Hasta el momento se ha enviado una cookie la cual es escencial para la ejecución del sitio web; aceptando futuras cookies mejorará su experiencia de navegación. Por favor revise nuestras políticas de privacidad para màs información."
_COOKIE_CONSENT_REJECT,"Cancelar"
_MONTH_LONG_01,"Enero"
_MONTH_LONG_02,"Febrero"
_MONTH_LONG_03,"Marzo"
_MONTH_LONG_04,"Abril"
_MONTH_LONG_05,"Mayo"
_MONTH_LONG_06,"Junio"
_MONTH_LONG_07,"Julio"
_MONTH_LONG_08,"Agosto"
_MONTH_LONG_09,"Septiembre"
_MONTH_LONG_10,"Octubre"
_MONTH_LONG_11,"Noviembre"
_MONTH_LONG_12,"Diciembre"
_MONTH_SHORT_01,"Ene"
_MONTH_SHORT_02,"Feb"
_MONTH_SHORT_03,"Mar"
_MONTH_SHORT_04,"Abr"
_MONTH_SHORT_05,"May"
_MONTH_SHORT_06,"Jun"
_MONTH_SHORT_07,"Jul"
_MONTH_SHORT_08,"Ago"
_MONTH_SHORT_09,"Sep"
_MONTH_SHORT_10,"Oct"
_MONTH_SHORT_11,"Nov"
_MONTH_SHORT_12,"Dic"
_WEEKDAY_0,"Domingo"
_WEEKDAY_1,"Lunes"
_WEEKDAY_2,"Martes"
_WEEKDAY_3,"Miércoles"
_WEEKDAY_4,"Jueves"
_WEEKDAY_5,"Viernes"
_WEEKDAY_6,"Sábado"
