"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",es

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"Enero"
_MONTH_LONG_02,"Febrero"
_MONTH_LONG_03,"Marzo"
_MONTH_LONG_04,"Abril"
_MONTH_LONG_05,"Mayo"
_MONTH_LONG_06,"Junio"
_MONTH_LONG_07,"Julio"
_MONTH_LONG_08,"Agosto"
_MONTH_LONG_09,"Septiembre"
_MONTH_LONG_10,"Octubre"
_MONTH_LONG_11,"Noviembre"
_MONTH_LONG_12,"Diciembre"
_MONTH_SHORT_01,"Ene"
_MONTH_SHORT_02,"Feb"
_MONTH_SHORT_03,"Mar"
_MONTH_SHORT_04,"Abr"
_MONTH_SHORT_05,"May"
_MONTH_SHORT_06,"Jun"
_MONTH_SHORT_07,"Jul"
_MONTH_SHORT_08,"Ago"
_MONTH_SHORT_09,"Sep"
_MONTH_SHORT_10,"Oct"
_MONTH_SHORT_11,"Nov"
_MONTH_SHORT_12,"Dic"
_WEEKDAY_0,"Domingo"
_WEEKDAY_1,"Lunes"
_WEEKDAY_2,"Martes"
_WEEKDAY_3,"Miércoles"
_WEEKDAY_4,"Jueves"
_WEEKDAY_5,"Viernes"
_WEEKDAY_6,"Sábado"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"