"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",fi

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"tammikuu"
_MONTH_LONG_02,"helmikuu"
_MONTH_LONG_03,"maaliskuu"
_MONTH_LONG_04,"huhtikuu"
_MONTH_LONG_05,"toukokuu"
_MONTH_LONG_06,"kesäkuu"
_MONTH_LONG_07,"heinäkuu"
_MONTH_LONG_08,"elokuu"
_MONTH_LONG_09,"syyskuu"
_MONTH_LONG_10,"lokakuu"
_MONTH_LONG_11,"marraskuu"
_MONTH_LONG_12,"joulukuu"
_MONTH_SHORT_01,"tammikuu"
_MONTH_SHORT_02,"helmikuu"
_MONTH_SHORT_03,"maaliskuu"
_MONTH_SHORT_04,"huhtikuu"
_MONTH_SHORT_05,"toukokuu"
_MONTH_SHORT_06,"kesäkuu"
_MONTH_SHORT_07,"heinäkuu"
_MONTH_SHORT_08,"elokuu"
_MONTH_SHORT_09,"syyskuu"
_MONTH_SHORT_10,"lokakuu"
_MONTH_SHORT_11,"marraskuu"
_MONTH_SHORT_12,"joulukuu"
_WEEKDAY_0,"sunnuntai"
_WEEKDAY_1,"maanantai"
_WEEKDAY_2,"tiistai"
_WEEKDAY_3,"keskiviikko"
_WEEKDAY_4,"torstai"
_WEEKDAY_5,"perjantai"
_WEEKDAY_6,"lauantai"