"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",fr

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"janvier"
_MONTH_LONG_02,"février"
_MONTH_LONG_03,"mars"
_MONTH_LONG_04,"avril"
_MONTH_LONG_05,"mai"
_MONTH_LONG_06,"juin"
_MONTH_LONG_07,"juillet"
_MONTH_LONG_08,"août"
_MONTH_LONG_09,"septembre"
_MONTH_LONG_10,"octobre"
_MONTH_LONG_11,"novembre"
_MONTH_LONG_12,"décembre"
_MONTH_SHORT_01,"jan"
_MONTH_SHORT_02,"fev"
_MONTH_SHORT_03,"mars"
_MONTH_SHORT_04,"avr"
_MONTH_SHORT_05,"mai"
_MONTH_SHORT_06,"juin"
_MONTH_SHORT_07,"juil"
_MONTH_SHORT_08,"août"
_MONTH_SHORT_09,"sep"
_MONTH_SHORT_10,"oct"
_MONTH_SHORT_11,"nov"
_MONTH_SHORT_12,"dec"
_WEEKDAY_0,"dimanche"
_WEEKDAY_1,"lundi"
_WEEKDAY_2,"mardi"
_WEEKDAY_3,"mercredi"
_WEEKDAY_4,"jeudi"
_WEEKDAY_5,"vendredi"
_WEEKDAY_6,"samedi"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"