"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",gu

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"જાન્યુઆરી"
_MONTH_LONG_02,"ફેબ્રુઆરી"
_MONTH_LONG_03,"માર્ચ"
_MONTH_LONG_04,"એપ્રિલ"
_MONTH_LONG_05,"મે,"
_MONTH_LONG_06,"જૂન"
_MONTH_LONG_07,"જુલાઈ"
_MONTH_LONG_08,"ઓગસ્ટ"
_MONTH_LONG_09,"સપ્ટેમ્બર"
_MONTH_LONG_10,"ઓક્ટોબર"
_MONTH_LONG_11,"નવેમ્બર"
_MONTH_LONG_12,"ડિસેમ્બર"
_MONTH_SHORT_01,"જાન્યુઆરી"
_MONTH_SHORT_02,"ફેબ્રુઆરી"
_MONTH_SHORT_03,"માર્ચ"
_MONTH_SHORT_04,"એપ્રિલ"
_MONTH_SHORT_05,"મે,"
_MONTH_SHORT_06,"જૂન"
_MONTH_SHORT_07,"જુલાઈ"
_MONTH_SHORT_08,"ઓગસ્ટ"
_MONTH_SHORT_09,"સપ્ટેમ્બર"
_MONTH_SHORT_10,"ઓક્ટોબર"
_MONTH_SHORT_11,"નવેમ્બર"
_MONTH_SHORT_12,"ડિસેમ્બર"
_WEEKDAY_0,"રવિવાર"
_WEEKDAY_1,"સોમવાર"
_WEEKDAY_2,"મંગળવાર"
_WEEKDAY_3,"બુધવાર"
_WEEKDAY_4,"ગુરુવાર"
_WEEKDAY_5,"શુક્રવાર"
_WEEKDAY_6,"શનિવાર"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"