"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",hu

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"január"
_MONTH_LONG_02,"február"
_MONTH_LONG_03,"március"
_MONTH_LONG_04,"április"
_MONTH_LONG_05,"május"
_MONTH_LONG_06,"június"
_MONTH_LONG_07,"július"
_MONTH_LONG_08,"augusztus"
_MONTH_LONG_09,"szeptember"
_MONTH_LONG_10,"október"
_MONTH_LONG_11,"november"
_MONTH_LONG_12,"december"
_MONTH_SHORT_01,"január"
_MONTH_SHORT_02,"február"
_MONTH_SHORT_03,"március"
_MONTH_SHORT_04,"április"
_MONTH_SHORT_05,"május"
_MONTH_SHORT_06,"június"
_MONTH_SHORT_07,"július"
_MONTH_SHORT_08,"augusztus"
_MONTH_SHORT_09,"szeptember"
_MONTH_SHORT_10,"október"
_MONTH_SHORT_11,"november"
_MONTH_SHORT_12,"december"
_WEEKDAY_0,"vasárnap"
_WEEKDAY_1,"hétfő"
_WEEKDAY_2,"kedd"
_WEEKDAY_3,"szerda"
_WEEKDAY_4,"csütörtök"
_WEEKDAY_5,"péntek"
_WEEKDAY_6,"szombat"