"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",it

Plugin
zenario_common_features

"Phrase Code",Translation
_COOKIE_CONSENT_ACCEPT,"Accetta"
_COOKIE_CONSENT_CLOSE,"Chiudi"
_COOKIE_CONSENT_CONTINUE,"Continuare"
_COOKIE_CONSENT_IMPLIED_MESSAGE,"Questo sito mette i cookie sul vostro computer per fornire funzionalità essenziale e per offrire la migliore esperienza. Se si continua a utilizzare questo sito, si suppone che si accetta a questo. Si prega di consultare la nostra politica sulla privacy per ulteriori informazioni."
_COOKIE_CONSENT_MESSAGE,"Questo sito potrebbe caricare cookies sul tuo computer. Uno di questi è essenziale per il funzionamento del sito e quindi è già stato caricato; accettandone altri faciliterai la tua navigazione. Per favore guarda la pagina dedicata alla Privacy Policy per ulteriori informazioni."
_COOKIE_CONSENT_REJECT,"Rifiuta"
_MONTH_LONG_01,"gennaio"
_MONTH_LONG_02,"febbraio"
_MONTH_LONG_03,"marzo"
_MONTH_LONG_04,"aprile"
_MONTH_LONG_05,"maggio"
_MONTH_LONG_06,"giugno"
_MONTH_LONG_07,"luglio"
_MONTH_LONG_08,"agosto"
_MONTH_LONG_09,"settembre"
_MONTH_LONG_10,"ottobre"
_MONTH_LONG_11,"novembre"
_MONTH_LONG_12,"dicembre"
_MONTH_SHORT_01,"gennaio"
_MONTH_SHORT_02,"febbraio"
_MONTH_SHORT_03,"marzo"
_MONTH_SHORT_04,"aprile"
_MONTH_SHORT_05,"maggio"
_MONTH_SHORT_06,"giugno"
_MONTH_SHORT_07,"luglio"
_MONTH_SHORT_08,"agosto"
_MONTH_SHORT_09,"settembre"
_MONTH_SHORT_10,"ottobre"
_MONTH_SHORT_11,"novembre"
_MONTH_SHORT_12,"dicembre"
_WEEKDAY_0,"domenica"
_WEEKDAY_1,"Lunedi"
_WEEKDAY_2,"martedì"
_WEEKDAY_3,"mercoledì"
_WEEKDAY_4,"Giovedi"
_WEEKDAY_5,"venerdì"
_WEEKDAY_6,"sabato"