"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",it

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"gennaio"
_MONTH_LONG_02,"febbraio"
_MONTH_LONG_03,"marzo"
_MONTH_LONG_04,"aprile"
_MONTH_LONG_05,"maggio"
_MONTH_LONG_06,"giugno"
_MONTH_LONG_07,"luglio"
_MONTH_LONG_08,"agosto"
_MONTH_LONG_09,"settembre"
_MONTH_LONG_10,"ottobre"
_MONTH_LONG_11,"novembre"
_MONTH_LONG_12,"dicembre"
_MONTH_SHORT_01,"gennaio"
_MONTH_SHORT_02,"febbraio"
_MONTH_SHORT_03,"marzo"
_MONTH_SHORT_04,"aprile"
_MONTH_SHORT_05,"maggio"
_MONTH_SHORT_06,"giugno"
_MONTH_SHORT_07,"luglio"
_MONTH_SHORT_08,"agosto"
_MONTH_SHORT_09,"settembre"
_MONTH_SHORT_10,"ottobre"
_MONTH_SHORT_11,"novembre"
_MONTH_SHORT_12,"dicembre"
_WEEKDAY_0,"domenica"
_WEEKDAY_1,"Lunedi"
_WEEKDAY_2,"martedì"
_WEEKDAY_3,"mercoledì"
_WEEKDAY_4,"Giovedi"
_WEEKDAY_5,"venerdì"
_WEEKDAY_6,"sabato"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"