"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",ja

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"1月"
_MONTH_LONG_02,"2月"
_MONTH_LONG_03,"3月"
_MONTH_LONG_04,"4月"
_MONTH_LONG_05,"5月"
_MONTH_LONG_06,"6月"
_MONTH_LONG_07,"7月"
_MONTH_LONG_08,"8月"
_MONTH_LONG_09,"9月"
_MONTH_LONG_10,"10月"
_MONTH_LONG_11,"11月"
_MONTH_LONG_12,"12月"
_MONTH_SHORT_01,"1月"
_MONTH_SHORT_02,"2月"
_MONTH_SHORT_03,"3月"
_MONTH_SHORT_04,"4月"
_MONTH_SHORT_05,"5月"
_MONTH_SHORT_06,"6月"
_MONTH_SHORT_07,"7月"
_MONTH_SHORT_08,"8月"
_MONTH_SHORT_09,"9月"
_MONTH_SHORT_10,"10月"
_MONTH_SHORT_11,"11月"
_MONTH_SHORT_12,"12月"
_WEEKDAY_0,"日曜日"
_WEEKDAY_1,"月曜日"
_WEEKDAY_2,"火曜日"
_WEEKDAY_3,"水曜日"
_WEEKDAY_4,"木曜日"
_WEEKDAY_5,"金曜日"
_WEEKDAY_6,"土曜日"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"