"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",pl

Plugin
zenario_common_features

"Phrase Code",Translation
_COOKIE_CONSENT_ACCEPT,"Zgadzam się"
_COOKIE_CONSENT_CLOSE,"Zamknij"
_COOKIE_CONSENT_CONTINUE,"Kontunuuj"
_COOKIE_CONSENT_IMPLIED_MESSAGE,"Ta strona umieszcza w pamięci Twojej przeglądarki internetowej ciasteczka. Są one niezbędne do prawidłowego i pełnego działania strony. Pozostając na tej stronie wyrażasz zgodę na umieszczenie ciasteczek. Więcej informacji na ten temat znajdziesz w naszej Polityce Prywatności."
_COOKIE_CONSENT_MESSAGE,"Ta strona chce uzyskać Twoją zgodę na umieszczenie w pamięci Twojej przeglądarki ciasteczek. Jedno z nich, niezbędne do poprawnego działania strony zostało już zainstalowane. Wyrażając zgodę na zainstalowanie kolejnych ciasteczek możesz osiągnąć lepszą i szybszą funkcjonalność strony. Więcej informacji na ten temat znajdziesz w naszej Polityce Prywatności."
_COOKIE_CONSENT_REJECT,"Nie zgadzam się"
_MONTH_LONG_01,"Styczeń"
_MONTH_LONG_02,"Luty"
_MONTH_LONG_03,"Marzec"
_MONTH_LONG_04,"Kwiecień"
_MONTH_LONG_05,"Maj"
_MONTH_LONG_06,"Czerwiec"
_MONTH_LONG_07,"Lipiec"
_MONTH_LONG_08,"Sierpień"
_MONTH_LONG_09,"Wrzesień"
_MONTH_LONG_10,"Październik"
_MONTH_LONG_11,"Listopad"
_MONTH_LONG_12,"Grudzień"
_MONTH_SHORT_01,"Sty"
_MONTH_SHORT_02,"Lut"
_MONTH_SHORT_03,"Mar"
_MONTH_SHORT_04,"Kwi"
_MONTH_SHORT_05,"Maj"
_MONTH_SHORT_06,"Cze"
_MONTH_SHORT_07,"Lip"
_MONTH_SHORT_08,"Sie"
_MONTH_SHORT_09,"Wrz"
_MONTH_SHORT_10,"Paź"
_MONTH_SHORT_11,"Lis"
_MONTH_SHORT_12,"Gru"
_WEEKDAY_0,"Niedziela"
_WEEKDAY_1,"Poniedziałek"
_WEEKDAY_2,"Wtorek"
_WEEKDAY_3,"Środa"
_WEEKDAY_4,"Czwartek"
_WEEKDAY_5,"Piątek"
_WEEKDAY_6,"Sobota"