"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",pl

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"Styczeń"
_MONTH_LONG_02,"Luty"
_MONTH_LONG_03,"Marzec"
_MONTH_LONG_04,"Kwiecień"
_MONTH_LONG_05,"Maj"
_MONTH_LONG_06,"Czerwiec"
_MONTH_LONG_07,"Lipiec"
_MONTH_LONG_08,"Sierpień"
_MONTH_LONG_09,"Wrzesień"
_MONTH_LONG_10,"Październik"
_MONTH_LONG_11,"Listopad"
_MONTH_LONG_12,"Grudzień"
_MONTH_SHORT_01,"Sty"
_MONTH_SHORT_02,"Lut"
_MONTH_SHORT_03,"Mar"
_MONTH_SHORT_04,"Kwi"
_MONTH_SHORT_05,"Maj"
_MONTH_SHORT_06,"Cze"
_MONTH_SHORT_07,"Lip"
_MONTH_SHORT_08,"Sie"
_MONTH_SHORT_09,"Wrz"
_MONTH_SHORT_10,"Paź"
_MONTH_SHORT_11,"Lis"
_MONTH_SHORT_12,"Gru"
_WEEKDAY_0,"Niedziela"
_WEEKDAY_1,"Poniedziałek"
_WEEKDAY_2,"Wtorek"
_WEEKDAY_3,"Środa"
_WEEKDAY_4,"Czwartek"
_WEEKDAY_5,"Piątek"
_WEEKDAY_6,"Sobota"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"bajt"
_FILE_SIZE_UNIT_BYTES,"bajty"