"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",pt-eu

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"janeiro"
_MONTH_LONG_02,"fevereiro"
_MONTH_LONG_03,"março"
_MONTH_LONG_04,"abril"
_MONTH_LONG_05,"maio"
_MONTH_LONG_06,"junho"
_MONTH_LONG_07,"julho"
_MONTH_LONG_08,"agosto"
_MONTH_LONG_09,"setembro"
_MONTH_LONG_10,"outubro"
_MONTH_LONG_11,"novembro"
_MONTH_LONG_12,"dezembro"
_MONTH_SHORT_01,"janeiro"
_MONTH_SHORT_02,"fevereiro"
_MONTH_SHORT_03,"março"
_MONTH_SHORT_04,"abril"
_MONTH_SHORT_05,"maio"
_MONTH_SHORT_06,"junho"
_MONTH_SHORT_07,"julho"
_MONTH_SHORT_08,"agosto"
_MONTH_SHORT_09,"setembro"
_MONTH_SHORT_10,"outubro"
_MONTH_SHORT_11,"novembro"
_MONTH_SHORT_12,"dezembro"
_WEEKDAY_0,"domingo"
_WEEKDAY_1,"segunda-feira"
_WEEKDAY_2,"terça-feira"
_WEEKDAY_3,"quarta-feira"
_WEEKDAY_4,"quinta-feira"
_WEEKDAY_5,"sexta-feira"
_WEEKDAY_6,"sábado"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"