"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",ro

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"ianuarie"
_MONTH_LONG_02,"februarie"
_MONTH_LONG_03,"martie"
_MONTH_LONG_04,"aprilie"
_MONTH_LONG_05,"mai"
_MONTH_LONG_06,"iunie"
_MONTH_LONG_07,"iulie"
_MONTH_LONG_08,"august"
_MONTH_LONG_09,"septembrie"
_MONTH_LONG_10,"octombrie"
_MONTH_LONG_11,"noiembrie"
_MONTH_LONG_12,"decembrie"
_MONTH_SHORT_01,"ianuarie"
_MONTH_SHORT_02,"februarie"
_MONTH_SHORT_03,"martie"
_MONTH_SHORT_04,"aprilie"
_MONTH_SHORT_05,"mai"
_MONTH_SHORT_06,"iunie"
_MONTH_SHORT_07,"iulie"
_MONTH_SHORT_08,"august"
_MONTH_SHORT_09,"septembrie"
_MONTH_SHORT_10,"octombrie"
_MONTH_SHORT_11,"noiembrie"
_MONTH_SHORT_12,"decembrie"
_WEEKDAY_0,"duminică"
_WEEKDAY_1,"luni"
_WEEKDAY_2,"marţi"
_WEEKDAY_3,"miercuri"
_WEEKDAY_4,"joi"
_WEEKDAY_5,"vineri"
_WEEKDAY_6,"sâmbătă"