"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",ru

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"январь"
_MONTH_LONG_02,"февраль"
_MONTH_LONG_03,"март"
_MONTH_LONG_04,"апрель"
_MONTH_LONG_05,"может"
_MONTH_LONG_06,"июнь"
_MONTH_LONG_07,"июль"
_MONTH_LONG_08,"август"
_MONTH_LONG_09,"сентябрь"
_MONTH_LONG_10,"октябрь"
_MONTH_LONG_11,"ноябрь"
_MONTH_LONG_12,"декабрь"
_MONTH_SHORT_01,"январь"
_MONTH_SHORT_02,"февраль"
_MONTH_SHORT_03,"март"
_MONTH_SHORT_04,"апрель"
_MONTH_SHORT_05,"может"
_MONTH_SHORT_06,"июнь"
_MONTH_SHORT_07,"июль"
_MONTH_SHORT_08,"август"
_MONTH_SHORT_09,"сентябрь"
_MONTH_SHORT_10,"октябрь"
_MONTH_SHORT_11,"ноябрь"
_MONTH_SHORT_12,"декабрь"
_WEEKDAY_0,"воскресенье"
_WEEKDAY_1,"понедельник"
_WEEKDAY_2,"вторник"
_WEEKDAY_3,"среда"
_WEEKDAY_4,"четверг"
_WEEKDAY_5,"пятница"
_WEEKDAY_6,"суббота"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"