"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",th

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"มกราคม"
_MONTH_LONG_02,"กุมภาพันธ์"
_MONTH_LONG_03,"มีนาคม"
_MONTH_LONG_04,"เมษายน"
_MONTH_LONG_05,"อาจ"
_MONTH_LONG_06,"มิถุนายน"
_MONTH_LONG_07,"กรกฎาคม"
_MONTH_LONG_08,"สิงหาคม"
_MONTH_LONG_09,"กันยายน"
_MONTH_LONG_10,"ตุลาคม"
_MONTH_LONG_11,"พฤศจิกายน"
_MONTH_LONG_12,"ธันวาคม"
_MONTH_SHORT_01,"มกราคม"
_MONTH_SHORT_02,"กุมภาพันธ์"
_MONTH_SHORT_03,"มีนาคม"
_MONTH_SHORT_04,"เมษายน"
_MONTH_SHORT_05,"อาจ"
_MONTH_SHORT_06,"มิถุนายน"
_MONTH_SHORT_07,"กรกฎาคม"
_MONTH_SHORT_08,"สิงหาคม"
_MONTH_SHORT_09,"กันยายน"
_MONTH_SHORT_10,"ตุลาคม"
_MONTH_SHORT_11,"พฤศจิกายน"
_MONTH_SHORT_12,"ธันวาคม"
_WEEKDAY_0,"วันอาทิตย์"
_WEEKDAY_1,"วันจันทร์"
_WEEKDAY_2,"วันอังคาร"
_WEEKDAY_3,"วันพุธ"
_WEEKDAY_4,"วันพฤหัสบดี"
_WEEKDAY_5,"วันศุกร์"
_WEEKDAY_6,"วันเสาร์"