"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",uk

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"січень"
_MONTH_LONG_02,"лютий"
_MONTH_LONG_03,"Березень"
_MONTH_LONG_04,"Квітень"
_MONTH_LONG_05,"може"
_MONTH_LONG_06,"Червень"
_MONTH_LONG_07,"Липень"
_MONTH_LONG_08,"Серпень"
_MONTH_LONG_09,"вересень"
_MONTH_LONG_10,"Жовтень"
_MONTH_LONG_11,"Листопад"
_MONTH_LONG_12,"грудень"
_MONTH_SHORT_01,"січень"
_MONTH_SHORT_02,"лютий"
_MONTH_SHORT_03,"Березень"
_MONTH_SHORT_04,"Квітень"
_MONTH_SHORT_05,"може"
_MONTH_SHORT_06,"Червень"
_MONTH_SHORT_07,"Липень"
_MONTH_SHORT_08,"Серпень"
_MONTH_SHORT_09,"вересень"
_MONTH_SHORT_10,"Жовтень"
_MONTH_SHORT_11,"Листопад"
_MONTH_SHORT_12,"грудень"
_WEEKDAY_0,"неділя"
_WEEKDAY_1,"Понеділок"
_WEEKDAY_2,"вівторок"
_WEEKDAY_3,"середа"
_WEEKDAY_4,"четвер"
_WEEKDAY_5,"п\'ятниця"
_WEEKDAY_6,"Субота"