"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",vi

Plugin
zenario_common_features

"Phrase Code",Translation
_MONTH_LONG_01,"tháng một"
_MONTH_LONG_02,"Tháng hai"
_MONTH_LONG_03,"diễu hành"
_MONTH_LONG_04,"Tháng Tư"
_MONTH_LONG_05,"có thể"
_MONTH_LONG_06,"Tháng sáu"
_MONTH_LONG_07,"Tháng Bảy"
_MONTH_LONG_08,"Tháng Tám"
_MONTH_LONG_09,"Tháng Chín"
_MONTH_LONG_10,"Tháng Mười"
_MONTH_LONG_11,"Tháng mười một"
_MONTH_LONG_12,"Tháng mười hai"
_MONTH_SHORT_01,"tháng một"
_MONTH_SHORT_02,"Tháng hai"
_MONTH_SHORT_03,"diễu hành"
_MONTH_SHORT_04,"Tháng Tư"
_MONTH_SHORT_05,"có thể"
_MONTH_SHORT_06,"Tháng sáu"
_MONTH_SHORT_07,"Tháng Bảy"
_MONTH_SHORT_08,"Tháng Tám"
_MONTH_SHORT_09,"Tháng Chín"
_MONTH_SHORT_10,"Tháng Mười"
_MONTH_SHORT_11,"Tháng mười một"
_MONTH_SHORT_12,"Tháng mười hai"
_WEEKDAY_0,"Chủ Nhật"
_WEEKDAY_1,"Thứ Hai"
_WEEKDAY_2,"Thứ ba"
_WEEKDAY_3,"Thứ tư"
_WEEKDAY_4,"Thứ năm"
_WEEKDAY_5,"Thứ Sáu"
_WEEKDAY_6,"Thứ bảy"