"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",zh-hans

Plugin
zenario_common_features

"Phrase Code",Translation
__LANGUAGE_ENGLISH_NAME__,"Chinese"
__LANGUAGE_FLAG_FILENAME__,"cn"
__LANGUAGE_LOCAL_NAME__,"中文"
_GROUP_1,"询问"
_MONTH_LONG_01,"一月"
_MONTH_LONG_02,"二月"
_MONTH_LONG_03,"三月"
_MONTH_LONG_04,"四月"
_MONTH_LONG_05,"五月"
_MONTH_LONG_06,"六月"
_MONTH_LONG_07,"七月"
_MONTH_LONG_08,"八月"
_MONTH_LONG_09,"九月"
_MONTH_LONG_10,"十月"
_MONTH_LONG_11,"十一月"
_MONTH_LONG_12,"十二月"
_MONTH_SHORT_01,"一月"
_MONTH_SHORT_02,"二月"
_MONTH_SHORT_03,"三月"
_MONTH_SHORT_04,"四月"
_MONTH_SHORT_05,"五月"
_MONTH_SHORT_06,"六月"
_MONTH_SHORT_07,"七月"
_MONTH_SHORT_08,"八月"
_MONTH_SHORT_09,"九月"
_MONTH_SHORT_10,"十月"
_MONTH_SHORT_11,"十一月"
_MONTH_SHORT_12,"十二月"
_WEEKDAY_0,"星期日"
_WEEKDAY_1,"星期一"
_WEEKDAY_2,"星期二"
_WEEKDAY_3,"星期三"
_WEEKDAY_4,"星期四"
_WEEKDAY_5,"（星期五）"
_WEEKDAY_6,"星期六"
_FILE_SIZE_UNIT_GB,"GB"
_FILE_SIZE_UNIT_MB,"MB"
_FILE_SIZE_UNIT_KB,"KB"
_FILE_SIZE_UNIT_BYTE,"byte"
_FILE_SIZE_UNIT_BYTES,"bytes"