"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",zh-hans

Plugin
zenario_common_features

"Phrase Code",Translation
__LANGUAGE_ENGLISH_NAME__,"Chinese"
__LANGUAGE_FLAG_FILENAME__,"cn"
__LANGUAGE_LOCAL_NAME__,"中文"
_COOKIE_CONSENT_ACCEPT,"接受"
_COOKIE_CONSENT_CLOSE,"关闭"
_COOKIE_CONSENT_CONTINUE,"继续"
_COOKIE_CONSENT_IMPLIED_MESSAGE,"这个网站放置了少量信息为了对您的计算机提供必要的功能，为您提供最好的体验。如果您继续使用本网站，我们将假定您同意这个。请参见我们的隐私权政策的更多信息"
_COOKIE_CONSENT_MESSAGE,"这个网站将把少量信息放在你的电脑。少量信息，是网站操作发送出去必不可少的。如果你接受进一步的小量信息将会提高你的经验。请参见我们的隐私权政策的更多信息"
_COOKIE_CONSENT_REJECT,"拒绝"
_GROUP_1,"询问"
_MONTH_LONG_01,"一月"
_MONTH_LONG_02,"二月"
_MONTH_LONG_03,"三月"
_MONTH_LONG_04,"四月"
_MONTH_LONG_05,"五月"
_MONTH_LONG_06,"六月"
_MONTH_LONG_07,"七月"
_MONTH_LONG_08,"八月"
_MONTH_LONG_09,"九月"
_MONTH_LONG_10,"十月"
_MONTH_LONG_11,"十一月"
_MONTH_LONG_12,"十二月"
_MONTH_SHORT_01,"一月"
_MONTH_SHORT_02,"二月"
_MONTH_SHORT_03,"三月"
_MONTH_SHORT_04,"四月"
_MONTH_SHORT_05,"五月"
_MONTH_SHORT_06,"六月"
_MONTH_SHORT_07,"七月"
_MONTH_SHORT_08,"八月"
_MONTH_SHORT_09,"九月"
_MONTH_SHORT_10,"十月"
_MONTH_SHORT_11,"十一月"
_MONTH_SHORT_12,"十二月"
_WEEKDAY_0,"星期日"
_WEEKDAY_1,"星期一"
_WEEKDAY_2,"星期二"
_WEEKDAY_3,"星期三"
_WEEKDAY_4,"星期四"
_WEEKDAY_5,"（星期五）"
_WEEKDAY_6,"星期六"
