# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_contact_form
    tabs:
        first_tab:
            label: Contact form
            fields:
                basic_fields_tab_description:
                    ord: 0
                    full_width: true
                    snippet:
                        html: >
                            This tab lets you show and hide basic fields on your contact
                            form.
                display_mode:
                    label: 'Display mode:'
                    type: radios
                    plugin_setting:
                        name: display_mode
                    values:
                        inline_in_page: inline in page
                        in_modal_window: in modal window
                    value: inline_in_page
                Name_field:
                    plugin_setting:
                        name: Name_field
                    label: 'Name:'
                    type: select
                    style: width:220px;
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: mandatory
                    note_below: 'This field uses the &quot;_NAME:&quot; and &quot;_NAME_INCOMPLETE&quot; visitor phrases'
                Email_field:
                    plugin_setting:
                        name: Email_field
                    label: 'Email:'
                    type: select
                    style: width:220px;
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show and validate
                        mandatory:
                            label: Show, validate and check complete
                    value: mandatory
                    note_below: 'This field uses the &quot;_EMAIL:&quot; and &quot;_EMAIL_INCOMPLETE&quot; visitor phrases'
                Phone_field:
                    plugin_setting:
                        name: Phone_field
                    label: 'Phone:'
                    type: select
                    style: width:220px;
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: optional
                    note_below: 'This field uses the &quot;_PHONE:&quot; and &quot;_PHONE_INCOMPLETE&quot; visitor phrases'
                Textarea_field:
                    plugin_setting:
                        name: Textarea_field
                    label: 'Textarea:'
                    type: select
                    style: width:220px;
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: mandatory
                    format_onchange: Yes
                Textarea_field_name:
                    plugin_setting:
                        name: Textarea_field_name
                    label: 'Field name:'
                    type: text
                    value: _MESSAGE
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_MESSAGE:&quot; and &quot;_MESSAGE_INCOMPLETE&quot;'
                use_thankyou_page:
                    plugin_setting:
                        name: use_thankyou_page
                    label: 'Use thank you page:'
                    type: checkbox
                    format_onchange: Yes
                thankyou_page:
                    plugin_setting:
                        name: thankyou_page
                        foreign_key_to: content
                        dangling_cross_references: remove
                    label: 'Content Item:'
                    pick_items:
                        by_language: Yes
                        min_path: zenario__content/nav/languages/panel
                        max_path: zenario__content/nav/content/panel
                        target_path: zenario__content/nav/content/panel
                        disallow_refiners_looping_on_min_path: Yes
                        select_phrase: Select Content Item...
                        hide_remove_button: Yes
                    validation:
                        required_if_not_hidden: Please select a Content Item
                    format_onchange: Yes
        additional_fields:
            label: Additional fields
            fields:
                additional_fields_tab_description:
                    full_width: Yes
                    snippet:
                        html: >
                            This Tab lets you add additional fields on your contact
                            form. You may also choose which visitor phrases they use.
                Additional_field_1:
                    plugin_setting:
                        name: Additional_field_1
                    label: 'Additional field 1:'
                    type: select
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: hidden
                    format_onchange: Yes
                Additional_field_1_name:
                    plugin_setting:
                        name: Additional_field_1_name
                    label: 'Field name:'
                    type: text
                    value: _COMPANY
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_COMPANY:&quot; and &quot;_COMPANY_INCOMPLETE&quot;'
                Additional_field_2:
                    plugin_setting:
                        name: Additional_field_2
                    label: 'Additional field 2:'
                    type: select
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: hidden
                    format_onchange: Yes
                Additional_field_2_name:
                    plugin_setting:
                        name: Additional_field_2_name
                    label: 'Field name:'
                    type: text
                    value: _ADDRESS
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_ADDRESS:&quot; and &quot;_ADDRESS_INCOMPLETE&quot;'
                Additional_field_3:
                    plugin_setting:
                        name: Additional_field_3
                    label: 'Additional field 3:'
                    type: select
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: hidden
                    format_onchange: Yes
                Additional_field_3_name:
                    plugin_setting:
                        name: Additional_field_3_name
                    label: 'Field name:'
                    type: text
                    value: _CITY
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_CITY:&quot; and &quot;_CITY_INCOMPLETE&quot;'
                Additional_field_4:
                    plugin_setting:
                        name: Additional_field_4
                    label: 'Additional field 4:'
                    type: select
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: hidden
                    format_onchange: Yes
                Additional_field_4_name:
                    plugin_setting:
                        name: Additional_field_4_name
                    label: 'Field name:'
                    type: text
                    value: _PROVINCE
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_PROVINCE:&quot; and &quot;_PROVINCE_INCOMPLETE&quot;'
                Additional_field_5:
                    plugin_setting:
                        name: Additional_field_5
                    label: 'Additional field 5:'
                    type: select
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: hidden
                    format_onchange: Yes
                Additional_field_5_name:
                    plugin_setting:
                        name: Additional_field_5_name
                    label: 'Field name:'
                    type: text
                    value: _POST_CODE
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_POST_CODE:&quot; and &quot;_POST_CODE_INCOMPLETE&quot;'
                Additional_field_6:
                    plugin_setting:
                        name: Additional_field_6
                    label: 'Additional field 6:'
                    type: select
                    values:
                        hidden:
                            label: "Don't show"
                        optional:
                            label: Show
                        mandatory:
                            label: Show and check complete
                    value: hidden
                    format_onchange: Yes
                Additional_field_6_name:
                    plugin_setting:
                        name: Additional_field_6_name
                    label: 'Field name:'
                    type: text
                    value: _COUNTRY
                    note_below: 'This name is used for visitor phrases; e.g. &quot;_COUNTRY:&quot; and &quot;_COUNTRY_INCOMPLETE&quot;'
        captcha:
            label: Captcha
            fields:
                captcha_tab_description:
                    full_width: Yes
                    snippet:
                        html: This tab lets you enable a captcha.
                use_captcha:
                    plugin_setting:
                        name: use_captcha
                    label: 'Require visitors to complete a captcha:'
                    type: checkbox
                    value: "1"
                    format_onchange: Yes
                    
                captcha_type:
                    plugin_setting:
                        name: captcha_type
                    label: 'Type of captcha:'
                    type: select
                    values:
                        words:
                            label: 'Words'
                        math:
                            label: 'Math'
                    value: words
                
                extranet_users_use_captcha:
                    plugin_setting:
                        name: extranet_users_use_captcha
                    label: 'Require extranet users to complete a captcha:'
                    type: checkbox
        email:
            label: Email
            fields:
                email_tab_description:
                    full_width: Yes
                    snippet:
                        html: >
                            This tab lets you set up the email you will receive when a
                            visitor uses your contact form.
                send_email:
                    label: Send email
                    type: radios
                    plugin_setting:
                        name: send_email
                    values:
                        send: Send
                        do_not_send: Do not send
                    value: send
                    format_onchange: Yes
                email_template:
                    plugin_setting:
                        name: email_template
                        foreign_key_to: email_template
                        dangling_cross_references: remove
                    label: 'Use this email template to send form submissions:'
                    type: sk
                    pick_items:
                        path: zenario__email_template_manager/nav/email_templates/panel
                        min_path: zenario__email_template_manager/nav/email_templates/panel
                        max_path: zenario__email_template_manager/nav/email_templates/panel
                        target_path: zenario__email_template_manager/nav/email_templates/panel
                        select_phrase: Select Email Template...
                        nothing_selected_phrase: No Email Template selected
                        hide_remove_button: Yes
                    value: zenario_contact_form__to_admin_contact_form_en
                    note_below: >
                        Please see the module description to get a full list of
                        merge fields which can be used in the selected email
                        template.
                    validation:
                        required_if_not_hidden: Please select an email template
                email_address:
                    plugin_setting:
                        name: email_address
                    label: 'Send to email address:'
                    type: text
                    note_below: Separate multiple addresses with commas.
                    validation:
                        required_if_not_hidden: Please enter an email address

                add_reply_to: 
                    label: |
                        Optional "reply-to":
                    plugin_setting: 
                        name: add_reply_to
                    
                    type: checkbox
                    format_onchange: Yes
                
                
                reply_to_email_address: 
                    plugin_setting: 
                        name: reply_to_email_address
                    
                    label: 'Reply-to email using:'
                    type: text
                    validation: 
                        required_if_not_hidden: |
                            Please enter an email address form field.
                    
                    note_below: |
                        You should specify a form field to be used as email on "reply-to".
                
                reply_to_first_name: 
                    plugin_setting: 
                        name: reply_to_first_name
                    
                    label: 'Reply-to first name using:'
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a first name form field.
                    
                    note_below: |
                        You should specify a form field to be used as first name to be used on "reply-to".
                
                reply_to_last_name: 
                    plugin_setting: 
                        name: reply_to_last_name
                    
                    label: 'Reply-to last name using:'
                    type: text
                    note_below: |
                        Optionally you can specify one form field for the last name to be used on "reply-to".
                
