# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_document_container
    tabs:
        first_tab:
            fields:
                container_mode:
                    plugin_setting:
                        name: container_mode
                    label: 'Scope:'
                    type: radios
                    value: documents
                    values: 
                        documents: 
                            ord: 1
                            label: "Show a specific document, or select a folder to show documents inside"
                        user_documents: 
                            ord: 2
                            label: "Automatically show confidential documents for the logged-in user"
                    format_onchange: true
                document_source:
                    visible_if: |
                        zenarioAB.value('container_mode') == 'documents'
                    plugin_setting:
                        name: document_source
                    label: 'Select document or folder:'
                    side_note: 'Select either a specific document, or a folder containing one or more documents.'
                    pick_items:
                        path: zenario__content/panels/documents
                        min_path: zenario__content/panels/documents
                        max_path: zenario__content/panels/documents
                        target_path: zenario__content/panels/documents
                        select_phrase: Select...
                    format_onchange: true
                    indent: 1
                show_files_in_folders:
                    plugin_setting:
                        name: show_files_in_folders
                    label: "Show documents:"
                    type: radios
                    value: folder
                    values:
                        folder:
                            label: 'Only in selected folder'
                        sub-folders:
                            label: 'Descend one level of sub-folder'
                        all:
                            label: 'Descend all levels of sub-folder'
                    format_onchange: true
                    indent: 1
                show_folders_in_results:
                    plugin_setting:
                        name: show_folders_in_results
                    label: "Show sub-folder names in results"
                    type: checkbox
                    indent: 2
                show_folder_name_as_title:
                    plugin_setting:
                        name: show_folder_name_as_title
                    label: "Show selected folder name as title"
                    type: checkbox
                    redraw_onchange: true
                    indent: 1
                title_tags:
                    hide_with_previous_field: true
                    visible_if: |
                        zenarioAB.value('show_folder_name_as_title')
                    plugin_setting:
                        name: title_tags
                    label: 'Title heading tags'
                    type: select
                    values:
                        h1: Heading 1
                        h2: Heading 2
                        h3: Heading 3
                        h4: Heading 4
                        h5: Heading 5
                        h6: Heading 6
                        p: Paragraph
                    value: h1
                    side_note: |
                        Choose which HTML tags the title will be displayed in.
                    indent: 2
                show_filename:
                    plugin_setting:
                        name: show_filename
                    label: 'Show document filename'
                    type: checkbox
                    value: 1
                show_title:
                    plugin_setting:
                        name: show_title
                    label: "Show document title"
                    type: checkbox
                    redraw_onchange: true
                show_filename_if_no_title:
                    visible_if: |
                        zenarioAB.value('show_title');
                    indent: 1
                    plugin_setting:
                        name: show_filename_if_no_title
                    label: "Show document filename if no title exists"
                    type: checkbox
                show_file_size:
                    plugin_setting:
                        name: show_file_size
                    label: "Show document file size"
                    type: checkbox
                show_upload_date:
                    plugin_setting:
                        name: show_upload_date
                    label: "Show document upload date"
                    type: checkbox
                show_thumbnails:
                    plugin_setting:
                        name: show_thumbnails
                    label: "Show document thumbnails (if available)"
                    type: checkbox
                    format_onchange: true
                lazy_load_images:
                    plugin_setting:
                        name: lazy_load_images
                    label: "Lazy load thumbnails"
                    type: checkbox
                    indent: 1
                    visible_if: |
                        zenarioAB.value('show_thumbnails');
                canvas:
                    plugin_setting:
                        name: canvas
                    label: 'Image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                    indent: 1
                width:
                    plugin_setting:
                        name: width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                height:
                    plugin_setting:
                        name: height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                offer_download_as_zip:
                    plugin_setting:
                        name: offer_download_as_zip
                    label: 'Offer download as ZIP file'
                    type: checkbox
                    redraw_onchange: true
                zip_file_name:
                    visible_if: |
                        zenarioAB.value('offer_download_as_zip')
                    plugin_setting:
                        name: zip_file_name
                    label: 'ZIP archive name'
                    type: text
                    side_note: >
                        You can specify the name of the ZIP archive. If you
                        leave this field empty, the folder name will be used.
                    post_field_html: '.zip'
                    indent: 1
                document_tags:
                    plugin_setting:
                        name: document_tags
                    label: 'Only show documents with one of the tags:'
                    type: checkboxes
                    load_values_from_organizer_path: zenario__content/panels/document_tags
