# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Navigator settings
            fields:
                menu_section:
                    plugin_setting:
                        name: menu_section
                        foreign_key_to: menu_section
                        dangling_cross_references: delete_instance
                    label: 'Menu section:'
                    pick_items:
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/sections
                        max_path: zenario__menu/panels/sections
                        target_path: zenario__menu/panels/sections
                        select_phrase: Select Menu Section...
                        hide_remove_button: Yes
                    value: "1"
                    validation:
                        required: Please select a menu section
                show_parent:
                    plugin_setting:
                        name: show_parent
                    label: 'Show parent:'
                    type: checkbox
                    value: "1"
                show_previous:
                    plugin_setting:
                        name: show_previous
                    label: 'Show previous:'
                    type: checkbox
                    value: "1"
                show_next:
                    plugin_setting:
                        name: show_next
                    label: 'Show next:'
                    type: checkbox
                    value: "1"
                min_level:
                    plugin_setting:
                        name: min_level
                    label: 'Show on:'
                    type: select
                    values:
                        0:
                            label: Top level menu nodes and lower
                        1:
                            label: Second level menu nodes and lower
                        2:
                            label: Third level menu nodes and lower
    module_class_name: zenario_menu_forward_back_navigator
