# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Destination
            fields:
                redirect:
                    plugin_setting:
                        name: redirect
                    label: 'Redirect visitors back to the page they logged out from:'
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                redirect_if_private:
                    plugin_setting:
                        name: redirect_if_private
                    label: 'Redirect even if the page is Private:'
                    type: checkbox
                    value: ""
                    note_below: >
                        Visitors will be asked to log back in again in for Private
                        pages.
    module_class_name: zenario_extranet_logout
