# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    tabs:
        zenario_pro_features__caching:
            label: Caching
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            notices:
                img_dir_writable:
                    type: success
                    message: >
                        The public/images/
                        and private/images/
                        directories are writable.
                img_dir_not_writable:
                    type: warning
                    message: >
                        The public/images/
                        and private/images/
                        directories are not writable, images and thumbnails will not be cached.
            
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab contains settings for caching the output of the CMS into static files,
                            to reduce the load on your server and make your Web Pages load more quickly for visitors.
                caching_enabled:
                    site_setting:
                        name: caching_enabled
                    label: 'Enable caching'
                    type: checkbox
                    redraw_onchange: true
                    note_below: |
                        Allows pages and other generated files to be saved to disk, then later served up from
                        the disk without needing to run the CMS to generate the file again.
                
                cache_web_pages:
                    site_setting:
                        name: cache_web_pages
                    label: 'Cache web pages'
                    type: checkbox
                    redraw_onchange: true
                    visible_if: |
                        zenarioAB.value('caching_enabled')
                    note_below: |
                        Allows a page to be saved to disk.
                        Page caching provides a greater speedup than plugin caching, but is only possible on pages
                        where every plugin on the page allows itself to be cached.
                caching_debug_info:
                    site_setting:
                        name: caching_debug_info
                    label: 'Show debug info'
                    type: checkbox
                    visible_if: |
                        zenarioAB.value('caching_enabled') &&
                        zenario.engToBoolean(zenarioAB.value('cache_web_pages'))
                    redraw_onchange: true
                    note_below: |
                        This allows you to click on a button at the bottom right of each page in visitor mode
                        to see debug information on caching.
                        <br/>
                        As this information is shown to visitors, you should not enable this setting on a live site.
                limit_caching_debug_info_by_ip:
                    label: 'Only show debug info to my current IP address'
                    type: checkbox
                    visible_if: |
                        zenario.engToBoolean(zenarioAB.value('caching_enabled')) &&
                        zenario.engToBoolean(zenarioAB.value('cache_web_pages')) &&
                        zenario.engToBoolean(zenarioAB.value('caching_debug_info'))
                    note_below: |
                        Only shows caching debug info when pages are viewed from your current IP address.
                cache_plugins:
                    site_setting:
                        name: cache_plugins
                    label: 'Cache plugins'
                    type: checkbox
                    visible_if: |
                        zenarioAB.value('caching_enabled')
                    note_below: |
                        Allows the output of each plugin on a page to be saved to disk.
                        Plugin caching is helpful on pages that cannot be fully cached.
                cache_css_js_wrappers:
                    site_setting:
                        name: cache_css_js_wrappers
                    label: 'Cache CSS and JavaScript file wrappers'
                    type: checkbox
                    visible_if: |
                        zenarioAB.value('caching_enabled')
                    note_below: |
                        Allows CSS and JavaScript file wrappers to be saved to disk.
                        This won't affect your CSS files if you have &quot;CSS File Wrappers&quot; turned off.
                cache_ajax:
                    site_setting:
                        name: cache_ajax
                    label: 'Cache AJAX and RSS'
                    type: checkbox
                    visible_if: |
                        zenarioAB.value('caching_enabled')
                    note_below: |
                        Allows AJAX requests and RSS feeds to be saved to disk.
                        
                cache_images:
                    label: 'Cache images'
                    type: checkbox
                    read_only: true
                    note_below: |
                        The CMS will create cached copies of images and thumbnails in the <code>public/images/</code>
                        and <code>private/images/</code> directories if they are writable.
                
                browser_caching_note:
                    full_width: true
                    snippet:
                        html: |
                            Browsers may cache AJAX requests, CSS and JavaScript files, even if the
                            caching in the CMS is disabled.
                            <br/>
                            CSS and JavaScript files will be automatically cleared from the caches of all browsers
                            when you edit these files on the server and then refresh the site in admin mode.
                
                    
                
        zenario_pro_features__cache_stats:
            priv: _PRIV_EDIT_SITE_SETTING
            label: Cache Stats
            visible_if: |
                zenario.engToBoolean(zenarioAB.value('caching_enabled', 'zenario_pro_features__caching'))
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: true
                always_on: true
            notices:
                notice:
                    type: success
                    message: The statistics have been reset.
                    show: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                This tab shows you how this site is using the cache.
                            </p><p>
                                Sites that frequently change will have a lower percentage of hits than sites that are static.
                                Sites that use lots of User customisation (such as GeoIP, &quot;Welcome&quot; messages for logged in Extranet Users or Private Menu Nodes)
                                will have a lower percentage of hits than sites without an Extranet.
                            </p>
                total:
                    label: 'Total:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 10em;'
                    note_below: The total number of pages requested.
                hits:
                    label: 'Hits:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 10em;'
                    note_below: The number of pages served from the cache.
                hits_pc:
                    label: 'Hit Percentage:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 6em;'
                    post_field_html: %
                writes:
                    label: 'Writes:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 10em;'
                    note_below: The number of pages written to the cache.
                partial_hits:
                    label: 'Partial Hits:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 10em;'
                partial_writes:
                    label: 'Partial Writes:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 10em;'
                    note_below: >
                        Partial hits and writes are where a page could not be
                        cached, but some of the Plugins on the page were cached.
                misses:
                    label: 'Misses:'
                    type: text
                    read_only: true
                    value: ""
                    style: 'width: 10em;'
                    note_below: >
                        The number of requested pages that did not make use of the
                        cache.
                from:
                    label: 'From:'
                    type: datetime
                    read_only: true
                    value: ""
                to:
                    label: 'To:'
                    type: datetime
                    read_only: true
                    value: ""
                    note_below: The date range that these statistics have been recorded in.
                refresh_stats:
                    full_width: false
                    value: Refresh Stats
                    class: submit
                    type: submit
                clear_stats:
                    full_width: false
                    value: Reset Stats
                    class: submit_selected
                    type: toggle
                    format_onchange: true
        zenario_pro_features__clear_cache:
            priv: _PRIV_EDIT_SITE_SETTING
            label: Clear the Cache
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: true
                always_on: true
            notices:
                notice:
                    type: success
                    message: The cache has been cleared.
                    show: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                Any change that could potentially affect your whole site (for example a change to a plugin, site setting, template file, layout or Phrase)
                                will clear the entire cache.
                                Any changes made in the filesystem (for example changes to frameworks or modules) will also clear the cache,
                                however the cache will not be cleared until someone logged in as an administrator visits the site.
                            </p><p>
                                Any change that affects only a specific content item (such as publishing a draft, hiding or trashing a published page) will only clear related files.
                            </p><p>
                                Any change that does not relate to the contents of a page (for example a change to an administrator, email template, spare alias or spare domain name) will not
                                clear anything in the cache.
                            </p><p>
                                If you wish to manually clear the cache you may do so by pressing this button.
                            </p>
                clear_cache:
                    full_width: false
                    value: Clear Cache
                    class: submit_selected
                    type: toggle
                    format_onchange: true
    setting_group: web_pages
