# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    tabs:
        security:
            fields:
                admin_use_ssl:
                    site_setting:
                        name: admin_use_ssl
                    label: 'Force Admin SSL:'
                    type: checkbox
                    format_onchange: Yes
                    note_below: |
                        If this is enabled, Administrators will not be able to log in to the site without using an SSL connection.
                                                    As a safety measure to stop you locking yourself out of your site, you may only enable this whilst using an SSL connection.
                admin_use_ssl_port:
                    site_setting:
                        name: admin_use_ssl_port
                    label: 'Port Number:'
                    type: text
                    size: "10"
                    maxlength: "10"
                    note_below: >
                        If this is left blank the port number will not be added to
                        the URL.
                    validation:
                        numeric: The Port Number must be numeric.
    setting_group: administration
