# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: domains
    tabs:
        admin_domain:
            fields:
                admin_use_ssl:
                    site_setting:
                        name: admin_use_ssl
                        protect_from_database_restore: true
                    label: 'Force Admin SSL:'
                    type: checkbox
                    format_onchange: Yes
                    side_note: |
                        If this is enabled, Administrators will not be able to log in to the site without using an SSL connection.
                        As a safety measure to stop you locking yourself out of your site, you may only enable this whilst using an SSL connection.