# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    tabs:
        zenario_pro_features__caching:
            label: Page and Plugin Caching
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: |
                            This tab contains settings for caching the output of the CMS into static files,
                                                                to reduce the load on your server and make your Web Pages load more quickly for visitors.
                cache_web_pages:
                    site_setting:
                        name: cache_web_pages
                    label: 'Cache Web Pages'
                    type: checkbox
                    format_onchange: Yes
                    note_below: |
                        Allows a page to be saved to disk, then later served up from the disk without needing to run the CMS to generate the page again.
                                                        Page caching provides a greater speedup than Plugin caching, but is only possible on pages where every Plugin on the page allows itself to be cached.
                                                        <br/>
                                                        To enable this setting, you must first enable the &quot;Compress Web Pages&quot; Site Setting on the &quot;Speed&quot; tab.
                cache_plugins:
                    site_setting:
                        name: cache_plugins
                    label: 'Cache Plugins'
                    type: checkbox
                    note_below: |
                        Allows the output of each Plugin on a page to be saved to disk, then later served up from the disk without needing to run the Module to generate the Plugin again.
                                                        Plugin caching is helpful on pages that cannot be fully cached.
                                                        <br/>
                                                        To enable this setting, you must first enable the &quot;Cache Web Pages&quot; Site Setting above.
                cache_ajax:
                    site_setting:
                        name: cache_ajax
                    label: 'Cache AJAX and RSS'
                    type: checkbox
                    note_below: |
                        Allows the server response to any AJAX requests and RSS feeds generated by Plugins to be cached.
                                                        <br/>
                                                        To enable this setting, you must first enable the &quot;Cache Web Pages&quot; Site Setting above.
                                                        
                caching_debug_info:
                    site_setting:
                        name: caching_debug_info
                    label: 'Show debug info'
                    type: checkbox
                    format_onchange: true
                    note_below: |
                        This allows you to click on a button at the bottom right of each page in Visitor Mode to see debug information on caching.
                                                        <br/>
                                                        As this information is shown to visitors, you should not enable this setting on a live site.
                limit_caching_debug_info_by_ip:
                    label: 'Only show debug info to my current IP address'
                    type: checkbox
                    note_below: |
                        Only shows caching debug info when pages are viewed from your current IP address.
                    
                
        zenario_pro_features__cache_stats:
            priv: _PRIV_EDIT_SITE_SETTING
            label: Cache Stats
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: Yes
                always_on: Yes
            notices:
                notice:
                    type: success
                    message: The statistics have been reset.
                    show: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                                                    This tab shows you how this site is using the cache.
                                                                </p><p>
                                                                    Sites that frequently change will have a lower percentage of hits than sites that are static.
                                                                    Sites that use lots of User customisation (such as GeoIP, &quot;Welcome&quot; messages for logged in Extranet Users or Private Menu Nodes)
                                                                    will have a lower percentage of hits than sites without an Extranet.
                                                                </p>
                total:
                    label: 'Total:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 10em;'
                    note_below: The total number of pages requested.
                hits:
                    label: 'Hits:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 10em;'
                    note_below: The number of pages served from the cache.
                hits_pc:
                    label: 'Hit Percentage:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 6em;'
                    post_field_html: %
                writes:
                    label: 'Writes:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 10em;'
                    note_below: The number of pages written to the cache.
                partial_hits:
                    label: 'Partial Hits:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 10em;'
                partial_writes:
                    label: 'Partial Writes:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 10em;'
                    note_below: >
                        Partial hits and writes are where a page could not be
                        cached, but some of the Plugins on the page were cached.
                misses:
                    label: 'Misses:'
                    type: text
                    read_only: Yes
                    value: ""
                    style: 'width: 10em;'
                    note_below: >
                        The number of requested pages that did not make use of the
                        cache.
                from:
                    label: 'From:'
                    type: datetime
                    read_only: Yes
                    value: ""
                to:
                    label: 'To:'
                    type: datetime
                    read_only: Yes
                    value: ""
                    note_below: The date range that these statistics have been recorded in.
                refresh_stats:
                    full_width: No
                    value: Refresh Stats
                    class: submit
                    type: submit
                clear_stats:
                    full_width: No
                    value: Reset Stats
                    class: submit_selected
                    type: toggle
                    format_onchange: Yes
        zenario_pro_features__clear_cache:
            priv: _PRIV_EDIT_SITE_SETTING
            label: Clear the Cache
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: Yes
                always_on: Yes
            notices:
                notice:
                    type: success
                    message: The cache has been cleared.
                    show: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                Any change that could potentially affect your whole site (for example a change to a plugin, site setting, template file, layout or Phrase)
                                will clear the entire cache.
                                Any changes made in the filesystem (for example changes to frameworks or modules) will also clear the cache,
                                however the cache will not be cleared until someone logged in as an administrator visits the site.
                            </p><p>
                                Any change that affects only a specific content item (such as publishing a draft, hiding or trashing a published page) will only clear related files.
                            </p><p>
                                Any change that does not relate to the contents of a page (for example a change to an administrator, email template, spare alias or spare domain name) will not
                                clear anything in the cache.
                            </p><p>
                                If you wish to manually clear the cache you may do so by pressing this button.
                            </p>
                clear_cache:
                    full_width: No
                    value: Clear Cache
                    class: submit_selected
                    type: toggle
                    format_onchange: Yes
    setting_group: web_pages
