# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: email
    tabs:
        zenario_newsletter__site_settings:
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: Yes
            label: Newsletters
            fields:
                zenario_newsletter__default_from_name:
                    label: 'Default "From" name:'
                    site_setting:
                        name: zenario_newsletter__default_from_name
                    type: text
                    validation:
                        required: Please enter default "From" name.
                zenario_newsletter__default_from_email_address:
                    label: 'Default "From" address:'
                    site_setting:
                        name: zenario_newsletter__default_from_email_address
                    type: text
                    validation:
                        required: Please enter default "From" email address.
                        email: Please enter valid "From" email address.
                zenario_newsletter__default_unsubscribe_text:
                    label: 'Default "Unsubscribe" text:'
                    site_setting:
                        name: zenario_newsletter__default_unsubscribe_text
                    type: textarea
                    validation:
                        required: Please enter default "Unsubscribe" text.
                    value: 'To unsubscribe, please click the following link or copy and paste it into your browser:'
                zenario_newsletter__default_delete_account_text:
                    label: 'Default "Delete my account" text:'
                    site_setting:
                        name: zenario_newsletter__default_delete_account_text
                    type: textarea
                    validation:
                        required: Please enter default "Delete account" text.
                    value: 'To have your details deleted from the website that sent you this email, please click the following link or copy and paste it into your browser:'
                zenario_newsletter__all_newsletters_opt_out:
                    label: 'User opt-out flag:'
                    side_note: 'When a recipient clicks an Unsubscribe link, set this flag.'
                    site_setting:
                        name: zenario_newsletter__all_newsletters_opt_out
                    type: select
                    empty_value: '-- Select --'
                    validation:
                        required: Please select the flag on the user/contact record that should be set when a recipient clicks an Unsubscribe link.
                
                
                zenario_newsletter__newsletter_consent_policy:
                    label: 'Consent policy:'
                    site_setting:
                        name: zenario_newsletter__newsletter_consent_policy
                    type: select
                    empty_value: '-- Select --'
                    values:
                        consent_required:
                            label: 'Users must consent to receiving newsletters (recommended)'
                        no_consent_required:
                            label: 'No consent required'
                    redraw_onchange: true
                    validation:
                        required: Please choose a consent policy for newsletters.
                    
                zenario_newsletter__newsletter_consent_flag:
                    indent: 1
                    visible_if: zenarioAB.value('zenario_newsletter__newsletter_consent_policy') == 'consent_required'
                    label: 'User consent flag:'
                    side_note: 'The flag that indicates a user has consented to receive newsletters'
                    site_setting:
                        name: zenario_newsletter__newsletter_consent_flag
                    type: select
                    empty_value: '-- Select --'
                    validation:
                        required_if_not_hidden: Please select the flag on the user/contact record that shows consent to receive newsletters.
                
                zenario_newsletter__enable_opened_emails:
                    label: 'Enable opened-email tracking'
                    side_note: 'Check this option to enable tracking of opened emails.'
                    site_setting:
                        name: zenario_newsletter__enable_opened_emails
                    type: checkbox
        
        newsletter_css_rules:
            label: Newsletter CSS rules
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>These CSS rules will be available when composing a newsletter or newsletter template.</p>
                            <p>The contents are automatically wrapped in <code>&lt;style&gt;&lt;/style&gt;</code> tags.</p>
                newsletter_css_rules:
                    site_setting:
                        name: newsletter_css_rules
                    label: 'CSS rules:'
                    type: code_editor
                    tall_as_possible: true
                    dont_trim: true
                    language: css
                    style: >
                        width: 98%;
                    value: |
                        .newsletter.style_blue {
                            background-color: #f8f9fa;
                        }
                        
                        .newsletter.style_green {
                            background-color: #ffffff;
                        }
                        
                        .newsletter table.button tr td {
                            padding: 12px 24px; 
                            background-color: #0e76bc; 
                            text-align: center;
                        }
                        
                        .newsletter table.button tr td a {
                            color:#ffffff;
                            display:inline-block !important;
                        }
                        
                        .newsletter.style_green table.button tr td {
                            background-color: #42bd4c;
                        }
                        
                        .newsletter h1,
                        .newsletter h2,
                        .newsletter h3,
                        .newsletter h4 {
                            font-family: Arial, Helvetica, sans-serif;
                            color:#000;
                        }
                        
                        .newsletter h2,
                        .newsletter h3,
                        .newsletter h4 {
                            font-weight: bold;
                        }
                        
                        .newsletter.style_blue h1 {
                            margin: 0; 
                            font-size: 28px; 
                            font-weight: normal; 
                        }
                        
                        .newsletter.style_blue h2 {
                            margin: 0 0 12px; 
                            font-size: 22px;  
                            line-height: 1.3; 
                        }
                        
                        .newsletter.style_blue h3 {
                            margin: 0 0 20px; 
                            font-size: 16px; 
                            text-transform: uppercase; 
                        }
                        
                        .newsletter.style_blue h4 {
                            margin: 0 0 6px; 
                            font-size: 16px; 
                            line-height: 1.3; 
                        }
                        
                        .newsletter.style_green h1 {
                            margin: 0; 
                            font-size: 24px; 
                            font-weight: bold;
                        }
                        
                        .newsletter.style_green h2 {
                            margin: 0 0 15px; 
                            font-size: 20px; 
                            line-height: 1.2; 
                        }
                        
                        .newsletter.style_green h3 {
                            margin: 0 0 10px; 
                            font-size: 14px;  
                            color: #0e76bc;  
                            text-transform: uppercase;
                        }