# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_user_forms
    tabs:
        first_tab:
            label: Settings
            fields:
                user_form:
                    label: 'Form:'
                    plugin_setting:
                        name: user_form
                    pick_items:
                        path: zenario__user_forms/panels/zenario_user_forms__forms
                        min_path: zenario__user_forms/panels/zenario_user_forms__forms
                        max_path: zenario__user_forms/panels/zenario_user_forms__forms
                        target_path: zenario__user_forms/panels/zenario_user_forms__forms
                        select_phrase: Select Form...
                        hide_remove_button: true
                    validation:
                        required: Please choose a Form
                display_mode:
                    plugin_setting:
                        name: display_mode
                    label: 'Display mode:'
                    type: radios
                    values:
                        inline_in_page: 
                            label: inline in page
                            ord: 1
                        in_modal_window: 
                            label: in modal window
                            ord: 2
                    value: inline_in_page
                    format_onchange: true
                display_text:
                    plugin_setting:
                        name: display_text
                    label: 'Display text:'
                    type: text
                    value: Click me
                    side_note: |
                        This text will be translated
                    validation:
                        required_if_not_hidden: Please enter text to be used as a link to the form
                checkbox_columns:
                    plugin_setting:
                        name: checkbox_columns
                    label: 'Checkbox columns:'
                    type: select
                    values:
                        1: 1
                        2: 2
                        3: 3
                        4: 4
                        5: 5
                        6: 6
                    value: 1
                    side_note: The number of columns that a multiple checkboxes field will be displayed in. If there aren't at least 2x the number of checkboxes as columns, the list will be displayed in a single column.
