site_settings:
    setting_group: zenario_user_forms__site_settings_group
    title: |
        Editing settings for Forms and CRM integration
    tabs:
        zenario_user_forms_emails:
            label: Details
            edit_mode:
                enabled: Yes
            fields:
                site_settings:
                    type: grouping
                file_size:
                    type: grouping
                    snippet:
                        label: "Maximum file size for form attachments:"
                        label_class: subheading
                data_protection_link:
                    grouping: site_settings
                    snippet:
                        html: ''
                zenario_user_forms_admin_email_attachments:
                    grouping: site_settings
                    site_setting:
                        name: zenario_user_forms_admin_email_attachments
                    label: 'When sending response emails to administrators, attach uploaded files'
                    type: checkbox
                    side_note: |
                        Emails sent to administrators will include attachments. If not set, administrators will need to log in to Zenario to retrieve uploads.
                zenario_user_forms_enable_predefined_text:
                    grouping: site_settings
                    site_setting:
                        name: zenario_user_forms_enable_predefined_text
                    label: 'Enable pre-defined text'
                    type: checkbox
                    side_note: |
                        Textareas in a form can have text pre-defined. The text is stored next to other fields. When a button next to the textarea is clicked by a visitor, the other fields are evaluated and if they have been checked the respective text is added to the textarea.
                zenario_user_forms_max_attachment_file_size_override:
                    grouping: file_size
                    site_setting:
                        name: zenario_user_forms_max_attachment_file_size_override
                    label: "Restrict uploads to..."
                    type: checkbox
                    value: false
                    redraw_onchange: true
                zenario_user_forms_content_max_filesize:
                    grouping: file_size
                    indent: 1
                    site_setting:
                        name: zenario_user_forms_content_max_filesize
                    label: 'User Forms maximum file size:'
                    type: text
                    value: 8
                    validation:
                        required_if_not_hidden: Please enter a maximum content file size.
                        numeric: Must be numeric.
                    decimal_places: ""
                    visible_if: lib.value('zenario_user_forms_max_attachment_file_size_override')
                    maxlength: 10
                    style: "width: 7em;"
                zenario_user_forms_content_max_filesize_unit:
                    grouping: file_size
                    indent: 1
                    site_setting:
                        name: zenario_user_forms_content_max_filesize_unit
                    label: 'Unit:'
                    same_row: true
                    type: select
                    values:
                        KB:
                            label: KB
                        MB:
                            label: MB
                        GB:
                            label: GB
                    value: MB
                    redraw_onchange: true
                    visible_if: lib.value('zenario_user_forms_max_attachment_file_size_override')
                global_upload_setting_info:
                    grouping: file_size
                    snippet:
                        html: |
                            <div class="zenario_fbInfo">
                                [[global_upload_setting_string]]
                            </div>
        zenario_user_forms_profanity_filter:
            label:  Profanity filter
            edit_mode:
                enabled: Yes
            fields:
                zenario_user_forms_set_profanity_filter:
                    site_setting:
                        name: zenario_user_forms_set_profanity_filter
                    label: 'Enable profanity filtering'
                    row_class: sub_field
                    type: checkbox
                    note_below: |
                        Scan text and textarea fields for swear words. Must be enabled on each specific form using the "Filter for profanities" option. Blocked forms will be logged, but not emailed.
                    redraw_onchange: true
                    disabled: false
                zenario_user_forms_set_profanity_tolerence:
                    site_setting:
                        name: zenario_user_forms_set_profanity_tolerence
                    label: 'Tolerance level:'
                    type: select
                    values:
                        5:
                            ord: 1
                            label: Low (blocks most forms with profanities)
                        10:
                            ord: 2
                            label: Medium
                        15:
                            ord: 3
                            label: High (blocks only the worst profanities)
                    value: 5
                    visible_if: |
                        zenarioAB.value('zenario_user_forms_set_profanity_filter')
                    disabled: false
