# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: data_protection
    tabs:
        data_protection:
            fields:
                period_to_delete_the_form_response_log_headers:
                    label: 'How long should form responses be saved?'
                    site_setting:
                        name: period_to_delete_the_form_response_log_headers
                    ord: 2
                    type: select
                    values:
                        0:
                            label: Don't save
                        1:
                            label: Delete after 1 day
                        7:
                            label: Delete after 1 week
                        14:
                            label: Delete after 2 weeks
                        30:
                            label: Delete after 1 month
                        90:
                            label: Delete after 3 months
                        180:
                            label: Delete after 6 months
                        270:
                            label: Delete after 9 months
                        365:
                            label: Delete after 1 year
                        730: 
                            label: Delete after 2 years
                        never_delete:
                            label: Save forever  
                    value: never_delete
                    redraw_onchange: true
                
                delete_form_response_log_content_sooner:
                    visible_if: zenarioAB.value('period_to_delete_the_form_response_log_headers') != '0'
                    indent: 1
                    site_setting:
                        name: delete_form_response_log_content_sooner
                    label: Delete content sooner (just save headers)
                    ord: 3
                    type: checkbox
                    redraw_onchange: true

                
                period_to_delete_the_form_response_log_content:
                    visible_if: zenarioAB.value('delete_form_response_log_content_sooner')
                    hide_with_previous_field: true
                    indent: 2
                    site_setting:
                        name: period_to_delete_the_form_response_log_content
                    ord: 4
                    type: select
                    values:
                        0:
                            label: Don't save
                        1:
                            label: Delete after 1 day
                        7:
                            label: Delete after 1 week
                        14:
                            label: Delete after 2 weeks
                        30:
                            label: Delete after 1 month
                        90:
                            label: Delete after 3 months
                        180:
                            label: Delete after 6 months
                        270:
                            label: Delete after 9 months
                        365:
                            label: Delete after 1 year
                        730: 
                            label: Delete after 2 years
                
                period_to_delete_the_form_partial_responses:
                    label: 'If save-until-later enabled, how long should partial response form data be saved?'
                    site_setting:
                        name: period_to_delete_the_form_partial_responses
                    ord: 5
                    type: select
                    
                    values:
                        7:
                            label: Delete after 1 week
                        14:
                            label: Delete after 2 weeks
                        30:
                            label: Delete after 1 month
                        90:
                            label: Delete after 3 months
                        180:
                            label: Delete after 6 months
                        270:
                            label: Delete after 9 months
                        365:
                            label: Delete after 1 year
                        730: 
                            label: Delete after 2 years
                        never_delete:
                            label: Save forever  
                    value: 90