# You must use a tab-size of 4 spaces to edit this file.
---
author_name: Tribal Systems
copyright_info: © Tribal Limited
editions: Pro, ProBusiness, Enterprise
start_running_on_install: false
license_info: 'Modified BSD License'
display_name: Newsletter
description: |
            <p>Design and send HTML Newsletters to extranet users and contacts.</p>
            <p>You can create an HTML formatted newsletter using the usual Zenario WYSIWYG editor.</p>
            <p>You can choose from a number of pre-formatted emails (you'll find these in your Email Templates), or design your own.</p>
            <p>It's possible to preview the newsletter on-screen when editing, and there is a "Send test" button to send a test email to yourself or your colleagues.</p>
            <p>When the content is complete, you can select the recipients, these being defined via a smart group, of extranet users and/or contacts.</p>
            <p>Press the "Live send" button to send the newsletter. Once started, you can check progress, and see which recipients have opened the email.</p>
            <p>Each individual email will contain a unique tracking code which allows you to see which recipients have opened the email. (This feature will only work for recipients whose email clients allow viewing of remote images.)</p>
            <p>Unsubscribe functionality is built in, so that recipients can opt out of receiving newsletters.</p>
category: management
keywords: email, inbox, mail, news

# Reminder: you need to increment the LATEST_REVISION_NO in this module's
# latest_revision_no.inc.php file if you change any of the fields below:
is_pluggable: false

# Warning: adding a new dependency to an existing module will break any existing sites
# where the dependency is not running.
# You can fix this on a per-site basis by manually running the dependency, i.e. by running
#   UPDATE zenario_modules SET status = 'module_running' WHERE class_name = 'dependency'
# in MySQL and then going to /admin/ to apply database updates.
# If this is a core module, consider using runNewModuleDependency() in a 
# database-revision in zenario/admin/db_updates/step_4_migrate_the_data/plugins.inc.php
# to fix it automatically for every site.
dependencies:
    zenario_pro_features: true
    zenario_users: true
signals:
    signal1:
        name: eventSmartGroupDeleted
        static: true
jobs:
    job:
        name: jobSendNewsletters
        static: true
        months: jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
        days: mon,tue,wed,thr,fri,sat,sun
        hours: >
            0h,1h,2h,3h,4h,5h,6h,7h,8h,9h,10h,11h,12h,13h,14h,15h,16h,17h,18h,19h,20h,21h,22h,23h
        minutes: 0m,5m,10m,15m,20m,25m,30m,35m,40m,45m,50m,55m
        log_on_action: true
        log_on_no_action: false
        email_on_action: true
