# You must use a tab-size of 4 spaces to edit this file.
---
author_name: Zenario
copyright_info: © Tribal Limited
editions: Pro, ProBusiness, Enterprise
start_running_on_install: false
license_info: Modified BSD License
display_name: Newsletter
description: |
            <p>Design and send HTML Newsletters to your customers.</p>
            <p>You can create an HTML formatted newsletter using the usual zenario WYSIWYG editor.</p>
            <p>You can choose from a number of pre-formatted emails (you'll find these in your Email Templates), or design your own.
                You can embed hyperlinks and images in your Newsletters.</p>
            <p>You can easily specify email sending details (the Subject line, the "From:" Name and email address, and the Reply-to address.</p>
            <p>It's easy to view the newsletter on-screen when editing, and you can press the Test button to send a test email to yourself.</p>
            <p>When you're ready, you can select your recipients from your Extranet Users in your CMS database.
                You can include/exclude Extranet Users to/from Newsletters by:</p>
            <ul>
                <li>Group Membership</li>
                <li>Simple Characteristic (if you have Zenario ProBusiness)</li>
                <li>Recipients of previously sent Newsletters</li>
            </ul>
            <p>Then just press Send!</p>
            <p>If you have the Scheduled Task Module, you may send Newsletters in batch. This lets you send Newsletters to a very large number of 
                recipients.</p>
            <p>Once your sending has started you can check its progress, and even see which recipients have opened the email.
            Each Newsletter sent will contain a unique tracking code, which allows you to see which recipients have opened their Newsletters,
                and the time when they opened. (This feature will not work for Recipients who choose not to view remote images in their email clients.)</p>
            <p>Unsubscribe functionality is built in, so that recipients can opt out of a given Group of recipients,
                or can opt to be removed entirely from the database. Also included are merge fields for the recipient's salutation, first and last name,
                so that each email can be personalized to your taste.</p>
category: management
is_pluggable: No
dependencies:
    zenario_email_template_manager: true
    zenario_pro_features: true
    zenario_users: true
signals:
    signal1:
        name: eventSmartGroupDeleted
        static: Yes
jobs:
    job:
        name: jobSendNewsletters
        static: Yes
        months: jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
        days: mon,tue,wed,thr,fri,sat,sun
        hours: >
            0h,1h,2h,3h,4h,5h,6h,7h,8h,9h,10h,11h,12h,13h,14h,15h,16h,17h,18h,19h,20h,21h,22h,23h
        minutes: 0m,5m,10m,15m,20m,25m,30m,35m,40m,45m,50m,55m,59m
        log_on_action: Yes
        log_on_no_action: No
        email_on_action: Yes
        email_on_no_action: No
