<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed');

	/*
	 * DO NOT EDIT THIS FILE!
	 *
	 * This file was created by the Zenario Gridmaker system.
	 * Any manual edits will be lost when the system next changes this file.
	 */
?>

<script type="text/javascript">
	zenarioL.init({"cols":12,"minWidth":769,"maxWidth":1140,"fluid":true,"responsive":true,"bp1":600,"bp2":900});
</script>

<?php if (file_exists(CMS_ROOT. ze::$templatePath. '/includes/header.inc.php')) {
	require CMS_ROOT. ze::$templatePath. '/includes/header.inc.php';
}?>

<div class="Grid_Header">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega responsive_only slot small_slot Top_Mobile_Menu">
			<?php ze\plugin::slot('Top_Mobile_Menu', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Top_Area alpha omega">
			<div class="span span3 span1_4 alpha slot small_slot Top_1">
				<?php ze\plugin::slot('Top_1', 'grid'); ?>
			</div>
			<div class="span span7 span7_12 responsive slot small_slot Top_2">
				<?php ze\plugin::slot('Top_2', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Top_3">
				<?php ze\plugin::slot('Top_3', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Body">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega slot small_slot Full_Width">
			<?php ze\plugin::slot('Full_Width', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Main_Area alpha omega">
			<div class="span span8 span2_3 alpha slot small_slot Main_1">
				<?php ze\plugin::slot('Main_1', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Side_1">
				<?php ze\plugin::slot('Side_1', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span8 span2_3 Main_Slots alpha">
				<div class="span span8 span1_1 alpha omega slot small_slot Main_2">
					<?php ze\plugin::slot('Main_2', 'grid'); ?>
				</div>
				<div class="grid_clear"></div>
				<div class="span span8 span1_1 alpha omega slot small_slot Main_3">
					<?php ze\plugin::slot('Main_3', 'grid'); ?>
				</div>
				<div class="grid_clear"></div>
				<div class="span span8 span1_1 alpha omega slot small_slot Main_4">
					<?php ze\plugin::slot('Main_4', 'grid'); ?>
				</div>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Side_2">
				<?php ze\plugin::slot('Side_2', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Footer">
	<div class="container container_12">
		<div class="span span12 span1_1 Footer_Area alpha omega">
			<div class="span span2 span1_6 Space_In_Footer alpha responsive grid_space">
				<span class="pad_slot">&nbsp;</span>
			</div>
			<div class="span span8 span2_3 slot small_slot Footer">
				<?php ze\plugin::slot('Footer', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Built_On">
				<?php ze\plugin::slot('Built_On', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="slot Slot_Both">
	<?php ze\plugin::slot('Slot_Both', 'outside_of_grid'); ?>
</div>
<div class="slot Slot_Desktop_Only responsive">
	<?php ze\plugin::slot('Slot_Desktop_Only', 'outside_of_grid'); ?>
</div>
<div class="slot Slot_Mobile_Only responsive_only">
	<?php ze\plugin::slot('Slot_Mobile_Only', 'outside_of_grid'); ?>
</div>

<?php if (file_exists(CMS_ROOT. ze::$templatePath. '/includes/footer.inc.php')) {
	require CMS_ROOT. ze::$templatePath. '/includes/footer.inc.php';
}?>

<?php //data:eJydVFtvgjAU_i99Nosgccrb5qYzmTHRLT4shlSo2FgoobBLjP99p9xWLjVOn-jpd2m_c-wJuYQxgeyPE_qiXnJAtmH2kB9Tz9nFBB-RncQpKSquEI7LsAA8msnCC8EeidG5V2MLxpOSF-KAAPqNR86C7ygjzoKEKQJQgBmDHR6yn6aA6iOZD3ASoLSOOtB6GarkvRZmKgc5UI-oLP1FBui8bZz42sAeude6bYfLNGXM2WSQC9EsMA212Yw6hTNKLRyrE7eGMOq4UYf3Gojin-ZmQ1SHG1yJs-rNuHAd8_a2TTlP2nOuwnKEthuyzRF2SWmjUtdyw5mHpYt-JLtjaB-ue6geU8oSZxleE4NK747kfYX-4gU0jHZ7Wm8Rnmwawk9EHBP42y3lS6EP51a_9bzhV7xTDbv8ndpC67hsrXQLaLgpXpjhGJb4u1gahtXvoT1LqVd6BzSOeYzsPWYCljEREQ8F_awmwp9UuvKzUAIZf5Ymsr-2dWf2az-z2nwl--TZ84lKWFH_oBSz2pSlGp2aTAarSJVQWc4CNuDW_XJhInucLSIoD_OvvHb-BfOTFgY,//v2// ?>
<?php //checksum:I5afAcJK59wFN7Iyds-KZqbNfCQ,// ?>