<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed');

	/*
	 * DO NOT EDIT THIS FILE!
	 *
	 * This file was created by the Zenario Gridmaker system.
	 * Any manual edits will be lost when the system next changes this file.
	 */
?>

<script type="text/javascript">
	zenarioL.init({"cols":12,"minWidth":769,"maxWidth":1366,"fluid":true,"responsive":true,"bp1":0,"bp2":0});
</script>

<?php if (file_exists(CMS_ROOT. ze::$templatePath. '/includes/header.inc.php')) {
	require CMS_ROOT. ze::$templatePath. '/includes/header.inc.php';
}?>

<div class="slot Slot_Top slot_top">
	<?php ze\plugin::slot('Slot_Top', 'outside_of_grid'); ?>
</div>
<div class="Grid_Header Fixed">
	<div class="container container_12">
		<div class="span span3 span1_4 slot_logo alpha slot small_slot Slot_Logo">
			<?php ze\plugin::slot('Slot_Logo', 'grid'); ?>
		</div>
		<div class="span span9 span3_4 slot_menu omega responsive slot small_slot Slot_Menu">
			<?php ze\plugin::slot('Slot_Menu', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 slot_responsive_menu alpha omega responsive_only slot small_slot Slot_Responsive_Menu">
			<?php ze\plugin::slot('Slot_Responsive_Menu', 'grid'); ?>
		</div>
	</div>
</div>
<div class="slot Slot_Masthead slot_masthead">
	<?php ze\plugin::slot('Slot_Masthead', 'outside_of_grid'); ?>
</div>
<div class="Grid_Body">
	<div class="container container_12">
		<div class="span span12 span1_1 Main_Area alpha omega">
			<div class="span span12 span1_1 slot_breadcrumbs alpha omega slot small_slot Slot_Breadcrumbs">
				<?php ze\plugin::slot('Slot_Breadcrumbs', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span12 span1_1 alpha omega slot small_slot Slot_Main_1">
				<?php ze\plugin::slot('Slot_Main_1', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span12 span1_1 alpha omega slot small_slot Slot_Main_2">
				<?php ze\plugin::slot('Slot_Main_2', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span12 span1_1 alpha omega slot small_slot Slot_Main_3">
				<?php ze\plugin::slot('Slot_Main_3', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Footer">
	<div class="container container_12">
		<div class="span span12 span1_1 Footer_Area alpha omega">
			<div class="span span6 span1_2 slot_address alpha slot small_slot Slot_Address">
				<?php ze\plugin::slot('Slot_Address', 'grid'); ?>
			</div>
			<div class="span span6 span1_2 Grouping_Footer omega">
				<div class="span span6 span1_1 slot_social alpha omega slot small_slot Slot_Social">
					<?php ze\plugin::slot('Slot_Social', 'grid'); ?>
				</div>
				<div class="grid_clear"></div>
				<div class="span span6 span1_1 slot_footer alpha omega slot small_slot Slot_Footer">
					<?php ze\plugin::slot('Slot_Footer', 'grid'); ?>
				</div>
				<div class="grid_clear"></div>
				<div class="span span6 span1_1 slot_copyright alpha omega slot small_slot Slot_Copyright">
					<?php ze\plugin::slot('Slot_Copyright', 'grid'); ?>
				</div>
			</div>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 slot_contact_popup alpha omega slot small_slot Slot_Contact_Popup">
			<?php ze\plugin::slot('Slot_Contact_Popup', 'grid'); ?>
		</div>
	</div>
</div>

<?php if (file_exists(CMS_ROOT. ze::$templatePath. '/includes/footer.inc.php')) {
	require CMS_ROOT. ze::$templatePath. '/includes/footer.inc.php';
}?>

<?php //data:eJydVMtuwjAQ_JXKZw4JSFTNDWihB1ArqNRDVUUmNsGqE0e204IQ_961SUJIHR69eWdnZ9a7lncoopwrFHzs0A8jeo0Cv9tBsWQkXEqKv1CgZU47SHGhy7PNRkqFEccKatHEAI8vqINSnFAAFsAO30QGSJ1nREIN8L5zwc5t8UwxofJuzDaU1DV6p_3Vm5iKWLi64AavSTy0S8xomoOESjDngK0ZoS7FxNAaF2uTnFOViVSxb9pUFynfutTlscJldO0Eh4JsL9deXrbVaYwJK72GBTlnU-Ya1nXiDLM0HEAbRsD1KNuGOYQaEsk8WSqX97KWvnI9thX_Jnb3JnYP7T__ucGxEJrKc4M8MFpH2W_vbUAIvDPnFHGRqvn2T2kTKfKMpXHZ4W3WCxExzF3O6pA5NW6TOXo3ZVZ_5nZGZiSyrWTxWruUoioJS2yusV0x1TjS4avIcue3GBWEzBL2n0ARZnpGNGHp-8Hivg8fVYI3Rej3-nCLFc8ZKU0TJqWQKFhhriA8_hvVsxpVuuZYKHkQTXJtRmS-0-I8pSv9RGKo9Stsbq5-BC025vmh7KTKohWnqith-9h9uJPnFUEX_mEbZL7taJkB4u1_Ad4NQU0,//v2// ?>
<?php //checksum:-1bUuH6N0OlvSuWkIfpjhe17QRA,// ?>