<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed');

	/*
	 * DO NOT EDIT THIS FILE!
	 *
	 * This file was created by the Zenario Gridmaker system.
	 * Any manual edits will be lost when the system next changes this file.
	 */
?>

<script type="text/javascript">
	zenarioL.init({"cols":12,"minWidth":960,"maxWidth":1140,"fluid":true,"responsive":true,"bp1":0,"bp2":0});
</script>

<?php if (file_exists(CMS_ROOT. ze::$templatePath. '/includes/header.inc.php')) {
	require CMS_ROOT. ze::$templatePath. '/includes/header.inc.php';
}?>

<div class="slot Slot_After_Body">
	<?php ze\plugin::slot('Slot_After_Body', 'outside_of_grid'); ?>
</div>
<div class="Grid_Header">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega responsive_only slot small_slot Top_Mobile_Menu">
			<?php ze\plugin::slot('Top_Mobile_Menu', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Top_Area alpha omega">
			<div class="span span3 span1_4 alpha slot small_slot Top_1">
				<?php ze\plugin::slot('Top_1', 'grid'); ?>
			</div>
			<div class="span span7 span7_12 responsive slot small_slot Top_2">
				<?php ze\plugin::slot('Top_2', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Top_3">
				<?php ze\plugin::slot('Top_3', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Body">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega slot small_slot Full_Width">
			<?php ze\plugin::slot('Full_Width', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Main_Area alpha omega">
			<div class="span span8 span2_3 alpha slot small_slot Main">
				<?php ze\plugin::slot('Main', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Box_1">
				<?php ze\plugin::slot('Box_1', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span4 span1_3 alpha slot small_slot Box_2">
				<?php ze\plugin::slot('Box_2', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 slot small_slot Box_3">
				<?php ze\plugin::slot('Box_3', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Box_4">
				<?php ze\plugin::slot('Box_4', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Footer">
	<div class="container container_12">
		<div class="span span12 span1_1 Footer_Area alpha omega">
			<div class="span span2 span1_6 Space_In_Footer alpha responsive grid_space">
				<span class="pad_slot">&nbsp;</span>
			</div>
			<div class="span span8 span2_3 slot small_slot Footer">
				<?php ze\plugin::slot('Footer', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Built_On">
				<?php ze\plugin::slot('Built_On', 'grid'); ?>
			</div>
		</div>
		<div class="grid_clear"></div>
		<div class="span span2 span1_6 alpha slot small_slot Slot_VL">
			<?php ze\plugin::slot('Slot_VL', 'grid'); ?>
		</div>
		<div class="span span10 span5_6 omega grid_space">
			<span class="pad_slot">&nbsp;</span>
		</div>
	</div>
</div>

<?php if (file_exists(CMS_ROOT. ze::$templatePath. '/includes/footer.inc.php')) {
	require CMS_ROOT. ze::$templatePath. '/includes/footer.inc.php';
}?>

<?php //data:eJydk11PwyAUhv8L142xXeNH7zbj5pItJm7RC2MIa2lHpNAA1Zll_13ol8xSXXZVzuE57zm80D2IMaUSRK978EkStQWRH3ggEySBG4HRO4iUKLEHJOWqXVe7sZQwpkjqWjAzifkaeIChHOvEStNwnCos4IQnX-Dg_SPvlnzAKMHid7U9StNvzQu45BtCMVxiVupBZI4o1Tuc0V57u4-pHOtJdEnPidFgL9-WvB7EAmuQLUmwXTV8kBE4vJ1pmMtsR5dpSSl8qZA_rFkiwga9uXEKmxJbMnRSE747dnAYC07DRqdh4fnOTjlX_adoYzUxaJi5iQLFuG1jl67MBpyztsvwq3Hb3h_Ofe-TklAFH9mxDW62-oWfFxrVs3JzFnPgnLD63US3V5c6RLsm9P1QxyktSdIK5UQILkCUIip1KLAsOJPko7Mgu-t0zbJR0jLZrFTmQFF4EXTRAqfqPsmwTTyRbPuT3BR-8w1qqGKmtGyFjnSqfEd1SnX68A2HLK3B//v2// ?>
<?php //checksum:ufrcRS_en1U5UMtOFFgjFalJui4,// ?>