<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed');

	/*
	 * DO NOT EDIT THIS FILE!
	 *
	 * This file was created by the Zenario Gridmaker system.
	 * Any manual edits will be lost when the system next changes this file.
	 */
?>

<script type="text/javascript">
	zenarioSGS({"cols":12,"minWidth":769,"maxWidth":1140,"fluid":true,"responsive":true});
</script>

<?php if (file_exists(CMS_ROOT. cms_core::$templatePath. '/includes/header.inc.php')) {
	require CMS_ROOT. cms_core::$templatePath. '/includes/header.inc.php';
}?>

<div class="slot Slot_After_Body">
	<?php slot('Slot_After_Body', 'outside_of_grid'); ?>
</div>
<div class="Grid_Header">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega responsive_only slot small_slot Top_Mobile_Menu">
			<?php slot('Top_Mobile_Menu', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Top_Area alpha omega">
			<div class="span span3 span1_4 alpha slot small_slot Top_1">
				<?php slot('Top_1', 'grid'); ?>
			</div>
			<div class="span span7 span7_12 responsive slot small_slot Top_2">
				<?php slot('Top_2', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Top_3">
				<?php slot('Top_3', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Body">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega slot small_slot Full_Width">
			<?php slot('Full_Width', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Main_Area alpha omega">
			<div class="span span8 span2_3 alpha slot small_slot Main">
				<?php slot('Main', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Box_1">
				<?php slot('Box_1', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span4 span1_3 alpha slot small_slot Box_2">
				<?php slot('Box_2', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 slot small_slot Box_3">
				<?php slot('Box_3', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Box_4">
				<?php slot('Box_4', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Footer">
	<div class="container container_12">
		<div class="span span12 span1_1 Footer_Area alpha omega">
			<div class="span span2 span1_6 Space_In_Footer alpha responsive grid_space">
				<span class="pad_slot">&nbsp;</span>
			</div>
			<div class="span span8 span2_3 slot small_slot Footer">
				<?php slot('Footer', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Built_On">
				<?php slot('Built_On', 'grid'); ?>
			</div>
		</div>
	</div>
</div>

<?php if (file_exists(CMS_ROOT. cms_core::$templatePath. '/includes/footer.inc.php')) {
	require CMS_ROOT. cms_core::$templatePath. '/includes/footer.inc.php';
}?>

<?php //data:eJydUl1vwiAU_S88N8tam330TZfpTGaWTBMfFkOw0EpGwQDdXIz_fVDbBm3ZjG_ce88593BgD1LCmALJxx58U6w3IAmjAOSSYriWBH2CRMuSBEAxoZtzNU2VgilDynDBxDamCxAAjgpiGnODhsNMEwlHAv-AQ_CPfL_kC0GYyHO2a6XetxBbOBNrygicEV4aI6pAjJmJ4Kyz3t1jmUPjxFA6SQy8u0JX8t4LixwjG4qJy_JfZAAOqysD6wu7Z8u4ZAwuK8gf0cwQ5d5sHnqFLcWVjHtRI7E7TdAPiy6DDS6DxdcnOxZCd7-iCzsivIHZl9iilDRrXOrcDuCUN1v8v6Y_9q65_ncflZRp-MZtDCtjQViL9h4F5cv6M989mhLt6jIM49sAZKykuNEqqJRCgiRDTJlSErUVXNGv9mb5U6trj7WSkcknpbY-k_gmaqtXkulnnBMX8U7zjdOsemNWNsQTXtVvUS3z2D78AiainLs,//v2// ?>
<?php //checksum:A6zw9giHQWWufEe8IAX6ssP4JFY,// ?>