<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed');

	/*
	 * DO NOT EDIT THIS FILE!
	 *
	 * This file was created by the Zenario Gridmaker system.
	 * Any manual edits will be lost when the system next changes this file.
	 */
?>

<script type="text/javascript">
	zenarioSGS({"cols":12,"minWidth":769,"maxWidth":1140,"fluid":true,"responsive":true});
</script>

<?php if (file_exists(CMS_ROOT. cms_core::$templatePath. '/includes/header.inc.php')) {
	require CMS_ROOT. cms_core::$templatePath. '/includes/header.inc.php';
}?>

<div class="slot Slot_After_Body">
	<?php slot('Slot_After_Body', 'outside_of_grid'); ?>
</div>
<div class="Grid_Header">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega responsive_only slot small_slot Top_Mobile_Menu">
			<?php slot('Top_Mobile_Menu', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Top_Area alpha omega">
			<div class="span span3 span1_4 alpha slot small_slot Top_1">
				<?php slot('Top_1', 'grid'); ?>
			</div>
			<div class="span span7 span7_12 responsive slot small_slot Top_2">
				<?php slot('Top_2', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Top_3">
				<?php slot('Top_3', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Body">
	<div class="container container_12">
		<div class="span span12 span1_1 alpha omega slot small_slot Full_Width">
			<?php slot('Full_Width', 'grid'); ?>
		</div>
		<div class="grid_clear"></div>
		<div class="span span12 span1_1 Main_Area alpha omega">
			<div class="span span8 span2_3 alpha slot small_slot Main">
				<?php slot('Main', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Box_1">
				<?php slot('Box_1', 'grid'); ?>
			</div>
			<div class="grid_clear"></div>
			<div class="span span4 span1_3 alpha slot small_slot Box_2">
				<?php slot('Box_2', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 slot small_slot Box_3">
				<?php slot('Box_3', 'grid'); ?>
			</div>
			<div class="span span4 span1_3 omega slot small_slot Box_4">
				<?php slot('Box_4', 'grid'); ?>
			</div>
		</div>
	</div>
</div>
<div class="Grid_Footer">
	<div class="container container_12">
		<div class="span span12 span1_1 Footer_Area alpha omega">
			<div class="span span2 span1_6 Space_In_Footer alpha responsive grid_space">
				<span class="pad_slot">&nbsp;</span>
			</div>
			<div class="span span8 span2_3 slot small_slot Footer">
				<?php slot('Footer', 'grid'); ?>
			</div>
			<div class="span span2 span1_6 omega slot small_slot Built_On">
				<?php slot('Built_On', 'grid'); ?>
			</div>
		</div>
		<div class="grid_clear"></div>
		<div class="span span2 span1_6 alpha slot small_slot Slot_VL">
			<?php slot('Slot_VL', 'grid'); ?>
		</div>
		<div class="span span10 span5_6 omega grid_space">
			<span class="pad_slot">&nbsp;</span>
		</div>
	</div>
</div>

<?php if (file_exists(CMS_ROOT. cms_core::$templatePath. '/includes/footer.inc.php')) {
	require CMS_ROOT. cms_core::$templatePath. '/includes/footer.inc.php';
}?>

<?php //data:eJydU1tvwiAU_i88N8tam136pst0Jpol08yHZSFYaCWjYIBuLsb_PqhtgyvdjG89h-9yzgfdg5QwpkDytgdfFOsNSMIoALmkGK4lQR8g0bIkAVBM6Oa7Ok2VgilDynDBxDamSxAAjgpiGguDhsNMEwlHAn-DQ_CPvF_yiSBM5G-2O0rttxRbOBdrygicE16aQVSBGDMngrOOvetjmUMziaF0khj0eoWu5G0vLHIG2VBMXFb_IgNweL8wMF_YHpdxyRhcVZA_opkjynuzufMKW4orGXtRI7E7TbAfFp0HG5wHiy9PdiyE7j5FF3ZE9AZmb2KLUtLYuNSFPYBT3rj0vxp_7N3h_Pc-KinT8JmfxuDHVr_w68xAzazC7mIXLihf1a_-5t6UaFeXYRhfByBjJcWNUEGlFBIkGWLKlJKoreCKfrYR5A-trv2slYxMPim1XSiJr6K2mpFMP-KcuIgXmm-cZtUbs7IhnvCqfotqmcf24Qc256oN//v2// ?>
<?php //checksum:v2k_Yh-DBJaf2TEZ1Z5-9VsB2zw,// ?>