# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_extranet_profile_edit
    tabs:
        first_tab:
            label: Editing
            fields:
                enable_edit_profile:
                    plugin_setting:
                        name: enable_edit_profile
                    label: 'Allow User to edit their Profile'
                    type: checkbox
                    value: "1"
                show_title_message:
                    plugin_setting:
                        name: show_title_message
                    label: 'Display a title'
                    type: checkbox
                    value: "1"
                repeat_edit_button_at_top_of_form:
                    plugin_setting:
                        name: repeat_edit_button_at_top_of_form
                    label: 'Repeat Profile edit button at top of form'
                    type: checkbox
                user_form:
                    plugin_setting:
                        name: user_form
                    label: 'Form:'
                    pick_items:
                        path: zenario__user_forms/panels/user_forms
                        target_path: zenario__user_forms/panels/user_forms
                        min_path: zenario__user_forms/panels/user_forms
                        max_path: zenario__user_forms/panels/user_forms
                        disallow_refiners_looping_on_min_path: Yes
                        one_to_one_choose_phrase: Choose this form
                        select_phrase: Select a form...
                        hide_remove_button: Yes
                    validation:
                        required_if_not_hidden: Please select a form
                    format_onchange: true
        phrases:
            label: Phrases
            fields:
                view_profile_title:
                    plugin_setting:
                        name: view_profile_title
                    label: 'View profile title:'
                    type: text
                    value: 'Your profile'
                    show_phrase_icon: true
                edit_profile_title:
                    plugin_setting:
                        name: edit_profile_title
                    label: 'Edit profile title:'
                    type: text
                    value: 'Edit your profile'
                    show_phrase_icon: true
                profile_updated:
                    plugin_setting:
                        name: profile_updated
                    label: 'Profile updated message:'
                    type: text
                    value: 'Your profile has been updated.'
                    show_phrase_icon: true
                edit_profile_button_text:
                    plugin_setting:
                        name: edit_profile_button_text
                    label: 'Edit profile button text:'
                    type: text
                    value: 'Edit profile'
                    show_phrase_icon: true
                cancel_button_text:
                    plugin_setting:
                        name: cancel_button_text
                    label: 'Cancel button text:'
                    type: text
                    value: 'Cancel'
                    show_phrase_icon: true