# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Feed
            fields:
                feed_source:
                    label: 'Feed Source:'
                    plugin_setting:
                        name: feed_source
                    type: text
                    value: 
                cache:
                    label: 'Time in minutes to cache feed content:'
                    type: select
                    plugin_setting:
                        name: cache
                    values:
                        1:
                            label: "1"
                        2:
                            label: "2"
                        5:
                            label: "5"
                        10:
                            label: "10"
                        30:
                            label: "30"
                        60:
                            label: "60"
                    value: "10"
                rss_date_format:
                    label: 'RSS source date format:'
                    type: radios
                    plugin_setting:
                        name: rss_date_format
                    values:
                        autodetect:
                            label: Try to autodetect
                        backslashed_american:
                            label: MM/DD/YY
                        backslashed_european:
                            label: DD/MM/YY
                    value: autodetect
        display:
            label: Display
            fields:
                title:
                    label: 'Title on slot:'
                    plugin_setting:
                        name: title
                    type: radios
                    values:
                        use_feed_title:
                            ord: "1"
                            label: Use feed title
                        dont_show:
                            ord: "2"
                            label: "Don't show title"
                        use_custom_title:
                            ord: "3"
                            label: Use custom title
                    value: use_custom_title
                    format_onchange: Yes
                feed_title:
                    label: 'Custom title:'
                    indent: 1
                    type: text
                    plugin_setting:
                        name: feed_title
                    value: 
                    validation:
                        required_if_not_hidden: Please enter a custom title
                title_tags:
                    indent: 1
                    plugin_setting:
                        name: title_tags
                    label: Title tags
                    value: h1
                    type: select
                    values: &tags
                        h1:
                            label: h1
                            ord: 1
                        h2:
                            label: h2
                            ord: 2
                        h3:
                            label: h3
                            ord: 3
                        h4:
                            label: h4
                            ord: 4
                        h5:
                            label: h5
                            ord: 5
                        h6:
                            label: h6
                            ord: 6
                        h7:
                            label: h7
                            ord: 7
                        p:
                            label: p
                            ord: 8
                number_feeds_to_show:
                    label: 'Number of feeds to show:'
                    type: select
                    plugin_setting:
                        name: number_feeds_to_show
                    values:
                        1:
                            label: "1"
                        2:
                            label: "2"
                        3:
                            label: "3"
                        4:
                            label: "4"
                        5:
                            label: "5"
                        6:
                            label: "6"
                        7:
                            label: "7"
                        8:
                            label: "8"
                        9:
                            label: "9"
                        10:
                            label: "10"
                        12:
                            label: "12"
                        15:
                            label: "15"
                        20:
                            label: "20"
                        50:
                            label: "50"
                        100:
                            label: "100"
                    value: "10"
                feed_title_tags:
                    plugin_setting:
                        name: feed_title_tags
                    label: Feed title tags
                    value: h2
                    type: select
                    values: *tags
                show_date_time:
                    label: 'Show date and time:'
                    type: radios
                    plugin_setting:
                        name: show_date_time
                    values:
                        dont_show:
                            label: "Don't show"
                        date_only:
                            label: Show date only
                        date_and_time:
                            label: Show date and time
                        show_original_from_feed:
                            label: Show original from feed
                    value: dont_show
                    format_onchange: Yes
                date_format:
                    label: 'Date Format:'
                    type: radios
                    plugin_setting:
                        name: date_format
                    values:
                        _SHORT:
                            label: Short
                        _MEDIUM:
                            label: Medium
                        _LONG:
                            label: Long
                    value: _SHORT
                size:
                    label: 'Number of characters from description/summary field to be displayed:'
                    plugin_setting:
                        name: size
                    type: text
                    style: width:100px;
                    value: "100"
                news_order:
                    label: 'News order:'
                    plugin_setting:
                        name: news_order
                    type: radios
                    values:
                        desc:
                            label: Newest first
                        asc:
                            label: Oldest first
                        title_alpha:
                            label: By title A-Z
                    value: desc
        target_link:
            label: Link Target Window
            fields:
                target:
                    label: 'Open feed link:'
                    plugin_setting:
                        name: target
                    type: radios
                    values:
                        same_window:
                            label: Same window
                        new_window:
                            label: New window
                    value: same_window
        filtering:
            label: Filtering
            fields:
                regexp_field:
                    label: 'Apply regular expression filter to this feed field:'
                    plugin_setting:
                        name: regexp_field
                    type: select
                    values:
                        title:
                            label: Title
                        description:
                            label: Description
                        date:
                            label: Date
                        title_or_description:
                            label: Title or Description
                        do_no_filter:
                            label: Do not filter
                    value: do_no_filter
                    format_onchange: Yes
                regexp:
                    label: 'Use this regular expression:'
                    plugin_setting:
                        name: regexp
                    type: text
    module_class_name: zenario_feed_reader
