# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_nest
    tabs:
        accordion:
            visible_if:
                zenarioAB.animationLibIs: accordion
            label: Accordion
            fields:
                accordion_1st_open:
                    plugin_setting:
                        name: accordion_1st_open
                    label: 'When first showing the accordion, open the first slide'
                    note_below: 'The visitor will be able to open further slides with a click or tap.'
                    type: checkbox
                    value: 1
                    redraw_onchange: true
                accordion_all_can_close:
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    plugin_setting:
                        name: accordion_all_can_close
                    label: 'Allow all slides to be closed'
                    note_below: 'If not set, one slide will be kept open even if the visitor tries to close all of them.'
                    type: checkbox
                    value: 1
                accordion_open_multiple:
                    plugin_setting:
                        name: accordion_open_multiple
                    label: 'Allow multiple slides to be open at the same time'
                    note_below: 'If not set, when one slide opens, the open one will close.'
                    type: checkbox
                    value: ''
