# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Footer Settings
            fields:
                menu_section:
                    plugin_setting:
                        name: menu_section
                        foreign_key_to: menu_section
                        dangling_cross_references: delete_instance
                    label: 'Menu Section:'
                    pick_items:
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/sections
                        max_path: zenario__menu/panels/sections
                        target_path: zenario__menu/panels/sections
                        select_phrase: Select Menu Section...
                        hide_remove_button: Yes
                    value: "2"
                    validation:
                        required: Please select a menu section
                show_missing_menu_nodes:
                    plugin_setting:
                        name: show_missing_menu_nodes
                    label: 'Where menu node translation is missing, show menu node in default language'
                    type: checkbox
                    value: ""
                show_visitor_cookie_management_link:
                    plugin_setting:
                        name: show_visitor_cookie_management_link
                    label: 'Show link to visitor cookie management'
                    type: checkbox
                    value: ""
                    redraw_onchange: true
                    side_note: 'This will only appear if the <a href=\'organizer.php#zenario__administration/panels/site_settings//cookies~.site_settings~tcookies~k{"id"%3A"cookies"}\' target=\'_blank\'>cookie policy</a> is set to "Explicit consent".'
                manage_cookies_phrase:
                    indent: 1
                    plugin_setting:
                        name: manage_cookies_phrase
                    label: '"Manage cookies" phrase:'
                    type: text
                    show_phrase_icon: true
                    value: 'Manage cookies'
                    visible_if: lib.value('show_visitor_cookie_management_link')
                    validation:
                        required_if_not_hidden: 'Please enter the "Manage cookies" phrase.'
    module_class_name: zenario_footer
