# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Footer Settings
            fields:
                menu_section:
                    plugin_setting:
                        name: menu_section
                        foreign_key_to: menu_section
                        dangling_cross_references: delete_instance
                    label: 'Menu Section:'
                    pick_items:
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/sections
                        max_path: zenario__menu/panels/sections
                        target_path: zenario__menu/panels/sections
                        select_phrase: Select Menu Section...
                        hide_remove_button: Yes
                    value: "2"
                    validation:
                        required: Please select a menu section
                show_missing_menu_nodes:
                    plugin_setting:
                        name: show_missing_menu_nodes
                    label: 'Show missing Menu Nodes:'
                    type: checkbox
                    value: ""
    module_class_name: zenario_footer
