# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: users
    tabs:
        passwords:
            fields:
                temp_password_timeout:
                    grouping: zenario_extranet
                    site_setting:
                        name: temp_password_timeout
                    pre_field_html: |
                        For users created by administrators, temporary password validity period:&nbsp;
                    side_note: |
                        After this time, users will need to perform a password reset in order to log in.
                    type: select
                    value: 14
                    values:
                        2:
                            label: 2 days
                        7:
                            label: 1 week
                        14:
                            label: 2 weeks
                        28:
                            label: 4 weeks
