# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: cookies
    tabs:
        cookies:
            fields:
                cookie_consent_for_extranet:
                    site_setting:
                        name: cookie_consent_for_extranet
                    label: 'For the Extranet:'
                    type: select
                    visible_if: "zenarioAB.value('cookie_require_consent') == 'explicit'"
                    values:
                        not_required:
                            label: Follow cookie policy
                        granted:
                            label: >
                                By registering or logging in, User implicitly accepts
                                cookies
                        required:
                            label: >
                                Before seeing Extranet Plugins, User must explicitly accept
                                cookies
