# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: sign_in_access_log
    title: Sign in log Settings for extranet Users
    tabs:
        names:
            label: Enable Sign in log
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: "This tab contains settings related to Sign in log for Extranet Users'."
                user_use_screen_name:
                    site_setting:
                        name: user_use_screen_name
                    label: 'Log all sign-ins:'
                    type: checkbox
                    value: "1"
                    note_below: |
                                                    If you enable Sign in log, This will record the date, time, IP address, client browser of every time each user signs in. 
       