# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            edit_mode:
                format_on_edit: true
                format_on_cancel_edit: true
                format_on_revert: true
            label: Image/link
            fields:
                image_source:
                    plugin_setting:
                        name: image_source
                    label: 'Image source'
                    type: select
                    value: _NO_IMAGE
                    values:
                        _NO_IMAGE:
                            label: "Don't show an image"
                        _CUSTOM_IMAGE:
                            label: Show an image
                        _STICKY_IMAGE:
                            label: Auto-show image from destination content item
                    format_onchange: true
                    side_note: |
                        If you choose auto-show, then an image marked as "sticky" on the destination content item will be used.

                image:
                    indent: 1
                    plugin_setting:
                        name: image
                        foreign_key_to: file
                        use_value_for_plugin_name: "2"
                        
                    label: Image
                    pick_items:
                        path: zenario__content/panels/image_library
                        min_path: zenario__content/panels/image_library
                        max_path: zenario__content/panels/image_library
                        target_path: zenario__content/panels/image_library
                        select_phrase: Select image...
                    value: ""
                    format_onchange: true
                    upload:
                        multi: false
                        accept: 'image/*'
                        extensions:
                            - .gif
                            - .jpg
                            - .jpeg
                            - .png
                        drag_and_drop: true
                        reorder_items: false
                    validation:
                        required_if_not_hidden: Please select an image.
                canvas:
                    indent: 1
                    plugin_setting:
                        name: canvas
                    label: 'Image canvas'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: true
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                width:
                    indent: 2
                    plugin_setting:
                        name: width
                    label: 'Width'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                height:
                    indent: 2
                    plugin_setting:
                        name: height
                    label: 'Height'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                offset:
                    indent: 2
                    plugin_setting:
                        name: offset
                    label: 'Offset'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: true
                        style: 'width: 200px;'
                    side_note: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.
                retina:
                    indent: 2
                    plugin_setting:
                        name: retina
                    label: 'Output a retina image'
                    type: checkbox
                    value: ""
                    visible_if: |
                        !zenarioAB.svgSelected('image') && !zenarioAB.svgSelected('images')
                    side_note: |
                        <% if (zenarioAB.value('canvas') == 'unlimited') { %>
                            Display image at double density.
                        <% } else { %>
                            If the source image is large enough,
                            output the resized image at double density,
                            so it appears crisp on retina screens.
                            This will increase the download size.
                            If the source image is not large enough this will have no effect.
                        <% } %>
                    enable_microtemplates_in_properties: true
                use_rollover:
                    indent: 1
                    plugin_setting:
                        name: use_rollover
                    label: 'Use a rollover image'
                    type: checkbox
                    value: ""
                    format_onchange: true
                rollover_image:
                    indent: 2
                    plugin_setting:
                        name: rollover_image
                        foreign_key_to: file
                    label: 'Change image on rollover'
                    pick_items:
                        path: zenario__content/panels/image_library
                        min_path: zenario__content/panels/image_library
                        max_path: zenario__content/panels/image_library
                        target_path: zenario__content/panels/image_library
                        select_phrase: Select image...
                    value: ""
                    upload:
                        multi: false
                        accept: 'image/*'
                        extensions:
                            - .gif
                            - .jpg
                            - .jpeg
                            - .png
                        drag_and_drop: false
                        reorder_items: false
                alt_tag:
                    indent: 1
                    plugin_setting:
                        name: alt_tag
                        translate: true
                    multiple_edit:
                        original_value: ""
                    label: 'Overwrite image alt-tag'
                    type: text
                    maxlength: "255"
                    value: ""
                link_type:
                    plugin_setting:
                        name: link_type
                    label: 'Destination'
                    type: select
                    value: _NO_LINK
                    values:
                        _NO_LINK:
                            label: No link
                        _CONTENT_ITEM:
                            label: Link to a content item
                        _EXTERNAL_URL:
                            label: Link to an external URL
                        _ENLARGE_IMAGE:
                            label: Enlarge image in floating box
                            disabled_if: |
                                !zenario.IN(zenarioAB.value('image_source'), '_CUSTOM_IMAGE', '_PICTURE')
                                || zenarioAB.svgSelected('image')
                                || zenarioAB.svgSelected('images')
                    format_onchange: true
                disable_rel:
                    visible_if: "zenarioAB.value('link_type') == '_ENLARGE_IMAGE'"
                    indent: 1
                    plugin_setting:
                        name: disable_rel
                    label: 'Disable the left and right navigation arrows in the floating box'
                    type: checkbox
                    value: ""
                    format_onchange: true
                floating_box_title:
                    indent: 1
                    plugin_setting:
                        name: floating_box_title
                        translate: true
                    multiple_edit:
                        original_value: ""
                    label: 'Overwrite image floating box title'
                    type: editor
                    dont_trim: true
                    cols: "70"
                    rows: "4"
                    value: ""
                hyperlink_target:
                    indent: 1
                    plugin_setting:
                        name: hyperlink_target
                        foreign_key_to: content
                        use_value_for_plugin_name: "4"
                    label: 'Content item'
                    pick_items:
                        path: zenario__content/panels/content/refiners/filter_by_lang////
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        select_phrase: Select a content item...
                        hide_remove_button: true
                    validation:
                        required_if_not_hidden: Please select a content item
                    format_onchange: true
                use_translation:
                    indent: 1
                    plugin_setting:
                        name: use_translation
                    label: "Link to content item in this page's language, if it exists"
                    type: checkbox
                    value: ""
                    side_note: |
                        If the destination content item has a translation in the visitor's language, link to that.
                        (Recommended for banners placed on the layout)
                hide_private_item:
                    indent: 1
                    plugin_setting:
                        name: hide_private_item
                    label: 'Privacy'
                    type: select
                    value: __ALWAYS_SHOW
                    values:
                        _ALWAYS_SHOW:
                            ord: true
                            label: Always show, even if the target item is private
                        _PRIVATE:
                            ord: "2"
                            label: Only show to visitors who can see the target Item
                        _LOGGED_OUT:
                            ord: "3"
                            label: Only show to visitors who are logged out
                        _LOGGED_IN:
                            ord: "4"
                            label: Always show to visitors who are logged in
                use_download_page:
                    indent: 1
                    plugin_setting:
                        name: use_download_page
                    label: 'Use a download page'
                    type: checkbox
                    value: ""
                    side_note: |
                        Link to the file's download page, rather than a direct link to the file.
                        Note that this option only applies to document content items.
                    hidden: true
                url:
                    indent: 1
                    plugin_setting:
                        name: url
                    label: 'External URL'
                    type: url
                    maxlength: "255"
                    value: ""
                target_blank:
                    indent: 1
                    plugin_setting:
                        name: target_blank
                    label: 'Open in a new window'
                    type: checkbox
                    value: ""
                enlarge_canvas:
                    indent: 1
                    plugin_setting:
                        name: enlarge_canvas
                    label: 'Enlarged image canvas'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: true
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                    format_onchange: true
                enlarge_width:
                    indent: 2
                    plugin_setting:
                        name: enlarge_width
                    label: 'Width'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter an enlarged width.
                        numeric: The enlarged width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                enlarge_height:
                    indent: 2
                    plugin_setting:
                        name: enlarge_height
                    label: 'Height'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter an enlarged height.
                        numeric: The enlarged height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
        text:
            label: 'Title & HTML'
            fields:
                translate_text:
                     plugin_setting:
                         name: translate_text
                     label: 'Make this plugin multilingual using the phrases system'
                     type: checkbox
                     value: 1
                     format_onchange: true
                title:
                    plugin_setting:
                        name: title
                        is_searchable_content: true
                        use_value_for_plugin_name: true
                        translate: true
                    label: 'Title'
                    type: text
                    width: "150"
                    maxlength: "255"
                    value: ""
                
                title_tags:
                    plugin_setting:
                        name: title_tags
                    label: 'Title heading tags'
                    type: select
                    values:
                        h1: Heading 1
                        h2: Heading 2
                        h3: Heading 3
                        h4: Heading 4
                        h5: Heading 5
                        h6: Heading 6
                        p: Paragraph
                    value: h2
                    side_note: |
                        Choose which HTML tags the title will be displayed in.
                
                text:
                    plugin_setting:
                        name: text
                        is_searchable_content: true
                        translate: true
                    label: 'HTML'
                    type: editor
                    dont_trim: true
                    insert_link_button:
                        exists: true
                    cols: "80"
                    rows: "10"
                    value: ""
                more_link_text:
                    plugin_setting:
                        name: more_link_text
                        is_searchable_content: true
                        translate: true
                    label: |
                        Text for "More info" link
                    type: text
                    width: "150"
                    maxlength: "255"
                    value: ""
    module_class_name: zenario_banner
