(function(l){function t(b,g){b=typeof b;return g?b==g:"undefined"!=b}function n(b,g,a){var e;if(!b)return 0;a=a?a:b;if(t(b.length))for(e=0;e<b.length;e++){if(!1===g.call(a,b[e],e,b))return 0}else for(e in b)if(b.hasOwnProperty(e)&&!1===g.call(a,b[e],e,b))return 0;return 1}function q(b,g){n(g,function(a,e){b[e]=a});return b}var y,A,B,k,C,m,h,p,w,z,v,D,x;x=navigator.userAgent;l.isOpera=z=window.opera&&opera.buildNumber;l.isWebKit=v=/WebKit/.test(x);l.isOldWebKit=D=v&&!window.getSelection().getRangeAt;
l.isIE=p=!v&&!z&&/MSIE/gi.test(x)&&/Explorer/gi.test(navigator.appName);l.isGecko=w=!v&&/Gecko/.test(x);l.plugins={};q(l,{is:t,each:n,extend:q});l.I18n=m={bold:"Bold (Ctrl+B)",italic:"Italic (Ctrl+I)",underline:"Underline (Ctrl+U)",strike:"Striketrough",ul:"Insert unordered list",ol:"Insert ordered list",indent:"Indent",outdent:"Outdent",left:"Align left",center:"Align center",right:"Align right",style:"Font style",removeformat:"Remove format",increasefontsize:"Increase text size",decreasefontsize:"Decrease text size"};
l.DOMUtils=y=function(b){this.files=[];try{b.execCommand("BackgroundImageCache",0,1)}catch(g){}q(this,{get:function(a){return a&&(a.nodeType||a.location?a:b.getElementById(a))},add:function(a,e,f,c){var g=this,d;d=b.createElement(e);n(f,function(a,c){g.setAttr(d,c,a)});c&&(c.nodeType?d.appendChild(c):d.innerHTML=c);return a?a.appendChild(d):d},create:function(a,e,b){return this.add(0,a,e,b)},setAttr:function(a,e,b){a=this.get(a);if(!a)return 0;"style"==e&&(a.setAttribute("mce_style",b),a.style.cssText=
b);"class"==e&&(a.className=b);null!=b&&""!=b?a.setAttribute(e,""+b):a.removeAttribute(e);return 1},getAttr:function(a,e,b){var c;a=this.get(a);if(!a)return!1;t(b)||(b="");if(/^(src|href|style)$/.test(e)&&(c=this.getAttr(a,"mce_"+e)))return c;c=a.getAttribute(e,2);"class"!=e||c||(c=a.className);"style"!=e||c?c||(c=(c=a.attributes[e])&&t(c.nodeValue)?c.nodeValue:c):c=a.style.cssText;v&&"class"==e&&c&&(c=c.replace(/(apple|webkit)\-[a-z\-]+/gi,""));return c&&""!=c?""+c:b},select:function(a,e,f){var c=
[];e=(e=this.get(e))?e:b;n(a.split(","),function(a){n(e.getElementsByTagName(a),function(a){f&&!f(a)||c.push(a)})});return c},getPos:function(a,e){var b=0,c=0;a=this.get(a);if(l.isIE&&a)return b=a.getBoundingClientRect(),c=document,a="CSS1Compat"==c.compatMode?c.documentElement:c.body,{x:b.left+(a.scrollLeft||0),y:b.top+(a.scrollTop||0)};for(;a&&a!=e;)b+=a.offsetLeft||0,c+=a.offsetTop||0,a=a.offsetParent;return{x:b,y:c}},loadCSS:function(a){var e=this;a&&n(a.split(","),function(a){var c=-1;n(e.files,
function(b,d){if(b==a)return c=d,!1});-1==c&&(e.files.push(a),b.createStyleSheet?b.createStyleSheet(a):e.add(e.select("head")[0],"link",{rel:"stylesheet",href:a}))})},addClass:function(a,b,f){var c;a=this.get(a);if(!a)return 0;c=this.removeClass(a,b);return a.className=f?b+(""!=c?" "+c:""):(""!=c?c+" ":"")+b},removeClass:function(a,b){a=this.get(a);if(!a)return 0;b=a.className.replace(RegExp("(^|\\s+)"+b+"(\\s+|$)","g")," ");return a.className=" "!=b?b:""},hasClass:function(a,b){a=this.get(a);return RegExp("\\b"+
b+"\\b","g").test(a.className)},getParent:function(a,b,f){for(;a&&a!=f;){if(b(a))return a;a=a.parentNode}return null},keep:function(a){w&&(a=a.replace(/<(\/?)strong>|<strong( [^>]+)>/gi,"<$1b$2>"),a=a.replace(/<(\/?)em>|<em( [^>]+)>/gi,"<$1i$2>"),a=a.replace(/<(\/?)del|<del( [^>]+)>/gi,"<$1strike$2>"));return a=a.replace(/ (src|href|style)=\"([^\"]+)\"/gi,' $1="$2" mce_$1="$2"')}})};l.DOM=h=new y(document);l.Event=k={events:[],inits:[],unloads:[],add:function(b,g,a,e){var f,c=this.events;b=h.get(b);
f=function(c){(c=c||window.event)&&!c.target&&p&&(c.target=c.srcElement);return e?a.call(e,c):a(c)};if("unload"==g)return this.unloads.push(f),f;if("init"==g)return this._init?f():this.inits.push(f),f;c.push({obj:b,name:g,func:a,cfunc:f,scope:e});this._add(b,g,f);p&&1==c.length&&k._add(window,"unload",this._unload,k);return f},remove:function(b,g,a){var e=this,f=e.events;b=h.get(b);n(f,function(c,h){if(c.obj==b&&c.name==g&&(!a||c.func==a))return f.splice(h,1),e._remove(b,g,c.cfunc),!1})},cancel:function(b){this.stop(b);
return this.prevent(b)},stop:function(b){b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;return!1},prevent:function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;return!1},_unload:function(){var b=k;n(b.events,function(g){b._remove(g.obj,g.name,g.cfunc)});b._remove(window,"unload",b._unload);b.events=[];n(b.unloads,function(b){b()})},_add:function(b,g,a){b.attachEvent?b.attachEvent("on"+g,a):b.addEventListener?b.addEventListener(g,a,!1):b["on"+g]=a},_remove:function(b,g,a){b.detachEvent?
b.detachEvent("on"+g,a):b.removeEventListener?b.removeEventListener(g,a,!1):b["on"+g]=null},_pageInit:function(){var b=k;b._remove(window,"DOMContentLoaded",b._pageInit);b._init=!0;n(b.inits,function(b){b()});b.inits=[]},_wait:function(){var b;if(!p||"https:"==document.location.protocol)if(k._add(window,"DOMContentLoaded",k._pageInit,k),p||v)b=setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(b),k._pageInit())},10)}};l.Dispatcher=B=function(b){var g=[];b||(b=this);
q(this,{add:function(a,e){g.push({cb:a,scope:e?e:b});return a},remove:function(a){n(g,function(b,f){a==b.cb&&g.splice(f,1);return!1});return a},dispatch:function(){var a,b=arguments;n(g,function(f){return a=f.cb.apply(f.scope,b)});return a}})};l.Editor=function(b){function g(b){var u,f,g,s;u=h.get(c.id+"_c");g=u.clientWidth-2;s=u.clientHeight-2;f=h.get(c.id+"_p");f.style.width=g+"px";f.style.height=s+"px";u.style.display="none";f.style.display="block";d.resize={x:b.screenX,y:b.screenY,w:g,h:s};k.add(document,
"mousemove",a,this);k.add(document,"mouseup",e,this);d.onResizeStart.dispatch(d,b,g,s)}function a(a){var b=d.resize,e,f;b.dx=a.screenX-b.x;b.dy=a.screenY-b.y;e=Math.max(c.min_width,b.w+b.dx);f=Math.max(c.min_height,b.h+b.dy);e=Math.min(c.max_width,e);f=Math.min(c.max_height,f);b=h.get(c.id+"_p");b.style.width=e+"px";b.style.height=f+"px";return k.cancel(a)}function e(b){var u=d.resize;k.remove(document,"mousemove",a,this);k.remove(document,"mouseup",e,this);h.get(c.id+"_c").style.display="";h.get(c.id+
"_p").style.display="none";d.resizeBy(u.dx,u.dy);d.onResizeEnd.dispatch(d,b,u.dx,u.dy)}function f(){var a=h.get(c.id),b=d.getDoc();w&&(d.getDoc().designMode="On");b.open();b.write('<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body id="punymce"></body></html>');b.close();d.dom=s=new y(d.getDoc());s.loadCSS(c.content_css);d.onPreInit.dispatch(d);c.spellcheck||(d.getBody().spellcheck=0);k.add(d.getDoc(),"mouseup",d.nodeChanged,d);k.add(d.getDoc(),"keyup",d.nodeChanged,
d);k.add(w?d.getDoc():d.getWin(),"focus",function(a){var b;null!=(b=l.focusEditor)&&b.onBlur.dispatch(b,d);d.onFocus.dispatch(d,b);l.focusEditor=d},this);p?d.getBody().contentEditable=!0:d.getDoc().designMode="On";d.setContent(t(a.value)?a.value:a.innerHTML,{load:!0});h.get(c.id+"_c").style.display=d.orgDisplay;h.get(c.id).style.display="none";d.onInit.dispatch(d)}var c,s,d=this;l.baseURL||n(h.select("script"),function(a){/puny_mce/g.test(""+a.src)&&(l.baseURL=a.src.replace(/^(.+)\/puny_mce.+$/,"$1/"))});
this.settings=c=q({content_css:l.baseURL+"css/content.css",editor_css:l.baseURL+"css/editor.css",blank_file:l.baseURL+"blank.html",width:0,height:0,min_width:260,min_height:50,max_width:800,max_height:600,entities:"raw",spellcheck:0,resize:!0,plugins:"",styles:[{title:"H1",cls:"h1",cmd:"FormatBlock",val:"<h1>"},{title:"H2",cls:"h2",cmd:"FormatBlock",val:"<h2>"},{title:"H3",cls:"h3",cmd:"FormatBlock",val:"<h3>"},{title:"Pre",cls:"pre",cmd:"FormatBlock",val:"<pre>"},{title:"Times",cls:"times",cmd:"FontName",
val:"Times"},{title:"Arial",cls:"arial",cmd:"FontName",val:"Arial"},{title:"Courier",cls:"courier",cmd:"FontName",val:"Courier"}],toolbar:"bold,italic,underline,strike,increasefontsize,decreasefontsize,ul,ol,indent,outdent,left,center,right,style,removeformat"},b);d.tools={bold:{cmd:"Bold",title:m.bold},italic:{cmd:"Italic",title:m.italic},underline:{cmd:"Underline",title:m.underline},strike:{cmd:"Strikethrough",title:m.strike},ul:{cmd:"InsertUnorderedList",title:m.ul},ol:{cmd:"InsertOrderedList",
title:m.ol},indent:{cmd:"Indent",title:m.indent},outdent:{cmd:"Outdent",title:m.outdent},left:{cmd:"JustifyLeft",title:m.left},center:{cmd:"JustifyCenter",title:m.center},right:{cmd:"JustifyRight",title:m.right},style:{cmd:"mceStyle",title:m.style},removeformat:{cmd:"RemoveFormat",title:m.removeformat},increasefontsize:{cmd:"IncreaseFontSize",title:m.increasefontsize},decreasefontsize:{cmd:"DecreaseFontSize",title:m.decreasefontsize}};h.loadCSS(c.editor_css);this.commands={mceStyle:function(a,b,c){function d(a){f.hideMenu=
null;k.remove(document,"click",d);k.remove(f.getDoc(),"click",d);h.get(g+"_mstyle").style.display="none"}var e,f=this;a=f.settings;var g=a.id;b=h.getPos(c.target);if(f.hideMenu)return f.hideMenu();e=h.get(g+"_mstyle");e||(e=h.get(g+"_t"),e=h.add(document.body,"div",{id:g+"_mstyle","class":"punymce_style punymce"}),n(a.styles,function(a){k.add(h.add(e,"a",{href:"#","class":a.cls},a.title),"mousedown",function(b){d.call(f);f.execCommand(a.cmd,a.ui,a.val);z&&f.getIfr().focus();return k.cancel(b)})}));
f.hideMenu=d;k.add(document,"click",d,f);k.add(f.getDoc(),"click",d,f);a=e.style;a.left=b.x+"px";a.top=b.y+c.target.clientHeight+2+"px";a.display="block"},FormatBlock:function(a,b,c){w&&/<(div|blockquote|code|dt|dd|dl|samp)>/gi.test(b)&&(b=b.replace(/[^a-z]/gi,""));d.getDoc().execCommand("FormatBlock",0,b)},CreateLink:function(a,b){var c=d.dom;d.getDoc().execCommand("CreateLink",0,"javascript:mox();");n(c.select("A"),function(a){"javascript:mox();"==c.getAttr(a,"href")&&(c.setAttr(a,"href",b),c.setAttr(a,
"mce_href",b))})},mceFontSizeDelta:function(a,b){var c=d.getDoc(),e;e=parseInt(c.queryCommandValue("FontSize")||3);v&&n([10,13,16,18,24,32,48],function(a,b){if(e==a)return e=b+1,!1});1>=e+b||c.execCommand("FontSize",!1,e+b)},IncreaseFontSize:function(){d.execCommand("mceFontSizeDelta",0,1)},DecreaseFontSize:function(){d.execCommand("mceFontSizeDelta",0,-1)},Indent:function(a,b,c){d.getDoc().execCommand("Indent",0,0);p&&d.dom.getParent(d.selection.getNode(),function(a){"BLOCKQUOTE"==a.nodeName&&(a.dir=
a.style.marginRight="")})},mceSetClass:function(a,b,c){a=d.selection;t(b,"string")&&(b={element:"span","class":b});a.isCollapsed()?d.dom.setAttr(a.getNode(),"class",b["class"]):a.setContent("<"+b.element+' class="'+b["class"]+'">'+a.getContent()+"</"+b.element+">")},RemoveFormat:function(a,b,c){c=d.selection;d.getDoc().execCommand("RemoveFormat",a,b);p&&(b=c.getContent(),b=b.replace(/ (class|style)=\"[^\"]+\"/g,""),b=b.replace(/<\/?(font|strong|em|b|i|u|strike)>/g,""),b=b.replace(/<(font|strong|em|b|i|u|strike) [^>]+>/g,
""),c.setContent(b))}};q(this,{serializer:new C(d),selection:new A(d),plugins:[]});n("onPreInit onInit onFocus onBlur onResizeStart onResizeEnd onPreProcess onPostProcess onSetContent onBeforeGetContent onGetContent onNodeChange".split(" "),function(a){d[a]=new B(d)});q(this,{init:function(){var a=h.get(c.id),b=a.parentNode,e,s,r,m,p,q,t="bold italic underline left center right".split(" ");n(c.plugins.split(","),function(a){a&&d.plugins.push(new l.plugins[a](d))});d.onNodeChange.add(function(){n(t,
function(a){var b;try{b=d.getDoc().queryCommandState(d.tools[a].cmd)?h.addClass:h.removeClass,b.call(h,c.id+"_"+a,"active")}catch(e){}})});"numeric"==c.entities&&d.onGetContent.add(function(a,b){"html"==b.format&&(b.content=b.content.replace(/[\u007E-\uFFFF]/g,function(a){return"&#"+a.charCodeAt(0)+";"}))});e=c.width?c.width:a.offsetWidth;s=c.height?c.height:a.offsetHeight;d.orgDisplay=a.style.display;a.style.display="none";a.form&&(r=a.form,d._submit=r.submit,r.submit=function(){var a=h.get(c.id).form;
d.save();a.submit=d._submit;a.submit()},k.add(0,"unload",function(){h.get(c.id);d._submit=d.submit=null}),k.add(r,"submit",d.save,d));r='<div id="'+c.id+'_w" class="punymce"><table id="'+c.id+'_c" class="punymce"><tr class="mceToolbar">';r+='<td id="'+c.id+'_t"></td></tr><tr class="mceBody"><td></div><div id="'+c.id+'_b" class="mceBody">';c.resize&&(r+='<div id="'+c.id+'_r" class="mceResize"></div>');r=r+"</td></tr></table>"+('<div id="'+c.id+'_p" class="mcePlaceholder"></div></div>');a.insertAdjacentHTML?
a.insertAdjacentHTML("beforeBegin",r):(q=a.ownerDocument.createRange(),q.setStartBefore(a),b.insertBefore(q.createContextualFragment(r),a));p=h.get(c.id+"_t");m=h.add(p,"ul",{id:c.id+"_tb","class":"punymce"});n(c.toolbar.split(","),function(a){var b=d.tools[a];p=h.add(h.add(m,"li",{id:c.id+"_"+a,"class":a}),"a",{href:"javascript:void(0);","class":a,title:b.title,tabIndex:-1,onmousedown:"return false;"});k.add(p,"click",function(a){h.hasClass(a.target.parentNode,"disabled")||d.execCommand(b.cmd,0,
0,a);return k.cancel(a)})});p=h.get(c.id+"_b");p=h.add(p,"iframe",{id:c.id+"_f",src:'javascript:""',frameBorder:"0","class":"punymce",style:"width:"+e+"px;height:"+s+"px"});d.resizeTo(e,s);v?(k.add(p,"load",f,d),p.src=c.blank_file):f();c.resize&&k.add(c.id+"_r","mousedown",function(a){return g(a,c.id)},this);m=r=a=p=null;"[[HIDE_ME]]"==d.getContent()&&d.setContent("")},getSize:function(){var a=h.get(c.id+"_f");return{w:a.clientWidth,h:a.clientHeight}},resizeTo:function(a,b){var e=h.get(c.id+"_f").style;
a=Math.max(c.min_width,a);b=Math.max(c.min_height,b);a=Math.min(c.max_width,a);b=Math.min(c.max_height,b);d.width=a;d.height=b;e.width=a+"px";e.height=b+"px"},resizeBy:function(a,b){var c=d.getSize();d.resizeTo(c.w+a,c.h+b)},show:function(){h.get(c.id+"_w").style.display="block";h.get(c.id).style.display="none";d.load()},hide:function(){p&&d.execCommand("SelectAll");h.get(c.id+"_w").style.display="none";h.get(c.id).style.display=d.orgDisplay;d.save()},load:function(){var a=h.get(c.id);d.setContent(t(a.value)?
a.value:a.innerHTML,{load:!0})},save:function(){var a=h.get(c.id),b=d.getContent({save:!0}),b=b.replace(/<(\/?)html(\/?)>/gi,"");/TEXTAREA|INPUT/.test(a.nodeName)?a.value=b:a.innerHTML=b},setUseCSS:function(a){a=d.getDoc();try{a.execCommand("styleWithCSS",0,!1)}catch(b){try{a.execCommand("useCSS",0,!0)}catch(c){}}},execCommand:function(a,b,c,e){var f=d.commands;d.getWin().focus();d.setUseCSS(0);!1!==(f[a]?f[a].call(d,b,c,e):d.getDoc().execCommand(a,b,c))&&d.nodeChanged()},getContent:function(a){var b;
a=a||{};a.format=a.format||"html";d.onBeforeGetContent.dispatch(this,a);b=d.serializer.serialize(d.getBody(),a);b=b.replace(/^\s*|\s*$/g,"");a.content=b;d.onGetContent.dispatch(this,a);return a.content},setContent:function(a,b){b=b||{};b.content=a;d.onSetContent.dispatch(this,b);a=b.content;a=h.keep(a);d.getBody().innerHTML=a;"raw"!=b.format?d.setContent(a=d.getContent(b),{format:"raw"}):d.getBody().innerHTML=a;return a},getIfr:function(){return h.get(c.id+"_f")},getWin:function(){return d.getIfr().contentWindow},
getDoc:function(){return d.getWin().document},getBody:function(){return d.getDoc().body},nodeChanged:function(){d.setUseCSS(0);d.onNodeChange.dispatch(d,d.selection.getNode())}});k.add(window,"init",d.init,this)};l.Selection=A=function(b){var g=this;q(g,{getContent:function(a){var e,f=g.getRng(),c=document.createElement("body");a=a||{};if(g.isCollapsed())return"";f.cloneContents?c.appendChild(f.cloneContents()):t(f.item)||t(f.htmlText)?c.innerHTML=f.item?f.item(0).outerHTML:f.htmlText:c.innerHTML=
f.toString();"raw"!=a.format?(a.content=e,b.serializer.serialize(c,a),a.content=a.content.replace(/^\s*|\s*$/g,""),b.onGetContent.dispatch(e,a),e=a.content):e=c.innerHTML;return e},getText:function(){var a=g.getRng(),b=g.getSel();return D?b:g.isCollapsed()?"":a.text||b.toString()},setContent:function(a,e){var f=g.getRng(),c,s;e=e||{format:"raw"};a=h.keep(a);"raw"!=e.format&&(e.content=a,b.onSetContent.dispatch(this,e),a=e.content,c=b.dom.create("body"),c.innerHTML=a);f.insertNode?(f.deleteContents(),
f.insertNode(f.createContextualFragment(a+'<span id="__caret">_</span>')),c=b.dom.get("__caret"),f=b.getDoc().createRange(),f.setStartBefore(c),f.setEndBefore(c),s=g.getSel(),s.removeAllRanges(),s.addRange(f),c.parentNode.removeChild(c)):f.pasteHTML?f.pasteHTML(a):f.item(0).outerHTML=a},select:function(a,b){var f=g.getRng(),c=g.getSel();if(f.moveToElementText)try{f.moveToElementText(a),f.select()}catch(h){}else c.addRange?(b?f.selectNodeContents(a):f.selectNode(a),c.removeAllRanges(),c.addRange(f)):
c.setBaseAndExtent(a,0,a,1);return a},isCollapsed:function(){var a=g.getRng();return a.item?!1:0==a.boundingWidth||g.getSel().isCollapsed},collapse:function(a){var b=g.getRng(),f=g.getSel();b.select?(b.collapse(a),b.select()):a?f.collapseToStart():f.collapseToEnd()},getSel:function(){var a=b.getWin();return a.getSelection?a.getSelection():b.getDoc().selection},getRng:function(){var a=g.getSel(),e=b.getDoc();if(!a)return null;try{return 0<a.rangeCount?a.getRangeAt(0):a.createRange?a.createRange():
null}catch(f){return e.body.createTextRange()}},setRng:function(a){var b=g.getSel();b.removeAllRanges();b.addRange(a)},setNode:function(a){g.setContent(b.dom.create("div",null,a).innerHTML)},getNode:function(){var a=g.getRng();g.getSel();var b;return p?a.item?a.item(0):a.parentElement():(a&&(b=a.commonAncestorContainer,a.collapsed||a.startContainer==a.endContainer&&2>a.startOffset-a.endOffset&&a.startContainer.hasChildNodes()&&(b=a.startContainer.childNodes[a.startOffset])),h.getParent(b,function(a){return 1==
a.nodeType}))}})};l.Serializer=C=function(b){function g(a){var b=[];a.cloneNode(!1).outerHTML.replace(/([a-z0-9\-_]+)=/gi,function(a,c){b.push({specified:1,nodeName:c})});return b}function a(b,d){var k,l,n,m,r,q;if(c.valid_nodes&&!c.valid_nodes.test(b.nodeName)||c.invalid_nodes&&c.invalid_nodes.test(b.nodeName)||c.node_filter&&!c.node_filter(b,d))1==b.nodeType&&(k=b.hasChildNodes());else switch(b.nodeType){case 1:if(p){if(b.mce_serialized==f)return;b.mce_serialized=f}k=b.hasChildNodes();l=e.createElement(b.nodeName.toLowerCase());
r=p?g(b):b.attributes;for(n=r.length-1;-1<n;n--)if(m=r[n],m.specified&&(m=m.nodeName.toLowerCase(),!c.invalid_attrs||!c.invalid_attrs.test(m)))if(!c.valid_attrs||c.valid_attrs.test(m))q=h.getAttr(b,m),""!==q&&l.setAttribute(m,q);k||c.closed.test(b.nodeName)||l.appendChild(e.createTextNode(""));d=d.appendChild(l);break;case 3:return d.appendChild(e.createTextNode(b.nodeValue));case 8:return d.appendChild(e.createComment(b.nodeValue))}if(k)for(k=b.firstChild;k;)a(k,d),k=k.nextSibling}var e,f=0,c;e=
function(){var a=document.implementation;if(a&&a.createDocument)return a.createDocument("","",null);try{return new ActiveXObject("MSXML2.DOMDocument")}catch(b){}try{return new ActiveXObject("Microsoft.XmlDom")}catch(c){}}();this.settings=c=q({valid_nodes:0,invalid_nodes:/(BODY)/,valid_attrs:0,node_filter:0,root_node:0,pi:0,invalid_attrs:/(^mce_|^_moz_|^contenteditable$)/,closed:/(BR|HR|INPUT|META|IMG)/},b.settings.serializer);q(this,{serialize:function(g,d){var h;f=""+(parseInt(f)+1);e.firstChild&&
e.removeChild(e.firstChild);g=d.node=g.cloneNode(1);b.onPreProcess.dispatch(this,d);a(g,e.appendChild(e.createElement("html")));h=e.xml||(new XMLSerializer).serializeToString(e);c.pi||(h=h.replace(/<\?[^?]+\?>/g,""));c.root_node||(h=h.replace(/<html>|<\/html>/g,""));d.content=h;b.onPostProcess.dispatch(this,d);return d.content}})};k._wait();window.punymce=l})({});
