display_name: Error log
description: |
    <p>
        This module logs all 404 errors that take users to the site's custom 404 page. So for example a URL of the format "www.example.com/not-a-real-page" will log an error, but a URL of the format "www.example.com/not-a-real-page.php" will not, which will be recorded in the apache error log.
    </p><p>
        There's an organizer panel which lists these errors along with the date/time they were received, the referrer URL in full, the requested page Alias and the link to which the request is connected via a spare alias (if set). 
    </p><p>
        A spare alias can be created for requested aliases in this panel from an item button. The log can be cleared.
    </p>
category: management
editions: ProBusiness, Enterprise
required_cms_version: 7.0.3
author_name: Tribal Systems
copyright_info: © Tribal Limited
license_info: 'Modified BSD License'
keywords: 404, error, log, access
start_running_on_install: true

jobs:
    job:
        name: jobReportErrors
        static: true
        months: jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
        days: mon,tue,wed,thr,fri,sat,sun
        hours: 0h
        minutes: 0m
        log_on_action: true
        log_on_no_action: false
        email_on_action: true
        email_on_no_action: false