# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: zenario_location_manager__site_settings_group
    title: Editing settings for Locations
    tabs:
        zenario_location_manager__site_settings:
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            label: Details
            fields:
                zenario_location_manager__enable_external_id:
                    label: 'Enable external number'
                    site_setting:
                        name: zenario_location_manager__enable_external_id
                    type: checkbox
                zenario_location_manager__enable_pending_status:
                    label: 'Enable pending status'
                    site_setting:
                        name: zenario_location_manager__enable_pending_status
                    type: checkbox
                    side_note: |
                        When the pending status is enabled, any new locations will be created as pending first instead of active.
                        You can also manually change a locations status to and from pending in the locations organizer panel.
                zenario_location_manager__hierarchy_levels:
                    label: 'Number of levels allowed in a location hierarchy:'
                    site_setting:
                        name: zenario_location_manager__hierarchy_levels
                    type: select
                    values:
                        0:
                            label: No hierarchy
                            ord: "0"
                        2:
                            label: "2"
                            ord: "2"
                        3:
                            label: "3"
                            ord: "3"
                        4:
                            label: "4"
                            ord: "4"
                        5:
                            label: "5"
                            ord: "5"
                        6:
                            label: "6"
                            ord: "6"
                        7:
                            label: "7"
                            ord: "7"
                        8:
                            label: "8"
                            ord: "8"
                        9:
                            label: "9"
                            ord: "9"
                        10:
                            label: "10"
                            ord: "10"
                        999:
                            label: Unlimited
                            ord: "999"
                    validation:
                        numeric: Number of levels in the Location hierarchy must be a number.
                zenario_location_manager__sector_management:
                    label: 'Sector Management:'
                    type: radios
                    site_setting:
                        name: zenario_location_manager__sector_management
                    values:
                        1: Do not use Sectors
                        0: Quick Sector Management
                        2: Sector Score Management
                    side_note: |
                        <p>Quick Sector Management adds a Sectors tab to the Locations admin box on which you can add/remove Sectors from a Location via a hierarchical list of checkboxes.</p>
                                                    <p>Sector Score Management adds a button to a Location's selected toolbar that enables access to a panel where you can add/remove Sectors from the Location and administer the Sector Score.</p>
                
                zenario_location_manager__default_pin_placement_method:
                    label: 'Default pin placement method:'
                    type: radios
                    site_setting:
                        name: zenario_location_manager__default_pin_placement_method
                    values: {}
                
        filesizes:
            label: File Sizes
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: This tab contains settings for file uploads.
                max_location_image_filesize:
                    site_setting:
                        name: max_location_image_filesize
                    label: 'Maximum location image file size:'
                    type: text
                    value: 50000
                    side_note: >
                        Maximum allowed file size for location images uploaded by
                        Extranet Users, in bytes.
                    validation:
                        required: Please enter a maximum location image file size.
                        numeric: The maximum user image file size must be numeric.
