# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        locations:
            label: Locations
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                
                perm.view.location:
                    site_setting:
                        name: perm.view.location
                    type: radios
                    value: specific
                    values:
                        logged_out:
                            label: "Anonymous visitors can view ANY location's details"
                        logged_in:
                            label: "Extranet users can view ANY location's details"
                        specific:
                            label: "Extranet users can view a location's details if..."
                    redraw_onchange: true
                perm.view.location.by.group:
                    site_setting:
                        name: perm.view.location.by.group
                    indent: 1
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.view.location.groups:
                    site_setting:
                        name: perm.view.location.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can view a location's details.
                perm.view.location.atCountry:
                    site_setting:
                        name: perm.view.location.atCountry
                    indent: 1
                    row_class: zfab_or
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: "They are a member of the group(s) AND are linked to the location's country:"
                    redraw_onchange: true
                perm.view.location.atCountry.groups:
                    site_setting:
                        name: perm.view.location.atCountry.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can view a location's details.
                perm.view.location.atLocation:
                    site_setting:
                        name: perm.view.location.atLocation
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.view.location.atLocation.role:
                    site_setting:
                        name: perm.view.location.atLocation.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at the location'
                perm.view.location.atLocationAtCompany:
                    site_setting:
                        name: perm.view.location.atLocationAtCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The location is in a company at which the current user has
                perm.view.location.atLocationAtCompany.role:
                    site_setting:
                        name: perm.view.location.atLocationAtCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in that company'
                
                perm.view.location.enforce:
                    indent: 1
                    hide_if_previous_outdented_value_isnt:
                        - logged_in
                        - specific
                    snippet: {}
                    note_below: |
                        If the locationId variable is in the URL, the system will check if the visitor can see that location.
                
                perm.create-location.unassigned:
                    snippet:
                        label: "Create/unassigned: users can create an unassigned location if..."
                perm.create-location.unassigned.by.group:
                    site_setting:
                        name: perm.create-location.unassigned.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-location.unassigned.groups:
                    site_setting:
                        name: perm.create-location.unassigned.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create a location.
                
                perm.create-location.company:
                    snippet:
                        label: "Create/company: users can create a location assigned to a company if..."
                perm.create-location.company.by.group:
                    site_setting:
                        name: perm.create-location.company.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-location.company.groups:
                    site_setting:
                        name: perm.create-location.company.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a company.
                perm.create-location.company.atCompany:
                    site_setting:
                        name: perm.create-location.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.create-location.company.atCompany.role:
                    site_setting:
                        name: perm.create-location.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.edit.location:
                    snippet:
                        label: "Edit: users can edit a location's details if..."
                perm.edit.location.by.group:
                    site_setting:
                        name: perm.edit.location.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.edit.location.groups:
                    site_setting:
                        name: perm.edit.location.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a location.
                perm.edit.location.atCountry:
                    site_setting:
                        name: perm.edit.location.atCountry
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: "They are a member of the group(s) AND are linked to the location's country:"
                    redraw_onchange: true
                perm.edit.location.atCountry.groups:
                    site_setting:
                        name: perm.edit.location.atCountry.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a location.
                perm.edit.location.atLocation:
                    site_setting:
                        name: perm.edit.location.atLocation
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.edit.location.atLocation.role:
                    site_setting:
                        name: perm.edit.location.atLocation.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at the location'
                
                perm.delete.location:
                    snippet:
                        label: "Delete: users can delete a location if..."
                perm.delete.location.by.group:
                    site_setting:
                        name: perm.delete.location.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.delete.location.groups:
                    site_setting:
                        name: perm.delete.location.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a location.
                perm.delete.location.atCountry:
                    site_setting:
                        name: perm.delete.location.atCountry
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: "They are a member of the group(s) AND are linked to the location's country:"
                    redraw_onchange: true
                perm.delete.location.atCountry.groups:
                    site_setting:
                        name: perm.delete.location.atCountry.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a location.
                perm.delete.location.atLocation:
                    site_setting:
                        name: perm.delete.location.atLocation
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.delete.location.atLocation.role:
                    site_setting:
                        name: perm.delete.location.atLocation.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at the location'

