<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'WideImage' => array($vendorDir . '/smottt/wideimage/lib'),
    'NumbersPHP\\Tests' => array($vendorDir . '/powder96/numbers.php/test'),
    'NumbersPHP' => array($vendorDir . '/powder96/numbers.php/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
