# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_ctype_event
    tabs:
        first_tab:
            label: Event
            fields:
                show_title:
                    plugin_setting:
                        name: show_title
                    label: "Show title"
                    type: checkbox
                    value: true
                    redraw_onchange: true
                title_tags:
                    same_row: true
                    hide_with_previous_field: true
                    visible_if: zenarioAB.value('show_title')
                    plugin_setting:
                        name: title_tags
                    type: select
                    values:
                        h1: <h1>
                        h2: <h2>
                        h3: <h3>
                        h4: <h4>
                        h5: <h5>
                        h6: <h6>
                        p: <p>
                    value: h1
                    indent: 1
                pinned_events_icon:
                    plugin_setting:
                        name: pinned_events_icon
                    label: "For pinned events, show an icon:"
                    type: select
                    values:
                        show_to_all:
                            ord: 1
                            label: 'Show a "pinned" icon'
                        show_to_admins_only:
                            ord: 2
                            label: 'Show a "pinned" icon to administrators only'
                        do_not_show:
                            ord: 3
                            label: "Don't show an icon"
                    value: show_to_all
                pinned_events_text:
                    plugin_setting:
                        name: pinned_events_text
                    label: "For pinned events, show text:"
                    type: select
                    values:
                        show_to_all:
                            ord: 1
                            label: 'Show text'
                        show_to_admins_only:
                            ord: 2
                            label: 'Show text to administrators only'
                        do_not_show:
                            ord: 3
                            label: "Don't show text"
                    value: do_not_show
                    redraw_onchange: true
                pinned_events_text_wording:
                    indent: 1
                    plugin_setting:
                        name: pinned_events_text_wording
                    type: text
                    show_phrase_icon: true
                    label: '"Pinned" text:'
                    value: "Pinned"
                    visible_if: lib.value('pinned_events_text') != 'do_not_show'
                    validation:
                        required_if_not_hidden: 'Please enter the "pinned" text'
                    maxlength: 20
                    style: 'width: 10em;'
                pinned_events_text_html_tag:
                    indent: 2
                    plugin_setting:
                        name: pinned_events_text_html_tag
                    value: p
                    visible_if: lib.value('pinned_events_text') != 'do_not_show'
                    type: select
                    values:
                        h1:
                            label: <h1>
                        h2:
                            label: <h2>
                        h3:
                            label: <h3>
                        h4:
                            label: <h4>
                        h5:
                            label: <h5>
                        h6:
                            label: <h6>
                        p:
                            label: <p>
                    same_row: true
                show_online_when_event_is_online:
                    label: 'Show "Online" when event is online'
                    type: checkbox
                    plugin_setting:
                        name: show_online_when_event_is_online
                    redraw_onchange: true
                online_text:
                    indent: 1
                    label: 'Online text:'
                    type: text
                    plugin_setting:
                        name: online_text
                    value: 'Online'
                    visible_if: lib.value('show_online_when_event_is_online')
                show_address:
                    label: 'Show address if event has a physical location or address'
                    type: checkbox
                    plugin_setting:
                        name: show_address
                    redraw_onchange: true
                show_at_location_text:
                    indent: 1
                    label: 'Show "At location" when event has a physical location or address'
                    type: checkbox
                    plugin_setting:
                        name: show_at_location_text
                    visible_if: lib.value('show_address')
                    redraw_onchange: true
                at_location_text:
                    indent: 2
                    label: 'At location text:'
                    type: text
                    plugin_setting:
                        name: at_location_text
                    value: 'At location'
                    visible_if: lib.value('show_address') && lib.value('show_at_location_text')