# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Event
            fields:
                show_title:
                    plugin_setting:
                        name: show_title
                    label: "Show title"
                    type: checkbox
                    value: true
                    redraw_onchange: true
                title_tags:
                    hide_with_previous_field: true
                    visible_if: zenarioAB.value('show_title')
                    plugin_setting:
                        name: title_tags
                    label: 'Title heading tag:'
                    type: select
                    values:
                        h1: <h1>
                        h2: <h2>
                        h3: <h3>
                        h4: <h4>
                        h5: <h5>
                        h6: <h6>
                        p: <p>
                    value: h1
                    side_note: |
                        Choose which HTML tags the title will be displayed in
                    indent: 1
                show_details_and_link:
                    label: 'Show Event details from:'
                    type: radios
                    plugin_setting:
                        name: show_details_and_link
                    values:
                        current_content_item:
                            ord: "1"
                            label: Current Event content item
                        another_content_item:
                            ord: "2"
                            label: A specifc Event content item
                    side_note: |
                        This plugin may be on the layout for Event content items; alternatively it may be on another type of content item (e.g. HTML, News) and then link to an Event content item.
                    value: current_content_item
                    format_onchange: Yes
                another_event:
                    indent: 1
                    label: 'Select Event content item:'
                    plugin_setting:
                        name: another_event
                        foreign_key_to: content
                    pick_items:
                        path: zenario__content/panels/content/refiners/content_type//event//
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        select_phrase: Select Event content item...
                    validation:
                        required_if_not_hidden: Please select a content item.
                show_online_when_event_is_online:
                    label: 'Show "Online" when event is online'
                    type: checkbox
                    plugin_setting:
                        name: show_online_when_event_is_online
                    redraw_onchange: true
                online_text:
                    indent: 1
                    label: 'Online text:'
                    type: text
                    plugin_setting:
                        name: online_text
                    value: 'Online'
                    visible_if: lib.value('show_online_when_event_is_online')
                show_address:
                    label: 'Show address if event has a physical location or address'
                    type: checkbox
                    plugin_setting:
                        name: show_address
                    redraw_onchange: true
                show_at_location_text:
                    indent: 1
                    label: 'Show "At location" when event has a physical location or address'
                    type: checkbox
                    plugin_setting:
                        name: show_at_location_text
                    visible_if: lib.value('show_address')
                    redraw_onchange: true
                at_location_text:
                    indent: 2
                    label: 'At location text:'
                    type: text
                    plugin_setting:
                        name: at_location_text
                    value: 'At location'
                    visible_if: lib.value('show_address') && lib.value('show_at_location_text')
    module_class_name: zenario_ctype_event