# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_recurring_countdown
    tabs:
        first_tab:
            edit_mode:
                format_on_edit: true
                format_on_cancel_edit: true
                format_on_revert: true
            label: Details
            fields:
                heading:
                    plugin_setting:
                        name: heading
                    label: 'Heading:'
                    type: text
                    value: 'Time until countdown ends:'
                    maxlength: 255
                    
                message:
                    plugin_setting:
                        name: message
                    label: 'End of countdown message:'
                    type: text
                    value: 'The countdown has finnished'
                    maxlength: 255
                
                countdown_intervals:
                    plugin_setting:
                        name: countdown_intervals
                    label: 'Countdown intervals'
                    type: checkboxes
                    values:
                        0: 
                            ord: 1
                            label: '0:00'
                        1:
                            ord: 2
                            label: '1:00'
                        2:
                            ord: 3
                            label: '2:00'
                        3:
                            ord: 4
                            label: '3:00'
                        4:
                            ord: 5
                            label: '4:00'
                        5:
                            ord: 6
                            label: '5:00'
                        6:
                            ord: 7
                            label: '6:00'
                        7:
                            ord: 8
                            label: '7:00'
                        8:
                            ord: 9
                            label: '8:00'
                        9:
                            ord: 10
                            label: '9:00'
                        10:
                            ord: 11
                            label: '10:00'
                        11:
                            ord: 12
                            label: '11:00'
                        12:
                            ord: 13
                            label: '12:00'
                        13:
                            ord: 14
                            label: '13:00'
                        14:
                            ord: 15
                            label: '14:00'
                        15:
                            ord: 16
                            label: '15:00'
                        16:
                            ord: 17
                            label: '16:00'
                        17:
                            ord: 18
                            label: '17:00'
                        18:
                            ord: 19
                            label: '18:00'
                        19:
                            ord: 20
                            label: '19:00'
                        20:
                            ord: 21
                            label: '20:00'
                        21:
                            ord: 22
                            label: '21:00'
                        22:
                            ord: 23
                            label: '22:00'
                        23:
                            ord: 24
                            label: '23:00'
                    value: 0