# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_location_map_and_listing_2
    tabs:
        first_tab:
            label: Filters
            fields:
                desc:
                    ord: 0
                    snippet:
                        html: |
                            This plugin will show a map and a list of all of the active locations on your site.
                front_end_features:
                    type: grouping
                    snippet:
                        label: Front-end features
                        label_class: subheading
                show_fields:
                    type: grouping
                    snippet:
                        label: Show fields
                        label_class: subheading
                filter_locations:
                    type: grouping
                    snippet:
                        label: Filter locations
                        label_class: subheading
                show_location_list:
                    grouping: front_end_features
                    label: Show location list
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: show_location_list
                show_map:
                    grouping: front_end_features
                    label: Show map
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: show_map
                locations__field__name:
                    grouping: show_fields
                    label: Name
                    type: checkbox
                    value: 1
                    readonly: true
                    plugin_setting:
                        name: locations__field__name
                locations__field__checkbox_selection:
                    grouping: show_fields
                    label: Checkbox selection
                    type: checkbox
                    value: 1
                    side_note: "Show which filter checkboxes this location has."
                    plugin_setting:
                        name: locations__field__checkbox_selection
                locations__field__address:
                    grouping: show_fields
                    label: Address
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: locations__field__address
                locations__field__phone:
                    grouping: show_fields
                    label: Phone
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: locations__field__phone
                locations__field__email:
                    grouping: show_fields
                    label: Email
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: locations__field__email
                locations__field__website:
                    grouping: show_fields
                    label: Website
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: locations__field__website
                locations__field__link_to_descriptive_page:
                    grouping: show_fields
                    label: Link to descriptive page
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: locations__field__link_to_descriptive_page
                locations__field__summary:
                    grouping: show_fields
                    label: Summary (only appears on the list)
                    type: checkbox
                    value: 1
                    plugin_setting:
                        name: locations__field__summary
                locations__field__special_offers:
                    grouping: show_fields
                    label: Special offers
                    type: checkbox
                    value: 0
                    plugin_setting:
                        name: locations__field__special_offers
                location_display:
                    grouping: filter_locations
                    plugin_setting:
                        name: location_display
                    type: radios
                    values:
                        show_all_locations:
                            ord: 1
                            label: "Show all locations"
                        apply_a_filter:
                            ord: 2
                            label: "Apply a filter"
                    value: show_all_locations
                    redraw_onchange: true
                location_dataset_filter_level_1:
                    grouping: filter_locations
                    label: "Filter locations (level 1):"
                    indent: 1
                    plugin_setting:
                        name: location_dataset_filter_level_1
                    type: select
                    values: {}
                    empty_value: '-- Select --'
                    visible_if: zenarioAB.value('location_display') == 'apply_a_filter'
                    format_onchange: true
                    validation:
                        required_if_not_hidden: "Please select a dataset field."
                location_dataset_filter_level_2:
                    grouping: filter_locations
                    label: "Filter locations (level 2, optional):"
                    indent: 2
                    plugin_setting:
                        name: location_dataset_filter_level_2
                    type: select
                    values: {}
                    empty_value: '-- Select --'
                    visible_if: zenarioAB.value('location_display') == 'apply_a_filter'
                exclude_dataset_filters:
                    grouping: filter_locations
                    label: "Exclude filters"
                    type: checkbox
                    value: false
                    plugin_setting:
                        name: exclude_dataset_filters
                    redraw_onchange: true
                exclude_dataset_filters_picker:
                    grouping: filter_locations
                    label: "Hide the following categorisations:"
                    indent: 1
                    plugin_setting:
                        name: exclude_dataset_filters_picker
                    type: checkboxes
                    values: {}
                    visible_if: zenarioAB.value('exclude_dataset_filters')
                    validation:
                        required_if_not_hidden: "Please select one or more dataset fields to exclude."
                hide_filters_list:
                    label: "Hide filters list"
                    type: checkbox
                    value: false
                    plugin_setting:
                        name: hide_filters_list
        image:
            label: "Images"
            fields:
                show_images:
                    plugin_setting:
                        name: show_images
                    type: checkbox
                    label: 'Show location images on the list and in info windows'
                    format_onchange: true
                list_view_thumbnail_canvas:
                    indent: 1
                    plugin_setting:
                        name: list_view_thumbnail_canvas
                    label: 'Image size on the list:'
                    side_note: "Location info windows use the same image at half the size."
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: true
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                list_view_thumbnail_width:
                    indent: 3
                    plugin_setting:
                        name: list_view_thumbnail_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    value: "200"
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                list_view_thumbnail_height:
                    indent: 3
                    plugin_setting:
                        name: list_view_thumbnail_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    value: "200"
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                list_view_thumbnail_offset:
                    indent: 3
                    plugin_setting:
                        name: list_view_thumbnail_offset
                    label: 'Offset:'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: true
                        style: 'width: 200px;'
                    note_below: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.