"<?php if (!defined('NOT_ACCESSED_DIRECTLY')) exit('This file may not be directly accessed'); ?>"

"Zenario VISITOR LANGUAGE PACK WORKSHEET",,"Target Language ID"
"(Do not edit this column)","To create a new Language Pack, change the value of the cell to the right to the ID for the language you are creating ->",en

Plugin
zenario_contact_form

"Phrase Code",Translation
_ADDRESS_INCOMPLETE,"Please enter your address."
_ADDRESS:,"Your Address:"
_CAPTCHA_INVALID,"Please correctly verify that you are human."
_CAPTCHA:,"Please help us combat form submissions by spam devices:"
_CITY_INCOMPLETE,"Please enter your town or city."
_CITY:,"Your Town or City:"
_CLEAR_FORM,"Clear Form"
_CLICK_HERE, "Click here"
_COMPANY_INCOMPLETE,"Please enter your company name."
_COMPANY:,"Your Company Name:"
_CONTACT_FORM_CONFIRMATION_MSG, "Thank you, your message has been sent."
_CONTACT_US, "Contact us"
_COUNTRY_INCOMPLETE,"Please enter your country."
_COUNTRY:,"Your Country:"
_EMAIL_INCOMPLETE,"Please enter your email address."
_EMAIL_INVALID,"Please enter a valid email address."
_EMAIL_MESSAGE_NOT_SENT, "Sorry, there was a problem on our website. Your message could not be sent."
_EMAIL_SENDER_IP,"IP address of the sender: "
_EMAIL:, "Your Email Address:"
_HEADING,"Use this form to contact us"
_MESSAGE_INCOMPLETE,"Please enter a message."
_MESSAGE:,"Your Message:"
_NAME_INCOMPLETE,"Please enter your name."
_NAME:, "Your Name:"
_PHONE_INCOMPLETE,"Please enter your phone number."
_PHONE:, "Your Phone Number:"
_POST_CODE_INCOMPLETE,"Please enter your ZIP or postcode."
_POST_CODE:,"Your ZIP or Postcode:"
_PROVINCE_INCOMPLETE,"Please enter your State or province."
_PROVINCE:,"Your State or Province:"
_SUBMIT,"Submit"
