# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Filter and Order
            fields:
                sector:
                    label: 'Show Locations from Sector:'
                    plugin_setting:
                        name: sector
                    pick_items:
                        path: zenario__locations/nav/sectors/panel
                        target_path: zenario__locations/nav/sectors/panel
                        min_path: zenario__locations/nav/sectors/panel
                        max_path: zenario__locations/nav/sectors/panel
                        disallow_refiners_looping_on_min_path: 'false'
                        nothing_selected_phrase: Show Locations in all Sectors
                        select_phrase: Select Sector...
                    format_onchange: true
                country:
                    label: 'Show Locations from Country:'
                    plugin_setting:
                        name: country
                    pick_items:
                        path: zenario__languages/panels/countries
                        target_path: zenario__languages/panels/countries
                        min_path: zenario__languages/panels/countries
                        max_path: zenario__languages/panels/countries
                        disallow_refiners_looping_on_min_path: 'false'
                        nothing_selected_phrase: Show Locations in all Countries
                        select_phrase: Select Country...
                    format_onchange: true
                region:
                    label: 'Show Locations from Region:'
                    plugin_setting:
                        name: region
                    pick_items:
                        path: zenario__languages/panels/regions
                        target_path: zenario__languages/panels/regions
                        min_path: zenario__languages/panels/regions
                        max_path: zenario__languages/panels/regions
                        disallow_refiners_looping_on_min_path: 'false'
                        nothing_selected_phrase: Show Locations in all Regions
                        select_phrase: Select Region...
                location_filter:
                    plugin_setting:
                        name: location_filter
                    label: 'Filter locations on dataset field:'
                    type: select
                    values: {}
                    empty_value: "-- No filter --"
                    side_note: "Only locations that have the selected dataset field checked will show."
                order_by_1:
                    plugin_setting:
                        name: order_by_1
                    label: 'Order by 1st:'
                    type: select
                    values:
                        0: '-- Select a field to order by --'
                        sector_score: Sector Score (descending)
                        country: Country (ascending)
                        name: Name (ascending)
                    value: name
                order_by_2:
                    plugin_setting:
                        name: order_by_2
                    label: 'Order by 2nd:'
                    type: select
                    values:
                        0: '-- Select a field to order by --'
                        sector_score: Sector Score (descending)
                        country: Country (ascending)
                        name: Name (ascending)
                    value: name
                order_by_3:
                    plugin_setting:
                        name: order_by_3
                    label: 'Order by 3rd:'
                    type: select
                    values:
                        0: '-- Select a field to order by --'
                        sector_score: Sector Score (descending)
                        country: Country (ascending)
                        name: Name (ascending)
                    value: name
        display:
            label: Display
            fields:
                title:
                    plugin_setting:
                        name: title
                    label: 'Title:'
                    type: text
                    maxlength: 255
                title_tags:
                    plugin_setting:
                        name: title_tags
                    same_row: true
                    type: select
                    values:
                        h1: <h1>
                        h2: <h2>
                        h3: <h3>
                        h4: <h4>
                        h5: <h5>
                        h6: <h6>
                        p: <p>
                    value: h2
                loc_name_tags:
                    label: 'Location name:'
                    plugin_setting:
                        name: loc_name_tags
                    type: select
                    values:
                        h1: <h1>
                        h2: <h2>
                        h3: <h3>
                        h4: <h4>
                        h5: <h5>
                        h6: <h6>
                        p: <p>
                    value: h2
                
                show_featured_image:
                    plugin_setting:
                        name: show_featured_image
                    label: "Show location's image"
                    type: checkbox
                    value: ""
                    format_onchange: true
                canvas:
                    plugin_setting:
                        name: canvas
                        save_value_when_hidden: true
                    label: 'Image canvas:'
                    type: select
                    values:
                        unlimited:
                            label: Unlimited size
                        fixed_width:
                            label: Constrain by width
                        fixed_height:
                            label: Constrain by height
                        fixed_width_and_height:
                            label: Constrain by width and height
                        crop_and_zoom:
                            label: Crop and zoom
                    value: crop_and_zoom
                    format_onchange: true
                    indent: 1
                retina:
                    plugin_setting:
                        name: retina
                    label: |
                        Treat as a retina image (display at double density)
                    type: checkbox
                    value: ""
                    enable_microtemplates_in_properties: true
                    same_row: true
                width:
                    plugin_setting:
                        name: width
                        save_value_when_hidden: true
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: 240
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                height:
                    plugin_setting:
                        name: height
                        save_value_when_hidden: true
                    type: text
                    label: 'Height:'
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: 160
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                webp:
                    indent: 2
                    hide_with_previous_outdented_field: true
                    plugin_setting:
                        name: webp
                        save_value_when_hidden: true
                    type: checkbox
                    label: 'Link to WebP-format (with fallback for browsers not supporting WebP), recommended for smaller file size'
                    value: 1
                pagination:
                    plugin_setting:
                        name: pagination
                    label: 'Pagination style:'
                    type: select
                    value: zenario_common_features::pagCloseWithNPIfNeeded
                page_size:
                    plugin_setting:
                        name: page_size
                    label: 'Number of Locations on one page:'
                    type: select
                    values:
                        1: "1"
                        2: "2"
                        3: "3"
                        4: "4"
                        5: "5"
                        6: "6"
                        7: "7"
                        8: "8"
                        9: "9"
                        10: "10"
                        12: "12"
                        15: "15"
                        20: "20"
                        50: "50"
                        999999: All possible
                    value: "10"
                excerpt_length:
                    plugin_setting:
                        name: excerpt_length
                    label: 'Number of characters to show from Location Summary:'
                    type: select
                    values:
                        50: "50"
                        100: "100"
                        200: "200"
                        500: "500"
                    value: "200"
    module_class_name: zenario_location_listing
