# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_menu
    tabs:
        first_tab:
            ord: 1
            label: Menu display
            fields:
                menu_generation_current_or_specific:
                    plugin_setting:
                        name: menu_generation_current_or_specific
                    label: 'Menu origin:'
                    type: radios
                    value: _CURRENT
                    values:
                        _CURRENT:
                            ord: "1"
                            label: Auto
                        _SPECIFIC:
                            ord: "1"
                            label: Custom
                    format_onchange: Yes
                    side_note: >
                        Select "Auto" to generate the menu around the current content item (recommended). Select "Custom" to show the menu of a different part of the site.
                menu_section:
                    indent: 1
                    plugin_setting:
                        name: menu_section
                        foreign_key_to: menu_section
                        dangling_cross_references: delete_instance
                    label: 'Menu section:'
                    pick_items:
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/sections
                        max_path: zenario__menu/panels/sections
                        target_path: zenario__menu/panels/sections
                        select_phrase: Select menu section...
                        hide_remove_button: Yes
                    value: "1"
                    validation:
                        required: Please select a menu section
                    format_onchange: Yes
                    side_note: >
                        The principal menu navigation is usually in a secton called "Main". To display menu nodes from a different section, choose it here.
                specific_menu_node:
                    indent: 1
                    plugin_setting:
                        name: specific_menu_node
                    label: 'Select custom menu node:'
                    pick_items:
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/menu_nodes
                        max_path: zenario__menu/panels/menu_nodes
                        target_path: zenario__menu/panels/menu_nodes
                        select_phrase: Select menu node...
                        hide_remove_button: Yes
                    validation:
                        required_if_not_hidden: Please select a menu node
                    hidden: Yes
                menu_start_from:
                    indent: 1
                    plugin_setting:
                        name: menu_start_from
                    label: 'Starting level:'
                    type: select
                    value: _MENU_LEVEL_1
                    values:
                        _MENU_LEVEL_1:
                            ord: "1"
                            label: Level 1
                        _MENU_LEVEL_2:
                            ord: "2"
                            label: Level 2
                        _MENU_LEVEL_3:
                            ord: "3"
                            label: Level 3
                        _MENU_LEVEL_4:
                            ord: "4"
                            label: Level 4
                        _MENU_LEVEL_5:
                            ord: "5"
                            label: Level 5
                        _MENU_LEVEL_ABOVE:
                            ord: "10"
                            label: Menu level above current one
                        _MENU_CURRENT_LEVEL:
                            ord: "11"
                            label: Current menu level
                    side_note: >
                        To generate the main nav of the site from the top level, choose level 1 (recommended). Use other options to generate only deeper parts of the menu.
                menu_number_of_levels:
                    plugin_setting:
                        name: menu_number_of_levels
                    label: 'Number of levels to display:'
                    type: select
                    values:
                        1: "1 level"
                        1_full_width: "1 level (full width)"
                        2: "2 levels"
                        3: "3 levels"
                        4: "4 levels"
                        5: "5 levels"
                    value: "2"
                    side_note: "If displaying 3 or more levels, the menu can be hard for users to use. Hint: use the Promo Menu plugin instead."
                    format_onchange: true
                number_of_columns_full_width:
                    indent: 1
                    plugin_setting:
                        name: number_of_columns_full_width
                    label: "Number of columns to display:"
                    type: select
                    values:
                        1: "1"
                        2: "2"
                        3: "3"
                        4: "4"
                        5: "5"
                    value: 1
                    visible_if: lib.value('menu_number_of_levels') == "1_full_width"
                limit_initial_level_1_menu_nodes_checkbox:
                    plugin_setting:
                        name: limit_initial_level_1_menu_nodes_checkbox
                    label: |
                        Divide the menu with a "More" button
                    type: checkbox
                    side_note: 'Check this option to limit how many level 1 menu nodes are shown, so that the user must click the More button to reveal the remaining menu nodes.'
                    redraw_onchange: true
                    disabled_if: lib.valueNotIn('menu_number_of_levels', '1', '2', '3')
                limit_initial_level_1_menu_nodes:
                    indent: 1
                    plugin_setting:
                        name: limit_initial_level_1_menu_nodes
                    type: select
                    values:
                        1: "1 item"
                        2: "2 items"
                        3: "3 items"
                        4: "4 items"
                        5: "5 items"
                    value: 5
                    visible_if: lib.value('limit_initial_level_1_menu_nodes_checkbox')
                    disabled_if: lib.valueNotIn('menu_number_of_levels', '1', '2', '3')
                text_for_more_button:
                    indent: 1
                    plugin_setting:
                        name: text_for_more_button
                    type: text
                    label: 'Text for "More" button:'
                    value: "More"
                    show_phrase_icon: true
                    visible_if: lib.value('limit_initial_level_1_menu_nodes_checkbox')
                    disabled_if: lib.valueNotIn('menu_number_of_levels', '1', '2', '3')
                    validation:
                        required_if_not_hidden: 'This field is required.'
                menu_show_all_branches:
                    plugin_setting:
                        name: menu_show_all_branches
                    label: 'Generate distant branches'
                    type: checkbox
                    value: "1"
                    disabled_if: lib.value('menu_number_of_levels') == 1
                    side_note: >
                        Generate parts of the menu hierarchy not including the current page. Normally used to support a mouseover effect when all parts of the menu need to be displayed.
                show_missing_menu_nodes:
                    plugin_setting:
                        name: show_missing_menu_nodes
                    label: 'Show missing menu nodes'
                    type: checkbox
                    value: ""
                enable_open_close:
                    plugin_setting:
                        name: enable_open_close
                    label: 'Enable open/close menu with persistence across pages'
                    type: checkbox
                    value: false
                    redraw_onchange: true
                open_close_initial_state:
                    indent: 1
                    plugin_setting:
                        name: open_close_initial_state
                    label: 'Initial state:'
                    type: select
                    empty_value: "-- Select --"
                    values:
                        closed:
                            ord: 1
                            label: "Closed"
                        open:
                            ord: 2
                            label: "Open"
                    visible_if: lib.value('enable_open_close')
                    validation:
                        required_if_not_hidden: "Please select the initial state."
                hide_if_current_item_not_in_menu:
                    plugin_setting:
                        name: hide_if_current_item_not_in_menu
                    label: |
                            Hide menu when content item in view isn't attached to the menu
                    type: checkbox
                    side_note: >
                        Hide the menu when the current content item is orphaned, i.e. not in the menu hierarchy.
                reverse_order:
                    plugin_setting:
                        name: reverse_order
                    label: 'Reverse order'
                    type: checkbox
                    value: ""
                    side_note: >
                        Generate from right to left. Use this option for easier float-right styling.
                show_invisible_menu_nodes:
                    plugin_setting:
                        name: show_invisible_menu_nodes
                    label: 'Show invisible menu nodes'
                    type: checkbox
                    value: ""
                    side_note: >
                        Menu nodes flagged as "invisible" are normally not displayed; check here to show invisible menu nodes anyway.
                show_custom_title:
                    plugin_setting:
                        name: show_custom_title
                    label: 'Show a custom title'
                    type: checkbox
                    value: false
                    redraw_onchange: true
                    side_note: 'The title will appear above the menu.'
                title_tags:
                    plugin_setting:
                        name: title_tags
                    label: 'Title heading tags:'
                    type: select
                    values:
                        h1: Heading 1
                        h2: Heading 2
                        h3: Heading 3
                        h4: Heading 4
                        h5: Heading 5
                        h6: Heading 6
                        p: Paragraph
                    value: h2
                    same_row: true
                    visible_if: lib.value('show_custom_title')
                custom_title:
                    indent: 1
                    plugin_setting:
                        name: custom_title
                    label: 'Custom title:'
                    type: text
                    value: 'In this section'
                    visible_if: lib.value('show_custom_title')
                    validation:
                        required_if_not_hidden: 'Please enter a title.'
