# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: users
    tabs:
        registration:
            label: Registration
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                warning_message:
                    pre_field_html: '<div class="warning_icon">'
                    snippet:
                        html: 'The Scheduled Task "jobSendDelayedRegistrationEmails" is required, but it is not running.'
                    post_field_html: '</div>'
                send_delayed_registration_email:
                    site_setting:
                        name: send_delayed_registration_email
                    label: Send a delayed email after a user registers
                    type: checkbox
                    format_onchange: true
                delayed_registration_email_template:
                    site_setting:
                        name: delayed_registration_email_template
                    label: 'Email template:'
                    pick_items: 
                        path: zenario__email_template_manager/panels/email_templates
                        target_path: zenario__email_template_manager/panels/email_templates
                        min_path: zenario__email_template_manager/panels/email_templates
                        max_path: zenario__email_template_manager/panels/email_templates
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No email template selected
                        select_phrase: Select an email template...
                    indent: 1
                    visible_if: zenarioAB.value('send_delayed_registration_email');
                    validation:
                        required_if_not_hidden: Please select an email template.
                delayed_registration_email_days_delayed:
                    site_setting:
                        name: delayed_registration_email_days_delayed
                    label: 'Days after registration to send email:'
                    type: select
                    values:
                        1: 1
                        2: 2
                        3: 3
                        7: 7
                        10: 10
                        20: 20
                        30: 30
                    value: 1
                    indent: 1
                    visible_if: zenarioAB.value('send_delayed_registration_email');
                delayed_registration_email_time_of_day:
                    site_setting:
                        name: delayed_registration_email_time_of_day
                    label: 'Time of day to send:'
                    type: select
                    values: {}
                    value: 10
                    indent: 1
                    visible_if: zenarioAB.value('send_delayed_registration_email');
