# You must use a tab-size of 4 spaces to edit this file.
---
zenario__administration:
    panels:
        site_settings:
            items:
                zenario_location_manager__site_settings_group:
                    name: Location Manager
                    desc: Settings for the Location Manager
