# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
	module_class_name: zenario_content_list_probusiness
	tabs:
		first_tab:
			fields:
				content_type:
					values:
						all: All Content Types
					format_onchange: Yes
				only_show:
					ord: "13"
					plugin_setting:
						name: only_show
					label: 'Items to show:'
					type: select
					value: all
					values:
						public:
							ord: "1"
							label: Public Content Items only
						all:
							ord: "2"
							label: Public and Private Content Items
						private:
							ord: "3"
							label: Private Content Items only
				language_selection:
					ord: "15"
					plugin_setting:
						name: language_selection
					label: 'Only show Items in:'
					type: select
					value: visitor
					values:
						visitor:
							ord: "1"
							label: "Visitor's language"
						all:
							ord: "2"
							label: All enabled languages
						specific_languages:
							ord: "3"
							label: Specific languages
					format_onchange: Yes
				specific_languages:
					ord: "16"
					label: 'Select languages:'
					plugin_setting:
						name: specific_languages
					type: checkboxes
					load_values_from_organizer_path: zenario__languages/panels/languages
					validation:
						required_if_not_hidden: Please select a language.
				release_date:
					ord: "17"
					label: 'Release Date:'
					plugin_setting:
						name: release_date
					type: select
					values:
						ignore:
							ord: "1"
							label: Ignore
						date_range:
							ord: "2"
							label: Date range
						relative_date_range:
							ord: "3"
							label: Relative date range
						prior_to_date:
							ord: "4"
							label: Prior to a certain date
						on_date:
							ord: "5"
							label: On a certain date
						after_date:
							ord: "6"
							label: After a certain date
					#value: ignore
					format_onchange: Yes
				start_date:
					ord: "18"
					plugin_setting:
						name: start_date
					label: "Date range start:"
					type: date
					change_month_and_year: "1"
					side_note: "Content items must have been published and they must have the release date defined."
				end_date:
					ord: "19"
					plugin_setting:
						name: end_date
					label: "Date range end:"
					type: date
					change_month_and_year: "1"
					side_note: "Content items must have been published and they must have the release date defined."
				relative_operator:
					ord: "20"
					label: 'Relative date range:'
					plugin_setting:
						name: relative_operator
					type: select
					values:
						older: Older than
						newer: Not older than
					value: newer
					validation:
						required_if_not_hidden: Please specify a relative date range.
					side_note: "Content items must have been published and they must have the release date defined."
				relative_value:
					ord: "21"
					plugin_setting:
						name: relative_value
					type: text
					same_row: Yes
					style: width:50px;
					pre_field_html: '&nbsp;'
					post_field_html: '&nbsp;'
					value: "1"
					validation:
						required_if_not_hidden: Please specify a relative date range.
				relative_units:
					ord: "22"
					plugin_setting:
						name: relative_units
					type: select
					values:
						days: day(s)
						months: month(s)
						years: year(s)
					same_row: Yes
					value: "1"
					validation:
						required_if_not_hidden: Please specify a relative date range.
				prior_to_date:
					ord: "23"
					plugin_setting:
						name: prior_to_date
					label: "Prior to the date:"
					type: date
					change_month_and_year: "1"
					side_note: "Content items must have been published and they must have the release date defined."
				on_date:
					ord: "24"
					plugin_setting:
						name: on_date
					label: "On the date:"
					type: date
					change_month_and_year: "1"
					side_note: "Content items must have been published and they must have the release date defined."
				after_date:
					ord: "25"
					plugin_setting:
						name: after_date
					label: "After the date:"
					type: date
					change_month_and_year: "1"
					side_note: "Content items must have been published and they must have the release date defined."
				only_show_child_items:
					ord: "27"
					plugin_setting:
						name: only_show_child_items
					label: 'Only show content beneath current Item:'
					type: checkbox
					value: ""
					note_below: >
						Only show Content Items that are beneath the current Content
						Item in the menu structure.
					format_onchange: Yes
				child_item_levels:
					ord: "28"
					plugin_setting:
						name: child_item_levels
					label: 'Menu Levels:'
					type: select
					value: "1"
					values:
						1:
							ord: "1"
							label: Content in the menu one level below current Item
						2:
							ord: "2"
							label: Content in the menu up to 2 levels below
						3:
							ord: "3"
							label: Content in the menu up to 3 levels below
						4:
							ord: "4"
							label: Content in the menu up to 4 levels below
						99:
							ord: "99"
							label: All Content in the menu below current Item
				show_secondaries:
					ord: "29"
					plugin_setting:
						name: show_secondaries
					label: 'Redundancy:'
					type: select
					value: "0"
					values:
						- 
							ord: "1"
							label: Show Primary Menu Nodes
						- 
							ord: "1"
							label: Show Primary and Secondary Menu Nodes
				refine_by_category:
					ord: "31"
					plugin_setting:
						name: refine_by_category
					label: 'Refine by Category:'
					type: checkbox
					value: ""
					format_onchange: Yes
				refine_type:
					ord: "32"
					plugin_setting:
						name: refine_type
					type: select
					value: all_categories
					values:
						any_categories:
							ord: "1"
							label: ANY Category selected below
						all_categories:
							ord: "2"
							label: ALL Categories selected below
						not_in_any_category:
							ord: "3"
							label: NOT in ANY Category selected below
				category:
					ord: "332"
					plugin_setting:
						name: category
						foreign_key_to: categories
					label: ""
					type: checkboxes
		each_item:
			fields:
				target_blank:
					plugin_setting:
						name: target_blank
					label: 'Open content in a new window:'
					type: checkbox
					value: ""
					note_below: >
						With this option enabled the content link when clicked will open on a new window.

				show_language:
					plugin_setting:
						name: show_language
					label: 'Show content language:'
					type: checkbox
					value: ""
					note_below: >
						With this option enabled the content language will be shown next to the document title.

		author_advice:
			visible_if: '!zenarioAB.tuix.key.isVersionControlled && !zenarioAB.tuix.key.nest'
			label: Author advice
			fields:
				author_advice:
					plugin_setting:
						name: author_advice
					label: 'Author advice:'
					type: textarea
					rows: "4"
					cols: "60"
					style: 'width: auto;'
					note_below: >
						Enter advice that you would like to give to Authors. This
						will appear while in Edit Mode.
