# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Settings
            fields:
                action:
                    label: 'Action:'
                    type: radios
                    plugin_setting:
                        name: action
                    values:
                        record_and_display:
                            label: Record and Display recently viewed pages
                        record_only:
                            label: Record recently viewed pages only
                        display_only:
                            label: Display recently viewed pages only
                    value: record_and_display
                    format_onchange: Yes
                pot:
                    label: 'Pot number:'
                    type: select
                    plugin_setting:
                        name: pot
                    values:
                        1:
                            label: "1"
                        2:
                            label: "2"
                        3:
                            label: "3"
                        4:
                            label: "4"
                        5:
                            label: "5"
                    value: "1"
                    note_below: >
                        Advanced users can use pots to create multiple recently
                        viewed lists.
                number_to_record:
                    label: 'Number of Items to record:'
                    type: select
                    plugin_setting:
                        name: number_to_record
                    values:
                        1:
                            label: "1"
                        2:
                            label: "2"
                        3:
                            label: "3"
                        4:
                            label: "4"
                        5:
                            label: "5"
                        6:
                            label: "6"
                        7:
                            label: "7"
                        8:
                            label: "8"
                        9:
                            label: "9"
                        10:
                            label: "10"
                        15:
                            label: "15"
                        20:
                            label: "20"
                        25:
                            label: "25"
                        50:
                            label: "50"
                    value: "5"
                order:
                    label: 'Display order:'
                    plugin_setting:
                        name: order
                    type: radios
                    values:
                        most_recent_first:
                            label: Most recent on the top
                        most_recent_last:
                            label: Most recent at the bottom
                    value: most_recent_first
        filter:
            label: Filter
            fields:
                desc:
                    snippet:
                        html: |
                            Use the settings below to filter the pages recorded or 
                                                            displayed, "AND" logic is used. Use the 
                                                            "Content Items to Exclude" setting to exclude a list of Content 
                                                            Items from being recorded.
                    full_width: Yes
                category:
                    label: 'Category:'
                    plugin_setting:
                        name: category
                    pick_items:
                        path: zenario__content/panels/categories
                        min_path: zenario__content/panels/categories
                        max_path: zenario__content/panels/categories
                        target_path: zenario__content/panels/categories
                        select_phrase: Select Category...
                        nothing_selected_phrase: 'All Categories & uncategorized'
                contenttype:
                    label: 'Content Type:'
                    plugin_setting:
                        name: contenttype
                    pick_items:
                        path: zenario__content/panels/content_types
                        min_path: zenario__content/panels/content_types
                        max_path: zenario__content/panels/content_types
                        target_path: zenario__content/panels/content_types
                        select_phrase: Select Content Type...
                        nothing_selected_phrase: All Content Types
                excluded_content:
                    label: 'Content Items to Exclude:'
                    plugin_setting:
                        name: excluded_content
                    pick_items:
                        path: zenario__content/panels/content
                        min_path: zenario__content/panels/content
                        max_path: zenario__content/panels/content
                        target_path: zenario__content/panels/content
                        select_phrase: Select Content Items...
                        nothing_selected_phrase: No Content Items selected
                        multiple_select: Yes
                        one_to_one_choose_phrase: Exclude Content Item
                        one_to_many_choose_phrase: Exclude Content Items
                exclude_special_pages:
                    label: 'Exclude special pages:'
                    type: checkbox
                    plugin_setting:
                        name: exclude_special_pages
                    value: "1"
    module_class_name: zenario_recently_viewed
