(function(d){d.plugins.Emoticons=function(a){function v(a){var e;p(m.emoticons,function(b,c){p(b,function(k){if(k==a)return e=c,!1});return!e});return e}var l=d.Event,p,u,w,x,m,n,f,q;p=d.each;u=d.extend;w=d.isIE;x=d.isGecko;f=d.DOM;this.settings=m=u({emoticons:{happy:[":)","=)"],unhappy:[":|","=|"],sad:[":(","=("],grin:[":D","=D"],surprised:[":o",":O","=o","=O"],wink:[";)"],halfhappy:[":/","=/"],tounge:[":P",":p","=P","=p"],lol:[],mad:[],rolleyes:[],cool:[]},row_length:4,trans_img:d.baseURL+"plugins/emoticons/img/trans.gif",
skip_css:0,auto_convert:1},a.settings.emoticons);m.skip_css||f.loadCSS(d.baseURL+"/plugins/emoticons/css/editor.css");n="";p(m.emoticons,function(a){p(a,function(a){0!=n.length&&(n+="|");n+=a.replace(/([^a-zA-Z0-9])/g,"\\$1")})});n=RegExp(n,"g");u(a.commands,{mceEmoticons:function(d,e,b){function c(k){a.hideMenu=null;l.remove(document,"click",c);l.remove(a.getDoc(),"click",c);f.get(t+"_memoticons").style.display="none";return 1}var k,g=this,t=a.settings.id;d=f.getPos(b.target);var h;if(a.hideMenu)return a.hideMenu();
k=f.get(t+"_memoticons");k||(k=f.get(t+"_t"),k=f.add(document.body,"div",{id:t+"_memoticons","class":"punymce_emoticons punymce"}),k=f.add(k,"table",{"class":"punymce"}),k=f.add(k,"tbody"),h=m.row_length,p(m.emoticons,function(b,e){h==m.row_length&&(r=f.add(k,"tr"),h=0);h++;l.add(f.add(f.add(r,"td"),"a",{href:"#","class":"emoticon "+e}),"mousedown",function(k){c.call(g);a.selection.setNode(a.dom.create("img",{title:b[0]||e,src:m.trans_img,"class":"emoticon "+e}));return l.cancel(k)})}));l.add(document,
"click",c,g);l.add(a.getDoc(),"click",c,g);a.hideMenu=c;s=f.get(t+"_memoticons").style;s.left=d.x+"px";s.top=d.y+b.target.clientHeight+2+"px";s.display="block"}});a.onPreProcess.add(function(d,e){var b=e.node.getElementsByTagName("img"),c=[];p(b,function(a){c.push(a)});p(c,function(c){var b=a.dom.getAttr(c,"class");b&&-1!=b.indexOf("emoticon")&&c.parentNode.replaceChild(a.getDoc().createTextNode(c.getAttribute("title")),c)})});a.onSetContent.add(function(a,e){var b=[];q=e.content.replace(/(<\/?[^>]+>|:\/\/)/g,
function(a){return a.replace(n,function(a){return v(a)?(b.push(a),"`~`~"+b.length+"`"):a})});q=q.replace(n,function(a){return'<img src="'+m.trans_img+'" title="'+a+'" class="emoticon '+v(a)+'" />'});q=q.replace(/`~`~([^`]+)`/g,function(a,e){return b[parseInt(e)-1]});e.content=q});a.onInit.add(function(){var f=a.dom;m.skip_css||f.loadCSS(d.baseURL+"/plugins/emoticons/css/content.css");l.add(a.getDoc(),"controlselect",function(a){if(-1!=f.getAttr(a.target,"class").indexOf("emoticon"))return l.cancel(a)});
x&&(l.add(a.getDoc(),"mousedown",function(e){if(-1!=f.getAttr(e.target,"class").indexOf("emoticon"))return a.getDoc().execCommand("enableObjectResizing",!1,!1),l.cancel(e);a.getDoc().execCommand("enableObjectResizing",!1,!0)}),l.add(a.getDoc(),"keydown",function(e){var b=a.selection,c=b.getSel(),f=a.getDoc(),g=b.getRng(),d;d=g.startContainer;g=g.startOffset;if(1!=d.nodeType&&d){if(39==e.keyCode&&g==d.nodeValue.length&&(b=d.nextSibling)&&"IMG"==b.nodeName)return b=b.nextSibling,g=f.createRange(),g.setStart(b,
0),g.setEnd(b,0),c.removeAllRanges(),c.addRange(g),l.cancel(e);if(37==e.keyCode&&0==g&&(b=d.previousSibling)&&"IMG"==b.nodeName)return b=b.previousSibling,d=b.nodeValue.length,g=f.createRange(),g.setStart(b,d),g.setEnd(b,d),c.removeAllRanges(),c.addRange(g),l.cancel(e)}}));l.add(a.getDoc(),"keypress",function(e){function b(a){var b,c,d;if(w)return h=h.duplicate(),h.moveStart("character",a),h.text;b=h.startContainer;c=h.startOffset;d=h.endOffset;if(0<c&&3==b.nodeType)return b.nodeValue.substring(Math.max(0,
c+a),d)}var c,k,g;a.getDoc();c=a.selection;var p=c.getSel(),h=c.getRng();if(d.isOldWebKit||!m.auto_convert)return!0;if(!/(ttp|ftp):/i.test(b(-4))&&(g=b(-1),c=g+String.fromCharCode(e.charCode||e.keyCode),n.lastIndex=0,g&&n.test(c)&&(k=v(c))))return w?(h=a.selection.getRng(),h.moveStart("character",-1),h.select()):(h.setStart(h.startContainer,h.startOffset-1),p.removeAllRanges(),p.addRange(h)),a.selection.setNode(f.create("img",{id:"emoticon",title:c,src:m.trans_img,"class":"emoticon "+k})),c=f.get("emoticon"),
f.setAttr(c,"id",""),a.selection.select(c),a.selection.collapse(0),l.cancel(e)})});u(a.tools,{emoticons:{cmd:"mceEmoticons",title:d.I18n.emoticons}})};d.extend(d.I18n,{emoticons:"Insert emoticon"})})(punymce);
