<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'NumbersPHP\\Tests' => array($vendorDir . '/powder96/numbers.php/test'),
    'NumbersPHP' => array($vendorDir . '/powder96/numbers.php/lib'),
    'ImageOptimizer' => array($vendorDir . '/ps/image-optimizer/src'),
    'Guzzle\\Stream' => array($vendorDir . '/guzzle/stream'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Guzzle\\Http' => array($vendorDir . '/guzzle/http'),
    'Guzzle\\Common' => array($vendorDir . '/guzzle/common'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
);
