# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_location_map_and_listing
    tabs:
        first_tab:
            label: Filter and Order
            fields:
                desc:
                    ord: 0
                    snippet:
                        html: |
                                This plugin will show a map and a list of all of the
                                active locations on your site.
                filter_by_country:
                    plugin_setting:
                        name: filter_by_country
                    type: checkbox
                    label: 'Filter by country'
                    side_note: |
                        Shows a drop-down list of countries. When a visitor selects a country,
                        only that country's locations will be shown.
                    redraw_onchange: true
                default_country_options:
                    visible_if: |
                        zenarioAB.value('filter_by_country')
                    indent: 1
                    plugin_setting:
                        name: default_country_options
                    label: Default country
                    type: select
                    format_onchange: true
                    values:
                        select_country:
                            ord: 1
                            label: Select a country
                        geo_ip: 
                            ord: 2
                            label: Use GeoIP
                    value: geo_ip
                    side_note: |
                        If GeoIP is selected, the visitor IP address will be taken into account to define the default country in the select list.
                default_country:
                    indent: 2
                    visible_if: |
                        zenarioAB.value('filter_by_country') && zenarioAB.value('default_country_options') == 'select_country'
                    plugin_setting:
                        name: default_country
                    label: 'Default country:'
                    pick_items:
                        path: zenario__languages/panels/countries//
                        max_path: zenario__languages/panels/countries
                        min_path: zenario__languages/panels/countries
                        target_path: zenario__languages/panels/countries
                    validation:
                        required_if_not_hidden: 'Please select a default country'
                list_by_field:
                    plugin_setting:
                        name: list_by_field
                    type: checkbox
                    label: 'List by checkbox-type field(s)'
                    side_note: |
                        You can select up to three checkbox-type fields from the location dataset
                        to group the listings.
                        If you select one field, it will act as a filter - only locations with that field set
                        will be shown.
                        If you select multiple fields, they will act as filters with OR logic - locations
                        with one of the fields set will be shown.
                    redraw_onchange: true
                field1:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('list_by_field')
                    plugin_setting:
                        name: field1
                    type: select
                    empty_value: ' -- Select -- '
                    label: 'First list:'
                    validation:
                        required_if_not_hidden: 'Please select a field for the first list'
                    redraw_onchange: true
                field1_title:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('list_by_field')
                    plugin_setting:
                        name: field1_title
                    type: text
                    label: 'Title:'
                field2:
                    visible_if: |
                        zenarioAB.value('list_by_field')
                        && zenarioAB.value('field1')
                    plugin_setting:
                        name: field2
                    type: select
                    empty_value: ' -- Select -- '
                    label: 'Second list (optional):'
                    redraw_onchange: true
                field2_title:
                    visible_if: |
                        zenarioAB.value('list_by_field')
                        && zenarioAB.value('field1')
                        && zenarioAB.value('field2')
                    plugin_setting:
                        name: field2_title
                    type: text
                    label: 'Title:'
                field3:
                    visible_if: |
                        zenarioAB.value('list_by_field')
                        && zenarioAB.value('field1')
                        && zenarioAB.value('field2')
                    plugin_setting:
                        name: field3
                    type: select
                    empty_value: ' -- Select -- '
                    label: 'Third list (optional):'
                    redraw_onchange: true
                field3_title:
                    visible_if: |
                        zenarioAB.value('list_by_field')
                        && zenarioAB.value('field1')
                        && zenarioAB.value('field2')
                        && zenarioAB.value('field3')
                    plugin_setting:
                        name: field3_title
                    type: text
                    label: 'Title:'
                allow_scrolling:
                    plugin_setting:
                        name: allow_scrolling
                    type: checkbox
                    label: 'Allow scrolling'
                    side_note: |
                        If this is checked, a visitor will be able to scroll the map using the
                        scroll-wheel on their mouse.
                
                enable_postcode_search:
                    plugin_setting:
                        name: enable_postcode_search
                    label: Enable postcode search
                    type: checkbox
                    side_note: |
                        Show a search box which a user can use to filter locations to those closest to a postcode.
                    redraw_onchange: true
                hide_locations_list_before_search:
                    indent: 1
                    plugin_setting:
                        name: hide_locations_list_before_search
                    label: Hide locations list before search
                    type: checkbox
                    side_note: |
                        You can hide the list of locations before a search is made in case the unfiltered list of locations is too long.
                    visible_if: zenarioAB.value('enable_postcode_search')
                search_result_count:
                    indent: 1
                    plugin_setting:
                        name: search_result_count
                    label: 'Number of search results:'
                    type: select
                    values:
                        1: 1
                        2: 2
                        3: 3
                        4: 4
                        5: 5
                        10: 10
                        25: 25
                        50: 50
                        unlimited: Unlimited
                    value: 4
                    visible_if: zenarioAB.value('enable_postcode_search')
                search_result_distance:
                    plugin_setting:
                        name: search_result_distance
                    label: Search result distance
                    type: radios
                    values:
                        dont_show:
                            ord: 1
                            label: Don't show
                        km: 
                            ord: 1
                            label: Show in Kilometers
                        m: 
                            ord: 1
                            label: Show in Miles
                    value: dont_show
                    side_note: |
                        After searching for a postcode, display a distance next to each result.
                    visible_if: zenarioAB.value('enable_postcode_search')
                show_view_button:
                    plugin_setting:
                        name: show_view_button
                    label: Show button to go to the descriptive page
                    type: checkbox
                    format_onchange: true
                button_label:
                    visible_if: |
                        zenarioAB.value('show_view_button')
                    plugin_setting:
                        name: button_label
                    type: text
                    label: 'Button label:'
                    value: "View"
                    show_phrase_icon: true
                    side_note: "Enter text in the default language. <a href=\"zenario/admin/organizer.php#zenario__languages/panels/phrases\" target=\"_blank\">Click here to manage translations in Organizer.</a>."
                    indent: 1
                    validation:
                        required_if_not_hidden: Please enter a button label.
        image:
            label: "Images"
            fields:
                show_images:
                    plugin_setting:
                        name: show_images
                    type: checkbox
                    label: 'Show images'
                    format_onchange: true
                map_view_thumbnail_canvas:
                    indent: 1
                    plugin_setting:
                        name: map_view_thumbnail_canvas
                    label: 'Image size on the map info window:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: true
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                map_view_thumbnail_width:
                    indent: 3
                    plugin_setting:
                        name: map_view_thumbnail_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                map_view_thumbnail_height:
                    indent: 3
                    plugin_setting:
                        name: map_view_thumbnail_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                map_view_thumbnail_offset:
                    indent: 3
                    plugin_setting:
                        name: map_view_thumbnail_offset
                    label: 'Offset:'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: true
                        style: 'width: 200px;'
                    note_below: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.
                list_view_thumbnail_canvas:
                    indent: 1
                    plugin_setting:
                        name: list_view_thumbnail_canvas
                    label: 'Image size on the list:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: true
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                list_view_thumbnail_width:
                    indent: 3
                    plugin_setting:
                        name: list_view_thumbnail_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                list_view_thumbnail_height:
                    indent: 3
                    plugin_setting:
                        name: list_view_thumbnail_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                list_view_thumbnail_offset:
                    indent: 3
                    plugin_setting:
                        name: list_view_thumbnail_offset
                    label: 'Offset:'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: true
                        style: 'width: 200px;'
                    note_below: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.