# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Filter
            fields:
                hide_private_items:
                    plugin_setting:
                        name: hide_private_items
                    label: 'Private Items:'
                    type: select
                    value: "1"
                    values:
                        1:
                            label: >
                                Only show links to Forums on Private Content Items to
                                authorized visitors
                        0:
                            label: >
                                Show links to Forums on Private Content Items to all
                                visitors
                category:
                    plugin_setting:
                        name: category
                    label: 'Category:'
                    pick_items:
                        path: zenario__content/panels/categories
                        target_path: zenario__content/panels/categories
                        min_path: zenario__content/panels/categories
                        max_path: zenario__content/panels/categories
                        disallow_refiners_looping_on_min_path: Yes
                        one_to_one_choose_phrase: Choose Category
                        select_phrase: Select a Category...
                        nothing_selected_phrase: Show all Forums of all Categories
                        hide_remove_button: No
                    value: ""
        each_item:
            label: Each Forum
            fields:
                data_field:
                    plugin_setting:
                        name: data_field
                    label: 'Show summary from:'
                    type: select
                    value: none
                    values:
                        none:
                            label: Do not show a summary
                        content_summary:
                            label: "Item's Summary"
                        description:
                            label: "Item's Description"
                show_sticky_images:
                    plugin_setting:
                        name: show_sticky_images
                    label: "Show content item's feature image"
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                canvas:
                    plugin_setting:
                        name: canvas
                    label: 'Image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                width:
                    plugin_setting:
                        name: width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: "100"
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                height:
                    plugin_setting:
                        name: height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: "100"
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                date_format:
                    plugin_setting:
                        name: date_format
                    label: 'Date Format:'
                    type: select
                    value: _LONG
                    values:
                        _SHORT:
                            label: Short
                        _MEDIUM:
                            label: Medium
                        _LONG:
                            label: Long
    module_class_name: zenario_forum_list
