# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Filter
            fields:
                hide_private_items:
                    plugin_setting:
                        name: hide_private_items
                    label: 'Private Items:'
                    type: select
                    value: "1"
                    values:
                        1:
                            label: >
                                Show links to private forums (forums on private content items) only to authorized users
                        0:
                            label: >
                                Show links to private forums (forums on private content items) to all visitors
                category:
                    plugin_setting:
                        name: category
                    label: 'Category:'
                    pick_items:
                        path: zenario__library/panels/categories
                        target_path: zenario__library/panels/categories
                        min_path: zenario__library/panels/categories
                        max_path: zenario__library/panels/categories
                        disallow_refiners_looping_on_min_path: Yes
                        one_to_one_choose_phrase: Choose category
                        select_phrase: Select a category...
                        nothing_selected_phrase: Show all forums of all categories
                        hide_remove_button: No
                    value: ""
        overall_list:
            label: Overall list
            fields:
                options:
                    type: grouping
                pinned_content_items:
                    plugin_setting:
                        name: pinned_content_items
                    type: select
                    label: "Pinned content items:"
                    value: prioritise_pinned
                    values:
                        prioritise_pinned:
                            ord: 1
                            label: 'Show pinned items first'
                        only_show_pinned:
                            ord: 2
                            label: 'Show only pinned items'
                        ignore_pinned:
                            ord: 3
                            label: 'Don\'t give priority'
                    redraw_onchange: true
                show_pinned_icon:
                    plugin_setting:
                        name: show_pinned_icon
                    indent: 1
                    type: select
                    label: 'Show a "pinned" icon:'
                    value: to_admins_and_visitors
                    values:
                        to_admins_and_visitors:
                            ord: 1
                            label: 'Show a "pinned" icon'
                        to_admins_only:
                            ord: 2
                            label: 'Show a "pinned" icon to administrators only'
                        do_not_show:
                            ord: 3
                            label: 'Don\'t show an icon'
                    visible_if: lib.value('pinned_content_items') != 'ignore_pinned'
                show_pinned_text:
                    plugin_setting:
                        name: show_pinned_text
                    indent: 1
                    type: select
                    label: 'Show "pinned" text:'
                    value: to_admins_and_visitors
                    values:
                        to_admins_and_visitors:
                            ord: 1
                            label: 'Show text'
                        to_admins_only:
                            ord: 2
                            label: 'Show text to administrators only'
                        do_not_show:
                            ord: 3
                            label: 'Don\'t show any text'
                    visible_if: lib.value('pinned_content_items') != 'ignore_pinned'
                    redraw_onchange: true
                pinned_text:
                    plugin_setting:
                        name: pinned_text
                    hide_with_previous_outdented_field: true
                    type: text
                    show_phrase_icon: true
                    indent: 2
                    label: '"Pinned" text:'
                    value: "Pinned"
                    visible_if: lib.value('show_pinned_text') != 'do_not_show'
                    validation:
                        required_if_not_hidden: 'Please enter the "pinned" text'
        each_item:
            label: Each Forum
            fields:
                data_field:
                    plugin_setting:
                        name: data_field
                    label: 'Show summary from:'
                    type: select
                    value: none
                    values:
                        none:
                            label: Do not show a summary
                        content_summary:
                            label: "Item's summary"
                        description:
                            label: "Item's meta description"
                show_featured_image:
                    plugin_setting:
                        name: show_featured_image
                    label: "Show featured image of content item"
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                canvas:
                    plugin_setting:
                        name: canvas
                    label: 'Image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                retina:
                    plugin_setting:
                        name: retina
                    label: 'Treat as a retina image'
                    type: checkbox
                    value: ""
                    side_note: |
                        Display image at double density.
                    enable_microtemplates_in_properties: true
                    same_row: true
                width:
                    plugin_setting:
                        name: width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: "100"
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                height:
                    plugin_setting:
                        name: height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: "100"
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                webp:
                    indent: 1
                    hide_with_previous_outdented_field: true
                    plugin_setting:
                        name: webp
                    type: checkbox
                    label: 'Show WebP-format image where browser supports it; recommended for smaller file size'
                    value: 1
                date_format:
                    plugin_setting:
                        name: date_format
                    label: 'Date format:'
                    type: select
                    value: _LONG
                    values:
                        _SHORT:
                            label: Short
                        _MEDIUM:
                            label: Medium
                        _LONG:
                            label: Long
    module_class_name: zenario_forum_list
