# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Display
            fields:
                next_prev_buttons_loop:
                    ord: "0.1"
                    plugin_setting:
                        name: next_prev_buttons_loop
                    label: 'Loop next/previous buttons:'
                    type: checkbox
                    value: ""
                    note_below: |
                        I.e. pressing the Next button on the last tab goes to the first tab.
                                                    Only applies to Frameworks with Next/Previous buttons.
        size:
            label: Size
            fields:
                set_max_height:
                    ord: "0.1"
                    plugin_setting:
                        name: set_max_height
                    label: 'Set a Maximum Height for Tabs in a Tabbed Nest:'
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                max_height:
                    ord: "0.2"
                    plugin_setting:
                        name: max_height
                    label: 'Maximum Height:'
                    type: text
                    maxlength: "50"
                    value: 400px
                    note_below: >
                        This setting will only apply to Nests which use multiple
                        Tabs.
    module_class_name: zenario_plugin_nest_probusiness
