zenario__administration:
	panels:
		site_settings:
			items:
				#	The new item to add, which will form the Settings Group. We should
				#	prefix it with our Module name to help avoid any name-clashes.
				zenario_user_forms__site_settings_group:
					name: Forms
					desc: Settings for forms.