# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_advanced_search
    tabs:
        first_tab:
            ord: "1"
            label: Display
            fields:
                show_initial_results:
                    plugin_setting:
                        name: show_initial_results
                    label: 'Show initial result list'
                    type: checkbox
                    value: "1"
                    side_note: >
                        When the plugin is viewed without any filter options, show the unfiltered results.
                show_language_next_to_results:
                    plugin_setting:
                        name: show_language_next_to_results
                    label: 'Show language next to content items'
                    type: checkbox
                    value: '1'
                    site_note: >
                        Display the language of a content item next to each result.
                show_private_items:
                    plugin_setting:
                        name: show_private_items
                    label: 'Show private items'
                    type: checkbox
                    value: "1"
                    format_onchange: Yes
                hide_private_items:
                    plugin_setting:
                        name: hide_private_items
                    label: 'Private items:'
                    type: select
                    value: "1"
                    values:
                        1:
                            ord: "1"
                            label: >
                                Only show links to private content items to authorized
                                visitors
                        0:
                            ord: "2"
                            label: Show links to private content items to all visitors
                    indent: 1
                data_field:
                    plugin_setting:
                        name: data_field
                    label: 'Show summary from:'
                    type: select
                    value: content_summary
                    values:
                        none:
                            ord: "1"
                            label: Do not show a summary
                        content_summary:
                            ord: "2"
                            label: "Item's summary"
                        description:
                            ord: "3"
                            label: "Item's description"
                use_pagination:
                    plugin_setting:
                        name: use_pagination
                    label: 'Paginate'
                    type: checkbox
                    value: "1"
                pagination_style:
                    plugin_setting:
                        name: pagination_style
                    label: 'Pagination style:'
                    type: select
                    value: zenario_common_features::pagCloseWithNPIfNeeded
                page_size:
                    plugin_setting:
                        name: page_size
                    label: 'Page size:'
                    type: text
                    validation:
                        numeric: Please enter a number for the Page Size.
                    value: "5"
                enable_categories:
                    plugin_setting:
                        name: enable_categories
                    label: 'Enable searching by categories'
                    type: checkbox
                    value: ""
                    side_note: >
                        Categories containing matching content items will be
                        displayed to the visitor so that he may refine his search.

                show_default_stick_image:
                    plugin_setting:
                        name: show_default_stick_image
                    label: 'Show image'
                    type: checkbox
                    value: ""
                    format_onchange: Yes
                    
                sticky_image_show:
                    plugin_setting:
                        name: sticky_image_show
                    label: 'Show sticky image'
                    type: checkbox
                    value: ""
                    side_note: Display the content item's sticky image if available.
                    format_onchange: Yes
                    indent: 1
                sticky_image_canvas:
                    plugin_setting:
                        name: sticky_image_canvas
                    label: 'Sticky image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                    indent: 2
                sticky_image_width:
                    plugin_setting:
                        name: sticky_image_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width for listing photo.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 3
                sticky_image_height:
                    plugin_setting:
                        name: sticky_image_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height for listing photo.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 3
                keyboard_delay_before_submit:
                    plugin_setting:
                        name: keyboard_delay_before_submit
                    label: 'Wait before submit (ms):'
                    type: text
                    value: 500
                    maxlength: 5
                    style: 'width: 5em;'
                    validation:
                        required_if_not_hidden: Please enter the number of miliseconds to wait before send the request.
                        numeric: The number of miliseconds to wait must be a number.
                    side_note: |
                       When the user type words to search wait the above amount of miliseconds before send the request. Default 500 ms.
                    
        content_types:
            ord: "2"
            label: Content items to search
            fields:
                search_html:
                    plugin_setting:
                        name: search_html
                    label: 'HTML page'
                    type: checkbox
                    value: "1"
                search_document:
                    plugin_setting:
                        name: search_document
                    label: 'Document / File'
                    type: checkbox
                    value: "1"
                search_news:
                    plugin_setting:
                        name: search_news
                    label: 'News item'
                    type: checkbox
                    value: "1"
        weightings:
            ord: "3"
            label: Weightings
            fields:
                alias_weighting:
                    plugin_setting:
                        name: alias_weighting
                    label: 'Alias weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _LOW
                title_weighting:
                    plugin_setting:
                        name: title_weighting
                    label: 'Title weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _HIGH
                keywords_weighting:
                    plugin_setting:
                        name: keywords_weighting
                    label: 'Keywords weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _MEDIUM
                description_weighting:
                    plugin_setting:
                        name: description_weighting
                    label: 'Description weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _LOW
                content_summary_weighting:
                    plugin_setting:
                        name: content_summary_weighting
                    label: 'Content Summary weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _LOW
                content_weighting:
                    plugin_setting:
                        name: content_weighting
                    label: 'Content weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _LOW
                filename_weighting:
                    plugin_setting:
                        name: filename_weighting
                    label: 'Filename weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _LOW
                extract_weighting:
                    plugin_setting:
                        name: extract_weighting
                    label: 'File extract weighting:'
                    type: radios
                    values:
                        _NONE:
                            label: None
                        _LOW:
                            label: Low
                        _MEDIUM:
                            label: Medium
                        _HIGH:
                            label: High
                    value: _LOW
