# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Content
            fields:
                html:
                    plugin_setting:
                        name: html
                        is_searchable_content: true
                        translate: true
                        save_value_when_hidden: true
                    label: 'Display this HTML:'
                    type: editor
                    dont_trim: true
                    style: 'width: 750px; height: 250px;'
                    insert_image_button:
                        pick_items:
                            path: ""
                            target_path: zenario__content/panels/image_library
                            min_path: zenario__content/panels/image_library
                            max_path: zenario__content/panels/image_library
                            disallow_refiners_looping_on_min_path: true
                    value: ""
    module_class_name: zenario_wysiwyg_editor
