plugin_settings:
    module_class_name: zenario_slideshow_2
    max_height: 650
    tabs:
        first_tab:
            label: Display
            fields:
                heading:
                    plugin_setting:
                        name: heading
                    label: 'Heading:'
                    type: text
                    maxlength: 255
                    
                banner_canvas:
                    plugin_setting:
                        name: banner_canvas
                    label: 'Size constraint:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: 5
                            label: Resize and crop
                    format_onchange: true
                    
                banner_width:
                    plugin_setting:
                        name: banner_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em; text-align: right'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                banner_height:
                    plugin_setting:
                        name: banner_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em; text-align: right'
                    post_field_html: '&nbsp;pixels'
                    indent: 1
                slide_duration:
                    plugin_setting:
                        name: slide_duration
                    label: 'Slide duration:'
                    type: text
                    validation:
                        numeric: The animation duration must be a number.
                    style: 'width: 5em; text-align: right'
                    value: 4000
                    post_field_html: ms
                
                fx:
                    plugin_setting:
                        name: fx
                    label: 'Effect for Transitions:'
                    type: select
                    values:
                        _fade:
                            label: 'Fade'
                        _slide_right:
                            label: 'Slide right'
                        _switch:
                            label: 'Switch'
                        _doors:
                            label: 'Doors'
                        _rotate_up:
                            label: 'Rotate up'
                        _vertical_split_slide:
                            label: 'Vertical split slide'
                        _bars_replace:
                            label: 'Bars replace'
                        _squares_wind:
                            label: 'Squares wind'
                        _squares_expand_random:
                            label: 'Squares expand random'
                        _bounce_down:
                            label: 'Bounce down'
                    value: _fade
                    format_onchange: true
                    
                navigation_style:
                    plugin_setting:
                        name: navigation_style
                    label: Navigation style
                    type: select
                    values:
                        none:
                            label: None
                        thumbnail_navigator:
                            label: Tabs
                        bullet_navigator:
                            label: Bullets
                    value: bullet_navigator
                            
                arrow_buttons:
                    plugin_setting:
                        name: arrow_buttons
                    label: Show arrow buttons
                    type: checkbox
                    value: 1
                    side_note: Display arrow buttons to manually navigate the slideshow.
                    
                auto_play:
                    plugin_setting:
                        name: auto_play
                    label: Auto play
                    type: checkbox
                    value: 1
                    side_note: The slideshow will automatically move from slide to slide, rather than the visitor having to manually switch slides.
                    
                enable_swipe:
                    plugin_setting:
                        name: enable_swipe
                    label: Enable swipe
                    type: checkbox
                    value: 0
                    side_note: Visitors can swipe from slide to slide by swiping with their finger on a touch screen or dragging with their mouse.
                
                hover_to_pause:
                    plugin_setting:
                        name: hover_to_pause
                    label: Hover to pause
                    type: checkbox
                    value: 0
                    side_note: The slideshow will pause when a visitor hovers over it with their mouse.
        mobile:
            label: 'Mobile'
            fields:
                desc:
                    snippet:
                        html: These settings define what happens when the slideshow goes into mobile mode
                mobile_options:
                    plugin_setting:
                        name: mobile_options
                    type: radios
                    values:
                        none:
                            label: No mobile mode
                            ord: 1
                        desktop_fixed: 
                            label: Use the desktop slide image resized at a fixed size
                            ord: 2
                        desktop_resize:
                            label: Use the desktop slide image and resize with the browser window
                            ord: 3
                        seperate_fixed:
                            label: Use a separate set of images at a fixed size (set in "Choose slideshow images" option slide-by-slide on mobile tab)
                            ord: 4
                    value: none
                    format_onchange: true
                mobile_canvas:
                    plugin_setting:
                        name: mobile_canvas
                    label: 'Image canvas'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: 1
                            label: Unlimited size
                        fixed_width:
                            ord: 2
                            label: Constrain by width
                        fixed_height:
                            ord: 3
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: 4
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: 5
                            label: Resize and crop
                    format_onchange: true
                    indent: 1
                mobile_width:
                    plugin_setting:
                        name: mobile_width
                    label: 'Width'
                    type: text
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                mobile_height:
                    plugin_setting:
                        name: mobile_height
                    label: 'Height'
                    type: text
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                desktop_resize_greater_than_image:
                    plugin_setting: 
                        name: desktop_resize_greater_than_image
                    label: Allow the image to be resized greater than its original size
                    type: checkbox
                    indent: 1