plugin_settings:
    module_class_name: zenario_slideshow_2
    max_height: 650
    tabs:
        first_tab:
            label: Display
            fields:
                banner_canvas:
                    plugin_setting:
                        name: banner_canvas
                    label: 'Size constraint:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: Yes
                    
                banner_width:
                    plugin_setting:
                        name: banner_width
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em; text-align: right'
                    post_field_html: '&nbsp;pixels'
                    
                banner_height:
                    plugin_setting:
                        name: banner_height
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em; text-align: right'
                    post_field_html: '&nbsp;pixels'
                    
                offset:
                    plugin_setting:
                        name: offset
                    label: 'Offset'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: Yes
                        style: 'width: 200px;'
                    note_below: |
                        Moving the slider to the left will move the image left or down;
                                                    moving the slider to the right will move the image right or up.
                    
                slide_duration:
                    plugin_setting:
                        name: slide_duration
                    label: 'Slide duration:'
                    type: text
                    validation:
                        numeric: The animation duration must be a number.
                    style: 'width: 5em; text-align: right'
                    value: 4000
                    post_field_html: ms
                
                fx:
                    plugin_setting:
                        name: fx
                    label: 'Effect for Transitions:'
                    type: select
                    values:
                        _fade:
                            label: 'Fade'
                        _slide_right:
                            label: 'Slide right'
                        _switch:
                            label: 'Switch'
                        _doors:
                            label: 'Doors'
                        _rotate_up:
                            label: 'Rotate up'
                        _vertical_split_slide:
                            label: 'Vertical split slide'
                        _bars_replace:
                            label: 'Bars replace'
                        _squares_wind:
                            label: 'Squares wind'
                        _squares_expand_random:
                            label: 'Squares expand random'
                        _bounce_down:
                            label: 'Bounce down'
                    value: _fade
                    format_onchange: Yes
                    
                navigation_style:
                    plugin_setting:
                        name: navigation_style
                    label: Navigation style
                    type: select
                    values:
                        none:
                            label: None
                        thumbnail_navigator:
                            label: Tabs
                        bullet_navigator:
                            label: Bullets
                    value: bullet_navigator
                            
                arrow_buttons:
                    plugin_setting:
                        name: arrow_buttons
                    label: Arrow buttons
                    type: checkbox
                    value: "1"
                    
                auto_play:
                    plugin_setting:
                        name: auto_play
                    label: Auto play
                    type: checkbox
                    value: "1"
                    
                enable_swipe:
                    plugin_setting:
                        name: enable_swipe
                    label: Enable swipe
                    type: checkbox
                    value: ""
                
                hover_to_pause:
                    plugin_setting:
                        name: hover_to_pause
                    label: Hover to pause
                    type: checkbox
                    value: ""
                    