# You must use a tab-size of 4 spaces to edit this file.
---
zenario_admin:
    tabs:
        settings:
            edit_mode:
                priv: _PRIV_EDIT_ADMIN
                enabled: true
            notices:
                is_trashed:
                    show: false
                    type: warning
                    message: This administrator account is trashed and they cannot log in.
            label: Settings
            fields:
                #description:
                #    full_width: true
                #    snippet:
                #        html: >
                #            Use this screen to change how this Admin uses Zenario.
                show_help_tour_next_time:
                    admin_setting:
                        name: show_help_tour_next_time
                    type: checkbox
                    value: 0
                    disabled: true
                    label: Show this administrator the help tour when they next open Organizer
                show_dev_tools:
                    admin_setting:
                        name: show_dev_tools
                    type: checkbox
                    value: ''
                    label: Allow this administrator to view the developer tools
                    redraw_onchange: true
                cli_sftp_connection:
                    admin_setting:
                        name: cli_sftp_connection
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    type: text
                    value: ''
                    label: SFTP connection string for editor
                    validation:
                        ascii_only: Please don't enter special characters
                    note_below: |
                        E.g. <code>sftp://username@server.com/</code>. Or leave this field blank to use localhost.
                        <br/>This is used when displaying help text, and is for reference only.
