# You must use a tab-size of 4 spaces to edit this file.
---
zenario_admin:
    tabs:
        settings:
            edit_mode:
                priv: _PRIV_EDIT_ADMIN
                enabled: true
                always_on: true
            notices:
                is_trashed:
                    show: false
                    type: warning
                    message: This administrator is trashed and cannot log in.
            label: Settings
            fields:
                #description:
                #    full_width: true
                #    snippet:
                #        html: >
                #            Use this screen to change how this Admin uses Zenario.
                show_help_tour_next_time:
                    admin_setting:
                        name: show_help_tour_next_time
                    type: checkbox
                    value: 1
                    label: Show this administrator the help tour when they next open Organizer
                show_dev_tools:
                    admin_setting:
                        name: show_dev_tools
                    type: checkbox
                    value: ''
                    label: Allow this administrator to view the developer tools