# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    css_class: zenario_fab_plugin 
    key:
        id: ''
        frontEnd: ''
        skinId: false
        languageId: ''
        cID: ''
        cType: ''
        cVersion: ''
        slotName: ''
        isVersionControlled: ''
        instanceId: ''
        slideNum: ''
        eggId: ''
        moduleId: ''
        moduleClassName: ''
        moduleClassNameForPhrases: ''
        isFEA: false
        usesConductor: false
        framework: ''
        mode: ''
        lastMode: ''
        lastTuixSnippet: -1
    identifier:
        css_class: plugin_album_instance
        label: ''
        value: ''
    missing_items_warning: 'ID [[items]] missing, save settings to clean up.'
    tab: first_tab
    tabs:
        first_tab:
            label: Details
            fields:
                plugin_name:
                    type: grouping
                instance_name:
                    grouping: plugin_name
                    label: '~Plugin~ name:'
                    type: text
                    redraw_onchange: true
                    redraw_immediately_onchange: true
                duplicate_or_rename:
                    grouping: plugin_name
                    indent: 1
                    visible_if: |
                        tuix.key.instanceId &&
                        tuix.tabs.first_tab.fields.instance_name.current_value != undefined &&
                        tuix.tabs.first_tab.fields.instance_name.current_value != tuix.tabs.first_tab.fields.instance_name.value
                    type: radios
                    cols: 2
                    value: rename
                    values:
                        rename:
                            label: Rename
                        replace:
                            label: Save as new ~plugin~ and place here
                        duplicate:
                            label: Save as new ~plugin~ in library
        
        'phrases.framework':
            hidden: true
            label: Phrases
            ord: 100001
            fields: {}
        
        advanced_dropdown:
            ord: 100002
            label: CSS/framework
            hide_when_children_are_not_visible: true
        
        tuix_snippet:
            ord: 100003
            label: TUIX Snippet
            visible_if: |
                tuix.key.isFEA
            fields:
                desc:
                    snippet:
                        html: |
                            You can use TUIX Snippets to add visual elements (e.g. columns or buttons) or to customise existing ones, in this plugin.
                            Pick a TUIX Snippet to include.
                '~tuix_snippet~':
                    plugin_setting:
                        name: '~tuix_snippet~'
                    type: select
                    empty_value: ' -- None -- '
                    values: {}
                    format_onchange: true
                desc2:
                    indent: 1
                    snippet:
                        html: ''
                '~custom_yaml~':
                    type: code_editor
                    language: yaml
                    tall_as_possible: true
                    readonly: true
                desc3:
                    snippet:
                        html: |
                            This tab appears because is an FEA-type plugin or plugin mode
                            (i.e. its module contains a <code>tuix/visitor/</code> directory).
        
        last_tab:
            label: Help
            ord: 100009
            fields:
                module_description:
                    label: 'Module description:'
                    ord: 1
                    snippet:
                        html: {}
    confirm:
        show: No
        message: |
            You are editing a content item that's published.
                            
            Zenario will make a version in draft form for you to work on privately. Visitors won't see any changes until the new version is published.
        button_message: Create a draft
        cancel_button_message: Cancel
        message_type: warning
