# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    css_class: zab_plugin 
    key:
        id: ""
        instanceId: ""
        isVersionControlled: ""
        cID: ""
        cType: ""
        cVersion: ""
        slotName: ""
        languageId: ""
        nest: ""
        moduleId: ""
        frontEnd: ""
    tabs:
        first_tab:
            label: Details
            fields:
                instance_name:
                    label: 'Plugin name:'
                    type: text
    confirm:
        show: No
        message: |
            You are editing a Published Content Item.
                            
                            The CMS will make an identical Draft version for you to work on privately. Visitors will only see your changes when you Publish the new version.
        button_message: Create a Draft
        cancel_button_message: Cancel
        message_type: warning
