# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: categories
    title: Editing category settings
    tabs:
        categories:
            label: Categories
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                enable_display_categories_on_content_lists:
                    site_setting:
                        name: enable_display_categories_on_content_lists
                    label: 'Enable display of categories on content summary lists'
                    type: checkbox
                    value: ""
                    side_note: |
                        When enabled, a content item's lowest level public category can be displayed in content summary lists with a link to the landing page if one exists.