# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing settings for admin passwords
    key:
        current_password_min_score_value: 0
    setting_group: admin_passwords
    hide_tab_bar: true
    tabs:
        passwords:
            label: Passwords
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                password_requirements:
                    type: grouping
                    snippet:
                        label: "Admin password requirements"
                        label_class: subheading
                zenario_extranet:
                    type: grouping
                min_admin_password_score:
                    label: 'Minimum score:'
                    grouping: password_requirements
                    site_setting:
                        name: min_admin_password_score
                    type: text
                    value: 3
                    style: 'width: 50px;'
                    slider:
                        range: min
                        min: 1
                        max: 4
                        before_field: true
                        uses_colour_bands: true
                    validation:
                        numeric: true
                    format_onchange: true
                admin_password_score_info:
                    grouping: password_requirements
                    snippet:
                        html: |
                            <div class="zenario_fbInfo">
                                Password score:<br />
                                4: Very strong password, very unguessable and provides strong protection from offline slow-hash scenario.<br />
                                3: Strong password, safely unguessable, offers moderate protection from offline slow-hash scenario.<br />
                                2: Moderate password, somewhat guessable, provides some protection from unthrottled online attacks.<br />
                                1: Weak password, very guessable.<br />
                            </div>
                min_admin_password_length:
                    label: 'Minimum length (between 10 and 32 characters):'
                    grouping: password_requirements
                    site_setting:
                        name: min_admin_password_length
                    type: text
                    style: "width:50px;"
                    value: 10
                    validation:
                        numeric: true
                    # The <br /> tags above are required, as Extranet Base module adds its own field
                    # with pre- and post-field HTML, which blends with the snippet above.
                admin_password_creation_info:
                    grouping: password_requirements
                    snippet:
                        html: |
                            <div class="zenario_fbInfo">
                                When setting an admin password, Zenario will only accept a password if it is greater or equal to the minimum length and passes the selected score.
                            </div>