# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: cookies
    title: Editing cookie settings
    hide_tab_bar: false
    tabs:
        cookies:
            label: Cookie Policy
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>You can control when this site can place cookies on a visitor's browser.</p>
                            <p>Zenario can display simple "Continue" button (implied cookie consent), or a sequence of two popup boxes (where explicit consent is asked for, with one small box with summary info, and one large box with more detail about the types of cookies). The large box can be accessed again via the Footer menu.</p>
                cookie_require_consent:
                    site_setting:
                        name: cookie_require_consent
                    type: select
                    value: ""
                    label: 'Cookie policy:'
                    empty_value: "Don't inform visitor or require consent when setting cookies"
                    values:
                        implied:
                            ord: "1"
                            label: 'Implied consent: inform visitor that cookies are being set'
                        explicit:
                            ord: "2"
                            label: "Explicit consent: require visitor's consent before setting cookies"
                    redraw_onchange: true
                
                description__dont_inform:
                    snippet:
                        html: |
                            <p>
                                Modules that set cookies may do so irrespective of the visitor's action.
                            </p>
                    visible_if: |
                        !zenarioAB.value('cookie_require_consent')
                cookie_consent_type_implied:
                    label: 'Message for visitor:'
                    type: select
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'implied'
                    indent: 1
                    values:
                        message_continue: A consent message with a "Continue" button
                    redraw_onchange: true
                description__implied:
                    snippet:
                        html: |
                            <p>
                                A panel will appear on every page of your site, but only on the visitor's
                                first page load. On subsequent page loads or visits, the panel does not appear.
                            </p><p>
                                Modules that set cookies may do so irrespective of the visitor's action.
                            </p>
                    visible_if: "zenarioAB.value('cookie_require_consent') == 'implied'"
                    indent: 1
                description__explicit__message_accept_reject:
                    snippet:
                        html: |
                            <p>
                                A panel will appear on every page of your site, until the visitor presses either
                                the &quot;Accept&quot; or &quot;Manage cookies&quot; button.
                            </p><p>
                                Modules will not set cookies until the visitor presses the &quot;Accept&quot; button.
                                (A PHP session cookie will be placed on the visitor's computer regardless of this setting.)
                            </p>
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    indent: 1
                _COOKIE_BOX1_01_IMPLIED_MSG:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'implied'
                    label: Message
                    type: editor
                    insert_link_button: true
                    validation:
                        required_if_not_hidden: Please enter a message
                    note_below: 'The CSS class will be "cookies_implied".'
                _COOKIE_BOX1_02_CONTINUE_BTN:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'implied'
                    label: '"Continue" button text'
                    type: text
                    show_phrase_icon: true
                    validation:
                        required_if_not_hidden: true
                
                _COOKIE_BOX1_03_COOKIE_CONSENT_MSG:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: |
                        Initial message:
                    type: editor
                    insert_link_button: true
                    validation:
                        required_if_not_hidden: Please enter a message
                    note_below: 'The CSS class will be "cookies_explicit".'
                _COOKIE_BOX1_05_ACCEPT_BTN:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: |
                        Text for "Accept cookies" button:
                    note_below: |
                        If the visitor clicks this button, they agree to accept all cookies without seeing further information.
                    type: text
                    show_phrase_icon: true
                    validation:
                        required_if_not_hidden: true
                _COOKIE_BOX1_04_MANAGE_BTN:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: |
                        Text for "Manage cookies" button:
                    note_below: |
                        If the user clicks this button, they will see a "Manage cookies" popup box. They will be able to access this again later, usually via the Footer menu.
                    type: text
                    show_phrase_icon: true
                    validation:
                        required_if_not_hidden: true
                _COOKIE_BOX2_01_INTRO_MSG:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: |
                        Message in the large "Manage cookies" popup box:
                    type: editor
                    insert_link_button: true
                    validation:
                        required_if_not_hidden: Please enter a message
                _COOKIE_BOX2_02_ACCEPT_ALL_BTN:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: |
                        Text for "Accept all cookies" button:
                    note_below: |
                        In the large popup box, the text for the "Accept all cookies" button.
                    type: text
                    show_phrase_icon: true
                    validation:
                        required_if_not_hidden: true
                _COOKIE_BOX2_11_SAVE_PREFERENCES_BTN:
                    indent: 1
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: |
                        Text for "Save preferences" button:
                    note_below: |
                        In the large popup box, the text for the "Save preferences" button.
                    type: text
                    show_phrase_icon: true
                    validation:
                        required_if_not_hidden: true
                phrases_panel_link:
                    snippet:
                        html: '<div class="zenario_fbInfo">To edit further cookie-related phrases, go to <a href="organizer.php#zenario__languages/panels/phrases~-cookie" target="blank">Organizer's Phrases</a> panel.</div>'
                    visible_if: zenarioAB.value('cookie_require_consent') == 'explicit'
                popup_cookie_type_switches_initial_state:
                    indent: 1
                    site_setting:
                        name: popup_cookie_type_switches_initial_state
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit'
                    label: 'In popup message, cookie-type switches should appear to new visitors in an initial state of:'
                    type: radios
                    value: "off"
                    values:
                        off:
                            ord: 1
                            label: "Off"
                        on:
                            ord: 2
                            label: "On"
                extranet_info:
                    snippet:
                        html: |
                            <div class="zenario_fbInfo">
                                Extranet plugins will only be loaded when a user accepts Functionality-type cookies.
                            </div>
                    visible_if: zenarioAB.value('cookie_require_consent') == 'explicit'
        
        cookie_timeouts:
            label: Timeouts
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                The length of time that the cookie consent, &quot;remember me&quot;
                                and &quot;Log me in automatically&quot; options last.
                            </p>
                
                zenario_siteconfig:
                    type: grouping
                    name: zenario_siteconfig
                
                cookie_timeout:
                    grouping: zenario_siteconfig
                    legend: Set in the <code>zenario_siteconfig.php</code> file
                    
                    label: 'Cookie timeout:'
                    pre_field_post_label_html: |
                        (<code>COOKIE_TIMEOUT</code>)
                    readonly: true
                    type: text