# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing settings for documents, files and images
    setting_group: files_and_images
    tabs:
        docstore_dir:
            label: Docstore
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                dir_2_blurb:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                You should create a directory on your server where Zenario can store documents.
                            </p><p>
                                Please create a directory on your server in which to keep these backups.
                                Enter an absolute path starting with a slash, but do not add a trailing slash.
                            </p>
                docstore_dir:
                    site_setting:
                        name: docstore_dir
                        protect_from_database_restore: true
                    label: 'Source document directory (Docstore):'
                    type: text
                    #onkeyup: zenarioAB.quickValidateWelcomePage(500);
                #docstore_dir_status:
                #    snippet:
                #        html: '&nbsp;'

        image_privacy:
            label: Image privacy
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab lets you control whether images on your site appear in search engines.
                default_image_privacy:
                    site_setting:
                        name: default_image_privacy
                    label: 'Default image privacy:'
                    type: radios
                    value: auto
                    values:
                        public:
                            label: Public
                            note_below: |
                                Can be viewed by any visitor via a constant URL, and will normally be indexed by search engines. (Shown in the Organizer Images panel with a green border.) Recommended if your site only has public web pages.
                        private:
                            label: Private
                            note_below: |
                                Can only be viewed by logged-in extranet users via private content items. Cannot be indexed by search engines. (Shown in Organizer Images panel with a blue border.) Recommended if your site has an extranet area, or you want to protect certain images from unauthorised viewing.
                        auto:
                            label: Auto
                            note_below: |
                                Images will have the Auto state when first uploaded, but will be set to Public if on a public content item, or Private if on a private content item. (Shown in the Organizer Images panel with an orange border, but this changes once the image changes to Public or Private.)
        image_sizes:
            label: Image thumbnails
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            When images are uploaded, Zenario will automatically create thumbnails for them.
                            <br/><br/>
                            When a plugin requests a thumbnail of an image, where possible Zenario will use the premade ones
                            instead of generating a new one on the fly. This reduces the load on your server and make your
                            web pages load more quickly for visitors.
                            <br/><br/>
                            You can use this tab to define up to three different thumbnails for each image.
                
                thumbnail_180x130_width: 
                    label: 'Thumbnail size (width × height):'
                    type: text
                    readonly: true
                    value: 180
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;&nbsp;×&nbsp;'
                thumbnail_180x130_height: 
                    same_row: true
                    type: text
                    readonly: true
                    value: 130
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    note_below: |
                        This thumbnail is used by Organizer and cannot be modified.
                
                custom_thumbnail_1:
                    label: 'Create a second thumbnail'
                    type: checkbox
                    redraw_onchange: true
                
                custom_thumbnail_1_width: 
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_1_width
                    label: 'Size (width × height):'
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;&nbsp;×&nbsp;'
                custom_thumbnail_1_height: 
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_1_height
                    same_row: true
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                
                custom_thumbnail_2:
                    indent: 1
                    label: 'Create a third thumbnail'
                    type: checkbox
                    redraw_onchange: true
                
                custom_thumbnail_2_width: 
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_2_width
                    label: 'Size (width × height):'
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;&nbsp;×&nbsp;'
                custom_thumbnail_2_height: 
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_2_height
                    same_row: true
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
        
        image_resizing:
            label: Image resizing (advanced)
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            To prevent artifacts in images, Zenario will only use a thumbnail when:
                            <ul>
                                <li>The size of the thumbnail exactly matches the requested size.</li>
                                <li>The thumbnail is large enough to be resized down to the requested size without any visible artifacts.</li>
                            </ul>
                            If you are seeing artifacts in your thumbnails, you can change when this happens:
                
                thumbnail_threshold:
                    site_setting:
                        name: thumbnail_threshold
                    pre_field_html: |
                    label: 'Allowable threshold for resizing down:'
                    post_field_html: '&nbsp;%'
                    type: text
                    value: 66
                    style: 'width: 3em;'
                    slider:
                        range: min
                        min: 50
                        max: 100
                        before_field: true
                    validation:
                        required_if_not_hidden: Please enter a percentage.
                        numeric: The percentage must be numeric.
                    note_below: |
                        It's usually safe to leave this set to the default value (66%).
                        However if you see artifacts on your thumbnail then try making it smaller.
                
                description2:
                    full_width: true
                    snippet:
                        html: |
                            <br/>
                            <br/>
                            When Zenario resizes a JPEG image to create a thumbnail, the new image is then recompressed.
                            This compresson algorithm can use a quality of between 0 and 100.
                
                jpeg_quality_limit:
                    site_setting:
                        name: jpeg_quality_limit
                    label: 'JPEG image quality used when resizing images:'
                    type: text
                    value: 99
                    style: 'width: 50px;'
                    slider:
                        range: min
                        min: 80
                        max: 100
                        before_field: true
                    note_below: |
                        The lower this number the smaller the filesize of the thumbnail will be, however if you set setting it
                        too low then you may see artifacts on your thumbnails for JPEG images.
        filesizes:
            label: File Upload Sizes
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for file uploads.
                content_max_filesize:
                    site_setting:
                        name: content_max_filesize
                    label: 'Maximum Content File Size:'
                    type: text
                    value: 20
                    note_below: >
                        This allows you to set a maximum allowed uploadable file
                        size (in bytes) for Pictures, Audio, Video, and other
                        Content Types.
                    validation:
                        required: Please enter a Maximum Content File Size.
                        numeric: The Maximum Content File Size must be numeric.
                    decimal_places: ""
                content_max_filesize_unit:
                    site_setting:
                        name: content_max_filesize_unit
                    label: 'Unit:'
                    same_row: true
                    type: select
                    values:
                        KB:
                            label: KB
                        MB:
                            label: MB
                        GB:
                            label: GB
                    value: MB
                    redraw_onchange: true
                    hide_if_empty: true
                apache_max_filesize:
                    label: 'Largest Possible Upload Size:'
                    type: text
                    show_as_a_span: true
                    note_below: |
                        This is the size of the largest file that can be uploaded to your server. Your server administrator can change this by changing the server's Apache Config (it is the lesser of post_max_size and upload_max_filesize as set in the php.ini file).
                max_allowed_packet:
                    label: 'MySQL max_packet_size:'
                    type: text
                    show_as_a_span: true
                    note_below: |
                        This is the size of the largest possible SQL query Zenario can send to your database.
                                                        Images, along with their thumbnails and their working copies, will be added to the database using one command,
                                                        so this puts a limit on the size of image that you can add to Zenario.
                                                        Your server administrator can change this by changing the <code>max_allowed_packet</code> setting
                                                        in the server's MySQL configuration.
        file_downloads:
            label: File Downloads
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for file downloads.
                restrict_downloads_by_ip:
                    site_setting:
                        name: restrict_downloads_by_ip
                    label: 'Restrict by IP:'
                    type: checkbox
                    value: 1
                    note_below: "Places a <code>.htaccess</code> file in the temporary document directory to allow access only from the client's IP address."
                 
                    
        document_tags:
            label: Document tags
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                enable_document_tags:
                    site_setting:
                        name: enable_document_tags
                    label: 'Enable document tags'
                    type: checkbox
                    value: true
