# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: administration
    title: Editing settings for site administration
    tabs:
        content_items:
            label: Content items
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for when working with content items.
                create_draft_warning:
                    site_setting:
                        name: create_draft_warning
                    label: 'Warn me when creating a draft'
                    type: checkbox
                    value: 1
                lock_item_upon_draft_creation:
                    site_setting:
                        name: lock_item_upon_draft_creation
                    label: 'Auto-lock drafts of content items'
                    type: checkbox
                    value: ""
                    note_below: |
                        If enabled, when an administrator creates a draft, it will be locked automatically by that administrator.
                                                    Locking prevents other administrators editing the draft until it the content item is published.
                auto_set_release_date:
                    site_setting:
                        name: auto_set_release_date
                    label: 'Automatically set release date:'
                    type: select
                    empty_value: Never
                    values:
                        on_publication_if_not_set:
                            label: Upon publication if no release date is set
        security:
            label: Security
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for security.
                new_admin_email_expiry:
                    site_setting:
                        name: new_admin_email_expiry
                    label: Expiry time for new admin notifications
                    type: select
                    values:
                        1:
                            label: 1 day
                        3:
                            label: 3 days
                        7:
                            label: 7 days
                    value: 7
                    side_note: When a new admin is created they are sent a link that they can use to access the site and set a password for their accounts. Choose how long it takes before this link expires.
                
                zenario_site_description:
                    type: grouping
                    name: zenario_site_description
                
                enable_two_factor_authentication_for_admin_logins:
                    legend: Set in the <code>zenario_custom/site_description.yaml</code> file
                    grouping: zenario_site_description
                    
                    label: Require two-factor authentication on login
                    type: checkbox
                    readonly: true
                    note_below: |
                        If enabled, an admin must verify access to their email when logging into the site.
                
                apply_two_factor_authentication_by_ip:
                    grouping: zenario_site_description
                    label: Apply two-factor authentication on a per-IP basis
                    type: checkbox
                    readonly: true
                    note_below: |
                        If enabled, an admin must verify access for each IP address they use to access the site.
                
                two_factor_authentication_timeout:
                    grouping: zenario_site_description
                    label: Timeout for two-factor authentication
                    type: text
                    readonly: true
                    style: |
                        width: 4em;
                    note_below: |
                        The length of time (in days) before an administrator
                        needs to verify access to their email again.
        #anti_spam:
        #    label: Anti-spam
        #    edit_mode:
        #        enabled: true
        #        always_on: true
        #    fields:
        #        anti_spam_tab_description:
        #            full_width: true
        #            snippet:
        #                html: This tab lets you enable features to control spam.
        #        use_honeypot:
        #            label: 'Use honeypot'
        #            type: checkbox
        #            format_onchange: true  
        #            side_note: |
        #                The form will contain a "honeypot" field. It is in the source of the page made invisible to human visitors using CSS. Because it's invisible, it will only normally be filled in by a "bot"; at the same time it's mandatory to leave it blank.
        #        honeypot_label:
        #            label: 'Honeypot field label:'
        #            type: text
        #            maxlength: 255
        #            indent: 1
        #        use_captcha:
        #            label: 'Require anonymous visitors to complete a captcha'
        #            type: checkbox
        #            format_onchange: true  
        #        captcha_type:
        #            label: 'Type of captcha:'
        #            type: select
        #            empty_value: '-- Select --'
        #            values:
        #            validation: 
        #                required_if_not_hidden: Please select a type of captcha.
        #            indent: 1
        #        extranet_users_use_captcha:
        #            label: 'Require extranet users to complete a captcha'
        #            type: checkbox
        #            indent: 1
        email_template:
            label: Admin email templates
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                notification_to_new_admin:
                    site_setting:
                        name: notification_to_new_admin
                    label: 'Email template for admin account creation:'
                    pick_items:
                        path: zenario__email_template_manager/panels/email_templates
                        target_path: zenario__email_template_manager/panels/email_templates
                        min_path: zenario__email_template_manager/panels/email_templates
                        max_path: zenario__email_template_manager/panels/email_templates
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No email template selected
                        select_phrase: Select an email template...
                        hide_remove_button: true
                    validation:
                        required_if_not_hidden: Please select an email template
                    value: zenario_common_features__notification_to_new_admin_no_password
                
                    
                    
