# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: administration
    title: Editing settings for site administration
    tabs:
        content_items:
            label: Content items
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for when working with content items.
                create_draft_warning:
                    site_setting:
                        name: create_draft_warning
                    label: 'Warn me when creating a draft'
                    type: checkbox
                    value: 1
                lock_item_upon_draft_creation:
                    site_setting:
                        name: lock_item_upon_draft_creation
                    label: 'Auto-lock drafts of content items'
                    type: checkbox
                    value: ""
                    note_below: |
                        If enabled, when an administrator creates a draft, it will be locked automatically by that administrator.
                                                    Locking prevents other administrators editing the draft until it the content item is published.
                auto_set_release_date:
                    site_setting:
                        name: auto_set_release_date
                    label: 'Automatically set release date:'
                    type: select
                    empty_value: Never
                    values:
                        on_publication_if_not_set:
                            label: Upon publication if no release date is set
        security:
            label: Security
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for administrator passwords and security.
                min_admin_password_strength:
                    site_setting:
                        name: min_admin_password_strength
                    label: Minimum admin password strength
                    type: select
                    value: _MEDIUM
                    values:
                        _WEAK:
                            label: Weak
                        _MEDIUM:
                            label: Medium
                        _STRONG:
                            label: Strong
                        _VERY_STRONG:
                            label: Very strong
                
                zenario_site_description:
                    type: grouping
                    name: zenario_site_description
                
                enable_two_factor_security_for_admin_logins:
                    legend: Set in the <code>zenario_custom/site_description.yaml</code> file
                    grouping: zenario_site_description
                    
                    label: Require security code on login
                    type: checkbox
                    read_only: true
                    note_below: |
                        If enabled, an admin must verify access to their email when logging into the site.
                
                apply_two_factor_security_by_ip:
                    grouping: zenario_site_description
                    label: Issue security codes on a per-IP basis
                    type: checkbox
                    read_only: true
                    note_below: |
                        If enabled, an admin must verify access for each IP address they use to access the site.
                
                two_factor_security_timeout:
                    grouping: zenario_site_description
                    label: Security codes timeout
                    type: text
                    read_only: true
                    style: |
                        width: 4em;
                    note_below: |
                        The length of time (in days) that this should last.
        
        
        email_template:
            label: Admin email templates
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                    html: This tab contain email templates.
                notification_to_new_admin:
                    site_setting:
                        name: notification_to_new_admin
                    label: 'Email template for admin account creation:'
                    pick_items:
                        path: zenario__email_template_manager/panels/email_templates
                        target_path: zenario__email_template_manager/panels/email_templates
                        min_path: zenario__email_template_manager/panels/email_templates
                        max_path: zenario__email_template_manager/panels/email_templates
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No email template selected
                        select_phrase: Select an email template...
                        hide_remove_button: true
                    validation:
                        required_if_not_hidden: Please select an email template
                    
                    value: zenario_common_features__notification_to_new_admin
                    
                    
