# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: administration
    title: Editing settings for site administration
    tabs:
        sk:
            label: Organizer
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: >
                            The settings below will affect the behaviour of Organizer
                            for all administrators.
                storekeeper_page_size:
                    site_setting:
                        name: storekeeper_page_size
                    label: 'Organizer page size:'
                    type: select
                    value: "50"
                    values:
                        20: "20"
                        50: "50"
                        100: "100"
                        200: "200"
                    side_note: |
                        The number of items to show per page.
                        (This is capped at 50 when using Internet Explorer 7 or earlier, due to speed issues with these browsers.)
                    validation:
                        required: Please enter the number of items to show per page.
                        numeric: The number of items per page must be numeric.
                
                #(Periodic refresh is now disabled)
                #storekeeper_periodic_refresh_mins:
                #    site_setting:
                #        name: storekeeper_periodic_refresh_mins
                #    label: 'Periodic Refresh Time:'
                #    type: text
                #    value: "2"
                #    note_below: How often to refresh the view of a Panel, in minutes.
                #    validation:
                #        required: Please enter a Refresh Time.
                #        numeric: The Refresh Time must be numeric.
        content_items:
            label: Content items
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: This tab contains settings for when working with content items.
                lock_item_upon_draft_creation:
                    site_setting:
                        name: lock_item_upon_draft_creation
                    label: 'Auto-lock drafts of content items'
                    type: checkbox
                    value: ""
                    note_below: |
                        If enabled, when an administrator creates a draft, it will be locked automatically by that administrator.
                                                    Locking prevents other administrators editing the draft until it the content item is published.
                auto_set_release_date:
                    site_setting:
                        name: auto_set_release_date
                    label: 'Automatically set release date:'
                    type: select
                    empty_value: Never
                    values:
                        on_publication_if_not_set:
                            label: Upon publication if no release date is set
        security:
            label: Security
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: This tab contains settings for administrator passwords and security.
                min_admin_password_strength:
                    site_setting:
                        name: min_admin_password_strength
                    label: 'Minimum admin password strength:'
                    type: select
                    value: _MEDIUM
                    values:
                        _WEAK: Weak
                        _MEDIUM: Medium
                        _STRONG: Strong
                        _VERY_STRONG: Very strong
        email_template:
            label: Admin email templates
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: Yes
                    snippet:
                    html: This tab contain email templates.
                notification_to_new_admin:
                    site_setting:
                        name: notification_to_new_admin
                    label: 'Email template:'
                    pick_items:
                        path: zenario__email_template_manager/nav/email_templates/panel
                        target_path: zenario__email_template_manager/nav/email_templates/panel
                        min_path: zenario__email_template_manager/nav/email_templates/panel
                        max_path: zenario__email_template_manager/nav/email_templates/panel
                        disallow_refiners_looping_on_min_path: Yes
                        nothing_selected_phrase: No email template selected
                        select_phrase: Select an email template...
                        hide_remove_button: Yes
                    
                    value: zenario_common_features__notification_to_new_admin
                    
                    
