# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Changing the Default Language
    tabs:
        default_language:
            label: Default Language
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: |
                            The default Language of your site.
                                                            This will be the language that visitors first see when coming to your site without a page requested.
                default_language:
                    site_setting:
                        name: default_language
                    label: 'Default Language:'
                    type: select
                    note_below: |
                        Changing your default Language may cause new Special Pages to be created. You should
                        <a href="organizer.php#zenario__content/panels/content/refiners/special_pages////" target="_blank">
                            review your Special Pages in Organizer</a>
                        after changing this value.
    setting_group: default_language
