# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing API keys
    setting_group: api_keys
    tabs:
        google_maps:
            label: Google Maps
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: This site can display a Google Map on a web page. To make it do so, please enter an API key in the box below.
                google_maps_api_key:
                    site_setting:
                        name: google_maps_api_key
                    label: 'Google Maps API key:'
                    type: text
                    note_below: You can obtain an API key <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">here</a>.
                google_maps_geocode_api_key:
                    site_setting:
                        name: google_maps_geocode_api_key
                    label: 'Google Maps Geocode API key:'
                    type: text
                    note_below: Geocode API key should only be used for Location Map and Listing module. For all other purposes, please use the regular API key (above).
        google_custom_search:
            label: Google Programmable Search
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: This site can display Google Programmable Search results on a web page. To make it do so, please enter an API key in the box below.
                google_custom_search_json_api_key:
                    site_setting:
                        name: google_custom_search_json_api_key
                    label: 'Google Programmable Search JSON API key:'
                    type: text
                    note_below: You can obtain an API key <a href="https://developers.google.com/custom-search/v1/overview" target="_blank">here</a>.
        dropbox:
            label: Dropbox
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: When choosing files to upload to Zenario (e.g. documents and images), you can choose to pick them from Dropbox. To enable this feature, you will need an API Key from Dropbox entered into the field below.
                dropbox_api_key:
                    site_setting:
                        name: dropbox_api_key
                    label: 'Dropbox API Key:'
                    type: text
                    note_below: |
                        An application key that can use the Dropbox API.
                                                        You can obtain a key at
                                                        <a href="https://www.dropbox.com/developers/apps" target="_blank">
                                                            https://www.dropbox.com/developers/apps
                                                        </a>.