# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: cookies
    title: Editing cookie settings
    hide_tab_bar: false
    tabs:
        cookies:
            label: Cookie Policy
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                This tab allows you to control when your site's Modules can place cookies on a visitor's computer.
                            </p>
                cookie_require_consent:
                    site_setting:
                        name: cookie_require_consent
                    type: select
                    value: ""
                    label: 'Policy:'
                    empty_value: "Don't inform visitor or require consent when setting cookies"
                    values:
                        implied:
                            ord: "1"
                            label: 'Implied consent: inform visitor that cookies are being set'
                        explicit:
                            ord: "2"
                            label: "Explicit consent: require visitor's consent before setting cookies"
                    redraw_onchange: Yes
                description__dont_inform:
                    ord: "90"
                    snippet:
                        html: |
                            <p>
                                Modules that set cookies may do so irrespective of the visitor's action.
                            </p>
                    visible_if: |
                        !zenarioAB.value('cookie_require_consent')
                cookie_consent_type_implied:
                    label: 'Message for visitor:'
                    type: select
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'implied'
                    values:
                        message_continue: A consent message with a "Continue" button
                    redraw_onchange: Yes
                description__implied:
                    ord: "91"
                    snippet:
                        html: |
                            <p>
                                A panel will appear on every page of your site, but only on the visitor's
                                first page load. On subsequent page loads or visits, the panel does not appear.
                            </p><p>
                                Modules that set cookies may do so irrespective of the visitor's action.
                            </p>
                    visible_if: "zenarioAB.value('cookie_require_consent') == 'implied'"
                cookie_consent_type__explicit:
                    site_setting:
                        name: cookie_consent_type
                    label: 'Message for visitor:'
                    type: select
                    visible_if: "zenarioAB.value('cookie_require_consent') == 'explicit'"
                    values:
                        message_accept: A consent message with an "Accept" button
                        message_accept_reject: >
                            A consent message with an "Accept" button and a "Reject"
                            button
                    redraw_onchange: Yes
                description__explicit__message_accept:
                    ord: "92"
                    snippet:
                        html: |
                            <p>
                                A panel will appear on every page of your site, until the visitor presses
                                the &quot;Accept&quot; button.
                            </p><p>
                                Modules will not set cookies until the visitor presses the &quot;Accept&quot; button.
                                (A PHP session cookie will be placed on the visitor's computer regardless of this setting.)
                            </p><p>
                                HTML Snippet Plugins, HEAD Snippet Plugins, Head Slots and Foot Slots
                                gain a new setting, in their floating admin box panels.
                                Their new setting allows you to declare that the code you have entered for that Plugin or Slot can place
                                a cookie on a visitor's machine.
                                You should review the HTML Snippet Plugins, HEAD Snippet Plugins, Head Slots and Foot Slots
                                on your site and enable this option where appropriate.
                            </p>
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit' &&
                        zenarioAB.value('cookie_consent_type__explicit') != 'message_accept_reject'
                description__explicit__message_accept_reject:
                    ord: "93"
                    snippet:
                        html: |
                            <p>
                                A panel will appear on every page of your site, until the visitor presses either
                                the &quot;Accept&quot; or &quot;Reject&quot; button.
                            </p><p>
                                Modules will not set cookies until the visitor presses the &quot;Accept&quot; button.
                                (A PHP session cookie will be placed on the visitor's computer regardless of this setting.)
                            </p><p>
                                HTML Snippet Plugins, HEAD Snippet Plugins, Head Slots and Foot Slots
                                gain a new setting, in their floating admin box panels.
                                Their new setting allows you to declare that the code you have entered for that Plugin or Slot can place
                                a cookie on a visitor's machine.
                                You should review the HTML Snippet Plugins, HEAD Snippet Plugins, Head Slots and Foot Slots
                                on your site and enable this option where appropriate.
                            </p>
                    visible_if: |
                        zenarioAB.value('cookie_require_consent') == 'explicit' &&
                        zenarioAB.value('cookie_consent_type__explicit') == 'message_accept_reject'
        cookie_timeouts:
            label: Timeouts
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                The length of time that the cookie consent, &quot;remember me&quot;
                                and &quot;Log me in automatically&quot; options last.
                            </p>
                
                zenario_siteconfig:
                    type: grouping
                    name: zenario_siteconfig
                
                cookie_timeout:
                    grouping: zenario_siteconfig
                    legend: Set in the <code>zenario_siteconfig.php</code> file
                    
                    label: 'Cookie timeout:'
                    readonly: true
                    type: text
