# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: favicon
    hide_tab_bar: true
    title: Upload or remove a Favicon or a Home Screen Icon for this site
    tabs:
        favicon: 
            edit_mode: 
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: true
            fields:
                desc:
                    snippet:
                        html: >
                            You may upload an image to use as a Favicon, and an image to use as a Home Screen Icon for mobile devices.
                favicon: 
                    site_setting:
                        name: favicon
                    label: "Favicon:"
                    upload: 
                        accept: "image/*"
                        extensions: 
                            - .gif
                            - .ico
                            - .png
                        drag_and_drop: false
                    note_below: >
                        You can upload a <code>.gif</code>, <code>.ico</code> or <code>.png</code> file.<br/>
                        If you wish to support visitors using Internet Explorer 10 or earlier, you should
                        upload a <code>.ico</code> file that is either 16×16, 32×32, 48×48 or 64×64 pixels in size.
                    validation:
                        must_be_gif_ico_or_png: >
                            The favicon must be a .gif, .ico or a .png file.
                
                
                mobile_icon: 
                    site_setting:
                        name: mobile_icon
                    label: "Home screen icon:"
                    upload: 
                        accept: "image/*"
                        extensions: 
                            - .gif
                            - .png
                        drag_and_drop: false
                    note_below: >
                        You should upload a <code>.gif</code> or a <code>.png</code> file for a home-screen icon.
                        We recommend that the image should be 144×144 pixels in size;
                        the image will be auto-downsized.
                    validation:
                        must_be_gif_or_png: >
                            The home-screen icon must be a .gif or a .png file.
                default_icon:
                    site_setting:
                        name: default_icon
                    label: "Default icon:"
                    upload: 
                        accept: "image/*"
                        extensions: 
                            - .gif
                            - .png
                        drag_and_drop: false
                    note_below: >
                        This default image will be shown if a page does not have a feature image.
                        You should upload a <code>.gif</code> or a <code>.png</code> file for a default icon.
                        We recommend that the image should be at least 200x200 pixels in size;
                        the image will be auto-downsized.
                    validation:
                        must_be_gif_or_png: >
                            The default icon must be a .gif or a .png file.
                                    