# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing settings for documents, files and images
    setting_group: files_and_images
    tabs:
        image_privacy:
            label: Image privacy
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab lets you control whether images on your site appear in search engines.
                default_image_privacy:
                    site_setting:
                        name: default_image_privacy
                    label: 'Default image privacy:'
                    type: radios
                    value: auto
                    values:
                        public:
                            label: Public
                            note_below: |
                                Can be viewed by any visitor via a constant URL, and will normally be indexed by search engines. (Shown in the Organizer Images panel with a green border.) Recommended if your site only has public web pages.
                        private:
                            label: Private
                            note_below: |
                                Can only be viewed by logged-in extranet users via private content items. Cannot be indexed by search engines. (Shown in Organizer Images panel with a blue border.) Recommended if your site has an extranet area, or you want to protect certain images from unauthorised viewing.
                        auto:
                            label: Auto
                            note_below: |
                                Images will have the Auto state when first uploaded, but will be set to Public if on a public content item, or Private if on a private content item. (Shown in the Organizer Images panel with an orange border, but this changes once the image changes to Public or Private.)
        image_sizes:
            label: Image thumbnails
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            When images are uploaded, Zenario will automatically create thumbnails for them.
                            <br/><br/>
                            When a plugin requests a thumbnail of an image, where possible Zenario will use the premade ones
                            instead of generating a new one on the fly. This reduces the load on your server and make your
                            web pages load more quickly for visitors.
                            <br/><br/>
                            You can use this tab to define up to three different thumbnails for each image.
                
                thumbnail_180x130_width: 
                    label: 'Thumbnail size (width × height):'
                    type: text
                    readonly: true
                    value: 180
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;&nbsp;×&nbsp;'
                thumbnail_180x130_height: 
                    same_row: true
                    type: text
                    readonly: true
                    value: 130
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    note_below: |
                        This thumbnail is used by Organizer and cannot be modified.
                
                custom_thumbnail_1:
                    label: 'Create a second thumbnail'
                    type: checkbox
                    redraw_onchange: true
                
                custom_thumbnail_1_width: 
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_1_width
                    label: 'Size (width × height):'
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;&nbsp;×&nbsp;'
                custom_thumbnail_1_height: 
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_1_height
                    same_row: true
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                
                custom_thumbnail_2:
                    indent: 1
                    label: 'Create a third thumbnail'
                    type: checkbox
                    redraw_onchange: true
                
                custom_thumbnail_2_width: 
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_2_width
                    label: 'Size (width × height):'
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a width in pixels.
                        numeric: The width must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;&nbsp;×&nbsp;'
                custom_thumbnail_2_height: 
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: custom_thumbnail_2_height
                    same_row: true
                    type: text
                    validation: 
                        required_if_not_hidden: Please enter a height in pixels.
                        numeric: The height must be a number.
                    maxlength: 5
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
        
        image_resizing:
            label: Image resizing (advanced)
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            To prevent artifacts in images, Zenario will only use a thumbnail when:
                            <ul>
                                <li>The size of the thumbnail exactly matches the requested size.</li>
                                <li>The thumbnail is large enough to be resized down to the requested size without any visible artifacts.</li>
                            </ul>
                            If you are seeing artifacts in your thumbnails, you can change when this happens:
                
                thumbnail_threshold:
                    site_setting:
                        name: thumbnail_threshold
                    pre_field_html: |
                    label: 'Allowable threshold for resizing down:'
                    post_field_html: '&nbsp;%'
                    type: text
                    value: 66
                    style: 'width: 3em;'
                    slider:
                        range: min
                        min: 50
                        max: 100
                        before_field: true
                    validation:
                        required_if_not_hidden: Please enter a percentage.
                        numeric: The percentage must be numeric.
                    note_below: |
                        It's usually safe to leave this set to the default value (66%).
                        However if you see artifacts on your thumbnail then try making it smaller.
                
                description2:
                    full_width: true
                    snippet:
                        html: |
                            <br/>
                            <br/>
                            When Zenario resizes a JPEG image to create a thumbnail, the new image is then recompressed.
                            This compresson algorithm can use a quality of between 0 and 100.
                
                jpeg_quality_limit:
                    site_setting:
                        name: jpeg_quality_limit
                    label: 'JPEG image quality used when resizing images:'
                    type: text
                    value: 99
                    style: 'width: 50px;'
                    slider:
                        range: min
                        min: 80
                        max: 100
                        before_field: true
                    note_below: |
                        The lower this number the smaller the filesize of the thumbnail will be, however if you set setting it
                        too low then you may see artifacts on your thumbnails for JPEG images.
        filesizes:
            label: File Upload Sizes
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for file uploads.
                content_max_filesize:
                    site_setting:
                        name: content_max_filesize
                    label: 'Maximum Content File Size:'
                    type: text
                    value: 20000000
                    note_below: >
                        This allows you to set a maximum allowed uploadable file
                        size (in bytes) for Pictures, Audio, Video, and other
                        Content Types.
                    validation:
                        required: Please enter a Maximum Content File Size.
                        numeric: The Maximum Content File Size must be numeric.
                max_content_image_filesize:
                    site_setting:
                        name: max_content_image_filesize
                    label: 'Maximum Image File Size:'
                    type: text
                    value: 500000
                    note_below: |
                        This allows you to set a maximum allowed uploadable file size (in bytes) for images which are to be used with HTML and
                                                    other types of Content Items.
                    validation:
                        required: Please enter a Maximum Image File Size.
                        numeric: The Maximum Content Image File Size must be numeric.
                max_content_movie_filesize:
                    site_setting:
                        name: max_content_movie_filesize
                    label: 'Maximum Animation File Size:'
                    type: text
                    value: 20000000
                    note_below: |
                        This allows you to set a maximum allowed uploadable file size (in bytes) for Animation which are to be used with HTML and
                                                    other types of Content Items.
                    validation:
                        required: Please enter a Maximum Animation File Size.
                        numeric: The Maximum Content Movie File Size must be numeric.
                apache_max_filesize:
                    label: 'Largest Possible Upload Size:'
                    type: text
                    readonly: true
                    note_below: |
                        This is the size of the largest file that can be uploaded to your server. Your server administrator can change this by changing the server's Apache Config (it is the lesser of post_max_size and upload_max_filesize as set in the php.ini file).
                max_allowed_packet:
                    label: 'MySQL max_packet_size:'
                    type: text
                    readonly: true
                    note_below: |
                        This is the size of the largest possible SQL query Zenario can send to your database.
                                                        Images, along with their thumbnails and their working copies, will be added to the database using one command,
                                                        so this puts a limit on the size of image that you can add to Zenario.
                                                        Your server administrator can change this by changing the <code>max_allowed_packet</code> setting
                                                        in the server's MySQL configuration.
        file_downloads:
            label: File Downloads
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for file downloads.
                restrict_downloads_by_ip:
                    site_setting:
                        name: restrict_downloads_by_ip
                    label: 'Restrict by IP:'
                    type: checkbox
                    value: 1
                    note_below: "Places a <code>.htaccess</code> file in the temporary document directory to allow access only from the client's IP address."
                 
                    
        awss3_file_downloads:
            label: AWS S3
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>You can store document content items locally in the docstore, and/or on Amazon's AWS S3 storage.</p>
                            <p>To use S3, you will need an AWS account and an IAM programmatic user account with access keys.</p>
                            <p>This works for both public and private document content items. When downloading, Zenario creates a pre-signed URL for users to access each file.</p>
                aws_s3_support:
                    site_setting:
                        name: aws_s3_support
                    label: 'Enable support for AWS S3'
                    type: checkbox
                    redraw_onchange: true
                    note_below: "AWS S3 permits files up to 5GB to be uploaded, but also see the File Upload Sizes tab and the Largest Possible Upload Size setting for your server; if that is lower than 5GB, file sizes will be limited at the lower size."
                    
                aws_s3_region:
                    indent: 1
                    site_setting:
                        name: aws_s3_region
                    label: 'Region:'
                    type: text
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                    validation:
                        required_if_not_hidden: Please enter a region.
                    side_note: 'Enter AWS region, e.g. "eu-west-2"'
                aws_s3_key_id:
                    indent: 1
                    site_setting:
                        name: aws_s3_key_id
                    label: 'AWS access key ID:'
                    type: text
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                    validation:
                        required_if_not_hidden: Please enter key ID.
                aws_s3_secret_key:
                    indent: 1
                    site_setting:
                        name: aws_s3_secret_key
                    label: 'AWS secret access key:'
                    type: text
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                    validation:
                        required_if_not_hidden: Please enter access key.
                aws_s3_bucket:
                    indent: 1
                    site_setting:
                        name: aws_s3_bucket
                    label: 'Bucket ARN:'
                    type: text
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                    validation:
                        required_if_not_hidden: Please enter a bucket.
                csl_download_note: 
                    class_name: zenario_content_list
                    pre_field_html: "<div class=\"zenario_fbInfo\">"
                    snippet: 
                        html: "The settings below are used for document content items to show download link and file size of local and S3 files on Content Summary List plugins."
                    post_field_html: "</div>"
                    ord: 6
                    id: csl_download_note
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                local_file_link_text:
                    indent: 1
                    site_setting:
                        name: local_file_link_text
                    label: 'Show local file download link text:'
                    type: text
                    value: ""
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                
                s3_file_link_text:
                    indent: 1
                    site_setting:
                        name: s3_file_link_text
                    label: 'Show s3 file download link text:'
                    type: text
                    value: ""
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
                show_format_and_size:
                    indent: 1
                    site_setting:
                        name: show_format_and_size
                    label: 'Show format and size'
                    type: checkbox
                    value:  1
                    visible_if: |
                        zenarioAB.value('aws_s3_support')
        document_tags:
            label: Document tags
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                enable_document_tags:
                    site_setting:
                        name: enable_document_tags
                    label: 'Enable document tags'
                    type: checkbox
                    value: true
