# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: documents
    title: Editing settings for documents
    tabs:
        document_tags:
            label: Document tags
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                enable_document_tags:
                    site_setting:
                        name: enable_document_tags
                    label: 'Enable document tags'
                    type: checkbox
                    value: true