# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: email
    title: Editing email settings
    tabs:
        email:
            label: Email
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab contains default settings for the Emails sent by your site.
                            These are also used as default values for any Email Templates created when installing a Module.
                data_protection_link:
                    snippet:
                        html: ''
                email_address_admin:
                    site_setting:
                        name: email_address_admin
                    label: 'Notifications email address:'
                    type: text
                    note_below: |
                        Email address to which general administrative emails should be sent.
                    validation:
                        required: Please enter an email eddress.
                        email: Please ensure the email address is in a valid format.
                email_address_system:
                    label: 'Support email address:'
                    type: text
                    readonly: true
                    note_below: |
                        Any errors that occur on the site will be sent to this address.
                        You can change this address by editing the <code>EMAIL_ADDRESS_GLOBAL_SUPPORT</code> definition
                        in your <code>zenario_siteconfig.php</code> file.
                email_address_from:
                    site_setting:
                        name: email_address_from
                    label: '&quot;From&quot; email address:'
                    type: text
                    value: yourname@example.com
                    note_below: |
                        Email address which all server-generated emails should appear to come from.
                            (Some anti-spam systems can wrongly identify server-generated emails as spam,
                             so you might want to choose a special address here and tell your anti-spam software about it.
                             You might also use a real email account if you want to trap undeliverable messages sent to users,
                             so that you catch any bounces via this account.)
                    validation:
                        required: 'Please enter an email address &quot;From&quot;.'
                        email: 'Please ensure this &quot;From&quot; email address is in a valid format.'
                email_name_from:
                    site_setting:
                        name: email_name_from
                    label: '&quot;From&quot; name:'
                    type: text
                    value: Zenario website
                    note_below: |
                        A name associated with the &quot;From&quot; email address. If you enter your own SMTP details on the SMTP tab then this may be overwritten by your SMTP server.
                    validation:
                        required: Please enter a name.
                warning_email_frequency:
                    site_setting:
                        name: warning_email_frequency
                    label: 'Warning email frequency:'
                    type: select
                    values:
                        no_limit:
                            ord: 0
                            label: No limit
                        5 minutes:
                            ord: 1
                            label: 5 minutes
                        10 minutes:
                            ord: 2
                            label: 10 minutes
                        30 minutes:
                            ord: 3
                            label: 30 minutes
                        1 hour:
                            ord: 4
                            label: 1 hour
                        2 hours:
                            ord: 5
                            label: 2 hours
                        6 hours:
                            ord: 6
                            label: 6 hours
                        12 hours:
                            ord: 7
                            label: 12 hours
                        1 day:
                            ord: 8
                            label: 1 day
                    value: 'no_limit'
        template:
            label: Template
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            Define a standard email template in this tab. 
                            When an email template has the "Use standard email template" option selected, the email body is merged into the template below in [[email_body_content]].
                standard_email_template:
                    site_setting:
                        name: standard_email_template
                    label: 'Standard email template:'
                    type: editor
                    dont_trim: true
                    editor_options:
                        convert_urls: false
                        relative_urls: false
                    style: |
                        width: 98%;
                    rows: 30
                    insert_image_button:
                        pick_items:
                            path: 'zenario__content/panels/image_library'
                            target_path: 'zenario__content/panels/image_library'
                            min_path: 'zenario__content/panels/image_library'
                            max_path: 'zenario__content/panels/image_library'
                            disallow_refiners_looping_on_min_path: true
                    insert_link_button:
                        exists: true
                    value: |
                        <table style="table-layout: auto; width: 860px; height: 656px;" border="0" width="100%" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr>
                                    <td style="vertical-align: top; width: 860px; background: #f0f0f0;">
                                        <table style="table-layout: auto; margin: 30px auto;" border="0" width="620" cellspacing="0" cellpadding="0" align="center">
                                            <tbody>
                                                <tr>
                                                    <td style="background: #FFFFFF; vertical-align: top;">
                                                        <table style="table-layout: auto;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                            <tbody>
                                                                
                                                                <!-- HEADER -->
                                                                <tr>
                                                                    <td style="background: #3c3c3b; color: #fff; padding: 35px 0; border-bottom: 3px solid  #132833; text-align: center;">Company Logo</td>
                                                                </tr>
                                                                
                                                                <!-- BODY -->
                                                                <tr>
                                                                    <td style="font-family: Arial, Helvetica; padding: 0px 20px 0px; font-size: 14px; line-height: 22px; color: #132833;">
                                                                    <p>&nbsp;</p>
                                                                    [[email_body_content]]
                                                                    <p>&nbsp;</p>
                                                                    
                                                                    </td>
                                                                </tr>
                                                                
                                                                <!-- FOOTER -->
                                                                <tr>
                                                                    <td style="padding: 0px;">
                                                                        <table style="font-family: Tahoma, Geneva, sans-serif; table-layout: auto;" border="0" width="100%" cellspacing="0" cellpadding="0" bgcolor="#3c3c3b">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td>&nbsp;</td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td>
                                                                                        <br>
                                                                                        <p style="text-align: center; color: #fff; font-size: 13px; line-height: 18px;">© Your company<br> <span style="font-size: 11px;">Contact details</span></p>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td style="color: #3c3c3b;">&nbsp;.</td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

        smtp:
            label: SMTP
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
                validate_on_revert: true
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                    When the CMS sends an email, it can either use the PHP <code>mail()</code> function,
                                    or it can connect to a SMTP server.
                                    If not correctly set up, any emails sent could be lost without trace.
                                </p>
                smtp_specify_server:
                    site_setting:
                        name: smtp_specify_server
                    label: 'Specify a mail server:'
                    type: radios
                    value: ""
                    values:
                        - Use PHP mail()
                        - Use SMTP
                    redraw_onchange: true
                base64_encode_emails:
                    site_setting:
                        name: base64_encode_emails
                    indent: 1
                    label: 'Encoding (advanced):'
                    type: radios
                    value: ""
                    values:
                        - Do not encode (recommended)
                        - Use base64 encoding
                    visible_if: |
                        !zenarioAB.value('smtp_specify_server')
                    note_below: |
                        You should only use the base64 option if you are regularly seeing corrupted characters in sent emails.
                smtp_host:
                    site_setting:
                        name: smtp_host
                    label: 'Server Name:'
                    type: text
                    value: ""
                    note_below: e.g. smtp.example.com
                    visible_if: "zenarioAB.value('smtp_specify_server')"
                    indent: 1
                smtp_port:
                    site_setting:
                        name: smtp_port
                    label: 'Port Number:'
                    type: text
                    value: "25"
                    style: 'width: 5em;'
                    visible_if: "zenarioAB.value('smtp_specify_server')"
                    indent: 1
                    validation:
                        numeric: The Port number must be numeric.
                smtp_security:
                    site_setting:
                        name: smtp_security
                    label: 'Security:'
                    type: select
                    value: ""
                    empty_value: None
                    values:
                        tls: Transport Layer Security (tls)
                        ssl: Secure Sockets Layer (ssl)
                    visible_if: "zenarioAB.value('smtp_specify_server')"
                    indent: 1
                smtp_use_auth:
                    site_setting:
                        name: smtp_use_auth
                    label: 'Use Authentication:'
                    type: checkbox
                    value: ""
                    visible_if: "zenarioAB.value('smtp_specify_server')"
                    indent: 1
                    redraw_onchange: true
                smtp_username:
                    site_setting:
                        name: smtp_username
                    label: 'Username:'
                    type: text
                    value: ""
                    visible_if: "1 * zenarioAB.value('smtp_specify_server') && zenarioAB.value('smtp_use_auth')"
                    indent: 2
                smtp_password:
                    site_setting:
                        name: smtp_password
                        encrypt: true
                    label: 'Password:'
                    type: password
                    visible_if: "1 * zenarioAB.value('smtp_specify_server') && zenarioAB.value('smtp_use_auth')"
                    indent: 2
        test:
            priv: _PRIV_EDIT_SITE_SETTING
            label: Test
            edit_mode:
                enabled: true
                always_on: true
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab allows you to send a test email.
                            
                            If you do not receive the test email, you may need to change the settings on the SMTP tab.
                test_send_email_address:
                    type: text
                    maxlength: "100"
                    label: 'Test Send:'
                test_send_button:
                    same_row: true
                    type: submit
                    format_onchange: true
                    value: Test Send
                    class: submit_selected
            notices:
                test_send_sucesses:
                    show: ""
                    type: success
                    message: ""
                test_send_error:
                    show: ""
                    type: error
                    message: ""
            show_errors_after_field: description
        debug:
            label: Debug
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
                on: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: "This tab contains settings for overriding the recipient's address for all emails sent by the CMS."
                debug_override_enable:
                    label: 'Debug mode'
                    site_setting:
                        name: debug_override_enable
                    type: checkbox
                    value: ""
                    format_onchange: true
                    note_below: "Route all email to the debug email address rather than recipients' email addresses."
                debug_override_email_address:
                    label: 'Debug email address:'
                    site_setting:
                        name: debug_override_email_address
                    type: text
                    value: ""
                    validation:
                        required_if_not_hidden: Please enter an email address.
                        email: Please enter a valid email address.

        styles:
            label: Pre-defined styles
            edit_mode:
                enabled: false
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            These pre-defined styles will be available when composing a newsletter or an email template.
                            You can add more by editing the <code>zenario_custom/site_description.yaml</code> file.
                email_style_formats:
                    type: code_editor
                    tall_as_possible: true
                    dont_trim: true
                    language: yaml
                    style: |
                        height: 30em;
                description2:
                    full_width: true
                    snippet:
                        html: |
                            See
                                <a href="http://www.tinymce.com/wiki.php/Configuration:style_formats" target="_blank">
                                    http://www.tinymce.com/wiki.php/Configuration:style_formats</a>
                            for more information.
