# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing settings for documents, files and images
    setting_group: files_and_images
    tabs:
        image_privacy:
            label: Image privacy
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab lets you control whether images on your site appear in search engines.
                default_image_privacy:
                    site_setting:
                        name: default_image_privacy
                    label: 'Default image privacy:'
                    type: radios
                    value: auto
                    values:
                        public:
                            label: Public
                            note_below: |
                                Can be viewed by any visitor via a constant URL, and will normally be indexed by search engines. (Shown in the Organizer Images panel with a green border.) Recommended if your site only has public web pages.
                        private:
                            label: Private
                            note_below: |
                                Can only be viewed by logged-in extranet users via private content items. Cannot be indexed by search engines. (Shown in Organizer Images panel with a blue border.) Recommended if your site has an extranet area, or you want to protect certain images from unauthorised viewing.
                        auto:
                            label: Auto
                            note_below: |
                                Images will have the Auto state when first uploaded, but will be set to Public if on a public content item, or Private if on a private content item. (Shown in the Organizer Images panel with an orange border, but this changes once the image changes to Public or Private.)
        image_sizes:
            label: Image sizes
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            This tab contains settings for the storage and processing of images.
                                                            Working copy images may be stored to improve performance when automatically resizing large images.
                jpeg_quality_limit:
                    site_setting:
                        name: jpeg_quality_limit
                    label: 'Limit JPEG image quality:'
                    type: text
                    value: 99
                    style: 'width: 50px;'
                    slider:
                        range: min
                        min: 80
                        max: 100
                        before_field: true
                    note_below: |
                        When Zenario outputs a JPEG image on a page,
                        limit the quality to no more than this amount to keep page-sizes smaller.
                
                thumbnail_wc:
                    label: 'Create thumbnails for images as soon as they are uploaded'
                    type: checkbox
                    redraw_onchange: true
                thumbnail_wc_image_size:
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: thumbnail_wc_image_size
                    label: 'Thumbnail size (largest dimension):'
                    post_field_html: pixels
                    note_below: |
                        When an image is uploaded, Zenario will create a thumbnail of this size.
                        Having a thumbnail pre-created will allow any plugin
                        that uses a thumbnail of that size or smaller
                        to be generated faster.
                    type: text
                    value: 300
                    style: 'width: 5em;'
                    slider:
                        range: min
                        min: 200
                        max: 1000
                        before_field: true
                        step: 25
                    validation:
                        required_if_not_hidden: Please enter a thumbnail size.
                        numeric: The thumbnail size must be numeric.
                working_copy_image:
                    indent: 1
                    hide_if_previous_outdented_value_isnt: 1
                    label: 'Create a second thumbnail'
                    type: checkbox
                    redraw_onchange: true
                working_copy_image_size:
                    indent: 2
                    hide_with_previous_outdented_field: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: working_copy_image_size
                    label: 'Thumbnail size (largest dimension):'
                    post_field_html: pixels
                    type: text
                    style: 'width: 6em;'
                    slider:
                        range: min
                        min: 500
                        max: 2000
                        before_field: true
                        step: 50
                    validation:
                        required_if_not_hidden: Please enter a second thumbnail size.
                        numeric: The second thumbnail size must be numeric.
                set_working_copy_image_threshold:
                    indent: 1
                    hide_with_previous_outdented_field: 1
                    hide_if_previous_outdented_value_isnt: 1
                    label: 'Change the threshold for this (advanced)'
                    type: checkbox
                    redraw_onchange: true
                working_copy_image_threshold:
                    indent: 2
                    hide_with_previous_outdented_field: 1
                    hide_if_previous_outdented_value_isnt: 1
                    site_setting:
                        name: working_copy_image_threshold
                    pre_field_html: |
                        Zenario will use this thumbnail when the the requested thumbnail is exactly the same size,
                        or no larger than the following proportion of the working copy's dimensions:
                                                    <br/><br/>
                    post_field_html: %
                    type: text
                    style: 'width: 3em;'
                    slider:
                        range: min
                        min: 50
                        max: 100
                        before_field: true
                    validation:
                        required_if_not_hidden: Please enter a percentage.
                        numeric: The percentage must be numeric.
        filesizes:
            label: File Upload Sizes
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for file uploads.
                content_max_filesize:
                    site_setting:
                        name: content_max_filesize
                    label: 'Maximum Content File Size:'
                    type: text
                    value: 20000000
                    note_below: >
                        This allows you to set a maximum allowed uploadable file
                        size (in bytes) for Pictures, Audio, Video, and other
                        Content Types.
                    validation:
                        required: Please enter a Maximum Content File Size.
                        numeric: The Maximum Content File Size must be numeric.
                max_content_image_filesize:
                    site_setting:
                        name: max_content_image_filesize
                    label: 'Maximum Image File Size:'
                    type: text
                    value: 500000
                    note_below: |
                        This allows you to set a maximum allowed uploadable file size (in bytes) for images which are to be used with HTML and
                                                    other types of Content Items.
                    validation:
                        required: Please enter a Maximum Image File Size.
                        numeric: The Maximum Content Image File Size must be numeric.
                max_content_movie_filesize:
                    site_setting:
                        name: max_content_movie_filesize
                    label: 'Maximum Animation File Size:'
                    type: text
                    value: 20000000
                    note_below: |
                        This allows you to set a maximum allowed uploadable file size (in bytes) for Animation which are to be used with HTML and
                                                    other types of Content Items.
                    validation:
                        required: Please enter a Maximum Animation File Size.
                        numeric: The Maximum Content Movie File Size must be numeric.
                apache_max_filesize:
                    label: 'Largest Possible Upload Size:'
                    type: text
                    readonly: true
                    note_below: |
                        This is the size of the largest uploaded file that your server will accept.
                                                    Your server administrator can change this by changing the server's Apache Config.
                max_allowed_packet:
                    label: 'MySQL max_packet_size:'
                    type: text
                    readonly: true
                    note_below: |
                        This is the size of the largest possible command the CMS can send to your database.
                                                        Images, along with their thumbnails and their working copies, will be added to the database using one command,
                                                        so this puts a limit on the size of image that you can add to the CMS.
                                                        Your server administrator can change this by changing the <code>max_allowed_packet</code> setting
                                                        in the server's MySQL configuration.
        file_downloads:
            label: File Downloads
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: This tab contains settings for file downloads.
                restrict_downloads_by_ip:
                    site_setting:
                        name: restrict_downloads_by_ip
                    label: 'Restrict by IP:'
                    type: checkbox
                    value: 1
                    note_below: "Places a <code>.htaccess</code> file in the temporary document directory to allow access only from the client's IP address."
        document_tags:
            label: Document tags
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                enable_document_tags:
                    site_setting:
                        name: enable_document_tags
                    label: 'Enable document tags'
                    type: checkbox
                    value: true
