# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: categories
    title: Editing category settings
    tabs:
        categories:
            label: Categories
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                enable_display_categories_on_content_lists:
                    site_setting:
                        name: enable_display_categories_on_content_lists
                    label: 'Enable display of categories on content summary lists and in event listing'
                    type: checkbox
                    value: ""
                    side_note: |
                        When enabled, a content item's lowest level public category can be displayed in content summary lists.
                    format_onchange: true
                enable_category_landing_pages:
                    site_setting:
                        name: enable_category_landing_pages
                    label: 'Enable category landing pages'
                    type: checkbox
                    visible_if: |
                        zenarioAB.value('enable_display_categories_on_content_lists')
                    value: ""
                    indent: 1
                    side_note: |
                        When enabled, categories displayed on content summary lists whill have links to a landing page, if one exists.