# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: embedding
    title: Options for embedding elements of this site in third-party sites
    tabs:
        embedding:
            label: Embedding
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                description:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                Zenario allows slots on specific
                                content items, or entire content items, to be embedded in other pages. 
                            </p>
                            <p>
                                This is done by putting an <code>iframe</code> tag on a page of that site,
                                with it containing a reference to the element on this site.
                            </p>
                            <p>
                                Use these options to control what elements of this site can be embedded on a third party site
                                (i.e. a different domain name), and which such sites are allowed to do this.
                            </p>
                            <p>
                                Embedding is always allowed on the same site.
                            </p>
                xframe_options:
                    site_setting:
                        name: xframe_options
                    label: |
                       Embedding policy:
                    type: radios
                    value: this
                    values:
                        this:
                            label: Block embedding by all third party sites (safest)
                        all:
                            label: Allow any third party site to embed (not recommended)
                        specific:
                            label: |
                                Allow sites on these domains to embed:
                    redraw_onchange: true
                xframe_domains:
                    site_setting:
                        name: xframe_domains
                    visible_if:
                        zenarioAB.valueIn: xframe_options, specific
                    indent: 1
                    type: text
                    placeholder: eg. zenar.io
                    note_below: |
                            Do not include http:// or https://.
                            If specifying several domains, use commas to separate them.
                    validation:
                        required_if_not_hidden: Please enter at least one domain
                xframe_target:
                    site_setting:
                        name: xframe_target
                    visible_if:
                        zenarioAB.valueIn: xframe_options, specific, all
                    indent: 1
                    label: 'What can be embedded:'
                    type: radios
                    value: anything
                    values:
                        slots_with_nests:
                            label: Slots with nests only
                        all_slots:
                            label: Slots with any plugin
                        anything:
                            label: Slots with any nest or plugin, and entire content items
                    validation:
                        required_if_not_hidden: Please select what can be embedded
                admin_mode_warning:
                    visible_if:
                        zenarioAB.valueIn: xframe_options, specific, all
                    indent: 1
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                Attention server admins: your Apache config may override these settings.
                                To ensure that these settings are not overriden, the correct Apache config line is:
                            </p>
                            <pre>
                                Header setifempty X-Frame-Options SAMEORIGIN
                            </pre>
                            
