# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing the primary domain of the site
    hide_tab_bar: Yes
    max_height: "250"
    tabs:
        primary_domain:
            label: Primary domain
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: |
                            <p>
                                If your site can be accessed using more than one domain name, please set your primary one here.
                                Links to your site will use the primary domain, and Administrators will be directed to the primary domain when they log in.
                            </p>
                            <p>
                                If you set a preferred domain, this must be a domain that you can access, otherwise you will be unable to log into Admin Mode.
                            </p>
                primary_domain:
                    site_setting:
                        name: primary_domain
                    label: 'Primary domain:'
                    type: radios
                    value: ""
                    values:
                        none: Allow administrators to log in on any domain
                    format_onchange: true
    setting_group: primary_domain
