# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: external_programs
    title: Editing settings for external programs
    tabs:
        antiword:
            label: Antiword
            edit_mode:
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: true
                on: false
                format_on_edit: true
                format_on_cancel_edit: true
                format_on_revert: true
            fields:
                desc:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                When you upload a Word document, Zenario will attempt to
                                scan the document and create a plain-text extract.
                                This extract is not directly visible to visitors,
                                but plugins may use it to find documents that match a visitor's search.
                            </p><p>
                                For Word documents with the new <code>.docx</code> extension,
                                Zenario can create an extract without help.
                            </p><p>
                                For Word documents with the old <code>.doc</code> extension,
                                Zenario needs the help of an external tool called Antiword.
                            </p><p>
                                If Antiword is not installed on your server then your server administrator will need to install it;
                                e.g. by running:
                                <br/>
                                <code>&nbsp; &nbsp; sudo apt-get install antiword</code>
                                <br/>
                                on Ubuntu.
                            </p><p>
                                Zenario can only use Antiword if it is running on a Unix-based server;
                                there is not support for this feature on a Windows server.
                            </p>
                antiword_path:
                    name: antiword_path
                    site_setting:
                        name: antiword_path
                    label: 'Antiword path:'
                    type: select
                    value: PATH
                    empty_value: ' -- Do not use antiword -- '
                    values:
                        'PATH':
                            label: "Use your server's PATH environment variable"
                        '/usr/bin/':
                            label: '/usr/bin/antiword'
                        '/usr/local/bin/':
                            label: '/usr/local/bin/antiword'
                    format_onchange: true
                    style: >
                        margin-right: 0.5em;
                test:
                    same_row: true
                    visible_if:
                        zenarioAB.value: antiword_path
                    type: submit
                    value: Test
                    class: submit
                    can_be_pressed_in_view_mode: true
                    format_onchange: true
            show_errors_after_field: desc
            notices:
                success:
                    show: ""
                    type: success
                    message: Antiword is working successfully.
                error:
                    show: ""
                    type: error
                    message: Antiword is not correctly set up.
        pdftotext:
            label: PDF-to-Text
            edit_mode:
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: true
                on: false
                format_on_edit: true
                format_on_cancel_edit: true
            fields:
                desc:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                When you upload a PDF file, Zenario will attempt to
                                scan the file and create a plain-text extract.
                                This extract is not directly visible to visitors,
                                but plugins may use it to find documents that match a visitor's search.
                            </p><p>
                                To get an extract from a PDF file,
                                Zenario needs the help of a program called pdftotext,
                                which is part of an external library called Poppler.
                            </p><p>
                                If Poppler is not installed on your server then your server administrator will need to install it;
                                e.g. by running:
                                <br/>
                                <code>&nbsp; &nbsp; sudo apt-get install poppler-utils</code>
                                <br/>
                                on Ubuntu.
                            </p><p>
                                Zenario can only use pdftotext and Poppler if it is running on a Unix-based server;
                                there is not support for this feature on a Windows server.
                            </p>
                pdftotext_path:
                    name: pdftotext_path
                    site_setting:
                        name: pdftotext_path
                    label: 'pdftotext path:'
                    type: select
                    value: PATH
                    empty_value: ' -- Do not use pdftotext -- '
                    values:
                        'PATH':
                            label: "Use your server's PATH environment variable"
                        '/usr/bin/':
                            label: '/usr/bin/pdftotext'
                        '/usr/local/bin/':
                            label: '/usr/local/bin/pdftotext'
                    format_onchange: true
                    style: >
                        margin-right: 0.5em;
                test:
                    same_row: true
                    visible_if:
                        zenarioAB.value: pdftotext_path
                    type: submit
                    value: Test
                    class: submit
                    can_be_pressed_in_view_mode: true
                    format_onchange: true
            show_errors_after_field: desc
            notices:
                success:
                    show: ""
                    type: success
                    message: pdftotext is working successfully.
                error:
                    show: ""
                    type: error
                    message: pdftotext is not correctly set up.

        ghostscript:
            label: Ghostscript
            edit_mode:
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: true
                on: false
                format_on_edit: true
                format_on_cancel_edit: true
            fields:
                desc:
                    full_width: true
                    snippet:
                        html: |
                            <p>
                                When you upload a PDF file, Zenario will attempt to
                                scan the file and create a thumbnail of the first page that can be used as stick image.
                            </p><p>
                                To get a thumbnail from a PDF file,
                                Zenario needs the help of a program called "gs" (ghostscript).
                            </p><p>
                                If ghostscript is not installed on your server then your server administrator will need to install it;
                                e.g. by running:
                                <br/>
                                <code>&nbsp; &nbsp; sudo apt-get install ghostscript</code>
                                <br/>
                                on Ubuntu.
                            </p><p>
                                Zenario can only use ghostscript if it is running on a Unix-based server;
                                there is not support for this feature on a Windows server.
                            </p>
                ghostscript_dpi:
                    name: ghostscript_dpi
                    site_setting:
                        name: ghostscript_dpi
                    label: 'ghostscript output DPI:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a DPI number.
                        numeric: The DPI must be a number.
                    value: "72"
                    style: 'width: 6em; margin-right: 0.5em;'
                    note_below: |
                        This setting define the image definition that will be produced (higher definition also creates big images).
                        Recomended values can be any of 72, 150, 300, 600 (default 72).
                ghostscript_path:
                    name: ghostscript_path
                    site_setting:
                        name: ghostscript_path
                    label: 'ghostscript path:'
                    type: select
                    value: PATH
                    empty_value: ' -- Do not use ghostscript -- '
                    values:
                        'PATH':
                            label: "Use your server's PATH environment variable"
                        '/usr/bin/':
                            label: '/usr/bin/gs'
                        '/usr/local/bin/':
                            label: '/usr/local/bin/gs'
                    format_onchange: true
                    style: >
                        margin-right: 0.5em;
                test:
                    same_row: true
                    visible_if:
                        zenarioAB.value: ghostscript_path
                    type: submit
                    value: Test
                    class: submit
                    can_be_pressed_in_view_mode: true
                    format_onchange: true
            show_errors_after_field: desc
            notices:
                success:
                    show: ""
                    type: success
                    message: ghostscript is working successfully.
                error:
                    show: ""
                    type: error
                    message: ghostscript is not correctly set up.
