# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing settings for datasets
    tabs:
        datasets:
            label: Dataset settings
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                dataset_field_used_count:
                    site_setting:
                        name: dataset_field_used_count
                    label: 'Count number of records with dataset field set:'
                    type: select
                    value: 'always'
                    values:
                        'always':
                            label: 'Always count'
                        'never':
                            label: "Don't count"
                        'if_indexed':
                            label: 'Only count if field has DB index'
    setting_group: datasets
