# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: logos_and_branding
    title: Editing logos and branding
    tabs:
        favicon: 
            label: Site logos
            edit_mode: 
                priv: _PRIV_EDIT_SITE_SETTING
                enabled: true
            fields:
                desc:
                    snippet:
                        html: >
                            Set the image used as a favicon, an image that can be saved as a home screen icon on mobile devices, and an OG image for when the site is mentioned on social media.
                favicon: 
                    site_setting:
                        name: favicon
                    label: |
                        Browser favicon:
                    upload: 
                        accept: "image/png, image/gif, image/x-icon"
                        extensions: 
                            - .gif
                            - .ico
                            - .png
                        drag_and_drop: false
                    pick_items: 
                        path: zenario__library/panels/special_images
                        min_path: zenario__library/panels/special_images
                        max_path: zenario__library/panels/special_images
                        target_path: zenario__library/panels/special_images
                        select_phrase: Select from special images library...
                        disabled_if_for_all_selected_items: |
                            !zenario.IN(item.mime_type, 'image/png', 'image/gif', 'image/x-icon')
                    note_below: |
                        You may upload a <code>.ico</code>, <code>.gif</code> or <code>.png</code> file. (<code>.svg</code> files are not supported.) Should be square with 32×32 pixels or larger.
                    validation:
                        must_be_gif_ico_or_png: |
                            The favicon must be a file with format .gif, .ico or .png.
                    format_onchange: true
                mobile_icon: 
                    site_setting:
                        name: mobile_icon
                    label: |
                        Mobile device "home screen" icon:
                    upload: 
                        accept: "image/png, image/gif"
                        extensions: 
                            - .gif
                            - .png
                        drag_and_drop: false
                    pick_items: 
                        path: zenario__library/panels/special_images
                        min_path: zenario__library/panels/special_images
                        max_path: zenario__library/panels/special_images
                        target_path: zenario__library/panels/special_images
                        select_phrase: Select from special images library...
                        disabled_if_for_all_selected_items: |
                            !zenario.IN(item.mime_type, 'image/png', 'image/gif')
                    note_below: >
                        You may upload a <code>.png</code> or <code>.gif</code> file. (<code>.svg</code> files are not supported.)
                        We recommend that the image be 144×144 pixels in size; larger images will be auto-downsized.
                    validation:
                        must_be_gif_or_png: >
                            The home screen icon must be a .gif or a .png file.
                    format_onchange: true
                default_icon:
                    site_setting:
                        name: default_icon
                    label: "Open Graph (OG) image for the site:"
                    upload: 
                        accept: "image/png, image/gif, image/jpg, image/jpeg"
                        extensions: 
                            - .gif
                            - .png
                            - .jpg
                            - .jpeg
                        drag_and_drop: false
                    pick_items: 
                        path: zenario__library/panels/special_images
                        min_path: zenario__library/panels/special_images
                        max_path: zenario__library/panels/special_images
                        target_path: zenario__library/panels/special_images
                        select_phrase: Select from special images library...
                        disabled_if_for_all_selected_items: |
                            !zenario.IN(item.mime_type, 'image/png', 'image/gif', 'image/jpg', 'image/jpeg')
                    note_below: >
                        When a content item doesn’t have a featured image, this image will be used for the content item's <code>og:image</code> meta data tags.<br>
                        You should upload a <code>.jpg</code>, <code>.jpeg</code>, <code>.gif</code> or a <code>.png</code> file for a default icon (<code>.svg</code> files are not supported).
                        We recommend that the image should be at least 200x200 pixels in size;
                        Larger images will be auto-downsized.
                    validation:
                        must_be_image: >
                            The OG image must be a .gif, .jpg, .jpeg or a .png file.
                    format_onchange: true
        admin_login:
            label: Admin/site disabled
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: >
                            Set the logo used that is shown on the administrator login, and site disabled screens.
                
                brand_logo:
                    site_setting:
                        name: brand_logo
                    label: 'Logo on admin login and site disabled page:'
                    type: radios
                    value: zenario
                    values:
                        zenario:
                            label: Use the Zenario logo
                        custom:
                            label: 'Use a custom logo:'
                    redraw_onchange: true
                
                zenario_logo:
                    visible_if: zenarioAB.value('brand_logo') == 'zenario'
                
                custom_logo:
                    site_setting:
                        name: custom_logo
                    visible_if: zenarioAB.value('brand_logo') == 'custom'
                    upload:
                        accept: "image/*"
                        extensions: 
                            - .gif
                            - .jpg
                            - .jpeg
                            - .png
                            - .svg
                        drag_and_drop: true
                    pick_items: 
                        path: zenario__library/panels/special_images
                        min_path: zenario__library/panels/special_images
                        max_path: zenario__library/panels/special_images
                        target_path: zenario__library/panels/special_images
                        select_phrase: Select from special images library...
                    note_below: >
                        If your image is larger than 500p× wide by 250px high, it will be scaled down to fit.
                    validation:
                        required_if_not_hidden: >
                            Please upload an image.
                        must_be_image_or_svg: >
                            The custom logo must be a .gif, .jpg, .png or a .svg file.
                    format_onchange: true
                
                site_disabled_title:
                    label: "Browser title when site disabled:"
                    type: text
                site_disabled_message:
                    label: "Message for all visitors when site disabled:"
                    type: editor
                    editor_type: standard
                    dont_trim: true
                    editor_options:
                        convert_urls: true
                        relative_urls: true
                    rows: 4
                    cols: 80
        admin_login_link:
            label: Admin login link
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: >
                            Use this to change the logo used on the admin login link
                            (as seen on the front-end by an admin who is not logged in but
                             has previously logged in and selected the "remember me" option).
                
                admin_link_logo:
                    site_setting:
                        name: admin_link_logo
                    label: 'Logo:'
                    type: radios
                    value: zenario
                    values:
                        zenario:
                            label: Use the Zenario logo
                        custom:
                            label: 'Use a custom logo:'
                    redraw_onchange: true
                
                admin_link_custom_logo:
                    site_setting:
                        name: admin_link_custom_logo
                    visible_if: |
                        zenarioAB.value('admin_link_logo') == 'custom'
                    upload:
                        accept: "image/*"
                        extensions: 
                            - .gif
                            - .jpg
                            - .jpeg
                            - .png
                            - .svg
                        drag_and_drop: true
                    pick_items: 
                        path: zenario__library/panels/special_images
                        min_path: zenario__library/panels/special_images
                        max_path: zenario__library/panels/special_images
                        target_path: zenario__library/panels/special_images
                        select_phrase: Select from special images library...
                    validation:
                        required_if_not_hidden: >
                            Please upload an image.
                        must_be_image_or_svg: >
                            The admin login logo must be a .gif, .jpg, .png or a .svg file.
                    note_below: >
                        This image will be resized down if it is larger than 50×50 pixels in size.
                    format_onchange: true
                
                admin_link_logo_pos:
                    site_setting:
                        name: admin_link_logo_pos
                    label: 'Postion:'
                    type: radios
                    cols: 3
                    value: 'allt allr'
                    values:
                        'allt alll':
                            label: Top left
                        'allt allc':
                            label: Top center
                        'allt allr':
                            label: Top right
                        'allb alll':
                            label: Bottom left
                        'allb allc':
                            label: Bottom center
                        'allb allr':
                            label: Bottom right
                
                admin_link_logo_offset:
                    site_setting:
                        name: admin_link_logo_offset
                    label: 'Offset from top/bottom:'
                    type: text
                    style: |
                        width: 3em;
                    post_field_html: px
                    value: 125
                    validation:
                        numeric: The offset must be a number
        og:
            label: Organizer
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: >
                            Use this to change the description and favicon used for Organizer.
                
                organizer_title:
                    site_setting:
                        name: organizer_title
                    label: 'Organizer title:'
                    type: text
                    value: Organizer
                
                organizer_favicon:
                    site_setting:
                        name: organizer_favicon
                    label: 'Organizer favicon:'
                    type: radios
                    value: zenario
                    values:
                        site:
                            label: Use the site favicon
                        zenario:
                            label: Use the Zenario favicon
                        custom:
                            label: 'Use a custom favicon:'
                    redraw_onchange: true
                
                custom_organizer_favicon:
                    site_setting:
                        name: custom_organizer_favicon
                    visible_if: |
                        zenarioAB.value('organizer_favicon') == 'custom'
                    upload:
                        accept: "image/png, image/gif, image/x-icon"
                        extensions: 
                            - .gif
                            - .ico
                            - .png
                        drag_and_drop: true
                    pick_items: 
                        path: zenario__library/panels/special_images
                        min_path: zenario__library/panels/special_images
                        max_path: zenario__library/panels/special_images
                        target_path: zenario__library/panels/special_images
                        select_phrase: Select from special images library...
                        disabled_if_for_all_selected_items: |
                            !zenario.IN(item.mime_type, 'image/png', 'image/gif', 'image/x-icon')
                    note_below: >
                        You can upload a <code>.gif</code>, <code>.ico</code> or <code>.png</code> file.<br/>
                    validation:
                        must_be_gif_ico_or_png: >
                            The favicon must be a .gif, .ico or a .png file.
                    format_onchange: true
