# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    title: Editing settings for dates and times
    tabs:
        dates:
            label: Dates
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: >
                            This tab contains settings for the format of dates used for
                            visitors and Administrators.
                vis_date_format_short:
                    site_setting:
                        name: vis_date_format_short
                    label: 'Short date format:'
                    type: select
                    value: '%e/%c/%Y'
                    values:
                        '%e/%c/%y':
                            label: ''
                        '%e/%c/%Y':
                            label: ''
                        '%d/%m/%y':
                            label: ''
                        '%d/%m/%Y':
                            label: ''
#                       '%e.%c.%Y':
#                           label: ''
                        '%d.%m.%Y':
                            label: ''
#                       '%d-%m-%y':
#                           label: ''
#                       '%d-%m-%Y':
#                           label: ''
                        '%c/%e/%y':
                            label: ''
                        '%c/%e/%Y':
                            label: ''
#                       '%c/%d/%y':
#                           label: ''
                        '%m/%d/%y':
                            label: ''
                        '%m/%d/%Y':
                            label: ''
#                       '%Y/%m/%d':
#                           label: ''
#                       '%Y.%m.%d':
#                           label: ''
                        '%Y-%m-%d':
                            label: ''
                    validation:
                        required: Please enter a short date format.
                vis_date_format_med:
                    site_setting:
                        name: vis_date_format_med
                    label: 'Medium date format:'
                    type: select
                    value: '%e [[_MONTH_SHORT_%m]] %Y'
                    values:
                        '%e [[_MONTH_SHORT_%m]] %y':
                            label: ''
                        '%e [[_MONTH_SHORT_%m]] %Y':
                            label: ''
                        '[[_MONTH_SHORT_%m]] %e, %Y':
                            label: ''
                    validation:
                        required: Please enter a medium date format.
                vis_date_format_long:
                    site_setting:
                        name: vis_date_format_long
                    label: 'Long date format:'
                    type: select
                    value: '[[_WEEKDAY_%w]] %D [[_MONTH_LONG_%m]] %Y'
                    values:
                        '%D [[_MONTH_LONG_%m]] %Y':
                            label: ''
                        '[[_MONTH_LONG_%m]] %D, %Y':
                            label: ''
                        '[[_WEEKDAY_%w]] %D [[_MONTH_LONG_%m]] %Y':
                            label: ''
                        '[[_WEEKDAY_%w]] [[_MONTH_LONG_%m]] %D, %Y':
                            label: ''
                    validation:
                        required: Please enter a long date format.
                vis_date_format_datepicker:
                    site_setting:
                        name: vis_date_format_datepicker
                    label: 'Date-picker date format:'
                    type: select
                    value: 'd/m/yy'
                    values:
                        'd/m/y':
                            label: ''
                        'd/m/yy':
                            label: ''
                        'dd/mm/y':
                            label: ''
                        'dd/mm/yy':
                            label: ''
#                       'd.m.yy':
#                           label: ''
                        'dd.mm.yy':
                            label: ''
#                       'dd-mm-y':
#                           label: ''
#                       'dd-mm-yy':
#                           label: ''
                        'm/d/y':
                            label: ''
                        'm/d/yy':
                            label: ''
#                       'm/d/y':
#                           label: ''
                        'mm/dd/y':
                            label: ''
                        'mm/dd/yy':
                            label: ''
#                       'yy/mm/dd':
#                           label: ''
#                       'yy.mm.dd':
#                           label: ''
                        'yy-mm-dd':
                            label: ''
                        'd M y':
                            label: ''
                        'd M yy':
                            label: ''
                        'M d, yy':
                            label: ''
                    validation:
                        required: Please enter a date-picker date format.
                    note_below: |
                        Used for interactive date-pickers.
                        If you use names for months, these will not be translated.
                
                organizer_date_format:
                    site_setting:
                        name: organizer_date_format
                    label: 'Organizer date format:'
                    type: select
                    value: 'd M yy'
                    values:
                        'd/m/y':
                            label: ''
                        'd/m/yy':
                            label: ''
                        'dd/mm/y':
                            label: ''
                        'dd/mm/yy':
                            label: ''
#                       'd.m.yy':
#                           label: ''
                        'dd.mm.yy':
                            label: ''
#                       'dd-mm-y':
#                           label: ''
#                       'dd-mm-yy':
#                           label: ''
                        'm/d/y':
                            label: ''
                        'm/d/yy':
                            label: ''
#                       'm/d/y':
#                           label: ''
                        'mm/dd/y':
                            label: ''
                        'mm/dd/yy':
                            label: ''
#                       'yy/mm/dd':
#                           label: ''
#                       'yy.mm.dd':
#                           label: ''
                        'yy-mm-dd':
                            label: ''
                        'd M y':
                            label: ''
                        'd M yy':
                            label: ''
                        'M d, yy':
                            label: ''
                    validation:
                        required: Please enter a date format.
                    note_below: |
                        Used in Organizer and the admin back-end.
                
        times:
            label: Times
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: No
            fields:
                description:
                    full_width: Yes
                    snippet:
                        html: This tab contains settings for times.
                vis_time_format:
                    site_setting:
                        name: vis_time_format
                    label: 'Time Format:'
                    type: select
                    value: '%H:%i'
                    empty_value: ' -- Select -- '
                    values:
                        '%H:%i':
                            label: '09:00'
                        '%l:%i %p':
                            label: '9:00 AM'
                    validation:
                        required: Please enter a time format.
    setting_group: date_and_time
