# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_breadcrumbs
    tabs:
        first_tab:
            label: Breadcrumb Settings
            fields:
                menu_section:
                    plugin_setting:
                        name: menu_section
                        foreign_key_to: menu_section
                        dangling_cross_references: delete_instance
                    label: 'Menu Section:'
                    pick_items:
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/sections
                        max_path: zenario__menu/panels/sections
                        target_path: zenario__menu/panels/sections
                        select_phrase: Select Menu Section...
                        hide_remove_button: Yes
                    value: "1"
                    validation:
                        required: Please select a Menu Section
                        
                breadcrumb_trail:
                    plugin_setting:
                        name: breadcrumb_trail
                    label: "First breadcrumb:"
                    type: radios
                    values:
                        do_not_prefix:
                            label: "Use the top level menu node"
                        site_home_page:
                            label: "Use the home page"
                        other_menu_node:
                            label: "Use a specific menu node"
                    value: site_home_page
                    format_onchange: Yes
                    side_note: On multi-lingual sites, the link will always point to the page in the current visitor language, if it exists.
                    
                breadcrumb_prefix_menu:
                    plugin_setting:
                        name: breadcrumb_prefix_menu
                        foreign_key_to: content
                        dangling_cross_references: delete_instance
                        use_value_for_plugin_name: "4"
                    visible_if: >
                        zenarioAB.value('breadcrumb_trail') == 'other_menu_node'
                    label: 'Menu node:'
                    pick_items:
                        by_language: Yes
                        path: zenario__menu/panels/sections
                        min_path: zenario__menu/panels/sections
                        max_path: zenario__menu/panels/menu_nodes
                        target_path: zenario__menu/panels/menu_nodes
                        select_phrase: Select menu node...
                        disallow_refiners_looping_on_min_path: Yes
                        hide_remove_button: Yes
                    validation:
                        required_if_not_hidden: Please select a menu node
                        
                breadcrumb_trail_separator:
                    plugin_setting:
                        name: breadcrumb_trail_separator
                    label: 'Breadcrumb trail separator:'
                    type: text
                    value: '»'
                    style: 'width: 5em;'
                