# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_meta_data
    tabs:
        first_tab:
            label: Details
            fields:
                options:
                    type: grouping
                    snippet:
                        label: Options
                        label_class: subheading
                filters:
                    type: grouping
                    snippet:
                        label: Filters
                        label_class: subheading
                show_labels:
                    plugin_setting:
                        name: show_labels
                    grouping: options
                    label: "Show labels"
                    type: checkbox
                    value: "0"
                    format_onchange: true
                show_date:
                    plugin_setting:
                        name: show_date
                    grouping: filters
                    label: "Show item's release date"
                    type: checkbox
                    value: "1"
                    format_onchange: true
                date_format:
                    plugin_setting:
                        name: date_format
                    grouping: filters
                    label: 'Date format:'
                    type: radios
                    format_onchange: true
                    value: _MEDIUM
                    values:
                        _SHORT:
                            label: Short
                        _MEDIUM:
                            label: Medium
                        _LONG:
                            label: Long
                    indent: 1
                date_html_tag:
                    indent: 1
                    plugin_setting:
                        name: date_html_tag
                    grouping: filters
                    label: Date tags
                    value: h2
                    visible_if:
                        lib.value: show_date
                    type: select
                    values: &tags
                        h1:
                            label: h1
                            ord: 1
                        h2:
                            label: h2
                            ord: 2
                        h3:
                            label: h3
                            ord: 3
                        h4:
                            label: h4
                            ord: 4
                        h5:
                            label: h5
                            ord: 5
                        h6:
                            label: h6
                            ord: 6
                        p:
                            label: p
                            ord: 8
                show_title:
                    plugin_setting:
                        name: show_title
                    grouping: filters
                    label: 'Show title'
                    type: checkbox
                    value: "1"
                    format_onchange: true
                title_html_tag:
                    indent: 1
                    plugin_setting:
                        name: title_html_tag
                    grouping: filters
                    label: Title tags
                    value: h1
                    visible_if:
                        lib.value: show_title
                    type: select
                    values: *tags
                show_description:
                    plugin_setting:
                        name: show_description
                    grouping: filters
                    label: 'Show description'
                    type: checkbox
                    value: "0"
                    format_onchange: true
                description_html_tag:
                    indent: 1
                    plugin_setting:
                        name: description_html_tag
                    grouping: filters
                    label: Description tags
                    value: h2
                    visible_if:
                        lib.value: show_description
                    type: select
                    values: *tags
                show_summary:
                    plugin_setting:
                        name: show_summary
                    grouping: filters
                    label: 'Show summary'
                    type: checkbox
                    value: "0"
                    format_onchange: true
                summary_html_tag:
                    indent: 1
                    plugin_setting:
                        name: summary_html_tag
                    grouping: filters
                    label: Summary tags
                    value: h2
                    visible_if:
                        lib.value: show_summary
                    type: select
                    values: *tags
                show_categories:
                    plugin_setting:
                        name: show_categories
                    grouping: filters
                    label: 'Show public categories'
                    type: checkbox
                    note_below: "Categories not marked as Public will not be shown to visitors."
                    value: ""
                    format_onchange: true
                categories_html_tag:
                    indent: 1
                    plugin_setting:
                        name: categories_html_tag
                    grouping: filters
                    label: Categories tags
                    value: h2
                    visible_if:
                        lib.value: show_categories
                    type: select
                    values: *tags
                show_keywords:
                    plugin_setting:
                        name: show_keywords
                    grouping: filters
                    label: 'Show keywords'
                    type: checkbox
                    value: "0"
                    format_onchange: true
                keywords_html_tag:
                    indent: 1
                    plugin_setting:
                        name: keywords_html_tag
                    grouping: filters
                    label: Keywords tags
                    value: h2
                    visible_if:
                        lib.value: show_keywords
                    type: select
                    values: *tags
                show_language_name:
                    plugin_setting:
                        name: show_language_name
                    grouping: filters
                    label: 'Show language name'
                    type: checkbox
                    value: "0"
                    format_onchange: true
                language_name_html_tag:
                    indent: 1
                    plugin_setting:
                        name: language_name_html_tag
                    grouping: filters
                    label: Language name tags
                    value: h2
                    visible_if:
                        lib.value: show_language_name
                    type: select
                    values: *tags
                show_language:
                    plugin_setting:
                        name: show_language
                    grouping: filters
                    label: 'Show language'
                    type: checkbox
                    value: "0"
                    format_onchange: true
                language_html_tag:
                    indent: 1
                    plugin_setting:
                        name: language_html_tag
                    grouping: filters
                    label: Language tags
                    value: h2
                    visible_if:
                        lib.value: show_language
                    type: select
                    values: *tags
                show_writer_name:
                    plugin_setting:
                        name: show_writer_name
                    grouping: filters
                    label: 'Show writer name'
                    type: checkbox
                    value: "0"
                    format_onchange: true
                writer_name_html_tag:
                    indent: 1
                    plugin_setting:
                        name: writer_name_html_tag
                    grouping: filters
                    label: Writer name tags
                    value: h2
                    visible_if:
                        lib.value: show_writer_name
                    type: select
                    values: *tags
                show_writer_image:
                    plugin_setting:
                        name: show_writer_image
                    grouping: filters
                    label: 'Show writer image'
                    type: checkbox
                    value: '0'
                    format_onchange: true
                writer_image_label_html_tag:
                    indent: 1
                    plugin_setting:
                        name: writer_image_label_html_tag
                    grouping: filters
                    label: Writer image label tags
                    value: h2
                    #visible_if: (controlled in module code)
                    type: select
                    values: *tags
                
                canvas:
                    plugin_setting:
                        name: canvas
                    grouping: filters
                    label: 'Image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                    indent: 1
                width:
                    plugin_setting:
                        name: width
                    grouping: filters
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                height:
                    plugin_setting:
                        name: height
                    grouping: filters
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                offset:
                    plugin_setting:
                        name: offset
                    grouping: filters
                    label: 'Offset:'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: true
                        style: 'width: 200px;'
                    side_note: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.
                    indent: 2
                
                show_sticky_image:
                    plugin_setting:
                        name: show_sticky_image
                    grouping: filters
                    label: 'Show feature image'
                    type: checkbox
                    format_onchange: true
                sticky_image_label_html_tag:
                    indent: 1
                    plugin_setting:
                        name: sticky_image_label_html_tag
                    grouping: filters
                    label: Feature image label tags
                    value: h2
                    #visible_if: (controlled in module code)
                    type: select
                    values: *tags
                    
                sticky_image_canvas:
                    plugin_setting:
                        name: sticky_image_canvas
                    grouping: filters
                    label: 'Image canvas:'
                    type: select
                    value: unlimited
                    values:
                        unlimited:
                            ord: "1"
                            label: Unlimited size
                        fixed_width:
                            ord: "2"
                            label: Constrain by width
                        fixed_height:
                            ord: "3"
                            label: Constrain by height
                        fixed_width_and_height:
                            ord: "4"
                            label: Constrain by width and height
                        resize_and_crop:
                            ord: "5"
                            label: Resize and crop
                    format_onchange: true
                    indent: 1
                sticky_image_width:
                    plugin_setting:
                        name: sticky_image_width
                    grouping: filters
                    label: 'Width:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a width.
                        numeric: The width must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                sticky_image_height:
                    plugin_setting:
                        name: sticky_image_height
                    grouping: filters
                    label: 'Height:'
                    type: text
                    validation:
                        required_if_not_hidden: Please enter a height.
                        numeric: The height must be a number.
                    value: ""
                    maxlength: "5"
                    style: 'width: 5em;'
                    post_field_html: '&nbsp;pixels'
                    indent: 2
                sticky_image_offset:
                    plugin_setting:
                        name: sticky_image_offset
                    grouping: filters
                    label: 'Offset:'
                    type: text
                    style: 'width: 50px;'
                    value: "0"
                    slider:
                        min: "-10"
                        max: "10"
                        before_field: true
                        style: 'width: 200px;'
                    side_note: |
                        Moving the slider to the left will move the image left or down;
                        moving the slider to the right will move the image right or up.
                    indent: 2
        
        order_tab:
            label: Display order
            fields:
                reorder_info:
                    snippet:
                        html: 'You can choose the display order of meta data fields.'
                reorder_fields:
                    plugin_setting:
                        name: reorder_fields
                    label: 'Reorder fields:'
                    pick_items: 
                        multiple_select: true
                        nothing_selected_phrase: Select one or more meta data fields.
                        hide_select_button: true
                        hide_info_button: true
                        reorder_items: true
                    #values: