site_settings:
    setting_group: zenario_country_manager__site_settings_group
    title: Editing settings for countries and regions
    tabs:
        zenario_country_manager__site_settings:
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: Yes
            label: Details
            fields:
                zenario_country_manager__region_type_management:
                    label: 'Region type Management:'
                    type: radios
                    site_setting:
                        name: zenario_country_manager__region_type_management
                    values:
                        0: Do not use region types
                        1: Regions must have type
                    side_note: |
                        <p>If set to "Regions must have type" then each region must be mark as either a region, state or city.</p>