site_settings:
    setting_group: zenario_country_manager__site_settings_group
    title: Editing settings for countries and regions
    tabs:
        zenario_country_manager__site_settings:
            edit_mode:
                enabled: Yes
                priv: _PRIV_EDIT_SITE_SETTING
                on: Yes
            label: Details
            fields:
                zenario_country_manager__region_type_management:
                    label: 'Region type Management:'
                    type: radios
                    site_setting:
                        name: zenario_country_manager__region_type_management
                    values:
                        0: Use simple regions
                        1: Use types of region
                    note_below: |
                        <p>If set to "Use types of region", regions will be identified as a region, a state or a city.</p>
