# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: data_protection
    tabs:
        data_protection:
            fields:
                period_to_delete_the_email_template_sending_log_headers:
                    label: 'How long should emails sent from this site be saved?'
                    site_setting:
                        name: period_to_delete_the_email_template_sending_log_headers
                    type: select
                    values:
                        0:
                            label: Don't save
                        1:
                            label: Delete after 1 day
                        7:
                            label: Delete after 1 week
                        30:
                            label: Delete after 1 month
                        90:
                            label: Delete after 3 months
                        365:
                            label: Delete after 1 year
                        730: 
                            label: Delete after 2 years
                        never_delete:
                            label: Save forever  
                    value: never_delete
                    redraw_onchange: true
                
                delete_email_template_sending_log_content_sooner:
                    visible_if: zenarioAB.value('period_to_delete_the_email_template_sending_log_headers') != '0'
                    indent: 1
                    site_setting:
                        name: delete_email_template_sending_log_content_sooner
                    label: Delete email body sooner (just save headers)
                    type: checkbox
                    redraw_onchange: true
                
                period_to_delete_the_email_template_sending_log_content:
                    visible_if: zenarioAB.value('delete_email_template_sending_log_content_sooner')
                    hide_with_previous_field: true
                    indent: 2
                    site_setting:
                        name: period_to_delete_the_email_template_sending_log_content
                    type: select
                    values:
                        0:
                            label: Don't save email body
                        1:
                            label: Delete after 1 day   
                        7:
                            label: Delete after 1 week
                        30:
                            label: Delete after 1 month
                        90:
                            label: Delete after 3 months
                        365:
                            label: Delete after 1 year
                        730: 
                            label: Delete after 2 years