# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_location_viewer
    tabs:
        first_tab:
            label: Settings
            fields:
                location_source_mode:
                    plugin_setting:
                        name: location_source_mode
                    label: 'Location source mode:'
                    type: radios
                    format_onchange: Yes
                    note_below: 'If you select Get location from URL (l_id), you pass the location id in the url as parameter l_id'
                    values:
                        location_from_selector:
                            label: "Auto"
                            ord: 1
                            side_note: |
                                When placed on a content item that is a descriptive page for a specific location, display the images of that location.
                        location_from_organizer:
                            label: "Specific location"
                            ord: 2
                            side_note: |
                                Select a location from Organizer and display its images.
                        location_from_url:
                            label: "Get location from URL"
                            ord: 3
                            side_note: |
                                If the URL contains the parameter l_id, use its value to get the ID of the location.
                    value: location_from_selector
                
                show_title:
                    plugin_setting:
                        name: show_title
                    label: 'Show location title'
                    type: checkbox
                show_details:
                    plugin_setting:
                        name: show_details
                    label: 'Show location details'
                    type: checkbox
                    value: 1
                    format_onchange: true
                    side_note: |
                        Displays a location's details as defined in the framework.
                show_image:
                    plugin_setting:
                        name: show_image
                    label: 'Show location image'
                    type: checkbox
                    value: 1
                    format_onchange: true
                    side_note: |
                        If a location has any images associated with it, the first image will be displayed.
                
                max_location_image_width:
                    plugin_setting:
                        name: max_location_image_width
                    pre_field_html: 'width:'
                    label: 'Maximum image size:'
                    type: text
                    size: "5"
                    maxlength: "5"
                    style: 'width: 50px'
                    value: "120"
                    validation:
                        numeric: The maximum image width must be numeric
                max_location_image_height:
                    plugin_setting:
                        name: max_location_image_height
                    pre_field_html: '&nbsp;height:'
                    post_field_html: '&nbsp;pixels'
                    type: text
                    size: "5"
                    same_row: Yes
                    maxlength: "5"
                    style: 'width: 50px'
                    value: "120"
                    validation:
                        numeric: The maximum image width must be numeric
                
                show_map:
                    plugin_setting:
                        name: show_map
                    label: 'Show map'
                    type: checkbox
                    value: 1
                    format_onchange: true
                    
                location_user:
                    plugin_setting:
                        name: location_user
                    label: 'You must be an externet user and have a role at the location to see details'
                    type: checkbox
                location:
                    label: 'Other Location:'
                    plugin_setting:
                        name: location
                    pick_items:
                        path: zenario__locations/panel
                        target_path: zenario__locations/panel
                        min_path: zenario__locations/panel
                        max_path: zenario__locations/panel
                        select_phrase: Select Location...
                        nothing_selected_phrase: No Location selected
                    validation:
                        required_if_not_hidden: You must select a location
                
                
                map_width:
                    label: 'Map size:'
                    pre_field_html: 'width:'
                    plugin_setting:
                        name: map_width
                    type: text
                    value: "500"
                    style: width:50px;
                    validation:
                        required_if_not_hidden: Please enter the map width
                map_height:
                    pre_field_html: '&nbsp;height:'
                    post_field_html: '&nbsp;pixels'
                    same_row: Yes
                    type: text
                    plugin_setting:
                        name: map_height
                    value: "500"
                    validation:
                        required_if_not_hidden: Please enter the map height
                    style: width:50px;
