# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        schedules:
            visible_if: zenarioA.running.assetwolf_2
            label: Schedules
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
            
                perm.view.schedule:
                    site_setting:
                        name: perm.view.schedule
                    type: radios
                    value: specific
                    values:
                        logged_out:
                            label: "Anonymous visitors can view ANY schedule's details"
                        logged_in:
                            label: "Extranet users can view ANY schedule's details"
                        specific:
                            label: "Extranet users can view a schedule's details if..."
                    redraw_onchange: true
                perm.view.schedule.by.group:
                    site_setting:
                        name: perm.view.schedule.by.group
                    indent: 1
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.view.schedule.groups:
                    site_setting:
                        name: perm.view.schedule.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can view a schedule's details.
                perm.view.schedule.directlyAssigned:
                    site_setting:
                        name: perm.view.schedule.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The schedule is directly assigned to them
                perm.view.schedule.atCompany:
                    site_setting:
                        name: perm.view.schedule.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The schedule is assigned to a company, and they have
                perm.view.schedule.atCompany.role:
                    site_setting:
                        name: perm.view.schedule.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.view.schedule.enforce:
                    indent: 1
                    hide_if_previous_outdented_value_isnt:
                        - logged_in
                        - specific
                    snippet: {}
                    note_below: |
                        If the assetTypeId variable is in the URL, the system will check if the visitor can see that schedule.
                
                perm.create-schedule.unassigned:
                    snippet:
                        label: "Create/unassigned: users can create an unassigned schedule if..."
                perm.create-schedule.unassigned.by.group:
                    site_setting:
                        name: perm.create-schedule.unassigned.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-schedule.unassigned.groups:
                    site_setting:
                        name: perm.create-schedule.unassigned.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create unassigned schedules.
                
                perm.create-schedule.oneself:
                    snippet:
                        label: "Create/oneself: users can create a schedule assigned to themselves if..."
                perm.create-schedule.oneself.by.group:
                    site_setting:
                        name: perm.create-schedule.oneself.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-schedule.oneself.groups:
                    site_setting:
                        name: perm.create-schedule.oneself.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create schedules assigned to themselves.
                
                perm.create-schedule.company:
                    snippet:
                        label: "Create/company: users can create a schedule assigned to a company if..."
                perm.create-schedule.company.by.group:
                    site_setting:
                        name: perm.create-schedule.company.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-schedule.company.groups:
                    site_setting:
                        name: perm.create-schedule.company.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create schedules assigned to companies.
                perm.create-schedule.company.atCompany:
                    site_setting:
                        name: perm.create-schedule.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.create-schedule.company.atCompany.role:
                    site_setting:
                        name: perm.create-schedule.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.edit.schedule:
                    snippet:
                        label: "Edit: users can edit a schedule's details if..."
                perm.edit.schedule.by.group:
                    site_setting:
                        name: perm.edit.schedule.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.edit.schedule.groups:
                    site_setting:
                        name: perm.edit.schedule.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a schedule.
                perm.edit.schedule.directlyAssigned:
                    site_setting:
                        name: perm.edit.schedule.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The schedule is directly assigned to them
                perm.edit.schedule.atCompany:
                    site_setting:
                        name: perm.edit.schedule.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The schedule is assigned to a company, and they have
                perm.edit.schedule.atCompany.role:
                    site_setting:
                        name: perm.edit.schedule.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.delete.schedule:
                    snippet:
                        label: "Delete: users can delete a schedule if..."
                perm.delete.schedule.by.group:
                    site_setting:
                        name: perm.delete.schedule.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.delete.schedule.groups:
                    site_setting:
                        name: perm.delete.schedule.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a schedule.
                perm.delete.schedule.directlyAssigned:
                    site_setting:
                        name: perm.delete.schedule.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The schedule is directly assigned to them
                perm.delete.schedule.atCompany:
                    site_setting:
                        name: perm.delete.schedule.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The schedule is assigned to a company, and they have
                perm.delete.schedule.atCompany.role:
                    site_setting:
                        name: perm.delete.schedule.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'