# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        companies:
            visible_if: zenarioA.running.zenario_company_locations_manager
            label: Companies
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                
                perm.view.company:
                    site_setting:
                        name: perm.view.company
                    type: radios
                    value: specific
                    values:
                        logged_out:
                            label: "Anonymous visitors can view ANY company's details"
                        logged_in:
                            label: "Extranet users can view ANY company's details"
                        specific:
                            label: "Extranet users can view a company's details if..."
                    redraw_onchange: true
                perm.view.company.by.group:
                    site_setting:
                        name: perm.view.company.by.group
                    indent: 1
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.view.company.groups:
                    site_setting:
                        name: perm.view.company.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can view a company's details.
                perm.view.company.atCompany:
                    site_setting:
                        name: perm.view.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.view.company.atCompany.role:
                    site_setting:
                        name: perm.view.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.view.company.enforce:
                    indent: 1
                    hide_if_previous_outdented_value_isnt:
                        - logged_in
                        - specific
                    snippet: {}
                    note_below: |
                        If the companyId variable is in the URL, the system will check if the visitor can see that company.
                
                perm.create-company.unassigned:
                    snippet:
                        label: "Create: users can create a company if..."
                perm.create-company.unassigned.by.group:
                    site_setting:
                        name: perm.create-company.unassigned.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-company.unassigned.groups:
                    site_setting:
                        name: perm.create-company.unassigned.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create a company.
                
                perm.edit.company:
                    snippet:
                        label: "Edit: users can edit a company's details if..."
                perm.edit.company.by.group:
                    site_setting:
                        name: perm.edit.company.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.edit.company.groups:
                    site_setting:
                        name: perm.edit.company.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a company.
                perm.edit.company.atCompany:
                    site_setting:
                        name: perm.edit.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.edit.company.atCompany.role:
                    site_setting:
                        name: perm.edit.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.delete.company:
                    snippet:
                        label: "Delete: users can delete a company if..."
                perm.delete.company.by.group:
                    site_setting:
                        name: perm.delete.company.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.delete.company.groups:
                    site_setting:
                        name: perm.delete.company.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a company.

