# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        procedures:
            label: Procedures
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
            
                perm.view.procedure:
                    site_setting:
                        name: perm.view.procedure
                    type: radios
                    value: specific
                    values:
                        logged_out:
                            label: "Anonymous visitors can view ANY procedure's details"
                        logged_in:
                            label: "Extranet users can view ANY procedure's details"
                        specific:
                            label: "Extranet users can view a procedure's details if..."
                    redraw_onchange: true
                perm.view.procedure.by.group:
                    site_setting:
                        name: perm.view.procedure.by.group
                    indent: 1
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.view.procedure.groups:
                    site_setting:
                        name: perm.view.procedure.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can view a procedure's details.
                perm.view.procedure.directlyAssigned:
                    site_setting:
                        name: perm.view.procedure.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The procedure is directly assigned to them
                perm.view.procedure.atCompany:
                    site_setting:
                        name: perm.view.procedure.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The procedure is assigned to a company, and they have
                perm.view.procedure.atCompany.role:
                    site_setting:
                        name: perm.view.procedure.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.view.procedure.enforce:
                    indent: 1
                    hide_if_previous_outdented_value_isnt:
                        - logged_in
                        - specific
                    snippet: {}
                    note_below: |
                        If the assetTypeId variable is in the URL, the system will check if the visitor can see that procedure.
                
                perm.create-procedure.unassigned:
                    snippet:
                        label: "Create/unassigned: users can create an unassigned procedure if..."
                perm.create-procedure.unassigned.by.group:
                    site_setting:
                        name: perm.create-procedure.unassigned.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-procedure.unassigned.groups:
                    site_setting:
                        name: perm.create-procedure.unassigned.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create unassigned procedures.
                
                perm.create-procedure.oneself:
                    snippet:
                        label: "Create/oneself: users can create a procedure assigned to themselves if..."
                perm.create-procedure.oneself.by.group:
                    site_setting:
                        name: perm.create-procedure.oneself.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-procedure.oneself.groups:
                    site_setting:
                        name: perm.create-procedure.oneself.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create procedures assigned to themselves.
                
                perm.create-procedure.company:
                    snippet:
                        label: "Create/company: users can create a procedure assigned to a company if..."
                perm.create-procedure.company.by.group:
                    site_setting:
                        name: perm.create-procedure.company.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-procedure.company.groups:
                    site_setting:
                        name: perm.create-procedure.company.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create procedures assigned to companies.
                perm.create-procedure.company.atCompany:
                    site_setting:
                        name: perm.create-procedure.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.create-procedure.company.atCompany.role:
                    site_setting:
                        name: perm.create-procedure.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.edit.procedure:
                    snippet:
                        label: "Edit: users can edit a procedure's details if..."
                perm.edit.procedure.by.group:
                    site_setting:
                        name: perm.edit.procedure.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.edit.procedure.groups:
                    site_setting:
                        name: perm.edit.procedure.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a procedure.
                perm.edit.procedure.directlyAssigned:
                    site_setting:
                        name: perm.edit.procedure.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The procedure is directly assigned to them
                perm.edit.procedure.atCompany:
                    site_setting:
                        name: perm.edit.procedure.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The procedure is assigned to a company, and they have
                perm.edit.procedure.atCompany.role:
                    site_setting:
                        name: perm.edit.procedure.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.delete.procedure:
                    snippet:
                        label: "Delete: users can delete a procedure if..."
                perm.delete.procedure.by.group:
                    site_setting:
                        name: perm.delete.procedure.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.delete.procedure.groups:
                    site_setting:
                        name: perm.delete.procedure.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a procedure.
                perm.delete.procedure.directlyAssigned:
                    site_setting:
                        name: perm.delete.procedure.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The procedure is directly assigned to them
                perm.delete.procedure.atCompany:
                    site_setting:
                        name: perm.delete.procedure.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The procedure is assigned to a company, and they have
                perm.delete.procedure.atCompany.role:
                    site_setting:
                        name: perm.delete.procedure.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'