# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    tab: users
    setting_group: perms
    title: Settings for User Permissions
    lovs:
        roles: {}
    tabs:
        users: {}
            ord: 1
        organisations:
            label: Organisations
            hide_when_children_are_not_visible: true
            ord: 2
        companies:
            parent: organisations
            visible_if: zenarioA.running.zenario_company_locations_manager
        locations:
            parent: organisations
            visible_if: zenarioA.running.zenario_location_manager
        roles:
            parent: organisations
            visible_if: zenarioA.running.zenario_organization_manager
        document_envelopes:
            visible_if: zenarioA.running.zenario_document_envelopes_fea
            ord: 3
