# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        roles:
            visible_if: zenarioA.running.zenario_location_manager
            label: Roles
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                
                perm.assign-user.location:
                    snippet:
                        label: "Assign: users can assign a user to a location if..."
                perm.assign-user.location.by.group:
                    site_setting:
                        name: perm.assign-user.location.by.group
                    indent: 1
                    type: checkbox
                    label: 'The current user is a member of the group(s):'
                    redraw_onchange: true
                perm.assign-user.location.groups:
                    site_setting:
                        name: perm.assign-user.location.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can assign a user to a location.
                perm.assign-user.location.atLocation:
                    site_setting:
                        name: perm.assign-user.location.atLocation
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The current user has
                perm.assign-user.location.atLocation.role:
                    site_setting:
                        name: perm.assign-user.location.atLocation.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at the location'
                perm.assign-user.location.atLocationAtCompany:
                    site_setting:
                        name: perm.assign-user.location.atLocationAtCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The location is in a company at which the current user has
                perm.assign-user.location.atLocationAtCompany.role:
                    site_setting:
                        name: perm.assign-user.location.atLocationAtCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in that company'
                
                perm.deassign-user.location:
                    snippet:
                        label: "Deassign: users can deassign a user from a location if..."
                perm.deassign-user.location.by.group:
                    site_setting:
                        name: perm.deassign-user.location.by.group
                    indent: 1
                    type: checkbox
                    label: 'The current user is a member of the group(s):'
                    redraw_onchange: true
                perm.deassign-user.location.groups:
                    site_setting:
                        name: perm.deassign-user.location.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can deassign a user from a location.
                perm.deassign-user.location.atLocation:
                    site_setting:
                        name: perm.deassign-user.location.atLocation
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The current user has
                perm.deassign-user.location.atLocation.role:
                    site_setting:
                        name: perm.deassign-user.location.atLocation.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at the location'
                perm.deassign-user.location.atLocationAtCompany:
                    site_setting:
                        name: perm.deassign-user.location.atLocationAtCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The location is in a company at which the current user has
                perm.deassign-user.location.atLocationAtCompany.role:
                    site_setting:
                        name: perm.deassign-user.location.atLocationAtCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in that company'

