# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    title: Editing settings for user permissions and data protection
    lovs:
        roles: {}
    tabs:
        companies: {}
        locations: {}
        users: {}
        roles: {}
        assets: {}
        assetTypes: {}
        possibleEvents: {}
        procedures: {}
        schedules: {}
        thisPolicy: {}
