# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        possibleEvents:
            visible_if: zenarioA.running.assetwolf_2
            label: Possible Events
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
            
                perm.view.possibleEvent:
                    site_setting:
                        name: perm.view.possibleEvent
                    type: radios
                    value: specific
                    values:
                        logged_out:
                            label: "Anonymous visitors can view ANY possible event's details"
                        logged_in:
                            label: "Extranet users can view ANY possible event's details"
                        specific:
                            label: "Extranet users can view a possible event's details if..."
                    redraw_onchange: true
                perm.view.possibleEvent.by.group:
                    site_setting:
                        name: perm.view.possibleEvent.by.group
                    indent: 1
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.view.possibleEvent.groups:
                    site_setting:
                        name: perm.view.possibleEvent.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can view a possible event's details.
                perm.view.possibleEvent.directlyAssigned:
                    site_setting:
                        name: perm.view.possibleEvent.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The possible event is directly assigned to them
                perm.view.possibleEvent.atCompany:
                    site_setting:
                        name: perm.view.possibleEvent.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The possible event is assigned to a company, and they have
                perm.view.possibleEvent.atCompany.role:
                    site_setting:
                        name: perm.view.possibleEvent.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.view.possibleEvent.enforce:
                    indent: 1
                    hide_if_previous_outdented_value_isnt:
                        - logged_in
                        - specific
                    snippet: {}
                    note_below: |
                        If the assetTypeId variable is in the URL, the system will check if the visitor can see that possible event.
                
                perm.create-possibleEvent.unassigned:
                    snippet:
                        label: "Create/unassigned: users can create an unassigned possible event if..."
                perm.create-possibleEvent.unassigned.by.group:
                    site_setting:
                        name: perm.create-possibleEvent.unassigned.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-possibleEvent.unassigned.groups:
                    site_setting:
                        name: perm.create-possibleEvent.unassigned.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create unassigned possible events.
                
                perm.create-possibleEvent.oneself:
                    snippet:
                        label: "Create/oneself: users can create a possible event assigned to themselves if..."
                perm.create-possibleEvent.oneself.by.group:
                    site_setting:
                        name: perm.create-possibleEvent.oneself.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-possibleEvent.oneself.groups:
                    site_setting:
                        name: perm.create-possibleEvent.oneself.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create possible events assigned to themselves.
                
                perm.create-possibleEvent.company:
                    snippet:
                        label: "Create/company: users can create a possible event assigned to a company if..."
                perm.create-possibleEvent.company.by.group:
                    site_setting:
                        name: perm.create-possibleEvent.company.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-possibleEvent.company.groups:
                    site_setting:
                        name: perm.create-possibleEvent.company.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create possible events assigned to companies.
                perm.create-possibleEvent.company.atCompany:
                    site_setting:
                        name: perm.create-possibleEvent.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.create-possibleEvent.company.atCompany.role:
                    site_setting:
                        name: perm.create-possibleEvent.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.edit.possibleEvent:
                    snippet:
                        label: "Edit: users can edit a possible event's details if..."
                perm.edit.possibleEvent.by.group:
                    site_setting:
                        name: perm.edit.possibleEvent.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.edit.possibleEvent.groups:
                    site_setting:
                        name: perm.edit.possibleEvent.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a possible event.
                perm.edit.possibleEvent.directlyAssigned:
                    site_setting:
                        name: perm.edit.possibleEvent.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The possible event is directly assigned to them
                perm.edit.possibleEvent.atCompany:
                    site_setting:
                        name: perm.edit.possibleEvent.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The possible event is assigned to a company, and they have
                perm.edit.possibleEvent.atCompany.role:
                    site_setting:
                        name: perm.edit.possibleEvent.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.delete.possibleEvent:
                    snippet:
                        label: "Delete: users can delete a possible event if..."
                perm.delete.possibleEvent.by.group:
                    site_setting:
                        name: perm.delete.possibleEvent.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.delete.possibleEvent.groups:
                    site_setting:
                        name: perm.delete.possibleEvent.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a possible event.
                perm.delete.possibleEvent.directlyAssigned:
                    site_setting:
                        name: perm.delete.possibleEvent.directlyAssigned
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The possible event is directly assigned to them
                perm.delete.possibleEvent.atCompany:
                    site_setting:
                        name: perm.delete.possibleEvent.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The possible event is assigned to a company, and they have
                perm.delete.possibleEvent.atCompany.role:
                    site_setting:
                        name: perm.delete.possibleEvent.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'