# You must use a tab-size of 4 spaces to edit this file.
---
site_settings:
    setting_group: perms
    tabs:
        scheduled_reports:
            label: Scheduled reports
            edit_mode:
                enabled: true
                priv: _PRIV_EDIT_SITE_SETTING
            fields:
                perm.view.scheduledReport:
                    site_setting:
                        name: perm.view.scheduledReport
                    type: radios
                    value: specific
                    values:
                        logged_out:
                            label: "Anonymous visitors can view ANY scheduled report's details"
                        logged_in:
                            label: "Extranet users can view ANY scheduled report's details"
                        specific:
                            label: "Extranet users can view a scheduled report's details if..."
                    redraw_onchange: true
                perm.view.scheduledReport.by.group:
                    site_setting:
                        name: perm.view.scheduledReport.by.group
                    indent: 1
                    hide_if_previous_outdented_value_isnt: specific
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.view.scheduledReport.groups:
                    site_setting:
                        name: perm.view.scheduledReport.groups
                    indent: 2
                    hide_with_previous_outdented_field: true
                    hide_if_previous_outdented_value_isnt: 1
                    pick_items: &pick_group
                        path: zenario__users/panels/groups
                        target_path: zenario__users/panels/groups
                        min_path: zenario__users/panels/groups
                        max_path: zenario__users/panels/groups
                        disallow_refiners_looping_on_min_path: true
                        nothing_selected_phrase: No group selected
                        select_phrase: Select a group...
                        multiple_select: true
                    validation:
                        required_if_not_hidden: Please select a group who can view a scheduled report's details.
                perm.view.scheduledReport.atLocationAtCompany:
                    site_setting:
                        name: perm.view.scheduledReport.atLocationAtCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: The scheduled report is at a company at which the current user has
                perm.view.scheduledReport.atLocationAtCompany.role:
                    site_setting:
                        name: perm.view.scheduledReport.atLocationAtCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in that company'
                
                perm.create-scheduledReport.unassigned:
                    snippet:
                        label: "Create/unassigned: users can create an unassigned scheduled report if..."
                perm.create-scheduledReport.unassigned.by.group:
                    site_setting:
                        name: perm.create-scheduledReport.unassigned.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.create-scheduledReport.unassigned.groups:
                    site_setting:
                        name: perm.create-scheduledReport.unassigned.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can create a scheduled report.
                
                perm.edit.scheduledReport:
                    snippet:
                        label: "Edit: users can edit a scheduled report's details if..."
                perm.edit.scheduledReport.by.group:
                    site_setting:
                        name: perm.edit.scheduledReport.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.edit.scheduledReport.groups:
                    site_setting:
                        name: perm.edit.scheduledReport.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can edit a scheduled report.
                
                perm.edit.scheduledReport.company.atCompany:
                    site_setting:
                        name: perm.edit.scheduledReport.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.edit.scheduledReport.company.atCompany.role:
                    site_setting:
                        name: perm.edit.scheduledReport.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'
                
                perm.delete.scheduledReport:
                    snippet:
                        label: "Delete: users can delete a scheduled report if..."
                perm.delete.scheduledReport.by.group:
                    site_setting:
                        name: perm.delete.scheduledReport.by.group
                    indent: 1
                    type: checkbox
                    label: 'They are a member of the group(s):'
                    redraw_onchange: true
                perm.delete.scheduledReport.groups:
                    site_setting:
                        name: perm.delete.scheduledReport.groups
                    hide_if_previous_outdented_value_isnt: 1
                    indent: 2
                    pick_items: *pick_group
                    validation:
                        required_if_not_hidden: Please select a group who can delete a scheduled report.
                
                perm.delete.scheduledReport.company.atCompany:
                    site_setting:
                        name: perm.delete.scheduledReport.company.atCompany
                    hide_with_previous_indented_field: true
                    indent: 1
                    row_class: zfab_or
                    type: checkbox
                    label: They have
                perm.delete.scheduledReport.company.atCompany.role:
                    site_setting:
                        name: perm.delete.scheduledReport.company.atCompany.role
                    same_row: true
                    hide_with_previous_field: true
                    type: select
                    empty_value: ANY role
                    values: roles
                    post_field_html: '&nbsp; at ANY location in the company'

