# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    module_class_name: zenario_extranet_password_reset
    tabs:
        first_tab:
            label: Passwords
            fields:
                password_reset_email_template:
                    plugin_setting:
                        name: password_reset_email_template
                        foreign_key_to: email_template
                        dangling_cross_references: remove
                    label: 'Password reset Email Template:'
                    pick_items:
                        path: zenario__email_template_manager/panels/email_templates
                        min_path: zenario__email_template_manager/panels/email_templates
                        max_path: zenario__email_template_manager/panels/email_templates
                        target_path: zenario__email_template_manager/panels/email_templates
                        select_phrase: Select Email Template...
                        hide_remove_button: Yes
                    validation:
                        required: Please select an email template
                    value: >
                        zenario_extranet_password_reset__to_user_password_reset_en
                    note_below: 'By default this plugin uses the email template with code "zenario_extranet_password_reset__to_user_password_reset_en".'
                    side_note: >
                        Please see the Module description to get a full list of
                        Merge Fields which can be used in the selected Email
                        Template.
                block_email_enumeration:
                    plugin_setting:
                        name: block_email_enumeration
                    label: Block email enumeration
                    type: checkbox
                    side_note: >
                        If this option is enabled, users will not be told whether or not they entered a valid email address.
                stop_users_reseting_passwords:
                    plugin_setting:
                        name: stop_users_reseting_passwords
                    label: 'Stop users from reseting their own passwords'
                    type: checkbox
                    side_note: >
                        If this option is disabled then users will be shown a message saying they need to contact an administrator to reset their password. The plugin can still be used so long as a reset link is generated by other means.
                    redraw_onchange: true
                contact_for_reset_message:
                    visible_if: zenarioAB.value('stop_users_reseting_passwords')
                    indent: 1
                    plugin_setting:
                        name: contact_for_reset_message
                    label: 'Message to show users:'
                    value: Contact an administrator to have your password reset.
                    type: textarea
                    show_phrase_icon: true
                    validation:
                        required_if_not_hidden: Enter a message to display to users trying to reset their password.
                show_link_to_login_page:
                    plugin_setting:
                        name: show_link_to_login_page
                    label: 'Show "Back to login" link'
                    type: checkbox
                    value: 1