# You must use a tab-size of 4 spaces to edit this file.
---
plugin_settings:
    tabs:
        first_tab:
            label: Settings
            fields:
                destination:
                    label: 'Link destination:'
                    plugin_setting:
                        name: destination
                    type: radios
                    values:
                        home:
                            label: Always link to the home page of the target language.
                        equiv_or_home:
                            label: >
                                Link to the translation of the current content item.
                                If one does not exist, link to the home page in the target language.
                        equiv_only:
                            label: >
                                Link to the translation of the current content item.
                                If one does not exist, do not show a link.
                    value: equiv_or_home
                languages_without_home_page_warning:
                    snippet:
                        html: '<div class="zenario_fbWarning">[[languages_without_home_page_warning]]</div>'
                    hidden: true
                language_settings_info:
                    snippet:
                        html: '<div class="zenario_fbInfo">[[language_settings_info]]</div>'
    module_class_name: zenario_language_picker
